= Historisierung

include::glossary:licence:partial$licence.adoc[]

Die technische Konzeption der Historisierung mit JPA gliedert sich in zwei Aspekte: die Konzeption des Gültigkeitszeitraums und der Bearbeitungshistorie.

[[konzeption-gueltigkeitszeitraum]]
== Konzeption des Gültigkeitszeitraums

Manche Daten haben einen Zeitbezug, d. h. der Inhalt eines Datensatzes bezieht sich nur auf einen bestimmten Zeitraum.
Man möchte z. B. beschreiben, dass für eine Ware in einem bestimmten Zeitraum ein Rabatt gewährt wird.
Um einen solchen Gültigkeitszeitraum abzubilden, wird der Datensatz um zwei Datumsattribute ergänzt.
Falls diese Datumsattribute bereits fachlich etablierte Namen haben, werden diese genutzt.
Diese Attribute werden durch die Anwendung fachlich gepflegt.

[[konzeption-bearbeitungshistorie]]
== Konzeption der Bearbeitungshistorie

In diesem Abschnitt wird beschrieben, wie die Bearbeitungshistorie von Datensätzen umgesetzt wird.
Eine übliche Anforderung ist z. B. die Speicherung letzten X Änderungen zu einem Datensatz.

Hierzu wird zunächst beschrieben, wie die prinzipielle Herangehensweise dazu ist.
Anschließend wird dies durch Angabe eines Entwurfsmusters präzisiert.

Die grundlegenden Prinzipien bei der technischen Abbildung sind, dass:

* die Historisierung explizit durchgeführt wird,
* die Umsetzung in Form eines Patterns erfolgt, und dass
* die Historisierung konsistent mit den bereits getroffenen Festlegungen zur Persistenz ist.

Die Historisierung der Bearbeitung erfolgt *explizit*, d. h. die zu historisierenden Daten werden im Anwendungskern gepflegt und durch ihn persistiert.

****
Theoretisch wäre es auch möglich, die Historisierung auf der Ebene der Persistenzschicht durchzuführen.
Dazu würde die Persistenzschicht, statt Entitäten zu aktualisieren, neue Entitäten mit aktuellen Zeitstempeln anlegen.
Beim Auslesen würde die Persistenzschicht immer den aktuellsten Datensatz liefern.

Dieses Vorgehen lohnt sich aber nicht, da in der Regel nur sehr wenige Datensätze historisiert werden.
Ebenso widerspricht es der Anforderung, dass keine Daten gespeichert werden sollen, die nicht angezeigt werden.
Sinnvoll wäre ein solches Vorgehen dann, wenn über die Historisierung eine Nachvollziehbarkeit der Änderungen erreicht werden soll.
Dies ist im Rahmen der Referenzarchitektur aber explizit die Aufgabe der Protokollierung.
****

Die beschriebene Bearbeitungshistorie lässt sich nur schwer in der Form von Bibliotheken mit abstrakten Oberklassen, Interfaces und ähnlichem abbilden.
Die dadurch entstehenden Java-Konstrukte wären nur sehr sperrig zu nutzen und würden die Entwicklung eher behindern als beschleunigen.
Deshalb wird zur Umsetzung der Bearbeitungshistorie ein *Entwurfsmuster* vorgegeben.
Das Entwurfsmuster ist in den xref:nutzungsvorgaben/historisierung.adoc[Nutzungsvorgaben zur Historisierung] im Detail beschrieben.
