= Migrationsleitfaden: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Die IsyFact ist eine vom Bundesverwaltungsamt entwickele Software Factory für den Bau von Informationssystemen in komplexen IT-Anwendungslandschaften.
Sie bündelt bestehendes technisches Know-how um Anwendungssysteme effizienter entwickeln und betreiben zu können.

Für die IsyFact gibt es zwei Versionszweige, IsyFact 1.x und IsyFact 2.x.

Seit dem Jahr 2020 steht der neue Major Release Zweig IsyFact 2.x zur Verfügung.
Dieser beruht auf allen IsyFact Bausteinen aus IsyFact 1.8 mit zwei wesentlichen Neuerungen:

- IsyFact basierend auf Spring Boot
- Zusätzliche Unterstützung des Frondend-Frameworks Angular (bisher nur JSF)

Der bisherige, erste Release Zweig der IsyFact endet mit der Version 1.8.
In diesem Releasezweig werden keine neuen Features mehr Eingang finden.
Die Pflege dieses Releasezweigs wird sich auf Security-Patches beschränken und in Minor Releases 1.8.x veröffentlicht werden.



[[aufbau-und-zweck-des-dokuments]]
=== Aufbau und Zweck des Dokuments

Die in diesem Dokument aufgeführten Hinweise sollen IsyFact Anwendungsentwicklern bei der Umstellung einer auf IsyFact 1.x basierenden Anwendung auf IsyFact 2.x helfen.
// end::inhalt[]