= Werkzeuge zur Erstellung von OpenAPI-Spezifikationen
:navtitle: Werkzeuge

Die OpenAPI-Spezifikation wird im YAML-Format erstellt, da YAML aufgrund der übersichtlichen Syntax leichter und schneller zu erfassen ist.
Für die Bearbeitung ist eine IDE nicht zwingend erforderlich, ein einfacher Texteditor (z.B. Notepad++) reicht aus.
Wir empfehlen jedoch den Einsatz des Swagger-Editors, der sowohl die syntaktische Korrektheit der YAML-Vorgaben, als der OpenAPI-Vorgaben prüft und mögliche Fehler in der Spezifikation in Echtzeit aufdeckt.

Swagger Editor ist ein Tool zum Bearbeiten von OpenAPI-Spezifikationen und unterstützt OpenAPI 3.0.
Swagger Editor validiert die eingegebene Spezifikation und bietet darüber hinaus weitere Funktionalität, wie z.B. Auto-Completion.
Wir empfehlen das entsprechende IntelliJ und Eclipse Plugins dieses Editors (siehe https://plugins.jetbrains.com/plugin/14837-openapi-swagger-editor[OpenAPI (Swagger) Editor für IntelliJ] und https://marketplace.eclipse.org/content/openapi-swagger-editor[OpenAPI (Swagger) Editor für Eclipse]).
Die Verwendung dieser Plugins ist besonders sinnvoll, da sie die Integration der Spezifikation in das Projekt ermöglicht und die Verwaltung mit Version Control erleichtert.
