= Konzept Datum & Zeit: Inhalt

// tag::inhalt[]
[[anforderungen]]
== Anforderungen

Im  Folgenden werden die Anforderungen an die Verarbeitung von Datums- und Zeitwerten definiert. Diese bilden die Grundlage für die Vorgaben im darauffolgenden Kapitel.

[[definitionen]]
=== Definitionen

Die folgenden Begriffe sind zentral für den Baustein „Datum und Zeit“ und werden hier definiert.

[[datumswert]]
==== Datumswert

Datumswerte sind Daten, in denen Angaben zu einem kalendarischen Datum enthalten sind.
Typische Bestandteile eines kalendarischen Datums sind Angaben zu Jahr, Monat und Tag.
Datumswerte können Zeitwerte enthalten, müssen aber nicht.

Beispiele:

* 17. Juli 2017 (reiner Datumswert)
* 9. Juli 2017 14:50 MESZ (Datumswert mit Zeitwert)

[[zeitwert]]
==== Zeitwert

Zeitwerte sind Daten, in denen Angaben zu einem Zeitpunkt enthalten sind.
Typische Bestandteile eines Zeitpunkts sind Angaben zu Stunde, Minute, Sekunden und Zeitzone.
Zeitwerte können Teil von Datumswerten sein, aber selbst keine Datumswerte enthalten.

Beispiele:

* 05:04:23.233 GMT (Zeitwert mit Zeitzone)
* 14:50 (Zeitwert, bestehend nur aus Stunde und Minute)

[[dauer]]
==== Dauer

Eine Dauer ist eine quantifizierte Menge einer Zeiteinheit (z.B. 37 Sekunden, 14 Tage, 3 Jahre). Sie beschreibt eine zeitliche Länge unabhängig konkreter zeitlicher Angaben (z.B. Länge eines Spielfilms). In Verbindung mit einer Datums- oder Zeitangabe wird sie genutzt, um einen Zeitraum zu definieren (z.B. die Ausstrahlung des Spielfilms startet um 20:15 Uhr und endet um 21:50 Uhr).

Für die Zeiteinheiten gelten folgende Abkürzungen, welche für Ein- und Ausgabe benutzt werden können:

//Tab1
.Abkürzungen für Zeiteinheiten
[id="table-AbkZeitEin",reftext="{table-caption} {counter:tables}"]
[cols="4,6",options="header"]
|====
|Abkürzung |Zeiteinheit
|ms |Millisekunde
|s |Sekunde
|min |Minute
|h |Stunde
|d |Tag
|a |Jahr
|====

[[zeitraum]]
==== Zeitraum

Zeiträume bestehen aus zwei Datums- oder Zeitangaben, die den _Start_ und das _Ende_ eines Zeitraums markieren.
Die _Dauer_ des Zeitraums ist die Differenz aus Ende und Start.

[[darstellung]]
=== Darstellung

Die Bibliothek muss Datums- und Zeitwerte für die Anzeige auf grafischen Oberflächen in das in Deutschland gängige Format umwandeln können.
Die Bibliothek muss mindestens die folgenden Darstellungen beherrschen (Bestandteile in Klammern sind optional):

* (Montag,) 17. Juli 2017 14:35:19 (MESZ)
* 17.07.2017 14:35:19 (+02:00)
* 17.07.2017
* 14:35:19

Darüber hinaus muss die Bibliothek so flexibel sein, dass Abweichungen von den Standardformaten in den Anwendungen umgesetzt werden können.

Für die Verwendung an Schnittstellen muss die Bibliothek Datums- und Zeitwerte in eine ISO 8601-konforme Darstellung umwandeln können.
Dazu muss standardmäßig folgendes Format benutzt werden:

[frame="none"]
|====
^|yyyy-MM-dd'T'HH:mm:ssZ
|====

Die Angabe der Zeitzone kann nur dann entfallen, wenn sie global festgelegt wurde oder aus dem Kontext heraus
eindeutig hergeleitet werden kann.

[[eingabe]]
=== Eingabe

Die Bibliothek muss Eingaben von Datums- und Zeitwerten über Schnittstellen aus einer ISO 8601-konformen Darstellung einlesen können.

Eingaben über grafische Oberflächen muss die Bibliothek aus den in Deutschland gängigen Formaten in einen entsprechenden Datums- oder Zeitwert umwandeln können.
Die unterstützten Formate werden in den folgenden Abschnitten definiert.

[[datumswert-1]]
==== Datumswert

Eingaben von Datumswerten müssen Zeichenketten in folgendem Format sein:

[frame="none"]
|====
^|*<Tag>.<Monat>.<Jahr> <Zeitwert>*
|====

//Tab2
.Eingabeformate der Felder von Datumswerten
[id="table-InpFormDat",reftext="{table-caption} {counter:tables}"]
[cols="1,3,1,1",options="header"]
|====
|Feld |Format |Beispiel |Pflichtfeld
|Tag |Ganzzahl (1-31) |3, 03, 14 |Ja
|Monat |Ganzzahl (1-12) |5, 07, 11 |Ja
|Jahr |Ganzzahl (1-9999) |9, 476, 2013 |Ja
|Zeitwert
2+^|s. Kapitel <<zeitwert-1>>
|Nein
|====

<<table-InpFormDat>> zeigt die möglichen Formate der einzelnen Felder.
Anders als in der Anzeige sind keine textuellen Formate für z.B. Wochentage („Montag“) oder Monate („Dezember“) erlaubt. Das Jahr wird immer vollständig interpretiert und darf nicht verkürzt eingegeben werden (z.B. „69“ für „1969“). Anwendungen können eine solche Logik vorsehen, müssen die Jahreszahlen allerdings immer vollständig an den Baustein übergeben.

[[zeitwert-1]]
==== Zeitwert

Eingaben von Zeitwerten müssen Zeichenketten in folgendem Format sein:

[frame="none"]
|====
^|*<Stunde>:<Minute>:<Sekunde>.<Sekundenbruchteile> <Zeitzone>*
|====

//tab3
.Eingabeformate der Felder von Zeitwerten
[id="table-InpFormZeit",reftext="{table-caption} {counter:tables}"]
[cols="1,2,2,1",options="header"]
|====
|Feld |Format |Beispiel |Pflichtfeld
|Stunde |Ganzzahl (0-23) |0, 5, 08, 23 |Ja
|Minute |Ganzzahl (00-59) |00, 04, 23, 59 |Ja
|Sekunde |Ganzzahl (00-59) |00, 08, 44, 59 |Nein
|Sekunden-bruchteile |max.
neunstellige Ganzzahl +
(1-999999999) |127 (ms), +
235674 (µs), 349672834 (ns) |Nein
|Zeitzone |Abweichung von UTC oder +
Name der Zeitzone |+02:30, -05:00 +
oder +
CET, Europe/Berlin |Nein
|====

<<table-InpFormZeit>> zeigt die möglichen Formate der einzelnen Felder.
Alle Angaben außer Stunden müssen vollständig sein und bei Bedarf mit einer vorangestellten Null versehen werden.
Bei Sekundenbruchteilen reichen üblicherweise drei Nachkommastellen, was einer Genauigkeit im Millisekundenbereich entspricht.

[[dauer-1]]
==== Dauer

Eingaben einer Dauer müssen Zeichenketten in folgendem Format sein:

[frame="none"]
|====
^|*<Anzahl><Zeiteinheit> (<Anzahl><Zeiteinheit> …)*
|====

//Tab4
.Eingabeformate der Felder von Zeitwerten
[id="table-InpFormdauer",reftext="{table-caption} {counter:tables}"]
[cols="1,3",options="header"]
|====
|Feld |Format
|Anzahl |Ganzzahl
|Zeiteinheit |Abkürzung der Zeiteinheit (s. Tabelle <<table-AbkZeitEin>>)
|====

Eine Dauer muss mindestens eine Zeiteinheit beinhalten („37s“), kann aber auch aus mehreren bestehen („1h 28min“). Die Zeiteinheiten müssen von der gröbsten (Jahr) zur feinsten (Millisekunde) hin sortiert sein.

[[zeitraum-1]]
==== Zeitraum

Zeiträume sind kein eigener Datentyp, sondern werden durch zwei Werte beschrieben.
So gibt es zwei Möglichkeiten, einen Zeitraum darzustellen. Entweder

* Ein Anfang und ein Ende beschrieben durch zwei Datums- oder Zeitwerte oder
* Ein Anfang beschrieben durch einen Datums- oder Zeitwert sowie eine Dauer.

Die Bibliothek muss zur Eingabe eines Zeitraums diese Kombinationen von Werten unterstützen,
deren Format gemäß der Anforderungen der Kapitel <<datumswert-1>> bis <<dauer-1>> beschaffen sein muss.
<<table-InpFormZRaum>> zeigt Beispiele für die Eingabewerte von Zeiträumen.

//Tab5
.Eingabewerte für Zeiträume
[id="table-InpFormZRaum",reftext="{table-caption} {counter:tables}"]
[cols="1,1,2",options="header"]
|====
|1. Wert |2. Wert |Beispiel
|Datumswert |Datumswert |12.7.2017 14:00, 13.09.2018 19:00
|Datumswert |Dauer |12.8.2013, 14 d
|Zeitwert |Zeitwert |13:40:00, 15:45:12
|Zeitwert |Dauer |12:00, 90min 15s
|====

[[persistierung]]
=== Persistierung

Die Persistierung von Angaben zu Datum, Zeit, Dauer, Zeiträumen und  <<ungewisse-datums-und-zeitwerte,ungewissen Datums- und Zeitangaben>> wird durch den xref:isy-persistence:konzept/vorgaben-konventionen.adoc#behandlung-von-zeitangaben[Baustein JPA/Hibernate] behandelt.

[[berechnungen]]
=== Berechnungen

Die Bibliothek muss bestimmte Berechnungen auf Datumswerten, Zeitwerten und Zeiträumen bereitstellen.

[[datums--zeitwert]]
==== Datums- & Zeitwert

Die Bibliothek muss die folgenden Berechnungen auf Datums- & Zeitwerten ermöglichen:

* Chronologische Sortierung einer Menge von Datums- und Zeitwerten
* Chronologische Vergleiche zwischen Datums- und Zeitwerten +
 („früher als“, „später als“, „gleichzeitig“)
* Ermittlung des „Tagesdatums“ (der zeitliche Anteil eines Datumswerts wird auf 0, d.h. auf Mitternacht, gestellt)
* Berechnung des Abstands („Dauer“) zwischen zwei Datums- oder Zeitwerten
* Addition und Subtraktion von Datums- und Zeitwerten mit einer Dauer
* Prüfung, ob zwei Datumswerte für zwei direkt aufeinanderfolgende Tage stehen ("Liegt der 28.2.2016 direkt vor dem 1.3.2016?“)
* Berechnung des nächsten Werktags nach einem übergebenen Datumswert

[[zeitraum-2]]
==== Zeitraum

Die Bibliothek muss die folgenden Berechnungen auf Zeiträumen ermöglichen:

* Prüfung, ob ein Datumswert in einem Zeitraum liegt
** Liegt der 18. Juli 2017 zwischen dem 4. Juli 2016 und dem 6. Dezember 2017?
* Prüfung, ob sich zwei Zeiträume überlappen

[[ungewisse-datums-und-zeitwerte]]
=== Ungewisse Datums- und Zeitwerte

Die Bibliothek muss sogenannte _ungewisse_ Datums- und Zeitwerte verarbeiten können.
Dabei sind Teile eines Datums- oder Zeitwerts zunächst ungewiss.
Die Bibliothek muss die Möglichkeit vorsehen, solche ungewissen Angaben später zu konkretisieren.

//tab 6
.Konkretisierung eines ungewissen Datums
[id="table-KonkretunDat",reftext="{table-caption} {counter:tables}"]
[cols="3,2",options="header"]
|====
|Erkenntnisse |Wert
|Initiale Erkenntnis: Vom Geburtsdatum einer Person ist nur das Jahr bekannt |Geburtsdatum: +
1.1.1976 – 31.12.1976
|Zusätzliche Erkenntnis: Die Person ist im Juni des Jahres geboren.
Der Tag ist zweistellig. |Geburtsdatum: +
10.6.1976 – 30.6.1976
|Zusätzliche Erkenntnis: Die Person ist am 24.
geboren. |Geburtsdatum: +
24.6.1976 – 24.6.1976
|====


<<table-KonkretunDat>> zeigt einen beispielhaften Verlauf einer Konkretisierung eines Datumswerts: Das Datum ist zunächst ungewiss, wird durch spätere Erkenntnisse aber schlussendlich zu einem Datum ohne Ungewissheit konkretisiert.
Es gibt eine Einschränkung bei der Konkretisierung ungewisser Datums- und Zeitwerte.
Da die Ungewissheit durch Zeiträume abgebildet wird, müssen ungewisse Datums- und Zeitwerte immer einen in sich abgeschlossenen Zeitraum bilden.
Nicht abbildbar ist z.B. „Geburtsdatum: der 24.
eines beliebigen Monats des Jahres 1976“, da dies nicht als Zeitraum darstellbar ist.

Die Anforderungen zur Konkretisierung gelten ebenso für Zeitangaben.
<<table-KonkretunZeit>> verdeutlicht dies in einem beispielhaften Verlauf.

.Konkretisierung einer ungewissen Zeit
[id="table-KonkretunZeit",reftext="{table-caption} {counter:tables}"]
[cols="3,2",options="header"]
|====
|Erkenntnisse |Wert
|Initiale Erkenntnis: Das Ereignis fand nach Mittag statt.             |Start des Ereignisses: 12:01 – 23:59
|Zusätzliche Erkenntnis: Das Ereignis fand vor 18 Uhr statt.           |Start des Ereignisses: 12:01 – 17:59
|Zusätzliche Erkenntnis: Das Ereignis fand um Viertel nach Drei statt. |Start des Ereignisses: 15:15 – 15:15
|====

[[testunterstuetzung]]
=== Testunterstützung

Zur Unterstützung des Tests muss die Bibliothek es erlauben, die aktuelle Systemzeit mit eigenen Werten zu überschreiben, um Abläufe in der Vergangenheit oder Zukunft darstellen zu können.

[[vorgaben]]
== Vorgaben

Die folgenden architektonischen und technischen Vorgaben beziehen sich auf die Umsetzung der
in Kapitel <<anforderungen>> genannten Anforderungen in der zu diesem Baustein gehörenden Bibliothek.

[[namenskonventionen]]
=== Namenskonventionen

Die Bibliothek besitzt die folgenden Maven-Koordinaten:

* Group-ID: `de.bund.bva.isyfact`
* Artifact-ID: `isy-datetime`

Das Stammpackage für alle Klassen der Umsetzung setzt sich aus Group-ID und Artifact-ID zusammen und lautet: `de.bund.bva.isyfact.datetime`.

[[bedeutung-der-standardbibliothek]]
=== Bedeutung der Standardbibliothek

Die Bibliothek muss zur Umsetzung der Anforderungen so stark wie möglich auf die im JSR 310 beschriebene API setzen.
Falls einige der Anforderungen aus dem Kapitel <<anforderungen>> komplett durch die Funktionalität dieser API abgedeckt sind, wird in den xref:nutzungsvorgaben/master.adoc[Nutzungsvorgaben] die entsprechende Verwendung der API mit Verweis auf die Standarddokumentation knapp erläutert.
Abweichungen von der API oder eigene Implementierungen bereits vorhandener Funktionalität müssen in den Nutzungsvorgaben begründet und beschrieben werden.

[[verwendung-der-standardbibliothek]]
=== Verwendung der Standardbibliothek

Innerhalb von Anwendungen können alle Typen des „JSR 310: Date and Time API“ verwendet werden, insofern dieses Konzept an anderer Stelle die Nutzung nicht weiter einschränkt.

Die Bibliothek muss sicherstellen, dass die gesamte Funktionalität für alle geeigneten Typen angeboten wird und an geeigneten Stellen sinnvolle Umwandlungen (d.h. ohne Verlust von Daten oder Genauigkeit) möglich sind.

[[darstellung-eingabe]]
=== Darstellung & Eingabe

Die Bibliothek wird zur Umsetzung der Darstellung sowie Eingabe keine konkrete Technologie zur Erstellung
grafischer Oberflächen unterstützen.
Stattdessen muss sie die Funktionalität auf Basis der Standardbibliothek bereitstellen, damit sie leicht von
GUI-Technologien verwendet werden kann.
Zum Ausgeben von Werten und Einlesen von Eingaben muss die Bibliothek die Klasse `java.time.format.DateTimeFormatter`
verwenden und, falls nötig, auf die in Deutschland gängigen Formate hin konfigurieren oder Funktionen anbieten, um
gängige Formate leicht ausgeben und einlesen zu können.
Eine Reihe von Standardformaten, welche die Bibliothek unterstützen muss, sind im Kapitel <<darstellung>> beschrieben.

[[ungewisse-datums--und-zeitwerte-1]]
=== Ungewisse Datums- und Zeitwerte

Die Bibliothek muss zur Behandlung ungewisser Datums- und Zeitwerte die folgende Funktionalität bereitstellen:

* Definition der Datenobjekte zur Verwendung ungewisser Datums- und Zeitwerte im Anwendungskern
* Definition der Transportobjekte zur Übermittlung ungewisser Datums- und Zeitwerte über Schnittstellen
* Formatierung ungewisser Daten zur Anzeige
* Einlesen ungewisser Daten nach Eingabe durch Anwender

Bisherige Implementierungen ungewisser Datumswerte setzen immer den Sonderfall um, bei dem entweder der Tag, Tag und Monat oder alle Teile eines Datumswerts unbekannt sind.
Die Anzeige und Eingabe dieser unbekannten Werte erfolgt hierbei über Nullen, wie <<table-OldUmunZeitw>> zeigt.

.Bisherige Umsetzung ungewisser Datumswerte
[id="table-OldUmunZeitw",reftext="{table-caption} {counter:tables}"]
[cols=",,",options="header"]
|====
|Sonderfall |Eingabe / Darstellung |Intern
|Tag unbekannt |00.05.1966 |Zeichenkette: „00.05.1966“
|Tag und Monat unbekannt |00.00.1966 |Zeichenkette: „00.00.1966“
|Datum komplett unbekannt |00.00.0000 |Zeichenkette: „00.00.0000“
|====

Der Hauptnachteil dieser Umsetzung besteht darin, dass die Datumswerte durch ihre interne Darstellung als Zeichenkette nur mit großem Aufwand mit anderen Datumswerten verglichen bzw.
in Berechnungen verwendet werden können.
Trotzdem muss die Bibliothek ungewisse Datumswerte dieser Art einlesen und ausgeben können.
Die Werte werden beim Einlesen intern in entsprechende Zeiträume umgewandelt und bei der Darstellung wieder in die ursprüngliche Form überführt.
Eine Übersicht dieses Vorgangs zeigt <<table-UmsSonderNull>>.

.Umsetzung der Sonderfälle (mit Nullen)
[id="table-UmsSonderNull",reftext="{table-caption} {counter:tables}"]
[cols=",,",options="header"]
|====
|Sonderfall |Eingabe / Darstellung |Intern
|Tag unbekannt |00.05.1966 |Zeitraum: 1.5.1966 – 31.5.1966
|Tag und Monat unbekannt |00.00.1966 |Zeitraum: 1.1.1966 – 31.12.1966
|Datum komplett unbekannt |00.00.0000 |Zeitraum: nicht gesetzt (null)
|====

Des Weiteren muss die Bibliothek die Eingabe unbekannter Datums- oder Zeitbestandteile mittels „x“ unterstützen.
Diese Möglichkeit wird die Eingabe unbekannter Datums- oder Zeitbestandteile mittels Nullen mittelfristig ablösen.
Die Eingabe mittels „x“ ermöglicht die oben genannten Sonderfälle auch für Zeitwerte, bei denen im Unterschied zu Datumswerten „0“ ein korrekter Wert für die jeweiligen Bestandteile (Stunde, Minute und Sekunde) ist.
Eine Übersicht der so umgesetzten Spezialfälle zeigt <<table-UmsSonderX>>.

.Umsetzung der Sonderfälle (mit „x“)
[id="table-UmsSonderX",reftext="{table-caption} {counter:tables}"]
[cols=",,",options="header"]
|====
|Sonderfall |Eingabe / Darstellung |Intern
|Tag unbekannt |xx.05.1966 |Zeitraum: +
1.5.1966 – 31.5.1966
|Tag und Monat unbekannt |xx.xx.1966 |Zeitraum: +
1.1.1966 – 31.12.1966
|Datum komplett unbekannt |xx.xx.xxxx |Zeitraum: +
nicht gesetzt (null)
|Sekunde unbekannt |14:34:xx |Zeitraum: +
14:34:00 – 14:34:59
|Sekunde und Minute unbekannt |14:xx:xx |Zeitraum: +
14:00:00 – 14:59:59
|Zeit komplett unbekannt |xx:xx:xx |Zeitraum: +
nicht gesetzt (null)
|====

[[testunterstützung-1]]
=== Testunterstützung

Die Umsetzung der Testunterstützung geschieht über das Mocken der Klasse `java.time.Clock`.
Dazu muss die Bibliothek bei der Erzeugung von Datums- und Zeitangaben die Varianten mit einer `Clock` als Parameter
benutzen und in der Konfiguration eine `Clock` als Abhängigkeit definieren.
Des Weiteren müssen sich auch Anwendungen an diese Vorgabe halten, um die Testunterstützung nutzen zu können.
Insbesondere sind Aufrufe von `System.currentTimeMillis()` sowie der Varianten von `now()` auf Typen der Datums- und
Zeittypen ohne Verwendung einer `Clock` bei Nutzung dieses Bausteins verboten!
// end::inhalt[]

// tag::architekturregel[]

// end::architekturregel[]

// tag::sicherheit[]

// end::sicherheit[]
