= Konzept Datum & Zeit: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Dokument beschreibt die konzeptionellen Grundlagen der Verarbeitung von Datums- und Zeitwerten in der IsyFact.
Es definiert Vorgaben für die einheitliche Verwendung von Datums- und Zeitfunktionen sowie die Behandlung von
Datums- und Zeitwerten in Anwendungen und bildet so die Grundlage einer technisch und fachlich einheitlichen Umsetzung.

Die aus diesem Dokument abgeleitete Umsetzung der Verarbeitung von Datums- und Zeitwerten im Rahmen der
Anwendungsentwicklung ist in den xref:nutzungsvorgaben/master.adoc[Nutzungsvorgaben] beschrieben.

Sowohl dieses Dokument als auch das Umsetzungsdokument bedienen sich Projekterfahrungen sowie Best
Practices und setzen auf die Datums- und Zeitfunktionen des JSR 310 („Date and Time API“), die mit Java 8 eingeführt wurden.

NOTE: JSR 310: https://jcp.org/en/jsr/detail?id=310[Date and Time API]

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

Ziel des Dokuments ist die Definition einheitlicher Vorgaben für die Verarbeitung von Datums- und Zeitwerten unter Berücksichtigung fachlicher und technischer Anforderungen.

Das Dokument ist entsprechend dieser Zielsetzungen folgendermaßen aufgebaut:

Zunächst werden die *Anforderungen* an die Verarbeitung von Datums- und Zeitwerten definiert, welche die Grundlage für das nachfolgende Kapitel bilden.

Anschließend werden die *Vorgaben* zur Verwendung von Datums- und Zeitwerten innerhalb der Anwendungen sowie zur Umsetzung in der zu diesem Baustein gehörenden Bibliothek definiert.
// end::inhalt[]
