= Einrichtung Entwicklungsumgebung: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung
In diesem Dokument wird die Installation einer Entwicklungsumgebung erläutert, um Anwendungen mit der IsyFact zu entwickeln. Es richtet sich an Entwickler, die zum ersten Mal mit der xref:glossary:glossary:master.adoc#glossar-IsyFact[IsyFact] in Berührung kommen und möglichst schnell mit der Entwicklung einer Anwendung auf Basis der IsyFact beginnen möchten.

Bei der Softwareentwicklung werden Entwicklungsumgebungen (IDEs) wie Eclipse oder IntelliJ IDEA verwendet, welche die Anwendungsentwicklung in vielfältiger Weise unterstützen und effektiver gestalten.

Eine der unterstützenden Leistungen dieser IDEs, ist die einheitliche Formatierung des Quellcodes.
Hier ist die Maßgabe, dass der Quellcode nicht je nach Einsatz einer IDE unterschiedlich aussieht.
Dies kann, wenn in einem Team unterschiedliche IDEs verwendet werden, zu ständigen Wechseln der Formatierung führen, die sich in unnötig großen Commits ausdrücken.

Ebenso helfen Entwicklungsumgebungen dabei, Standard-Implementierungen für Konstruktoren, Getter/Setter und die Methoden `equals()` und `hashCode()` zu generieren.

Eine weitere Unterstützung ist die automatische Prüfung von Codierungsrichtlinien mit _Checkstyle_.
Die IsyFact liefert eine Konfiguration für _Checkstyle_ mit.

Dieses Dokument beschreibt die Einrichtung und Verwendung dieser Funktionen wie folgt:

Das Kapitel xref::einrichtung_entwicklungsumgebung/inhalt.adoc#formatierung-von-quellcode[Formatierung von Quellcode] beschreibt die einheitliche Konfiguration und Verwendung der in Eclipse und IntelliJ IDEA eingebauten Code-Formatierer.
Die Konfiguration hat zum Ziel, den Quellcode in beiden IDEs nahezu identisch formatiert zu formatieren.
Das Kapitel schließt mit einer kurzen Diskussion der verbleibenden Unterschiede bei der Formatierung.

Das Kapitel xref::einrichtung_entwicklungsumgebung/inhalt.adoc#generierung-von-equals-und-hashcode[Generierung von equals() und hashCode()] beschreibt insbesondere die Generierung von `equals()` und `hashCode()` konform zu den xref:methodik:java-programmierkonventionen/master.adoc[Java Programmierkonventionen].

Im Kapitel xref::einrichtung_entwicklungsumgebung/inhalt.adoc#einrichtung-von-checkstyle[Einrichtung von Checkstyle] wird die Installation und Einrichtung der Checkstyle-Plugins für Eclipse und IntelliJ IDEA beschrieben.
// end::inhalt[]
