= Neue Dokumente anlegen

include::glossary:licence:partial$licence.adoc[]

In diesem Kapitel wird für die xref:dokumentation/einleitung/einfuehrung.adoc#zentrale-dokumentation[Zentrale Dokumentation] gezeigt, wie die erforderliche Verzeichnisstruktur aussieht und wie ein neues Dokument dort einsortiert wird.

[[neues-verzeichnis-zentrale-dokumentation-anlegen]]
== Zentrale Dokumentation: Ein neues Verzeichnis anlegen

Die zentrale Dokumentation der IsyFact-Standards gliedert sich nach den Säulen der IsyFact.

Allgemein;; Einstiegsdokumente, Tutorial, Konventionen
Blaupausen;; Grundlagendokumente und Detailkonzepte für Architektur und Anwendungslandschaft
Bausteine;; Dokumente für die jeweiligen wiederverwendbaren Softwarelösungen
Methodik;; Methodische Dokumente bspw. zu Programmierkonventionen und Systemhandbuch und -entwurf
Werkzeuge;; Dokumente zur Verwendung von Werkzeugen und der Einrichtung der Entwicklungsumgebung (hierzu gehört auch dieses Dokument)

Ein neues IsyFact-Dokument muss unterhalb einer geeigneten Säule abgelegt werden.
Dazu wird unterhalb des Verzeichnisses, das die Säule repräsentiert, ein neues Verzeichnis
angelegt, dessen Name den Inhalt des Dokuments widerspiegelt.


[[neues-verzeichnis-bausteindokumentation-anlegen]]
=== Dokumentation eines Bausteins: Ein neues Verzeichnis anlegen

Soll für einen Baustein eine neue Dokumentation angelegt werden oder die bestehende Dokumentation um ein Dokument erweitert werden, so muss zunächst der geeignete Ort zur Ablage bestimmt werden.
I.d.R. ist dies das Repository, in dem sich der Baustein befindet, da die Dokumentation nah beim Code abgelegt werden soll.
Früher befand sich jedoch ein großer Teil der Bausteindokumentation im Repository `isy-documentation`.

Aktuell liegt dieser Teil der Bausteindokumentation im Repository `isyfact-standards` im Submodul `isyfact-standards-doc`.
Der Code dieser Bausteine befindet sich ebenfalls im Repository `isyfact-standards`, wodurch die Architekturregel "Dokumentation nah beim Code" erfüllt ist.

Zunächst muss der Baustein vom Git-Repository heruntergeladen werden.
Hierfür muss auf der Kommandozeile auf eine geeignete Stelle der lokalen Festplatte gewechselt werden und folgendes Kommando eingegeben werden.

====
C:\tmp\> *git clone* https://github.com/IsyFact/<Repository>

z.B. C:\tmp\> *git clone* https://github.com/IsyFact/isy-baustein
====

Bei <Repository> kann es sich um einen einzelnen Baustein handeln oder um ein Repository mit zentraler Dokumentation wie z.B. `isyfact-standards`.

In einem Baustein wird die Dokumentation in einem eigenen Maven-Submodul unter dem Pfad `src/docs` abgelegt.

<<verzeichnisstruktur-baustein>> zeigt die Verzeichnisstruktur für die Dokumentation des fiktiven Bausteins `isy-baustein` zusammen mit den AsciiDoc-Dateien für ein Dokument.

[[verzeichnisstruktur-baustein]]
.Verzeichnisse der Bausteindokumentation
----
📂 isy-baustein
  📂 isy-baustein-doc <1>
    📂 src
        📂 docs
            📂 Konzept <2>
                📄 anhaenge.adoc  <3>
                📄 docinfo.adoc
                📄 inhalt.adoc    <4>
                📄 master.adoc    <5>
                📄 thisdoc.adoc   <6>
                📂 images <7>
            📂 Nutzungsvorgaben <2>
                📄 anhaenge.adoc
                📄 docinfo.adoc
                📄 inhalt.adoc
                📄 master.adoc
                📄 thisdoc.adoc
                📂 images
----
<1> Maven-Submodul für die Dokumentation.
<2> Jeweils ein Dokument; bei Bausteinen findet sich häufig die Unterteilung in Konzept und Nutzungsvorgaben.
<3> Auflistung der Anhänge des Dokuments.
<4> Inhalte des Dokuments.
<5> Zentrale Datei, die alle anderen Dateien über spezielle Verweise (`include`) einbindet.
<6> Einleitendes Kapitel des Dokuments, das den Inhalt zusammenfasst sowie den Aufbau und Zweck des Dokuments erläutert.
<7> Bilder und Grafiken, die im neu zu erstellenden Dokument verwendet werden sollen.

TIP: Eine vollständige Vorschau des Dokuments wird angezeigt, wenn die Datei `master.adoc` im Editor geöffnet und die Vorschaufunktion verwendet wird.

[[dokument-struktur]]
== Struktur eines Dokuments

Wie bereits <<verzeichnisstruktur-baustein,im vorigen Abschnitt>> beschrieben, besteht ein Dokument aus mehreren Dateien.
Die folgenden Abschnitte beschreiben diese Dateien, stellen Vorlagen bereit und erklären Einstellungsmöglichkeiten in Form von Attributen.

[[master.adoc]]
=== `master.adoc`

Die Datei `master.adoc` fasst alle anderen Dateien zu einem Dokument zusammen.
Die <<listing-master,folgende Vorlage>> zeigt den Aufbau der Datei.

[[listing-master]]
.Vorlage für `master.adoc`
[source,asciidoc]
----
:doctitle: Neuer Baustein
:document-type: Konzept
:vs-einstufung: offen

// :revnumber: 1.0.5
// :revdate: 2020-01-01

colophon::[factory="IsyFact-Erweiterungen", open-source="false"]

\include::docinfo.adoc[]

\include::thisdoc.adoc[tags=inhalt]

\include::inhalt.adoc[tags=inhalt]

:sectnums!:

\include::anhaenge.adoc[tags=inhalt]
----

Am Anfang der Datei werden die Attribute `doctitle` und `document-type` gesetzt, aus denen ein einheitlicher Titel erzeugt wird.

Dann wird die Vertraulichkeitseinstufung `vs-einstufung` angegeben.
Dadurch wird ggf. ein Vertraulichkeitshinweis in das Dokument eingefügt und ggf. das Layout angepasst.
Die möglichen Werte für `vs-einstufung` finden sich in <<table-master-attributes,Übersicht der Attribute>>.

TIP: Die `vs-einstufung` kann auch xref:dokumentation/generierung/generierung-asciidoctorj.adoc#listing-pom-asciidoc[im Maven-POM] als globales Attribut für alle zu generierenden Dokumente angegeben werden.

Die manuelle Vergabe von Revisionsnummer und -datum betrifft nur Dokumente, die nicht mithilfe des Maven-Plugins erzeugt werden.
Ansonsten werden diese Attribute xref:dokumentation/generierung/generierung-asciidoctorj.adoc#listing-pom-asciidoc[über das Maven-Plugin] bereitgestellt.

<<table-master-attributes,Die folgende Tabelle>> zeigt alle Attribute, die in der `master.adoc` gesetzt werden können.

[[table-master-attributes]]
.Attribute der `master.adoc`
[cols="3,1,4,4",options="header"]
|===
|Attribut|Optional|Beschreibung|Werte
|`doctitle`|Nein|Titel des Dokuments|
|`document-type`|Ja|Dokumententyp (z.B. Konzept), welcher als Untertitel angezeigt wird|
|`vs-einstufung`|Nein|Vertraulichkeitseinstufung
a|
* open-source
* offen
* einstufung-fehlt
* vs-nfd
* vs-vertraulich
* geheim
* streng-geheim
|`revdate`|Nein|Release Datum des Bausteins oder Dokuments|
|`revnumber`|Nein|Versionsnummer des Bausteins oder Dokuments|
|===

Nach den Attributen wird der Kolophon eingebunden.
Dadurch wird ein einheitlicher Abschnitt mit Metadaten des Dokuments und Lizenzbestimmungen erzeugt.
Dabei können noch die optionalen <<kolophon-attributes,Parameter>> `factory` und `open-source` angegeben werden.

[[kolophon-attributes]]
.Parameter des Kolophons
[cols="2m,1,1,3,2a",options="header"]
|===
|Parameter|Optional|Default|Beschreibung|Werte
|factory|Ja|IsyFact-Standards|Definiert, ob das Dokument zu den IsyFact-Standards oder IsyFact-Erweiterungen gehört. Wählt das passende Logo und Deckblatt für die Factory.
|* IsyFact-Standards
* IsyFact-Erweiterungen
* Register Factory
|open-source|Ja|`true`|Beschreibt, ob das Dokument unter der Open Source (`true`) oder Closed Source (`false`) Lizenz der IsyFact veröffentlicht wird.|
|===

Nach dem Kolophon werden die übrigen AsciiDoc-Dateien in `master.adoc` inkludiert.
Leere Dateien können ausgelassen werden.
Inkludiert wird der Inhaltsbereich innerhalb der Dateien, der mit entsprechenden Tags gekennzeichnet ist.


[[docinfo.adoc]]
=== `docinfo.adoc`

Dokumente können sich direkt auf Bibliotheken oder IT-Systeme beziehen.
Ist dies der Fall, so werden diese Bibliotheken oder IT-Systeme in einer Datei `docinfo.adoc` angegeben.
Neben dem technischen Namen muss auch die Version angegeben werden, auf die sich das Dokument bezieht.
Die `docinfo.adoc` Datei wird dann in `master.adoc` direkt nach dem Kolophon eingebunden.

Die <<template-docinfo,folgende Vorlage>> zeigt den Aufbau der Datei.

[[template-docinfo]]
.Vorlage für `docinfo.adoc`
[source,asciidoc]
----
*Java Bibliothek / IT-System*

[cols="5m,2,3",options="header"]
|====
|Name |Art |Version
|<Technischer Name> |Bibliothek | <Version>
|<Technischer Name> |IT-System  | <Version>
|====
----

[[thisdoc.adoc]]
=== `thisdoc.adoc`

Die Datei `thisdoc.adoc` bietet eine Einleitung in das Dokument und erläutert den Aufbau und Zweck des Dokuments.
Die <<template-thisdoc,folgende Vorlage>> zeigt den Aufbau der Datei.

[[template-thisdoc]]
.Vorlage für `thisdoc.adoc`
[source,asciidoc]
----
= Konzept: Neuer Baustein - Einleitung
:imagesdir: images

// tag::inhalt[]

== Einleitung
// Einordnung des Dokuments

=== Aufbau und Zweck des Dokuments
// Informationen zur Zielgruppe des Dokuments
// Kurze Zusammenfassung des Aufbaus
// Auflistung der Kapitel und ihrer Kerninhalte

// end::inhalt[]
----

[[inhalt.adoc]]
=== `inhalt.adoc`

In `inhalt.adoc` wird der eigentliche Inhalt des Dokuments verfasst.
Die <<template-inhalt,folgende Vorlage>> zeigt den Aufbau der Datei.

[[template-inhalt]]
.Vorlage für `inhalt.adoc`
[source,asciidoc]
----
= Konzept: Neuer Baustein - Inhalt
:imagesdir: images

// tag::inhalt[]

// Eigentlicher Inhalt des Dokuments

== Erstes Thema
...

== Zweites Thema
...

// end::inhalt[]
----

[[anhaenge.adoc]]
=== `anhaenge.adoc`

In `anhaenge.adoc` sind Anhänge zum Dokument platziert.
Die <<template-anhaenge,folgende Vorlage>> zeigt den Aufbau der Datei.

[[template-anhaenge]]
.Vorlage für `anhaenge.adoc`
[source,asciidoc]
----
= Konzept: Neuer Baustein - Anhänge
:imagesdir: images

// tag::inhalt[]

== Anhang A: Titel
// Inhalt des Anhangs

== Anhang B: Titel
// Inhalt des Anhangs

// end::inhalt[]
----