// tag::inhalt[]

[[ein-neues-dokument-anlegen]]
== Ein neues Dokument anlegen

In diesem Kapitel wird jeweils für die xref:dokumentation/einleitung/einleitung.adoc#zentrale-dokumentation[Zentrale Dokumentation], als auch für die  xref:dokumentation/einleitung/einleitung.adoc#baustein-dokumentation[Bausteindokumentation] gezeigt, wie die erforderliche Verzeichnisstruktur aussieht und wie ein neues Dokument dort einsortiert wird.

[[neues-verzeichnis-zentrale-dokumentation-anlegen]]
=== Zentrale Dokumentation: Ein neues Verzeichnis anlegen

Die zentrale Dokumentation hat im Vergleich zur Bausteindokumentation eine erweiterte Verzeichnisstruktur.
Die zentrale Dokumentation der IsyFact-Standards gliedert sich nach den Säulen der IsyFact.

Allgemein;; Einstiegsdokumente, Tutorial, Konventionen
Blaupausen;; Grundlagendokumente und Detailkonzepte für Architektur und Anwendungslandschaft
Bausteine;; Dokumente für die jeweilig wiederverwendbaren Softwarelösungen
Methodik;; Methodische Dokumente bspw. zu Programmierkonventionen und Systemhandbuch und -entwurf
Werkzeuge;; Dokumente zur Verwendung von Werkzeugen und der Einrichtung der Entwicklungsumgebung (hierzu gehört auch dieses Dokument)

Ein neues IsyFact-Dokument muss unterhalb einer geeigneten Säule abgelegt werden.
Dazu wird unterhalb des Verzeichnisses, das die Säule repräsentiert, ein neues Verzeichnis
angelegt, dessen Name den Inhalt des Dokuments widerspiegelt.


[[neues-verzeichnis-bausteindokumentation-anlegen]]
=== Bausteindokumentation: Ein neues Verzeichnis anlegen

Soll für einen Baustein eine neue Dokumentation angelegt werden oder die bestehende Dokumentation um ein Dokument erweitert werden, so muss zunächst der geeignete Ort zur Ablage bestimmt werden.
I.d.R. ist dies das Repository, in dem sich der Baustein befindet, da die Dokumentation nah beim Code abgelegt werden soll.
Bis zur IsyFact 2.4.x befindet sich jedoch ein großer Teil der Bausteindokumentation im Repository isy-documentation.

Ab IsyFact 2.5.0 liegt dieser Teil der Bausteindokumentation im Repository isyfact-standards im Submodul isyfact-standards-doc.
Der Code dieser Bausteine befindet sich ebenfalls im Repository isyfact-standards, wodurch die Architekturregel "Dokumentation nah beim Code" erfüllt ist.

Zunächst muss der Baustein vom Git-Repository heruntergeladen werden.
Hierfür muss auf der Kommandozeile auf eine geeignete Stelle der lokalen Festplatte gewechselt werden und folgendes Kommando eingegeben werden.

====
C:\tmp\> *git clone* https://github.com/IsyFact/<Repository>

z.B. C:\tmp\> *git clone* https://github.com/IsyFact/isy-baustein
====

Bei <Repository> kann es sich um einen einzelnen Baustein handeln oder um ein Repository mit zentraler Dokumentation wie isy-documentation (bis IsyFact 2.4.x) oder isyfact-standards (ab IsyFact 2.5.0).

In einem Baustein wird die Dokumentation in einem eigenen Maven-Submodul unter dem Pfad `src/docs` abgelegt.

<<verzeichnisstruktur-baustein>> zeigt die Verzeichnisstruktur für die Dokumentation des fiktiven Bausteins `isy-baustein` zusammen mit den Asciidoc-Dateien für ein Dokument.

[[verzeichnisstruktur-baustein]]
.Verzeichnisse der Bausteindokumentation
----
📂 isy-baustein
  📂 isy-baustein-doc <1>
    📂 src
        📂 docs
            📂 Konzept <2>
                📄 anhaenge.adoc  <3>
                📄 inhalt.adoc    <4>
                📄 master.adoc    <5>
                📄 thisdoc.adoc   <6>
                📂 images <4>
            📂 Nutzungsvorgaben <2>
                📄 anhaenge.adoc
                📄 inhalt.adoc
                📄 master.adoc
                📄 thisdoc.adoc
                📂 images
----
<1> Maven-Submodul für die Dokumentation.
<2> Jeweils ein Dokument; bei Bausteinen findet sich häufig die Unterteilung in Konzept und Nutzungsvorgaben.
<3> Auflistung der Anhänge des IsyFact-Dokuments.
<4> Inhalte des IsyFact-Dokuments.
<5> Zentrale Datei, die alle anderen Dateien über spezielle Verweise (`include`) einbindet.
Eine vollständige Vorschau des IsyFact-Dokuments wird angezeigt, wenn die Datei `master.adoc` im Editor geöffnet und die Vorschaufunktion verwendet wird.
<6> Einleitendes Kapitel des IsyFact-Dokuments, das den Inhalt zusammenfasst sowie den Aufbau und Zweck des Dokuments erläutert.
<7> Bilder und Grafiken, die im neu zu erstellenden Dokument verwendet werden sollen.


[[dateien-bearbeiten]]
=== Dateien bearbeiten

Dieser Abschnitt beschreibt, welche Attribute und Inhalte in den Dateien angepasst werden können.

[[master.adoc-bearbeiten]]
==== master.adoc bearbeiten

Zunächst werden die Attribute `doctitle` und `document-type` gesetzt, aus denen ein einheitlicher Titel erzeugt wird, vgl. <<listing-master>>.

Dann wird die Vertraulichkeits-Einstufung `vs-einstufung` angegeben.
Dadurch wird ggf. ein Vertraulichkeitshinweis in das Dokument eingefügt und ggf. das Layout angepasst.
Die möglichen Werte für `vs-einstufung` finden sich in <<table-master-attributes>>.
Die `vs-einstufung` kann auch in der pom.xml als globales Attribut für alle zu generierenden Dokumente angegeben werden.
Ein Beispiel findet sich in <<listing-pom-asciidoc>>.

Daraufhin wird die Colophon-Angabe eingebunden.
Dadurch wird ein einheitlicher Abschnitt mit Metadaten des Dokuments und Lizenzbestimmungen erzeugt.
Dabei können noch die optionalen Attribute `factory` und `open-source` angegeben werden.
Sie sind in <<table-master-attributes>> näher beschrieben.

Weitere Erläuterungen zum Colophon Block finden sich im Abschnitt <<colophon-block>>.

[[listing-master]]
.master.adoc
[source,asciidoc,indent=0]
----
 :doctitle: Super tolles Feature
 :document-type: Konzept
 :vs-einstufung: offen

colophon::[factory="IsyFact-Erweiterungen", open-source="false"]

 // Wird normalerweise vom Maven-Plugin gesetzt
 // :revnumber: 1.0.5
 // :revdate: 2020-01-01

\include::thisdoc.adoc[tags=inhalt]

\include::inhalt.adoc[tags=inhalt]
----

NOTE: Die manuelle Vergabe von Revisionsnummer und -datum betrifft nur Dokumente, die nicht mit Hilfe des Maven-Plugins erzeugt werden.
Ansonsten werden diese Attribute über das Maven-Plugin bereitgestellt (siehe <<listing-pom-asciidoc>>).

<<table-master-attributes>> zeigt alle Attribute, die in der `master.adoc` Datei angepasst werden können.

[[table-master-attributes]]
.Attribute der master.adoc
[cols="1,1,1,3,1",options="header"]
|===
|Attribut|Optional|Default|Beschreibung|Werte
|`doctitle`|Nein||Titel des Dokuments|
|`document-type`|Ja||Dokumententyp (z.B. Konzept), welcher als Untertitel angezeigt wird|
|`vs-einstufung`|Nein||Vertraulichkeits-Einstufung
a|
* open-source
* offen
* einstufung-fehlt
* vs-nfd
* vs-vertraulich
* geheim
* streng-geheim
|`colophon`|Nein|colophon::[]|Metadaten des Dokuments und Lizenzbestimmungen|
|`factory` als Attribut zu `colophon`|Ja|IsyFact-Standards|Definiert, ob das Dokument zu den IsyFact-Standards oder IsyFact-Erweiterungen gehört. Wählt das passende Logo und Deckblatt für die Factory.
a|
* IsyFact-Standards
* IsyFact-Erweiterungen
* Register Factory
|`open-source` als Attribut zu `colophon`|Ja|true|Beschreibt, ob das Dokument unter der Open Source (true) oder Closed Source (false) Lizenz der IsyFact veröffentlicht wird.|
|`revdate`|Nein||Release Datum des Bausteins oder Dokuments|
|`revnumber`|Nein||Versionsnummer des Bausteins oder Dokuments|
|===

Zuletzt werden die übrigen Asciidoc Dateien in master.adoc inkludiert.
Leere Dateien können ausgelassen werden.
Inkludiert wird der Inhaltsbereich innerhalb der Dateien, der mit

`// tag::inhalt[]`

Dateiinhalt

`// end::inhalt[]`

getaggt ist.


[[docinfo.adoc-bearbeiten]]
==== docinfo.adoc bearbeiten

Bezieht sich das zu erstellende Dokument auf einen Baustein (Bibliothek) der IsyFact, so ist dieser Baustein inklusive der Version in einer eigenen Datei docinfo.adoc anzugeben und in master.adoc zu inkludieren.
In <<listing-master-bib>> wird beispielsweise auf den Baustein `isy-web` verwiesen.

[[listing-master-bib]]
.docinfo.adoc - Angabe des zugehörigen Bausteins
[source,asciidoc,indent=0]
----
// Einbindung Bibliotheken, wenn nicht genutzt, entfernen
*Java Bibliothek / IT-System*

[cols="5,2,3",options="header"]
|====
|Name |Art |Version
|isy-web |Bibliothek |{version-ifs}
|====
----

In der Vorschau sollten die Änderungen unmittelbar erscheinen. Ihre Änderungen speichern Sie über kbd:[Strg + S].

[[thisdoc.adoc-bearbeiten]]
==== thisdoc.adoc bearbeiten

Die Datei `thisdoc.adoc` ist optional auszufüllen und sollte eine Einleitung in das Dokument bieten und den Aufbau und Zweck des Dokuments erläutern.
Diese Datei ist in der `master.adoc` integriert und wird beim Generieren in das vollständige Dokument eingefügt.

[[inhalt.adoc-bearbeiten]]
==== inhalt.adoc bearbeiten

In `inhalt.adoc` wird der eigentliche Inhalt des Dokuments verfasst.
Diese Datei wird in der `master.adoc` nach der Datei `thisdoc.adoc` inkludiert.

Im Folgenden wird die Inhaltserstellung erläutert.

// end::inhalt[]
