= Seiten anlegen

include::glossary:licence:partial$licence.adoc[]

Soll eine neue Dokumentation angelegt werden oder die bestehende Dokumentation um eine Seite erweitert werden, so muss zunächst der geeignete Ort zur Ablage bestimmt werden.
I.d.R. ist dies das Repository, in dem sich der zu dokumentierende Erweiterungsbaustein befindet, da die Dokumentation nah beim Code abgelegt werden soll, oder der Baustein liegt im <<verzeichnisstruktur-antora-komponente,Repository `isyfact-standards` im Submodul `isyfact-standards-doc`>>.

[[repository-klonen]]
== Klonen Repository

Zunächst muss der zu dokumentierende Erweiterungsbaustein oder `isyfact-standards` von Git heruntergeladen werden.
Hierfür muss auf der Kommandozeile auf eine geeignete Stelle der lokalen Festplatte gewechselt werden und folgendes Kommando eingegeben werden:

====
C:\tmp\> *git clone* https://github.com/IsyFact/<Repository>

z.B. C:\tmp\> *git clone* https://github.com/IsyFact/isy-baustein
====

Bei <Repository> kann es sich um einen einzelnen xref:dokumentation/einleitung/einfuehrung.adoc#dokumentation-erweiterungen[Erweiterungsbaustein] handeln oder um ein Repository mit xref:dokumentation/einleitung/einfuehrung.adoc#zentrale-dokumentation[zentraler Dokumentation].

Danach werden die Schritte durchlaufen, die in den folgenden Kapiteln beschrieben sind.

[[maven-submodul]]
== Maven Submodul

Als Beispiel dient das Repository `isyfact-standards`.
Es enthält ein Maven Submodul zur Dokumentation: `isyfact-standards-doc`.
In Repositories, die noch keine Dokumentation enthalten, muss ein derartiges Submodul noch angelegt werden.

Das folgende Listing <<verzeichnisstruktur-submodul>> zeigt die Verzeichnisstruktur bis zum Maven Submodul.

[[verzeichnisstruktur-submodul]]
.Repository mit Maven Submodul zur Dokumentation
----
📂 isyfact-standards
  📂 isyfact-standards-doc <.>
----
<.> Maven-Submodul für die Dokumentation.


[[antora-komponente]]
== Antora-Dokumentationskomponente

Innerhalb des Submoduls wird der Pfad `src/docs/antora` angelegt.
Unterhalb dieses Pfades liegt die Antora-Dokumentationskomponente, repräsentiert durch die Konfigurationsdatei `antora.yml`.
In Repositories, die noch keine Antora-Komponente enthalten, muss diese Konfigurationsdatei noch angelegt werden.
Ein Repository sollte jedoch nur eine Antora-Komponente enthalten.
(Mehrere Antora-Komponenten hätten unterschiedliche Versionen, die eventuell nicht mehr synchron zum Versionsstand des Repositories gehalten werden könnten.)

Das folgende Listing <<verzeichnisstruktur-antora-komponente>> zeigt die Verzeichnisstruktur bis zur Antora-Dokumentationskomponente.

[[verzeichnisstruktur-antora-komponente]]
.Verzeichnisstruktur Antora-Komponente
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
        📂 docs
            📂 antora
                📄 antora.yml  <.>
----
<.> Antora Konfigurationsdatei für die Antora-Komponente.

In der `antora.yml`-Datei wird mindestens der Name der Dokumentationskomponente und ihre Version angegeben.
Näheres dazu in xref:glossary:literaturextern:inhalt.adoc#litextern-antora-komponente[Antora-Dokumentationskomponente].

[[antora-modul]]
== Antora-Modul

Im gleichen Verzeichnis wie `antora.yml`, `src/docs/antora`, muss das Verzeichnis `modules` liegen.
Näheres dazu siehe xref:glossary:literaturextern:inhalt.adoc#litextern-antora-verzeichnisstruktur[Antora-Verzeichnisstruktur].

In einem Antora-Modul wird die Dokumentation eines Bausteins abgelegt oder die Dokumentation einer Säule der IsyFact.
Unterhalb des Verzeichnisses `modules` wird ein Modul-Verzeichnis mit entsprechendem Namen abgelegt, sofern noch nicht vorhanden.

Das folgende Listing <<verzeichnisstruktur-antora-modul>> zeigt die Verzeichnisstruktur bis zum Antora-Modul.

[[verzeichnisstruktur-antora-modul]]
.Verzeichnisstruktur Antora-Modul `isy-sonderzeichen`
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
        📂 docs
            📂 antora
                📄 antora.yml
                📂 modules               <.>
                    📂 isy-sonderzeichen <.>
----
<.> Obligatorisches Verzeichnis für Antora-Modul(e).
<.> Modul `isy-sonderzeichen`.


Für die zentrale Dokumentation gibt es für jede Säule ein Antora-Modul mit Ausnahme der Bausteine, für die es für jeden Baustein ein Antora-Modul gibt.

Allgemein;; _Antora-Modul:_ `einstieg`
Blaupausen;; _Antora-Modul:_ `blaupausen`
Bausteine;; _Antora-Modul:_ Der jeweilige Baustein, z.B. `isy-sonderzeichen` +
Methodik;; _Antora-Modul:_ `methodik`
Werkzeuge;; _Antora-Modul:_ `werkzeuge`

[[struktur-dokuseite]]
== Strukturierung innerhalb eines Antora-Moduls

Unterhalb des Modul-Verzeichnisses, z.B. `isy-sonderzeichen`, wird ein Verzeichnis mit Namen `pages` angelegt.
An diesem Ort werden die Dokumentationsseiten als .adoc abgelegt mit einem Namen, der ihren Inhalt widerspiegelt.

Außer dem Verzeichnis `pages` kann es bei Bedarf noch weitere Verzeichnisse geben wie `images` und `attachments`.
Siehe dazu ebenfalls xref:glossary:literaturextern:inhalt.adoc#litextern-antora-verzeichnisstruktur[Antora-Verzeichnisstruktur].
Unterhalb von `images` und `attachments` kann eine weitere Strukturierung erfolgen, die sich an der Struktur unter `pages` orientiert, siehe auch <<verzeichnisstruktur-pages-images>>.

Wenn unter `pages` viele Dokumentationsseiten abzulegen sind, können sie noch weiter strukturiert werden, siehe auch <<verzeichnisstruktur-pages-images>> und  xref:seitenvorlage.adoc#dateien-thema[Dateiablage].
Für Bausteine wird häufig die Strukturierung `konzept` und `nutzungsvorgaben` gewählt.

Das folgende <<verzeichnisstruktur-pages-images,Listing>> zeigt die Verzeichnisstruktur innerhalb eines Antora-Moduls.

[[verzeichnisstruktur-pages-images]]
.Verzeichnisstruktur innerhalb eines Antora-Moduls
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
        📂 docs
            📂 antora
                📄 antora.yml
                📂 modules
                    📂 isy-sonderzeichen <1>
                        📂 images <2>
                            📂 konzept <3>
                                sonderzeichen.dn.svg
                        📂 pages <4>
                            📂 konzept <5>
                                📄 sonderzeichen.adoc <6>
                            📂 nutzungsvorgaben <5>
                                ...
----
<1> Modul `isy-sonderzeichen`.
<2> Verzeichnis zur Bildablage für das Modul `isy-sonderzeichen`.
<3> Die Bilder können analog zur Strukturierung unter `pages` abgelegt werden.
<4> Obligatorisches Verzeichnis für die eigentlichen Dokumentationsseiten.
<5> Die Dokumentationsseiten können strukturiert abgelegt werden.
<6> Eigentliche Dokumentationsseite.

[[aufbau-dokuseite]]
== Dokumentationsseite Aufbau

Eine Dokumentationsseite enthält ein in sich abgeschlossenes Thema und entspricht damit in etwa einem Kapitel in konventionellen Dokumenten.

Der Aufbau einer Dokumentationsseite ist in der xref:seitenvorlage.adoc[Seitenvorlage] beschrieben.

[[linksnavigation-antora]]
== Navigationsdatei `nav.adoc`
Nach der Erstellung der Dokumentationsseiten in `.adoc`-Dateien muss dafür gesorgt werden, dass sie aufrufbar sind, üblicherweise über die Linksnavigation von Antora.
In der Antora-Datei `nav.adoc` wird die Linksnavigation bezüglich einer xref:glossary:glossary:master.adoc#glossar-antora-dokumentations-komponente[Antora-Dokumentationskomponente] festgelegt, siehe auch xref:seitenvorlage.adoc#navigation-thema[Navigationsstruktur].

Die Top-Level Linksnavigation der Antora-Komponente `IsyFact Standards` spiegelt die Säulen der IsyFact wider.
Unter `Bausteine` befinden sich beispielsweise die Bausteine, die in `isyfact-standards` dokumentiert werden.
I.d.R. strukturiert sich die Dokumentation eines Bausteins in Konzept und Nutzungsvorgaben, was bei der Linksnavigation beibehalten wird.

Der Name des Bausteins in der Linksnavigation, z.B. "Sonderzeichen", kann nur der Strukturierung dienen, oder er kann auf eine Übersichtsseite für den Baustein verlinken, die kurze Informationen über den Baustein enthält, z.B. die Version.

Die Datei `nav.adoc` wird in `antora.yml` angegeben, damit sie von Antora berücksichtigt werden kann.
Eine Antora-Komponente kann mehrere `nav.adoc` enthalten.
Die Verweise aus jeder `nav.adoc` werden in der Reihenfolge der Erwähnung der `nav.adoc`-Dateien in `antora.yml` aufgelistet.

[[listing-antora-yml]]
.Beispiel `nav.adoc` in `antora.yml`
[source,yaml]
----
nav:
- modules/einstieg/nav.adoc
- modules/blaupausen/nav.adoc
- modules/bausteine/nav.adoc
- modules/plattform/nav.adoc
- modules/methodik/nav.adoc
- modules/werkzeuge/nav.adoc
- modules/changelog/nav.adoc
----

[[listing-nav-adoc]]
.Beispiel Modul `Werkzeuge`, Verlinkung in `nav.adoc`
[source,asciidoc]
----
* xref:werkzeuge.adoc[]
** xref:dokumentation/einleitung/einfuehrung.adoc[]
*** Antora (empfohlen)
**** xref:dokumentation/erstellung/erstellung-antora.adoc[]
***** xref:seitenvorlage.adoc[]
***** xref:kopiervorlage.adoc[]
**** xref:dokumentation/bearbeitung/bearbeitung-antora.adoc[]
**** xref:dokumentation/generierung/generierung-antora.adoc[]
*** AsciidoctorJ
**** xref:dokumentation/erstellung/erstellung-asciidoctorj.adoc[]
**** xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc[]
**** xref:dokumentation/generierung/generierung-asciidoctorj.adoc[]
*** xref:dokumentation/changelog/changelog-doku.adoc[]
** xref:entwicklungsumgebung/master.adoc[Entwicklungsumgebung]
** xref:versionierungskontrolle/master.adoc[]
** xref:gui-tests/gui-tests-mit-selenium.adoc[]
----

Die durch das Beispiel generierte Navigation ist links dieser Seite aufgeklappt zu sehen.

[[konfiguration-antora]]
== Konfigurationsdateien `playbook.yml` und `pom.xml`

Die genannten Konfigurationsdateien befinden sich in einem eigenen Repository.
`playbook.yml` steuert die Antora-Dokumentengenerierung, z.B. welche Antora-Komponenten in welchen Repositories und Branches verwendet werden sollen für die Generierung der Gesamtdokumentation.

Maven sorgt mithilfe der pom.xml dafür, dass lokal im Projekt Node.js, npm und Antora installiert werden und die Dokumentengenerierung ausgeführt wird.

Im Normalfall müssen die Antora-Konfigurationsdatei `playbook.yml` und die Maven-Konfigurationsdatei pom.xml nicht geändert werden.
Die Konfigurationsdatei `playbook.yml` muss jedoch geändert werden, wenn in einem Repository eine Dokumentation neu erstellt wird, und wenn weitere Branches zur Dokumentengenerierung herangezogen werden sollen.

Zu beachten ist, dass bei Änderungen an `playbook.yml` und pom.xml zunächst nur die lokale Generierung betroffen ist.
Ggf. muss die Generierung über die CI/CD-Pipeline ebenfalls geändert werden.

// end::inhalt[]
