= Nutzungsvorgaben Task Scheduling: Inhalt

// tag::inhalt[]
[[verwendung-der-querschnittsbibliothek-isy-task]]
== Verwendung der Querschnittsbibliothek `isy-task`

In diesem Abschnitt werden Inhalt und Einsatz der Querschnittsbibliothek `isy-task` beschrieben.

[[maven]]
=== Maven

Um die Querschnittsbibliothek einzubinden, fügen Sie die `isy-task` Abhängigkeit in Ihre pom.xml hinzu.

[source, xml]
----
<dependency>
    <groupId>de.bund.bva.isyfact</groupId>
    <artifactId>isy-task</artifactId>
</dependency>
----

[[spring-konfiguration]]
=== Spring Konfiguration

Als Nächstes wird der `TaskScheduler` über Spring eingebunden.

Die Bibliothek authentifiziert Benutzer bei entsprechender Konfiguration und bindet sie in den Aufrufkontext der Aufgabe ein.
Sie sichert die Aufgaben selbst allerdings nicht gegen unerlaubte Ausführungen ab.
Die Verantwortlichkeit dafür liegt bei den jeweiligen Fachkomponenten der Anwendungen, die sich gemäß den Sicherheitsrichtlinien der IsyFact und den Anforderungen an die Anwendung schützen müssen.
Authentifizierung und Autorisierung finden nach den Vorgaben des Berechtigungskonzepts statt.
Dazu wird die IsyFact-Bibliothek `isy-sicherheit` eingesetzt.
Die Nutzung der Bibliothek wird im Dokument xref:isy-sicherheit:nutzungsvorgaben/master.adoc#einleitung[Nutzungsvorgaben Sicherheit] beschrieben.

Um die Verwendung von `isy-sicherheit` für die Authentifizierung und Autorisierung zu konfigurieren, wird die Property `isy.task.authentication.enabled` in `application.properties` auf `true` oder `false` gesetzt.

[[erstellung-eines-tasks]]
=== Erstellung eines Tasks

Technisch gesehen ist ein Task eine Java-Klasse, die vom Interface `de.bund.bva.isyfact.task.model.Task` abgeleitet ist.

Ein Task kapselt die Tätigkeiten, die über `isy-task` zeitgesteuert ausgeführt werden sollen.
Das Interface Task enthält hierfür die abstrakte Methode `execute()`.
Im folgenden Listing sehen Sie die Methoden des Interfaces Task.

[source, java]
----
package de.bund.bva.isyfact.task.model;

public interface Task {
void execute();
    boolean isDeaktiviert();
    void aktivieren();
    void deaktivieren();
    void zeichneErfolgreicheAusfuehrungAuf();
    void zeichneFehlgeschlageneAusfuehrungAuf(Exception e);
}
----

Das direkte Ableiten vom Interface Task ist nicht empfohlen.
Die Bibliothek bietet hierfür die abstrakte Klasse `AbstractTask` an.
`AbstraktTask` ist eine abstrakte Basis-Klasse, die (bis auf die Methode `execute()`) bereits die folgende Standardimplementierung für jede abstrakte Task-Methode mitbringt:

* *sie aktiviert bzw. deaktiviert*

** Über die Methoden `aktivieren()` und `deaktivieren()` kann der Task manuell aktiviert bzw. deaktiviert werden.

** Ferner lässt sich der Status, ob der Task deaktiviert worden ist, über die Methode `isDeaktiviert()` abfragen.

* *sie zeichnet Erfolg bzw. Misserfolg auf*

** Wenn ein Task erfolgreich ausgeführt werden konnte, wird dies bei dem `TaskMonitor` mit dem genauen Zeitpunkt vermerkt.
Hierfür wird die Methode `zeichneErfolgreicheAusfuehrungAuf()` des Monitors ausgeführt.

** Beim Misserfolg führt der Runner die Methode `zeichneFehlgeschlageneAusfuehrungAuf(Exception)` aus.
Hierbei übergibt er ihm die geworfene Ausnahme.


Im `AbstractTask` ist also bereits die wesentliche Funktionalität für die Ausführung und Überwachung des Tasks implementiert worden.

Das folgende Listing zeigt eine Fachkomponente, die zeitgesteuert "Hallo Welt" auf der Konsole ausgibt.

[source, java]
----
public class HalloWeltTask extends AbstractTask {
    @Override
    public void execute() {
        System.out.println("Hallo Welt");
    }
}
----

Der Task muss als Nächstes über Properties in `application.properties` konfiguriert.
Im folgenden Listing sehen Sie die Konfiguration für den `HalloWeltTask`.

[source,properties]
----
isy.task.tasks.halloWeltTask.benutzer=TestUser1
isy.task.tasks.halloWeltTask.passwort=TestPasswort1
isy.task.tasks.halloWeltTask.bhkz=BHKZ1
isy.task.tasks.halloWeltTask.ausfuehrung=ONCE
isy.task.tasks.halloWeltTask.initial-delay=10s
isy.task.tasks.halloWeltTask.host=ComputerName
isy.logging.anwendung.typ=GA
isy.logging.anwendung.name=Beispiel
isy.logging.anwendung.version=0.0.1
----
`ComputerName` ist der Name der Maschine, auf der der Task läuft.

Ein Task wird grundsätzlich als Spring Bean konfiguriert.

[source, java]
----
@Bean
public HalloWeltTask halloWeltTask() {
    return new HalloWeltTask();
}
----

Damit die konfigurierten Tasks automatisch beim Start der Anwendung ausgeführt werden, bzw. der `TaskScheduler` gestartet wird, kann in `application.properties` der Autostart aktiviert werden:
[source,properties]
----
isy.task.autostart=true
----

Dadurch wird der `TaskScheduler` beim Anwendungsstart gestartet.
Dieser führt alle konfigurierten Tasks, deren konfigurierter Ausführungszeitpunkt überschritten ist, direkt aus.
In der Zukunft liegende oder wiederholende Tasks werden auch dem Scheduler bekannt gemacht, sodass dieser sie zum entsprechenden Zeitpunkt ausführt.
Zudem wird mit der Einstellung der `TaskScheduler` beim Beenden der Anwendung automatisch heruntergefahren.

Wird kein Autostart konfiguriert, kann alternativ der `TaskScheduler` über die Methode `starteKonfigurierteTasks()` manuell gestartet werden.

[source, java]
----
taskScheduler.starteKonfigurierteTasks();
----

In diesem Fall muss der `TaskManager` auch manuell gestoppt werden, wenn die Geschäftsanwendung herunterfährt.
Hierfür wird die Methode `shutdownMitTimeout()` aufgerufen, um die Tasks ordentlich zu beenden.

[source, java]
----
taskScheduler.shutdownMitTimeout(10);
----

[[verwendung-bereitgestellter-tasks]]
=== Verwendung der bereitgestellten Tasks

Die Bibliothek `isy-task` enthält nützliche Tasks für die xref:glossary:glossary:master.adoc#glossar-ifs[Bibliothek (IsyFact Standards)].

==== Automatische Aktualisierung der Konfiguration
Dieser Task dient der periodischen Prüfung der Konfigurationsdateien auf Änderungen sowie der automatischen Aktualisierung der Konfiguration bei Änderungen.
Anwendungen können den Task einsetzen, in dem sie ihn als Spring Bean konfigurieren:

[source,java]
----
@Configuration
public class UpdateKonfigurationTaskConfiguration {

    @Bean
    public KonfigurationUpdateTask(@Qualifier("konfigurationUpdateTaskMonitor") TaskMonitor monitor, Konfiguration konfiguration) {
        return new KonfigurationUpdateTask(konfiguration, monitor);
    }

    @Bean
    public TaskMonitor konfigurationUpdateTaskMonitor() {
        return new TaskMonitor();
    }
}
----

Der Task `KonfigurationUpdateTask` erwartet task-spezifische Konfigurationsparameter, wie sie im Kapitel xref:nutzungsvorgaben/master.adoc#aufgabenspezifische-konfiguration[Aufgabenspezifische Konfiguration] beschrieben werden:

[source,properties]
----
isy.task.tasks.konfigurationUpdateTask.ausfuehrung=FIXED_DELAY
isy.task.tasks.konfigurationUpdateTask.initial-delay=5s
isy.task.tasks.konfigurationUpdateTask.fixed-delay=60s
----

[[programmatisches-anlegen-von-aufgaben]]
== Programmatisches Anlegen von Aufgaben

Eine weitere Möglichkeit, wie `isy-task` auf einfacher Weise verwendet werden kann, bietet die Möglichkeit des programmatischen Anlegens von Aufgaben.
Hierbei wird die Aufgabe nicht über eine Konfigurationsdatei geplant, sondern programmatisch.

Für die programmatische Variante erstellen Sie eine `TaskKonfiguration`.
Der `TaskKonfiguration` werden die Properties mithilfe von Setter-Methoden übergeben.
Für die Properties in der TaskKonfiguration gelten dieselben Regeln wie für die Schlüssel in der Konfigurationsdatei.

[source, java]
----
TaskKonfiguration taskKonfiguration =
    new TaskKonfiguration();
taskKonfiguration.setTaskId("halloWeltTask");
taskKonfiguration.setAuthenticator(new NoOpAuthenticator());
taskKonfiguration.setHostname("localhost");
taskKonfiguration.setAusfuehrungsplan(
TaskKonfiguration.Ausfuehrungsplan.ONCE);
taskKonfiguration.setInitialDelay(Duration.ofSeconds(1));
----

Die Querschnittsbibliothek `isy-task` sieht vor, dass jeder Task von einem `de.bund.bva.isyfact.task.model.TaskRunner` gesteuert wird.
Ein `TaskRunner` übernimmt nicht nur die eigentliche Ausführung des Tasks, sondern enthält darüber hinaus auch die zur Ausführung benötigte Konfiguration.
Um den Task auszuführen, wird er dem `TaskRunner` gemeinsam mit der `TaskKonfiguration` übergeben.

Der `TaskRunner` wird dem `TaskScheduler` mithilfe der Methode `addTask()` übergeben.
Während für den Start im oberen Abschnitt (mit der Spring-Konfiguration) beim `TaskScheduler` die Methode `starteKonfigurierteTasks()` ausgeführt wurde, ruft man bei dem manuellen Verfahren die Methode `start()` auf.

[source, java]
----
TaskRunner taskRunner = new TaskRunnerImpl(manuellerTask,taskKonfiguration);
taskScheduler.addTask(taskRunner);
taskScheduler.start();
----

[[konfigurationsschluessel]]
== Konfigurationsschlüssel

Die folgenden Konfigurationsschlüssel werden von `isy-task` eingelesen und verwertet.

[[allgemeine-konfiguration]]
=== Allgemeine Konfiguration

Ob der TaskScheduler automatisch beim Anwendungsstart gestartet werden soll.
(Standardwert `false`; setze auf `true` für Autostart)

[source,properties]
----
isy.task.autostart
----

Die Anzahl der Threads, die im Thread-Pool initial angelegt werden:

[source,properties]
----
isy.task.default.amount_of_threads
----

Das DateTimePattern, das für den Start eines Tasks verwendet werden kann:

[source,properties]
----
isy.task.default.date_time_pattern
----

Die Dauer, die `isy-task` wartet, bis ein fehlgeschlagener Task erneut gestartet wird:

[source,properties]
----
isy.task.watchdog.restart_interval
----

Die Kennung die benutzt wird, wenn kein Task-spezifisches Kennwort konfiguriert wird:

[source,properties]
----
isy.task.default.benutzer
----

Das Passwort das benutzt wird, wenn kein Task-spezifisches Passwort konfiguriert wird:

[source,properties]
----
isy.task.default.passwort
----

Das Behördenkennzeichen, das benutzt wird, wenn kein Task-spezifisches konfiguriert wird:

[source,properties]
----
isy.task.default.bhkz
----

Der Host, wenn kein Task-spezifischer Host konfiguriert wird:

[source,properties]
----
isy.task.default.host
----

[[aufgabenspezifische-konfiguration]]
=== Aufgabenspezifische Konfiguration

Die Kennung des ausführenden Benutzers:

[source,properties]
----
isy.task.tasks.<Task>.benutzer
----

Das Passwort des ausführenden Benutzers:

[source,properties]
----
isy.task.tasks.<Task>.passwort
----

Behördenkennzeichen des ausführenden Benutzers:

[source,properties]
----
isy.task.tasks.<Task>.bhkz
----

Der Name des Hosts auf dem der Task ausgeführt werden soll.
Der Name kann als regulärer Ausdruck angegeben werden, es wird dann geprüft, ob der tatsächliche Hostname dem regulären Ausdruck entspricht.
Dadurch kann auch eine Liste von Hostnamen angegeben werden, z.B. `host1|host2|host3`:

[source,properties]
----
isy.task.tasks.<Task>.host
----

Der Ausführungsplan für einen Task:

[source,properties]
----
isy.task.tasks.<Task>.ausfuehrung
----

Der einmalige Zeitpunkt der Ausführung in Form eines Zeitstempels:

[source,properties]
----
isy.task.tasks.<Task>.zeitpunkt
----

Die Dauer, die zwischen dem Start des TaskSchedulers und der einmaligen Ausführung liegt.
Die Dauer muss die Form eines Zeitraums gemäß dem xref:isy-datetime:konzept/master.adoc[] besitzen:

[source,properties]
----
isy.task.tasks.<Task>.initial-delay
----

Die festgelegte Dauer zwischen zwei Starts einer Ausführung.
Die Dauer muss die Form eines Zeitraums gemäß dem  xref:isy-datetime:konzept/master.adoc[] besitzen:

[source,properties]
----
isy.task.tasks.<Task>.fixed-rate
----

Die festgelegte Dauer zwischen dem Ende einer und dem Start der nächsten Ausführung.
Die Dauer muss die Form eines Zeitraums gemäß dem  xref:isy-datetime:konzept/master.adoc[] besitzen:

[source,properties]
----
isy.task.tasks.<Task>.fixed-delay
----

[[ueberwachung-mit-jmx]]
== Überwachung mit JMX

Die Querschnittsbibliothek `isy-task` sieht eine Überwachung über JMX vor.

Der Überwachungsmechanismus von `isy-task`, der über JMX abgefragt werden kann, benötigt den TaskMonitor, um sich beispielsweise Erfolg oder Misserfolg des Tasks zu merken.
Wenn der Task vom AbstractTask abgeleitet ist, kann man dem Task einen TaskMonitor per Konstruktor übergeben.

Soll der JMX-Monitor verwendet werden, so muss dieser genau wie der Task als Spring Bean konfiguriert werden.

[source, java]
----
@Configuration
public class TaskConfiguration {

    @Bean
    public TestTask testTask(TaskMonitor monitor) {
        return new TestTask(monitor);
    }

    @Bean
    public TaskMonitor taskMonitor() {
        return new TaskMonitor();
    }
}
----

Der MBean-Exporter wird gemäß dem xref:isy-ueberwachung:konzept/master.adoc#einleitung[Konzept Überwachung] konfiguriert.

[[hinweise-fuer-den-task-im-parallelbetrieb]]
== Hinweise für den Task im Parallelbetrieb

Bei der Implementierung eines Tasks muss beachtet werden, dass ihn die Querschnittsbibliothek im Parallelbetrieb betreiben wird.
Werden hierbei die Besonderheiten der Java Multithreading API nicht berücksichtigt, kann dies zu einem fehlerhaften Verhalten in der xref:glossary:glossary:master.adoc#glossar-geschaeftsanwendung[Geschäftsanwendung] führen.

[[threadsicherheit]]
=== Threadsicherheit

Ein wichtiger Aspekt des Parallelbetriebs ist die Threadsicherheit.
In diesem Abschnitt werden die Probleme bezüglich der Threadsicherheit verdeutlicht.
Grundsätzlich ist es so, dass Rechner mit mehreren Rechnerkernen, den Parallelbetrieb auf Hardwareebene verwirklichen und somit den Gesamtprozess beschleunigen.
Die Anzahl der Rechnerkerne braucht programmatisch aber nicht berücksichtigt werden, weil die Java Laufzeitumgebung auch die Rechenzeit eines einzelnen Rechnerkerns in feingranulare Zeitscheiben schneidet.
Hierdurch kann die Rechenzeit einer blockierenden Aufgabe für die Erledigung anderer Aufgaben genutzt werden.
Allerdings bietet dies auch ein hohes Potenzial für ein fehlerhaftes Verhalten.
Denn die Zuordnung der Zeitscheiben erfolgt bei jeder erneuten Ausführung der Geschäftsanwendung unterschiedlich.
Daher kann ein erfolgreicher JUnit-Test eine fehlerfreie Ausführung in der Produktionsumgebung nicht gewährleisten.
Selbst die Aufteilung auf unterschiedliche Rechnerkerne verhindert von sich aus kein fehlerhaftes Verhalten.
Aus diesem Grund müssen Methoden, die nicht von mehreren Threads gleichzeitig durchlaufen werden sollen, über einen Lock-Mechanismus (beispielsweise über das Schlüsselwort synchronized) davor geschützt werden.
Ein weiteres Problem gemeinsamer Instanzen, betrifft die Objektvariablen.
Auch der Zugriff auf eine veränderbare Objektvariable (d.h. eine Objektvariable, die nicht mit final versehen wurde) eines gemeinsamen Objekts kann nicht konsistent erfolgen, weil jeder Rechnerkern über einen eigenen Cache verfügt, der sich bei Änderung des Wertes naturgemäß vom Wert im Cache des anderen Rechnerkerns unterscheidet.
Hilfreich ist hierbei das Schlüsselwort __volatile__, das dafür sorgt, dass vor jedem Zugriff eine Synchronisation zwischen dem Thread-spezifischen Cache und dem Hauptspeicher stattfindet.
Die Objektvariable die mit volatile versehen wurde, ist also scheinbar atomar.
Allerdings trifft das nicht für den schreibenden Zugriff zu, da jegliche Veränderung in mehreren Schritten erledigt wird. 
Um sicherzustellen, dass der Zugriff auf eine gemeinsame Objektvariable konsistent ist, wird beispielsweise der Wertebehälter einer Ganzzahl mit dem speziellen Wertetypen AtomicInteger definiert.
In der Regel wird es sich bei der Objektvariablen aber eher um einen Referenztypen handeln.
In diesen Fällen sollten die Objektvariablen in einem ThreadLocal-Objekt deklariert werden.

[[status-des-threads-abfragen]]
=== Status des Threads abfragen

Genau wie bei allen Multithreading Anwendungen, so kann es auch bei der Querschnittsbibliothek `isy-task` nützlich sein, dass ein Thread einen Thread-State hat, der über die Methode `Thread.currentThread().getState()` abgefragt werden kann.
Sobald die Querschnittsbibliothek `isy-task` den Thread zum Laufen bringt, wechselt der `Thread.State` von `NEW` auf `RUNNABLE`.
Dies ist genau genommen der Zeitpunkt, wenn die JVM die Methode `run()` ausführt.
Wenn die Methode `run()` durchlaufen worden ist oder der Auswurf einer `CheckedException` nicht abgefangen wurde, wechselt der `Thread-State` auf `TERMINATED`.
Dieser Wechsel lässt sich auch durch die spezielle Methode `isAlive()` der Klasse `Thread` abfragen, die beim `Thread.State` `RUNNABLE` `true` liefert und ansonsten `false`.
Grundsätzlich kann der `Thread-State` folgende Werte einnehmen:



[id="table-StateVals",reftext="{table-caption} {counter:tables}"]
[cols="1,4",options="header"]
|====
|Thread-State |Bedeutung
|NEW|wird noch nicht ausgeführt
|RUNNABLE|wird ausgeführt
|BLOCKED|wartet auf einen Monitor Lock
|WAITING|wartet auf einen anderen Thread
|TIMED_WAITING|wartet für eine bestimmte Dauer auf den anderen Thread
|TERMINATED|Ausführung ist beendet
|====

[[ausfuehrung-eines-tasks-vorzeitig-beenden]]
=== Ausführung eines Tasks vorzeitig beenden

Bei einem Thread ist ein Abbruch-Mechanismus eingebaut.
Der Mechanismus nutzt einen internen Flag, der sich interrupt status nennt und der mit einem Abbruchwunsch durch die Klassenmethode `Thread.interrupt()` auf den Status `interrupted` gesetzt werden kann.
Es ist Sache des Entwicklers der IsyFact Fachkomponente, wie er auf den Abbruchwunsch reagiert.
Beispielsweise könnte es passieren, dass der Abbruchwunsch während eines Pausierens durch die Methode `sleep()` auftritt.
In diesem Fall, wird das dazu führen, dass eine `InterruptedException` geworfen wird.
Deshalb muss dort entsprechend, also beispielsweise mit einer `return`-Anweisung reagiert werden.
In der Praxis ist es aber noch wahrscheinlicher, dass nicht während einer `sleep()` Methode, sondern beim Zugriff auf eine Netzwerkressource oder bei einer anderen langwierigen Tätigkeit ein Abbruchswunsch erfolgt.
In solch einem Fall, muss der Entwickler den Interrupt Status selber abfragen.
Hierfür bietet die Klasse `Thread` eine Methode an, die sich `interrupted()` nennt.
Zu beachten ist, dass die Methode `interrupted()` den Statusflag immer zurückgesetzt.
Was man auch beachten sollte ist, dass die `sleep()` Methode ebenso dafür sorgt, dass der Status `interrupted` wieder zurückgesetzt wird.

// end::inhalt[]

// tag::architekturregel[]

// end::architekturregel[]

// tag::sicherheit[]

// end::sicherheit[]
