= Nutzungsvorgaben Task Scheduling: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Dokument beschreibt alle Aspekte, die bei der Verwendung der `isy-task` xref:glossary:glossary:master.adoc#glossar-bibliothek[Bibliothek] zu berücksichtigen sind.

Die `isy-task` Bibliothek wurde im Dokument xref:konzept/master.adoc#einleitung[Task Scheduling - Konzept]  konzipiert.

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

Die `isy-task` Bibliothek wird im Rahmen der IsyFact Software Factory zur automatisierten Ausführung von wiederkehrenden Aufgaben innerhalb von fachlichen xref:glossary:glossary:master.adoc#glossar-anwendungskomponente[Anwendungskomponenten] eingesetzt.
Der Zweck dieses Dokuments ist Vorgaben zur Nutzung der Bibliothek `isy-task` zu geben.
Das Dokument richtet sich somit vorrangig an Entwickler, Konstrukteure und technische Chefarchitekten von Anwendungssystemen, die gemäß den Vorgaben der xref:glossary:glossary:master.adoc#glossar-isyfact[IsyFact] umgesetzt werden.

Kapitel xref:nutzungsvorgaben/master.adoc#verwendung-der-bibliothek-isy-task[Verwendung der Bibliothek isy-task] beschreibt das Arbeiten mit der Bibliothek `isy-task`.

Kapitel xref:nutzungsvorgaben/master.adoc#programmatisches-anlegen-von-aufgaben[Programmatisches Anlegen von Aufgaben] beschreibt, wie die Bibliothek ohne Spring Konfiguration verwendet werden kann.

Kapitel xref:nutzungsvorgaben/master.adoc#konfigurationsschluessel[Konfigurationsschlüssel] bietet einen Überblick über die Konfigurationsschlüssel.

Kapitel xref:nutzungsvorgaben/master.adoc#ueberwachung-mit-jmx[Überwachung mit jmx] zeigt, wie die JMX-Überwachung eingebunden wird.

Kapitel xref:nutzungsvorgaben/master.adoc#hinweise-fuer-den-task-im-parallelbetrieb[Hinweise für den Task im Parallelbetrieb] gibt Anmerkungen für die Implementierung eines Tasks.
// end::inhalt[]
