== Neuerungen in isy-persistence 2.0 / Datenzugriff

=== 5.5.1 Persistierung mit JPA
* `isy-persistence` 2.0 setzt Hibernate 5.3 ein, welches JPA 2.2. implementiert. Die `AttributeConverter` für die Klassen der Java 8 Date and Time API entfallen.

=== 6. Verwendung von JPA in der Anwendung
* `isy-persistence` setzt auf die Verwendung von Spring Data (https://docs.spring.io/spring-data/jpa/docs/current/reference/html/).
* Neue DAOs werden von `CrudRepository` abgeleitet.
  Wird Sortier- und Paging-Funktionalität benötigt, wird von `PagingAndSortingRepository` abgeleitet.
* Die Definition der Query wird vom Methodenamen abegeleitet. Bei Ausnahmen wird `@Query` verwendet.
* Die Interfaces von DAOs sind mit `@Repository` zu annotieren.
* Die von `isy-persistence` bereitgestellen abstrakten Klassen und Interfaces (`Dao`, `AbstractDao`) sind nur aus Gründen der Abwärtskompatibilität enthalten.
* Die Beans für die DAOs werden automatisch von Spring erzeugt.
  Dazu wird die Annotation `EnableJpaRepositories` verwendet.

[source,java]
----
@Configuration
@EnableJpaRepositories(basePackages = {"de.if2application.persistence"})
@EntityScan("de.if2application.persistence")
public class PersistenceConfig { }
----


=== 6.3 Ablage von Query-Definitionen in Konfigurationsdatei
* NamedQueries werden über Annotationen an den Entitätsklasssen definiert und nicht mehr in XML abgelegt.

=== 7.2 Konfiguration des EntityManagers
* Entfällt, der `EntityManager` wird durch Spring Boot konfiguriert.

=== 7.3 Konfiguration der Datasource
* Die Bean für die `DataSource` mit dem Namen `appDataSource` wird automatisch erstellt.
* Die Konfiguration der `DataSource` und des Connection Pools erfolgt über `application.properties`:
** `isy.persistence.datasource.database-url`
** `isy.persistence.datasource.database-username`
** `isy.persistence.datasource.database-password`
** `isy.persistence.datasource.database-schema-default`
** `isy.persistence.datasource.pool-name`
** `isy.persistence.datasource.pool-min-active`
** `isy.persistence.datasource.pool-max-active`
** `isy.persistence.datasource.pool-validate-on-borrow`
** `isy.persistence.datasource.pool-wait-timeout`
** `isy.persistence.datasource.pool-inactive-timeout`
** `isy.persistence.datasource.pool-time-to-live-timeout`
** `isy.persistence.datasource.pool-abandoned-timeout`
** `isy.persistence.datasource.pool-max-reuse-time`
** `isy.persistence.datasource.pool-max-reuse-count`
** `isy.persistence.datasource.pool-statement-cache`
** `isy.persistence.datasource.jdbc-timeout-connect`
** `isy.persistence.datasource.jdbc-timeout-read`
** `isy.persistence.datasource.jdbc-disable-oob`

=== 7.4 UCP verwenden
* Entfällt, wird über Properties in `application.properties` konfiguriert.

=== 8.3. Transaktionssteuerung für JPA über Annotationen
* Damit die Annotation `@Transactional` ausgewertet wird, muss das Transaction-Management von Spring per Java-Configuration eingeschaltet werden.

[source,java]
----
@Configuration
@EnableTransactionManagement
public class CoreConfig {}
----

[[isy-logging]]
== Neuerungen in isy-logging 2.0

=== 4.2 Konfiguration
* Die Konfiguration erfolgt über `logback.xml` und zusätzliche Properties in `application.properties`.
* Die Datei `logback.xml` liegt unter `src/main/resources/config`.
* Die Änderung der Log-Level erfolgt über `application.properties`, diese werden nicht in `logback.xml` angegeben.

.logback.xml
[source,xml]
----
<configuration scan="false">
    <include resource="resources/isylogging/logback/appender-entwicklung.xml" />

    <!-- Kein Log-Level angeben -->
    <root>
        <appender-ref ref="KONSOLE" />
    </root>

</configuration>
----

.application.properties
[source,properties]
----
logging.level.root = info
----
* Der `LogbackConfigListener` entfällt komplett, d.h., die Abhängigkeit in `pom.xml` und die Konfiguration in `web.xml` sind nicht notwendig.
* Interceptoren für System-  und Komponentengrenzen werden per Autokonfiguration erstellt; System- und Komponentengrenzen werden über Annotation `@Systemgrenze`  und `@Komponentengrenze` festgelegt.
* Konfiguration der Interceptoren (wenn abweichend von der Default-Konfiguration) über Properties nach dem Schema:

  isy.logging.<component | boundary>.logge<dauer | aufruf | ...>=<true | false>

* Konfiguration des `LogApplicationListener` über Properties:

.application.properties
[source,properties]]
----
isy.logging.anwendung.name=Anwendung
isy.logging.anwendung.version=2.0.0
isy.logging.anwendung.typ=GA
----
* Aktivieren des Performance Loggings über `isy.logging.performancelogging.enabled=true` in `application.properties`.

== Neuerungen in isy-task 2.0

=== 3.2 Spring Konfiguration
* Die benötigten Beans werden per Autokonfiguration erzeugt.
* Die Verwendung von Authentifizierung/Autorisierung wird über die Property `isy.task.authentiation.enabled=true/false` in `application.properties` gesteuert.

=== 5. Konfiguration (Properties)
* Die Namen der Properties zur Konfiguration von Tasks haben den Präfix `isy.task` lauten wie folgt:
** `default.host=XXX`
** `default.benutzer=XXX`
** `default.passwort=XXX`
** `default.bhkz=XXX`
** `default.datetimepattern=XXX`
** `default.amountofthreads=XXX`
** `watchdog.restart-interval=1s`
** `tasks.<ID des Tasks>.benutzer=TestUser1`
** `tasks.<ID des Tasks>.passwort=TestPasswort1`
** `tasks.<ID des Tasks>.bhkz=BHKZ1`
** `tasks.<ID des Tasks>.ausfuehrung=FIXED_RATE`
** `tasks.<ID des Tasks>.initial-delay=1s`
** `tasks.<ID des Tasks>.fixed-rate=3s`
** `tasks.<ID des Tasks>.fixed-delay=5s`

[[isy-ueberwachung]]
== Neuerungen in isy-ueberwachung 2.0
 * `isy-ueberwachung` setzt `micrometer` ein.

=== 3.3.4 Informationen von Services
* Die Überwachungsinformationen für Services werden über micrometer bereitgestellt.
* Die eigentliche Überwachung erfolgt über einen AOP-Advice. Dieser wird per Java-Config konfiguriert:

[source,java]
----
@Configuration
@EnableAspectJAutoProxy
public class UeberwachungConfig {
    @Bean
    public MethodInterceptor eintragMonitor(MeterRegistry meterRegistry) {
        return new ServiceStatistik(meterRegistry, Tags.of("servicestatistik", "eintragController"));
    }

    @Bean
    public Advisor erstellenMonitorAdvice(@Qualifier("eintragMonitor") MethodInterceptor eintragMonitor) {
        AspectJExpressionPointcut pointcut = new AspectJExpressionPointcut();
        pointcut.setExpression("target(some.package.service.rest.EintragController)");
        DefaultPointcutAdvisor advisor = new DefaultPointcutAdvisor(pointcut, eintragMonitor);
        advisor.setOrder(1000);
        return advisor;
    }
}
----

=== 3.3.5 Vorgaben für die Prüfung der Verfügbarkeit
* Die Implementierung von Ping- und Prüfmethoden wird über `HealthIndicator` (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_writing_custom_healthindicators) realisiert.
* Die Überwachung der Datenbankverbindung wird bei der Verwendung von `isy-persistence` automatisch konfiguriert und verwendet (`DataSourceHealthIndicator`).

=== 3.8.1 Loadbalancer-Servlet
* Das Loadbalancer-Servlet wird automatisch konfiguriert
* Der Pfad zur `isAlive`-Datei kann über die Property `isy.ueberwachung.loadbalancer.isalivefilelocation` geändert werden

== Neuerungen in isy-sicherheit 2.0

=== 3.6.2 Konfiguration
* Automatisch konfiguriert werden die `@Gesichert`-Annotation, die `AufrufKontextFactory` und Thread-Scope für Spring.
* In der Anwendung müssen die Beans für `AufrufKontextVerwalter`, `Sicherheit` und `AccessManager` konfiguriert werden.

=== 3.6.5 Konfiguration des Caches
* Die Properties für die Konfiguration des Caches lauten `isy.sicherheit.cache.ttl` und `isy.sicherheit.cache.maxelements`.

[[konfiguration]]
== Neuerungen isy-konfiguration 2.0

4.3.1.3 Implementierungsvorgaben für Property-Dateien

* Die Bean `konfiguration` wird automatisch erstellt, sobald die Property `isy.konfiguration.properties` in `application.properties` gesetzt wird.
* Die Property `isy.konfiguration.properties` enhält eine Liste von Pfaden zu Property-Dateien, die von Konfiguration gelesen werden sollen.
[source,properties]
----
isy.konfiguration.properties=/config/config_A.properties, /config/config_B.properties
----


[[anwendung]]
== Neuerungen Anwendungskonfiguration / Spring

* Es wird eine Anwendungsklasse im Root-Package erstellt:

[source,java]
----
@SpringBootApplication
public class IsyFact2Application extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(IsyFact2Application.class);
    }
}
----

* Die Konfiguration erfolgt mit Konfigurationklassen, wenn nötig.
* Klassen, die als Beans bereitgestellt werden sollen, werden mit `@Component`/ `@Service`/ `@Repository` annotiert.

=== Konfiguration in web.xml

Beispiel für ein `web.xml` nach IsyFact 1.x.
Die auskommentierten Teile entfallen.
Erläuterungen siehe unten.

.web.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-app PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN" "http://java.sun.com/dtd/web-app_2_3.dtd">

<web-app>
    <display-name>IsyFact2Application</display-name>

    <1>
    <!-- Spring: Registration of ApplicationContext -->
    <!--context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            classpath:resources/spring/application.xml,
            classpath:resources/spring/timertasks.xml,
            classpath:resources/spring/ueberwachung.xml,
            classpath:resources/spring/service/service.xml,
            classpath:resources/spring/service/remoting-servlet.xml
        </param-value>
    </context-param-->

    <context-param>
        <param-name>webAppRootKey</param-name>
        <param-value>IsyFact2Application</param-value>
    </context-param>

    <2>
    <!--context-param>
    	<param-name>logbackConfigLocation</param-name>
    	<param-value>classpath:/config/logback.xml</param-value>
    </context-param-->

    <!--listener>
    	<listener-class>ch.qos.logback.ext.spring.web.LogbackConfigListener</listener-class>
    </listener-->

    <3>
    <!--listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener-->

    <4>
    <!-- Servlet fuer HTTPInvoker-Aufrufe.
        Das Servlet nimmt die Aufrufe entgegen und verteilt sie auf die RemoteBeans.
        Die entsprechene Konfiguration befindet sich in remoting-servlet.xml -->
    <!--servlet>
        <servlet-name>remoting</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>/WEB-INF/classes/resources/spring/service/remoting-servlet.xml</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet-->

    <5>
    <!--servlet>
        <servlet-name>loadbalancer</servlet-name>
        <servlet-class>
            de.bund.bva.pliscommon.ueberwachung.service.loadbalancer.LoadbalancerServlet
        </servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet-->

    <!--servlet-mapping>
        <servlet-name>loadbalancer</servlet-name>
        <url-pattern>/Loadbalancer</url-pattern>
    </servlet-mapping-->

    <6>
    <!--servlet-mapping>
        <servlet-name>remoting</servlet-name>
        <url-pattern>/MeldungBean_v1_0</url-pattern>
    </servlet-mapping>

    <servlet-mapping>
        <servlet-name>remoting</servlet-name>
        <url-pattern>/AuskunftBean_v1_0</url-pattern>
    </servlet-mapping>

</web-app>

----
<1> Entfällt. Die Konfiguration des Spring-Kontextes erfolgt über Java-Config / Component Scan.
<2> Entfällt. Siehe <<isy-logging>>.
<3> Entfällt. Der Spring-Kontext wird über `ServletInitializer` hochgefahren. Siehe <<anwendung>>.
<4> Entfällt. Das Dispatcher-Servlet wird automatisch von Spring Boot konfiguriert.
    Die Trennung von Web- und Anwendungskontext entfällt.
<5> Entfällt. Siehe <<isy-ueberwachung>>.
<6> Entfällt. Beans vom Typ `HttpInvokerServiceExporter` werden automatisch von Spring Boot konfiguriert.
    Der Pfad für das Mapping wird vom Namen der Bean abgeleitet.
[source,java]
----
@Bean(name = "/AuskunftBean_v1_0")
public HttpInvokerServiceExporter meldung() {
----



== Neuerungen in isy-batchrahmen 2.0

=== 6.2.1. Konfigurationsdatei und Kommandozeilenparameter
* Die Property, mit der die Konfiguration für Spring-Kontexte angegeben werden, enthält nicht mehr einen Pfad zu einer XML-Konfigurationsdatei, sondern den voll qualifizierten Namen einer Java-Konfigurationsklasse (`@Configuration`).
* Sollen Beans für den Batch-Lauf nicht im Anwendungskontext erzeugt werden, können sie mit der Annotation `ExcludeFromBatchContext` annotiert werden.

== Neuerungen in isy-polling 2.0

=== 4.1 Anwendungskonfiguration

Die Properties zur Konfiguration von `isy-polling` haben folgendes Schema.
Die Listen kommaseparierter IDs entfallen.

[source,properties]
----
isy.polling.jmx.verbindungen.server1.host = host1
isy.polling.jmx.verbindungen.server1.port = 9001
isy.polling.jmx.verbindungen.server1.benutzer = userid1
isy.polling.jmx.verbindungen.server1.passwort = pwd1

isy.polling.jmx.verbindungen.server2.host = host2
isy.polling.jmx.verbindungen.server2.port = 9002
isy.polling.jmx.verbindungen.server2.benutzer = userid2
isy.polling.jmx.verbindungen.server2.passwort = pwd2

isy.polling.cluster.POSTFACH1_CLUSTER.name = Postfachabruf-1
isy.polling.cluster.POSTFACH1_CLUSTER.wartezeit = 600
isy.polling.cluster.POSTFACH2_CLUSTER.name = Postfachabruf-2
isy.polling.cluster.POSTFACH2_CLUSTER.wartezeit = 700
isy.polling.cluster.POSTFACH2_CLUSTER.jmxverbindungen = server1,server2
----

=== 4.2 Spring Konfiguration

* Die Bean `pollingVerwalter` wird automatisch erstellt.
  Die Konfiguration der JMX-Domain erfolgt über die Property `isy.polling.jmx.domain` in `application.properties`.
* Die MBeans und der MBeanExporter werden manuell über Java-Config konfiguriert.
* Der `PollingAktion`-Interceptor zur Verwendung der Annotation `@PollingAktion` wird automatisch konfiguriert.
