= Referenzarchitektur IT-System: Inhalt

// tag::inhalt[]
== Technische Architektur
Die technische Architektur (xref:glossary:glossary:master.adoc#glossar-t-architektur[T-Architektur]) beschreibt die Strukturierung der IsyFact-Plattform in IT-Systeme, den Aufbau einzelner IT-Systeme und die verwendeten übergreifenden technischen Konzepte.

[[die-referenzarchitektur-eines-it-systems]]
=== Die Referenzarchitektur eines IT-Systems

Die individuell erstellten Anwendungen der Anwendungslandschaft müssen technisch gleichartig aufgebaut sein.
Daher wird im Folgenden die Referenzarchitektur beschrieben, nach der diese Anwendungen software-technisch in IT-Systeme umgesetzt werden.

.Referenzarchitektur eines IT-Systems
[id="image-RAITSys",reftext="{figure-caption} {counter:figures}"]
image::blaupausen:referenzarchitektur-it-system/architektur-it-system.dn.svg[]

In der *Persistenzschicht* ist alle Funktionalität enthalten, die zum Erzeugen, Suchen, Bearbeiten und Löschen von Datenobjekten benötigt wird.
Der Datenzugriff auf das DBMS ist in dieser Schicht vollständig gekapselt.
In Richtung Datenbank kommuniziert diese Schicht mittels JDBC und SQL, in Richtung des Anwendungskerns stellt die Schicht Geschäftsobjekte zur Verfügung.
Die Persistenz nutzt dazu das Framework Hibernate über die Java Persistence API (JPA).

Der *Anwendungskern* umfasst die Geschäftslogik zur Datenbearbeitung, die mit dem System realisiert werden soll.
Dazu gehören zum Beispiel Datenvalidierungen oder Funktionen zum Verarbeiten von Geschäftsobjekten, die über den Datenzugriff geladen wurden.

Die *Nutzungsschicht* ist eine Erweiterung der klassischen Drei-Schichten Architektur:

* Aufgabe des **Batch**es ist es, automatisierte Prozesse ohne einen direkten menschlichen Anwender durchzuführen.
Dabei nutzt der Batch ebenfalls die Funktionen des Anwendungskerns.
Auch hier gibt es spezielle Batch-Schritte, die exklusiv vom Batch benötigt werden und deshalb nicht Bestandteil des Anwendungskerns sind.
Eine Besonderheit beim Batch ist, dass die Steuerung des Batch-Prozesses in der Regel über ein Scheduling-Werkzeug erfolgt.

* Andere Anwendungen greifen mittels *Services* auf den Anwendungskern zu.
Dieser Zugriff erfolgt nicht direkt auf den Anwendungskern, sondern über die Nutzungsschicht „Service“.
Dadurch können auf einfache Art technische Attribute in die Außenschnittstelle aufgenommen werden und der Service des Anwendungskerns kann auf die Kommunikationstechnik abgebildet werden, die für die Kommunikation zwischen IT-Systemen verwendet wird.

Details zur Konstruktion eines IT-Systems werden im xref:methodik:vorlage-systementwurf/antora-master.adoc[IsyFact Systementwurf] festgelegt und für das jeweilige IT-System dokumentiert.

[[uebergreifende-technische-konzeption]]
=== Übergreifende technische Konzeption

Für den Aufbau eines IT-Systems gelten einige übergreifende technische Regeln, die im Folgenden vorgestellt werden.

*Strukturierung des IT-Systems:* Aufgrund der durch die Fachlichkeit festgelegten Funktionalität können IT-Systeme sehr komplex werden.
Um diese Komplexität beherrschen zu können, wird das IT-System in Komponenten zerlegt, die jeweils genau festgelegte Teilfunktionalitäten erfüllen.
Damit die gesamte geforderte Funktionalität erreicht wird, müssen die einzelnen Komponenten miteinander kommunizieren und sich kennen.
Dadurch entsteht ein Komponentengeflecht.
Für die Verwaltung der Komponenten innerhalb des IT-Systems und deren Kopplung wird ein Framework verwendet.
Details hierzu werden im xref:detailkonzept-komponente-anwendungskern/master.adoc[Detailkonzept Komponente Anwendungskern] festgelegt.
Technisch lässt sich ein IT-System in Schichten unterteilen, fachlich in Teilanwendungen.
Details hierzu werden in Kapitel <<der-anwendungskern>> beschrieben.

*Transaktionen:* Veränderungen am Datenbestand gehören zur Kernaufgabe von Informationssystemen.
Diese Veränderungen können jedoch nicht beliebig erfolgen – sie müssen gewisse Eigenschaften haben, damit die Datenbestände nicht an Qualität verlieren: Sie müssen atomar, konsistent, isoliert und dauerhaft sein.
In der Fachliteratur sind diese Eigenschaften als ACID-Eigenschaften (atomicity, consistency, isolation, durability) bekannt.

Änderungen am Datenbestand können komplex sein, das heißt es können viele Informationen und Zusammenhänge von den Änderungen betroffen sein.
Solche komplexen Änderungen werden vom Informationssystem meist in einzelne, einfache Änderungsschritte zerlegt.
Damit die ACID-Eigenschaften der komplexen Änderung erhalten bleiben, muss das Informationssystem entweder alle Änderungsschritte ausführen oder keinen.
Damit es dazu in der Lage ist, werden die Änderungsschritte zunächst zu einer logischen Einheit zusammengefasst – einer Transaktion.

Für die Referenzarchitektur wird festgelegt, dass die Nutzungsschicht für die Steuerung der Transaktionen zuständig ist.
Der Anwendungskern selbst steuert in der Regel keine Transaktionen.
Er bietet der nutzenden Schicht eine Schnittstelle zur Transaktionssteuerung an, d. h. der Anwendungskern wird durch die Nutzungsschicht gesteuert.

*Zugriffe auf die Datenbank:* Bei Zugriffen auf die Datenbank werden die Objekte des Anwendungskerns auf die relationalen Tabellenstrukturen der Datenbank abgebildet.
Dabei müssen folgende Aufgaben erfüllt werden:

* *Objekt-relationales Mapping:* die Daten der relationalen Datenbank werden Attributen von Objekten zugeordnet.
Dabei werden Datentypen der Datenbank in ihre Objekt-Äquivalente umgesetzt, eine Abbildung von Vererbung im Objektmodell auf relationale Strukturen durchgeführt und Fremdschlüsselbeziehungen zwischen Tabellen durch Relationen zwischen Objekten abgebildet.

* *Objektidentität:* Wenn ein Datensatz im Verlauf der Bearbeitung mehrmals gelesen wird, so muss dafür gesorgt werden, dass nicht mehrfach gleiche Objekte in einer Anwendung erzeugt werden.

* *Transaktionssteuerung und Sperren:* Es müssen fachliche Transaktionen auf technische Transaktionen gegen die Datenbank abgebildet werden.
Dabei wird eine optimistische Sperrstrategie umgesetzt.
Ein übliches Verhalten ist zum Beispiel das Folgende: Erstreckt sich eine fachliche Transaktion über mehrere Dialogschritte, wird die Zugriffsschicht erst beim Verlassen des letzten Dialogs eine technische Datenbanktransaktion auslösen.
Um zu prüfen, ob die Daten in der Zwischenzeit nicht durch einen anderen Anwender verändert worden sind, wird die Zugriffsschicht beim Schreiben Zeitstempel oder Versionszähler der Datensätze überprüfen.
+
Um diesen großen Funktionsumfang abzudecken, wird ein Produkt zum objekt-relationalen Mapping gemäß JPA-Standard eingesetzt.
Details hierzu sind im xref:isy-persistence:konzept.adoc[Baustein JPA/Hibernate] dokumentiert.

*Caching:*
Anwendungsspezifische Caches sind mit Spring Cache Abstraction zu implementieren.
Die Caching-Funktionalität wird so mit Spring Cache Abstraction und einem Caching Provider (z.B. EHCache) bereitgestellt.
Spring Cache Abstraction bietet eine effiziente und flexible Möglichkeit Caching in Anwendungen zu implementieren.
Weitere und detaillierte Informationen sind in https://docs.spring.io/spring-framework/reference/integration/cache.html[der Spring Dokumentation] einzusehen.
Durch die Verwendung von Spring Cache Abstraction wird, z.B. über die Nutzung von Annotationen, das Hinzufügen von Caching zu bestehenden Methoden erleichtert.
Der zugrundeliegende Code ist nicht wesentlich zu verändern.
Mit dem abstrahierten Caching ist die Cache-Implementierung unabhängig von dem genutzten Cache-Provider.
Die Wahl des Cache-Providers ist gemäß einer notwendigen Skalierung und betrieblichen Gegebenheiten abzustimmen.
EHCache wird empfohlen (Vlg. xref:einstieg:produktkatalog/technologiestackJavaSpring.adoc#Entwicklung[Produktkatalog: Entwicklung]).
Für weitere Informationen zu EHCache sind in der https://www.ehcache.org/documentation/[EHCache Dokumentation] einzusehen.


[[der-anwendungskern]]
=== Der Anwendungskern

include::blaupausen:page$detailkonzept-komponente-anwendungskern/inhalt.adoc[tags=anwendungskern-definition]

Nicht Teil des Anwendungskerns sind spezielle Dialogabläufe, z.B. dialogspezifische Bearbeitungsverfahren wie die Anwenderführung über Wizards.
Diese Prozesse, die nur durch einen einzigen Dialog genutzt werden, sind Teil der Schicht Nutzung.
Der Anwendungskern stellt somit im Wesentlichen allgemein nutzbare xref:glossary:glossary:master.adoc#glossar-service[Services] zur Verfügung.

include::blaupausen:page$detailkonzept-komponente-anwendungskern/inhalt.adoc[tags=fachkomponente-definition]

*Komponenten-Framework:* Für querschnittliche Funktionalität innerhalb des Anwendungskerns wird das Spring-Framework genutzt.
Hauptaufgabe des Frameworks ist es, die Komponenten zu konfigurieren und miteinander bekannt zu machen.
Dadurch wird die Trennung zwischen Fachlichkeit und Technik verbessert.
Beispiel für querschnittliche Funktionalität ist die deklarative Steuerung von Transaktionen.

*Externe Services:* Wenn der Anwendungskern fachliche Services benötigt, die von anderen IT-Systemen innerhalb der xref:glossary:glossary:master.adoc#glossar-plattform[Plattform] angeboten werden, so werden diese Services als Komponente im Anwendungskern abgebildet.
Dadurch ist die Funktionalität sauber gekapselt, was die Wartbarkeit erhöht.
Wenn der externe Service ausgetauscht werden soll, ist keine Änderung der gesamten Anwendung notwendig – es ist lediglich eine interne Änderung der externen Service-Komponente notwendig.
Für andere fachliche Komponenten des Anwendungskerns ist nicht zu unterscheiden, ob es sich beim Aufruf einer Komponentenschnittstelle um eine in dieser Komponente implementierte Funktion oder um einen Serviceaufruf handelt.
Komponenten, die externe Services kapseln, sind im Idealfall von außen nicht von fachlichen Komponenten des Anwendungskerns unterscheidbar.
Diese Komponenten haben damit zwei Hauptaufgaben: Sie müssen die technischen Aspekte der Kommunikation umsetzen und sie müssen Schnittstellendaten und Exceptions der aufgerufenen Services in die Datenformate der Anwendung transformieren.

Weitere Details können dem xref:detailkonzept-komponente-anwendungskern/master.adoc[Detailkonzept Komponente Anwendungskern] entnommen werden.

[[datenzugriff]]
=== Datenzugriff

In der Persistenz-Schicht sind die Fachkomponenten auch gemäß den Komponenten aus der fachlichen Architektur strukturiert.
Die Komponenten des Anwendungskerns besitzen die Datenhoheit auf die Entitäten, die ihnen eindeutig zuzuordnen sind.
Diese Entitäten stammen aus den korrespondierenden Komponenten in der Persistenz-Schicht.
Nur die korrespondierende Anwendungskern-Komponente darf Änderungen an den entsprechenden persistenten Entitäten vornehmen.

.icon:university[title=Architekturregel] Persistente Entitäten im Anwendungskern
****
Persistente Entitäten dürfen nicht über den Anwendungskern hinaus herausgegeben werden. Sie haben im Anwendungskern zu verbleiben.
****

Andernfalls ist nicht sichergestellt, dass andere Komponenten keine Änderungen an den persistenten Entitäten vornehmen.
Für den Transfer über Komponentengrenzen hinweg - oder aus dem Anwendungskern hinaus - müssen alle Komponenten des Anwendungskerns die ihnen zugeordneten persistenten Entitäten auf Geschäftsobjekte abbilden.
Wenn Entitäten von mehreren Komponenten genutzt werden und keiner einzelnen Komponente zugeordnet werden können, sollten sie in einem eigenen querschnittlichen Package abgelegt werden.


[[batch]]
=== Batch

Ein xref:glossary:glossary:master.adoc#glossar-batch[Batch] realisiert eine eigenständige Verarbeitung ohne direkten Benutzereingriff während des Ablaufes.
An einen Batch werden verschiedene Anforderungen gestellt: Ausführungszeitpunkt, Abhängigkeiten, Datenvolumen, ausgeführte Funktionalität, Eingaben, Ausgaben usw.

Aus Architektur-Sicht werden diese Anforderungen durch zwei Komponenten abgedeckt: den Batchrahmen und die Batchlogik.

*Batchrahmen:* Der Batchrahmen stellt die Schnittstelle für den Aufruf der Batchfunktionalität zur Verfügung.
Er übernimmt auch die Transaktionssteuerung und die Steuerung für einen Restart.

*Batchlogik:* Die Batchlogik wird vom Batchrahmen aufgerufen, um die Funktionalität des Batchverarbeitungsprogramms zu aktivieren.
Die Funktionalität, das heißt die Geschäftslogik und die Arbeitsschritte eines Batches, werden als Anwendungsfälle erfasst.
Wenn diese Anwendungsfälle auch von anderen Nutzern benötigt werden, dann sind sie im Anwendungskern implementiert.

.Bestandteile von Batchverarbeitungsprogrammen
[id="image-TeileBat",reftext="{figure-caption} {counter:figures}"]
image::blaupausen:referenzarchitektur-it-system/architektur-it-system-batch.dn.svg[]

Batches werden als eigener Prozess auf einem eigenen Server ausgeführt, das heißt sie laufen nicht in der virtuellen Maschine des Application Servers ab.
Batches werden somit in einer eigenen Ablaufumgebung ausgeführt und greifen direkt auf die Datenbank oder auch auf Dateien zu.
Die benötigte Funktionalität des Anwendungskerns wird dem Batch als Bibliothek zur Verfügung gestellt und nicht über einen Service-Aufruf genutzt.
Der Grund für diese Entscheidung liegt in den Datenmengen, die normalerweise von einem Batch verarbeitet werden: Die Übermittlung dieser Datenmengen über eine remote genutzte Schnittstelle ist ein möglicher Flaschenhals in der Anwendung.
Dieser Flaschenhals wird durch die Nutzung der Anwendungskernfunktionalität als Bibliothek vermieden.

Batch-Abläufe bestehen aus einem oder mehreren Batch-Schritten.
Die einzelnen Batch-Schritte werden von einem Scheduler aufgerufen und zum vollständigen Batch-Ablauf verbunden.
Ein Batch-Schritt wird von einem Programm implementiert, das mit entsprechenden Parametern vom Scheduler aufgerufen werden kann.
Die hier beschrieben Batches sind genau diese Batch-Schritte.

Die Batch-Schritte haben eine genormte Schnittstelle für Aufruf und Rückgabewerte.
Sie sind in der Regel restart-fähig.
Es gibt einen Batch-Rahmen, der dies unterstützt.

Weiterführende technische Details zum Batch sind im xref:detailkonzept-komponente-batch/master.adoc[Detailkonzept Komponente Batch] enthalten.

[[servicezugriffe]]
=== Servicezugriffe

Services des Anwendungskerns, die vom IT-System zur Verfügung gestellt werden sollen, werden durch die Komponenten von „Service“ innerhalb der Schicht „Nutzung“ angereichert und nach außen gegeben.
Dabei können alle Funktionen des xref:glossary:glossary:master.adoc#glossar-anwendungskern[Anwendungskerns] genutzt werden.
Die Service-Komponenten werden entsprechend den Anwendungskern-Komponenten geschnitten, d.h. für jede Komponente des Kerns, die einen Service anbieten soll, wird eine eigene Service-Komponente implementiert.
Service-Komponenten werden nicht mehrere Anwendungskern-Komponenten.
Dies würde dem Gebot, in den Services keine Logik zu implementieren, widersprechen.

Der Aufbau der Komponente Service ist in <<image-TeileServ>> dargestellt.
Intern besteht die Komponente „Service“ aus zwei Teilen: dem Service-Framework und der Service-Logik.

.Die Bestandteile von Services
[id="image-TeileServ",reftext="{figure-caption} {counter:figures}"]
image::blaupausen:referenzarchitektur-it-system/architektur-it-system-service.dn.svg[]

*Service-Framework:* Das Service-Framework ist die Bezeichnung für die Technologie, mit der die Services des Anwendungskerns zur Verfügung gestellt werden.

*Service-Logik:* Die Service-Logik selbst beinhaltetet (und nutzt) Funktionalität des Anwendungskerns.  
Im Normalfall ist dabei der Funktionsumfang der Komponente Service-Logik viel geringer als der Funktionsumfang der Entsprechungen im Anwendungskern.
Dies liegt darin begründet, dass die Komponente Service-Logik die Funktionalität des Anwendungskerns nutzt, um den Service bereitzustellen.
Die Kernfunktionalität des Services ist also im Anwendungskern implementiert.
Die Schnittstelle zwischen den Komponenten „Service“ und „Anwendungskern“ ist daher eine interne Schnittstelle.

Weiterführende technische Details zu Services sind im xref:detailkonzept-komponente-service/master.adoc[Detailkonzept Komponente Service] beschrieben.


[[unterstuetzung-technischer-funktionalitaeten]]
=== Unterstützung technischer Funktionalitäten

Neben Services, Batch, Anwendungskern und Persistenzschicht benötigt ein IT-System mehrere querschnittliche Funktionalitäten.
Diese querschnittlichen Funktionalitäten sind in jeweils eigenen Dokumenten beschrieben.
Eine Übersicht dazu liefern die Beschreibungen der Bausteine der xref:einstieg:vorstellung/isyfact-standards.adoc#bausteine-der-isyfact-standards[IsyFact-Standard] sowie der xref:einstieg:vorstellung/isyfact-erweiterungen.adoc#bausteine-der-isyfact-erweiterungen[IsyFact-Erweiterungen].

// end::inhalt[]
