= Nutzungsvorgaben Task Scheduling

[[verwendung-der-bibliothek-isy-task]]
== Verwendung der Bibliothek `isy-task`

In diesem Abschnitt werden Inhalt und Einsatz der Bibliothek `isy-task` beschrieben.

[[maven]]
=== Maven

Um die Bibliothek einzubinden, fügen Sie die `isy-task` Abhängigkeit in Ihre pom.xml hinzu.

[source, xml]
----
<dependency>
    <groupId>de.bund.bva.isyfact</groupId>
    <artifactId>isy-task</artifactId>
</dependency>
----

[[erstellung-eines-tasks]]
=== Erstellung eines Tasks

Um einen Task zu erstellen, muss eine Methode mit `@Scheduled` annotiert werden. Dabei handelt es sich um eine Annotation, die eine zu planende Methode kennzeichnet. Es muss genau eines der Attribute `cron()`, `fixedDelay()` oder `fixedRate()` angegeben werden.

Die annotierte Methode darf keine Argumente erwarten. Sie hat normalerweise den Rückgabetyp `void`; andernfalls wird der zurückgegebene Wert beim Aufruf durch den Scheduler ignoriert.

Die Verarbeitung von mit `@Scheduled` annotierten Methoden wird durch die mit `@EnableScheduling` annotierte Konfigurationsklasse `IsyTaskAutoConfiguration` sichergestellt.

Die `@Scheduled`-Annotation kann beliebig oft verwendet werden.

[source, java]
----
@Timed(value = "task.scheduledTasks.scheduleTaskWithFixedDelay")
@Scheduled(fixedDelay = 2000)
public void scheduleTaskWithFixedDelay() {
    System.out.println("Fixed delay task - " + System.currentTimeMillis() / 1000);
}
----

In diesem Fall ist die Dauer zwischen dem Ende der letzten Ausführung und dem Beginn der nächsten Ausführung festgelegt. Der Task wartet immer, bis der vorhergehende beendet ist.

Diese exemplarische Option sollte verwendet werden, wenn es zwingend erforderlich ist, dass die vorherige Ausführung abgeschlossen ist, bevor sie erneut ausgeführt wird.

Weitere Informationen über den Einsatz von Annotationsattributen finden sich in der https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/Scheduled.html#dokumentation-spring[Spring Dokumentation].

Damit eine `@Scheduled`-Annotation von Spring registriert wird, muss die Klasse, in welcher der Task erstellt wird, entweder mit `@Component` annotiert werden oder über eine @Bean-Methode in den Kontext gelegt werden.

Das Starten und Stoppen eines Tasks wird durch Einsatz der Annotationen vollständig von Spring übernommen.


[[manuelles-starten-stoppen]]
=== Manuelles Starten und Stoppen von Tasks

Es ist ebenfalls möglich, Tasks händisch zu starten und/oder zu stoppen. Zu diesem Zweck wurde `isy-task` um die Annotation `OnceTask` erweitert. Darüber hinaus kommt der `TaskScheduler` aus dem Spring-Framework zum Einsatz.

Eine Klasse, die einen Task bzw. eine Funktion beinhaltet, die manuell gestartet und gestoppt werden soll, muss zunächst mit @Component annotiert werden und das Runnable-Interface implementieren, damit die mit `@OnceTask` annotierte Methode von `isy-task` verarbeitet werden kann.

[source, java]
----
@Component
public class ProgrammaticallyScheduledTask implements Runnable {

    private static final IsyLogger logger = IsyLoggerFactory.getLogger(ScheduledTasks.class);

    private static final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    @Override
    @OnceTask
    public void run() {
        for (int i = 0; i < 3; i++) {
            try {
                MILLISECONDS.sleep(100);
                logger.info(LogKategorie.JOURNAL, "EISYTA99994", "Manual Task {} :: Execution Time - {}", i, dateTimeFormatter.format(LocalDateTime.now()));
            } catch (InterruptedException e) {
                logger.debug("Thread unterbrochen");
                return;
            }
        }
    }
}
----

Exemplarisch kann der Task anschließend durch den Aufruf `taskScheduler.scheduleWithFixedDelay(task, Duration.ofSeconds(3));` gestartet werden. `schedule()` liefert einen Rückgabewert vom Typ `ScheduledFuture`, welcher unter anderem die `cancel()`-Methode bereitstellt und ein manuelles Stoppen des Tasks ermöglicht.

Im folgenden Beispiel wird ein Task mit einer Verzögerung von jeweils drei Sekunden ausgeführt. Nach zehn Sekunden wird der Task durch die `cancel()`-Methode manuell gestoppt. Folglich wird der Task dreimal erfolgreich ausgeführt.

[source, java]
----
@RunWith(SpringRunner.class)
@Import(ProgrammaticallyScheduledTask.class)
@SpringBootTest(classes = TestConfig.class, webEnvironment = SpringBootTest.WebEnvironment.NONE, properties = { "isy.logging.anwendung.name=test", "isy.logging.anwendung.typ=test",
    "isy.logging.anwendung.version=test",
    "isy.task.tasks.programmaticallyScheduledTask-run.host=.*"})
public class TestTaskScheduledProgrammatically {

    @Autowired
    private TaskScheduler taskScheduler;

    @Autowired
    private ProgrammaticallyScheduledTask task;

    @Test
    public void testScheduleManuell() throws Exception {

        String className = ProgrammaticallyScheduledTask.class.getSimpleName();
        String annotatedMethodName = "run";

        ScheduledFuture<?> scheduledFuture =
            taskScheduler.scheduleWithFixedDelay(task, Duration.ofSeconds(3));

        SECONDS.sleep(10);

        scheduledFuture.cancel(true);

        Counter successCounter = TaskCounterBuilder.successCounter(className, annotatedMethodName, registry);

        assertEquals(3, successCounter.count());

    }
}
----

Erweiterte Funktionalität: Es muss nicht zwangsläufig das Runnable-Interface implementiert werden, alternativ kann eine beliebige Methode mit @OnceTask annotiert werden. Diese muss anschließend per Lambda dem Scheduler übergeben werden:

[source, java]
----
@RunWith(SpringRunner.class)
@Import(ProgrammaticallyScheduledTask.class)
@SpringBootTest(classes = TestConfig.class, webEnvironment = SpringBootTest.WebEnvironment.NONE, properties = { "isy.logging.anwendung.name=test", "isy.logging.anwendung.typ=test",
    "isy.logging.anwendung.version=test",
    "isy.task.tasks.programmaticallyScheduledTask-run.host=.*"})
public class TestTaskScheduledProgrammatically {

    @Autowired
    private TaskScheduler taskScheduler;

    @Autowired
    // has an @OnceTask-annotated execute()-Method
    private AlternativeTask task;

    @Test
    public void testScheduleManuell() throws Exception {

        ScheduledFuture<?> schedule = taskScheduler.scheduleWithFixedDelay(() -> task.execute(), Duration.ofSeconds(3));

        // ...

        schedule.cancel(true);

    }
}
----

[[konfigurieren-von-tasks]]
=== Konfigurieren von Tasks

Tasks können über zwei Wege konfiguriert werden. Bevorzugt sollten Tasks über die `application.properties` konfiguriert werden.

Das folgende Listing zeigt die Konfiguration für einen `scheduleTaskWithFixedDelay` Task.

[source,properties]
----
isy.task.tasks.scheduledTasks-scheduleTaskWithFixedDelay.deaktiviert={true/false}
isy.task.tasks.scheduledTasks-scheduleTaskWithFixedDelay.host={host}
isy.task.tasks.scheduledTasks-scheduleTaskWithFixedDelay.oauth2-client-registration-id={id}
----

Zu beachten ist die Konvention zur Namensgebung für Tasks.
Sie folgt immer dem Schema `"klassenName-methodenName"`.

`ComputerName` ist der Name der Maschine, auf der der Task läuft.

Eine weitere Möglichkeit besteht über die programmatische Konfiguration. Hierzu muss, bevor der Task geschedulet wird, die TaskConfig bearbeitet werden und anschließend der Task-Map zusammen mit der Task ID wieder hinzugefügt werden.

Ein Task wird grundsätzlich als Spring Bean konfiguriert.

[source, java]
----
public void configureTasks(IsyTaskConfigurationProperties cp) {
    taskConfig = cp.getTasks().computeIfAbsent(taskId, k -> new TaskConfig());

    taskConfig.setDeaktiviert("...");
    taskConfig.setHost("...");
    taskConfig.setOauth2ClientRegistrationId("...");
}
----

[[absicherung-von-tasks]]
== Absicherung von Tasks

Für die Absicherung eines Tasks benötigt es in der Task-Konfiguration eine OAuth 2.0 Client Registration ID.
Diese kann als Teil der <<allgemeine-konfiguration,allgemeinen Konfiguration>> gültig für alle Tasks definiert werden oder in der <<aufgabenspezifische-konfiguration,aufgabenspezifischen Konfiguration>> speziell für jeden einzelnen Task.
Die Details einer `ClientRegistration`-Konfiguration sind in den xref:isy-security:nutzungsvorgaben/master.adoc#authentifizierungsmanager-authentication[Nutzungsvorgaben Sicherheit und der Authentifizierung eines OAuth 2.0 Clients mit dem Authentifizierungsmanager] beschrieben.
Hierbei kann der Sicherheitsbaustein entweder Resource Owner Password Credentials (ROPC) oder Client Credentials verwenden.
Die Verwendung von ROPC ermöglicht es, die Identität des Benutzers abzufragen und die Tasks sicher auszuführen, während der Client Credentials Flow die Authentifizierung und Autorisierung der Anwendung selbst ermöglicht, um auf geschützte Ressourcen zuzugreifen.

Weitere detaillierte Informationen zur Implementierung und Konfiguration dieser Sicherheitsbausteine finden sich in der Spring Boot Security Dokumentation, die eine umfassende Anleitung und Best Practices bereitstellt.

[[konfigurationsschluessel]]
== Konfigurationsschlüssel

Die folgenden Konfigurationsschlüssel werden von `isy-task` eingelesen und verwertet.

[[allgemeine-konfiguration]]
=== Allgemeine Konfiguration

Die ID der Client Registration aus `isy-security` zur Authentifizierung, wenn keine Task-spezifische `oauth2-client-registration-id` konfiguriert wird.
Hierüber wird der zu verwendende OAuth 2.0 Client und die Kennung, das Passwort und das BHKNZ des Nutzers aufgelöst:

[source,properties]
----
isy.task.default.oauth2-client-registration-id={default-id}
----

Der Host, wenn kein Task-spezifischer Host konfiguriert wird:

[source,properties]
----
isy.task.default.host={default-host}
----

[[aufgabenspezifische-konfiguration]]
=== Aufgabenspezifische Konfiguration

Die ID der Client Registration aus `isy-security`, die zur Authentifizierung genutzt wird.
Hierüber wird der zu verwendende OAuth 2.0 Client und die Kennung, das Passwort und das BHKNZ des Nutzers aufgelöst:

[source,properties]
----
isy.task.tasks.<Task>.oauth2-client-registration-id={id}
----

Der Name des Hosts auf dem der Task ausgeführt werden soll.
Der Name kann als regulärer Ausdruck angegeben werden, es wird dann geprüft, ob der tatsächliche Hostname dem regulären Ausdruck entspricht.
Dadurch kann auch eine Liste von Hostnamen angegeben werden, z.B. `host1|host2|host3`:

[source,properties]
----
isy.task.tasks.<Task>.host={host}
----

Actuator Monitoring-Endpunkte für Micrometer
[source,properties]
----
management.endpoints.web.exposure.include=info,health,metrics
----

Monitoring mit Actuator ermöglichen

[source,properties]
----
management.endpoint.metrics.enabled=true
----

[[monitoring]]
== Monitoring

isy-task stellt folgende Task-spezifische Metriken über den Endpunkt `/actuator/metrics` zur Verfügung.

:desc-table-metriken: Metriken
[id="table-standard-metriken", reftext = "{table-caption} {counter:tables}"]
.{desc-table-metriken}
[cols="1s,2,2m", options="header"]
|===
|Metriken
|Beschreibung
|Namespace

|Timer Metriken
|Metriken die das Timing von mit `@Timed`-annotierten Tasks betreffen. Zeigt an, wie oft ein Task ausgeführt wurde, wie viel Zeit alle Durchläufe eines Tasks in Anspruch genommen haben und die maximale Ausführungszeit. Darüber hinaus filtern nach Tags möglich, zum Beispiel: `/actuator/metrics/method.timed?tag=method:mySuccessTask`

|method.timed.

|Metriken Task erfolgreich
|Zeigt an wie oft ein Task erfolgreich durchgeführt wurde.
|className-taskName.success +

|Metriken Task fehlgeschlagen
|Zeigt an wie oft ein Task fehlgeschlagen ist. Ggf. Ausgabe von Exceptions.
|className-taskName.failure +

|===

Darüber hinaus sind über `/actuator/info` sowie `/actuator/health` Informationen über den Zustand des einbindenden Systems verfügbar.

[[monitoring-scheduled-future]]
=== Monitoring mit ScheduledFuture

Neben dem Monitoring mit Actuator ist ein Monitoring mit Objekten vom Typ `ScheduledFuture`
möglich.
Dies ist allerdings nur möglich, wenn ein Task über `taskScheduler.schedule()` manuell gestartet wurde.

[[hinweise-fuer-den-task-im-parallelbetrieb]]
== Hinweise für den Task im Parallelbetrieb

Bei der Implementierung eines Tasks muss beachtet werden, dass ihn die Bibliothek im Parallelbetrieb betreiben wird.
Werden hierbei die Besonderheiten der Java Multithreading API nicht berücksichtigt, kann dies zu einem fehlerhaften Verhalten in der xref:glossary:glossary:master.adoc#glossar-geschaeftsanwendung[Geschäftsanwendung] führen.

[[threadsicherheit]]
=== Threadsicherheit

Ein wichtiger Aspekt des Parallelbetriebs ist die Threadsicherheit.
In diesem Abschnitt werden die Probleme bezüglich der Threadsicherheit verdeutlicht.
Grundsätzlich ist es so, dass Rechner mit mehreren Rechnerkernen, den Parallelbetrieb auf Hardwareebene verwirklichen und somit den Gesamtprozess beschleunigen.
Die Anzahl der Rechnerkerne braucht programmatisch aber nicht berücksichtigt werden, weil die Java Laufzeitumgebung auch die Rechenzeit eines einzelnen Rechnerkerns in feingranulare Zeitscheiben schneidet.
Hierdurch kann die Rechenzeit einer blockierenden Aufgabe für die Erledigung anderer Aufgaben genutzt werden.
Allerdings bietet dies auch ein hohes Potenzial für ein fehlerhaftes Verhalten.
Denn die Zuordnung der Zeitscheiben erfolgt bei jeder erneuten Ausführung der Geschäftsanwendung unterschiedlich.
Daher kann ein erfolgreicher JUnit-Test eine fehlerfreie Ausführung in der Produktionsumgebung nicht gewährleisten.
Selbst die Aufteilung auf unterschiedliche Rechnerkerne verhindert von sich aus kein fehlerhaftes Verhalten.
Aus diesem Grund müssen Methoden, die nicht von mehreren Threads gleichzeitig durchlaufen werden sollen, über einen Lock-Mechanismus (beispielsweise über das Schlüsselwort synchronized) davor geschützt werden.

Ein weiteres Problem gemeinsamer Instanzen betrifft die Objektvariablen.
Auch der Zugriff auf eine veränderbare Objektvariable (d.h. eine Objektvariable, die nicht mit final versehen wurde) eines gemeinsamen Objekts kann nicht konsistent erfolgen, weil jeder Rechnerkern über einen eigenen Cache verfügt, der sich bei Änderung des Wertes naturgemäß vom Wert im Cache des anderen Rechnerkerns unterscheidet.
Hilfreich ist hierbei das Schlüsselwort __volatile__, das dafür sorgt, dass vor jedem Zugriff eine Synchronisation zwischen dem Thread-spezifischen Cache und dem Hauptspeicher stattfindet.
Die Objektvariable die mit volatile versehen wurde, ist also scheinbar atomar.
Allerdings trifft das nicht für den schreibenden Zugriff zu, da jegliche Veränderung in mehreren Schritten erledigt wird.
Um sicherzustellen, dass der Zugriff auf eine gemeinsame Objektvariable konsistent ist, wird beispielsweise der Wertebehälter einer Ganzzahl mit dem speziellen Wertetypen AtomicInteger definiert.
In der Regel wird es sich bei der Objektvariablen aber eher um einen Referenztypen handeln.
In diesen Fällen sollten die Objektvariablen in einem ThreadLocal-Objekt deklariert werden.
