= Nutzungsvorgaben Fehlerbehandlung: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Dokument enthält die Nutzungsvorgaben zur Fehlerbehandlung für alle Anwendungen gemäß Referenzarchitektur der IsyFact.

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

Ziel dieses Dokumentes ist es, eine Anleitung für die korrekte Verwendung von Exceptions zu geben.
Es enthält Vorgaben zur Nutzung der Isyfact-Fehlerbehandlung sowie zu deren Umsetzung und Anwendung.
Die von den Anwendungen benötigten Exception-Klassen sind von der konkreten Anwendung abhängig und müssen im entsprechenden Projekt unter Berücksichtigung dieser Vorgaben erstellt werden.
Zur Umsetzung werden ausführliche Beispiele gegeben.

Im Kapitel xref:nutzungsvorgaben/master.adoc#implementierung-der-fehlerbehandlung[Implementierung der Fehlerbehandlung] werden die Nutzungsvorgaben definiert, wie Exceptions zu erstellen sind und wie sie behandelt werden müssen.
Abschließend werden typische xref:nutzungsvorgaben/master.adoc#dos-und-donts[Dos and Don'ts] erläutert, die bei der Fehlerbehandlung beachtet werden müssen.
// end::inhalt[]
