
// tag::inhalt[]
:anwendung: Beispielverzeichnis
:anwendung-ga: Beispielverzeichnis-GA
:anwendung-sgw: Beispielverzeichnis-SGW
:anwendung-batch: Beispielverzeichnis-Batch
:it-system-ga: isy-bsp-ga
:it-system-sgw: isy-bsp-sgw
:it-system-batch: isy-bsp-batch

:!sectnums:
== Allgemeine Hinweise zur Dokumentvorlage

IMPORTANT: Dieses Kapitel wird in der finalen Fassung des Systemhandbuchs entfernt.

=== Zweck dieses Dokuments

Die Dokumentvorlage enthält die Gliederung für ein Systemhandbuch.
Das Systemhandbuch ist die Dokumentation eines IT-Systems aus betrieblicher Sicht.
Dazu gehören insbesondere Informationen zur Installation, Konfiguration, Batches, Fehleranalyse und Backup.

Das Dokument wird durch die Entwickler der Software erstellt und gepflegt.
Es enthält nur solche Informationen, welche die eigentliche Software betreffen, Informationen zu Systemumgebungen, Hardware usw. werden vom Betrieb in separaten Dokumenten gepflegt.

In diesem Dokument werden alle IT-Systeme einer Anwendung gemeinsam beschrieben.
Die Abgrenzung, welche IT-Systeme zusammen beschrieben werden, ist ggf. im Einzelfall abzuwägen.
Typischerweise werden eine Geschäftsanwendung und ein zugehöriges Service-Gateway gemeinsam beschrieben, aber z.B. nicht zwei Geschäftsanwendungen die zu unterschiedlichen Fachverfahren gehören, auch wenn Sie sich gegenseitig aufrufen.
Ein wichtiges Kriterium für die Auswahl der IT-Systeme ist deren Entwicklungszyklus.
IT-Systeme, die immer gemeinsam weiterentwickelt werden, können gut in einem gemeinsamen Dokument beschrieben werden.
Querschnittsanwendungen werden in eigenen Dokumenten beschrieben.

Die Vorlage enthält bewusst auch Kapitel für Themen, die nicht für alle Systeme benötigt werden.
Dies soll eine möglichst große Vollständigkeit der damit erstellten Dokumentationen begünstigen.

Bei Bedarf können Kapitel entfernt werden.

=== Verwendung von Dokumentattributen

Die Vorlage verwendet für zentrale Begriffe Dokumentattribute, damit diese an zentraler Stelle änderbar sind.

[[dokumentattribute]]
.Dokumentattribute der Vorlage für das Systemhandbuch
[cols="2m,4,3", options="header"]
|===
|Attribut
|Bedeutung
|Standardwert

|anwendung
|Fachlicher Name der Anwendung
|{anwendung}

|anwendung-ga
|Fachlicher Name der Geschäftsanwendung
|{anwendung-ga}

|anwendung-sgw
|Fachlicher Name des Service-Gateways
|{anwendung-sgw}

|anwendung-batch
|Fachlicher Name der Batch-Anwendung
|{anwendung-batch}

|it-system-ga
|Technischer Name der Geschäftsanwendung
|`{it-system-ga}`

|it-system-sgw
|Technischer Name des Service-Gateways
|`{it-system-sgw}`

|it-system-batch
|Technischer Name der Batch-Anwendung
|`{it-system-batch}`
|===

=== Verwendung von Namenskonventionen

In diesem Dokument werden die Namenskonventionen der IsyFact verwendet.
Die Namenskonventionen können dem jeweiligen Kontext, in dem die IsyFact eingesetzt wird, angepasst werden.

:sectnums:

[[einleitung]]
== Einleitung

Dieses Dokument enthält das Systemhandbuch für die Anwendung {anwendung}.

Es umfasst die folgenden IT-Systeme:

* {anwendung-ga} (technischer Name: `{it-system-ga}`),
* {anwendung-sgw} (technischer Name: `{it-system-sgw}`),
* {anwendung-batch} (technischer Name: `{it-system-batch}`).

Das Kapitel <<ueberblick>> bietet einen groben fachlichen, technischen sowie betrieblichen Überblick über die Anwendung und liefert Verweise auf weitergehende Dokumente.
Es ist für alle Leser des Dokuments relevant.

Das Kapitel <<bau-anwendung>> beschreibt, wie aus dem Quellcode die Deployment-Einheiten (RPMs) entstehen.
Es ist im Wesentlichen für die Softwareentwicklungsabteilung relevant.

Das Kapitel <<vorbereitung-systemumgebung>> beschreibt, wie die Systemumgebung auf den Betrieb der Anwendung hin zu konfigurieren ist.
Es ist für den Betrieb und die Softwareentwicklung relevant.

Die Kapitel <<installation-anwendung>> sowie <<konfiguration-anwendung>> beschreiben die Installation und Konfiguration der Anwendung auf der Systemumgebung.
Sie sind wiederum für den Betrieb und die Softwareentwicklung relevant.

Das Kapitel <<regulaerer-wirkbetrieb>> liefert Informationen für den Betrieb der Anwendung.
Es ist für den Betrieb relevant.

Das Kapitel <<hinweise-stoerungsdiagnose-behandlung>> schließlich liefer Informationen zur Fehleranalyse.
Es ist für den Betrieb und die Softwareentwicklung relevant.

Der <<anhang>> bietet zusätzliche Informationen wie eine Historie der Anwendung, ein fachliches Glossar und eine vollständige Liste der Fehlercodes anhand von Tabellen an.

[[ueberblick]]
== Überblick

In diesem Kapitel wird aus fachlicher und technischer Sicht ein Überblick über die Geschäftsprozesse gegeben, die mithilfe der Anwendung {anwendung} durchgeführt werden.

[[fachliche-beschreibung]]
=== Fachliche Beschreibung

_Kurze, prägnante fachliche Darstellung der Anwendung. [...]_

[[fachlicher-kontext]]
.{anwendung}: Fachlicher Kontext
image::vorlage-systemhandbuch/fachlicher-kontext.dn.svg[]

NOTE: Weitere fachliche Details können in der <<quellen,Systemspezifikation>> nachgelesen werden.

====
Inhalt::

* _Sehr kurze zusammenfassende fachliche Darstellung der Anwendung._
* _Darstellung des fachlichen Kontextes._
* _Verweis auf aktuelle Version der Systemspezifikation._

Quelle::
_Systemspezifikation (Extrakt aus Einleitung / Überblick & fachlicher Kontext)_

Dokumentationsform::
_Freitext, fachliches Kontextdiagramm_
====


[[anwendergruppen]]
==== Anwendergruppen

Die Anwendung {anwendung} hat folgende Anwendergruppen:

* [Name der Anwendergruppe, aus fachlichem Kontext] ([wichtigster Anwendungsfall]),
* ...

====
Inhalt::
_Sehr knappe Zusammenfassung der Anwendergruppen und ihrer wichtigsten Anwendungsfälle.
Ergänzungen können unterhalb der Liste vorgenommen werden, falls nötig._

Quelle::
_Systemspezifikation_

Dokumentationsform::
_Liste, Freitext_
====

[[anwendungsfaelle]]
==== Anwendungsfälle

Die Anwendung {anwendung} setzt die folgenden Anwendungsfälle um.

[Name des Anwendungsfalls]:: [Beschreibung des Anwendungsfalls in einem Satz].

====
Inhalt::
_Sehr knappe Zusammenfassung der Anwendungsfälle: Name und ein beschreibender Satz._

Quelle::
_Systemspezifikation_

Dokumentationsform::
_Liste_
====

[[technische-beschreibung]]
=== Technische Beschreibung

_Kurze, prägnante technische Darstellung der Anwendung. [...]_

[[technischer-kontext]]
.{anwendung}: Technischer Kontext
image::vorlage-systemhandbuch/technischer-kontext.dn.svg[]

NOTE: Weitere technische Details können im <<quellen,Systementwurf>> nachgelesen werden.

====
Inhalt::
* _Sehr kurze zusammenfassende technische Darstellung der Anwendung._
* _Darstellung des technischen Kontextes._
* _Verweis auf aktuelle Version der Systemspezifikation._

Quelle::
_Systementwurf (Extrakt aus Einleitung / Überblick & technischer Kontext)_

Dokumentationsform::
_Freitext, technisches Kontextdiagramm_
====

[[laufzeitumgebung]]
==== Laufzeitumgebung

Die Laufzeitumgebung für das {anwendung} besteht aus den Produkten, die in folgender Tabelle dargestellt sind.

[[laufzeitumgebung-produkte]]
.{anwendung}: Produkte der Laufzeitumgebung
[cols="2,2,1,1", options="header"]
|===
|Kategorie |Name |Version |Bemerkung

|Java Virtual Machine
|https://adoptium.net/de/temurin/releases[OpenJDK (Eclipse Temurin von Adoptium)]
| 17.x
|

|Servlet-Container
|Apache Tomcat
|8.5.x
|

|RDBMS
|(Datenbank)
|(Version)
|

|...
|...
|...
|
|===

====
Inhalt::
_Übersicht über alle Bestandteile der Laufzeitumgebung, die zum Betrieb der Anwendung nötig sind.
Hierbei sind nur die direkten Abhängigkeiten aufzulisten.
Transitive Abhängigkeiten, wie sie u.a. Betriebssysteme in der Regel darstellen, müssen nicht angegeben werden._

Quelle::
_Systementwurf, Produktkatalog IsyFact_

Dokumentationsform::
_Tabelle, Freitext (für weitergehende Bemerkungen)_
====

[[nachbarsysteme]]
==== Nachbarsysteme

Die Anwendung {anwendung} benötigt die folgenden Nachbarsysteme, um alle Anwendungsfälle erfolgreich durchführen zu können.

[[nachbarsysteme-auflistung]]
.{anwendung}: Benötigte Nachbarsysteme
[cols="2m,2,1,1", options="header"]
|===
|Nachbarsystem |Schnittstelle |Version |Essenziell?

|isy-nachbar-b-gk
|(Schnittstelle)
|(Version)
|nein

|isy-nachbar-c-qk
|(Schnittstelle)
|(Version)
|ja

|...
|...
|...
|
|===

====
Inhalt::
_Übersicht über alle Nachbarsystemen, die zum Betrieb der Anwendung nötig sind.
Neben der Tabelle sollte in einem kurzen Text für jedes Nachbarsystem der Grund der Abhängigkeit beschrieben sein._ +
_Essenzielle Abhängigkeiten sind nötig, um die Kernfunktionalität der Anwendung bereitzustellen.
Nicht essenzielle Abhängigkeiten hingegen bieten zusätzliche Funktionalität, falls benötigt._

Quelle::
_Systementwurf_

Dokumentationsform::
_Tabelle, Freitext (für weitergehende Bemerkungen)_
====

[[verteilungssicht]]
==== Verteilungssicht

====
Inhalt::
_Deployment-Diagramm des Systems mit grober Erklärung. +
Folgende Aspekte sind im Diagramm darzustellen:_

* _Verteilung der IT-Systeme der Anwendung auf Server, also das Clustering der IT-Systeme,_
* _Laufzeitumgebungen (Tomcat),_
* _Genutzte andere Systeme und deren Kommunikationsbeziehungen,_
* _Genutzte technische System, z.B. Datenbank,_
* _Firewalls bzw. Netzwerkzonen,_
* _Kommunikationsprotokolle._

_Hinweis: Das Clustering von Nachbarsystemen kann vereinfacht dargestellt werden._

Quelle::
_Systementwurf_

Dokumentationsform::
_Deployment-Diagramme, Tabellen, Freitext_
====


[[bau-anwendung]]
== Bau der Anwendung

Das Bauen der Anwendung erfolgt über einen standardisierten Build-Mechanismus.
Der Build benötigt die in <<table-build-tools>> aufgelisteten Werkzeuge und Technologien.
Weitere Abhängigkeiten werden durch die erforderlichen Build-Werkzeuge selbstständig nachgeladen.

:desc-table-build-tools: Erforderliche Build-Werkzeuge und Technologien
[id="table-build-tools", reftext = "{table-caption} {counter:tables}"]
.{desc-table-build-tools}
[cols="5,5",options="header"]
|===
|Werkzeug
|Version

|Maven
|3.x

|(RPM)
| ...

|Java Development Kit https://adoptium.net/de/temurin/releases[OpenJDK (Eclipse Temurin von Adoptium)]
| 17.x

|(node.js)
| ...

|===

====
Inhalt::
_Falls nötig, Tabelle mit weiteren Werkzeugen und Technologien vervollständigen._
_Die obige Tabelle ist mit Vorgaben aus dem Produktkatalog gefüllt._

Dokumentationsform::
_Tabelle_
====


[[bau-ga-batches-legacy]]
=== Bau der {anwendung-ga} und {anwendung-batch}

NOTE: *Falls die Anwendung den traditionellen RPM Build (via `ant` und `rpmbuild`) nicht verwendet, kann dieser Abschnitt entfallen.*

Zum Erzeugen der RPM-Pakete wird das Werkzeug `rpmbuild` mithilfe von Ant über Maven benutzt.
Dies setzt ein Artefakt-Repository zum Auflösen von Paketabhängigkeiten voraus.

Der Build wird folgendermaßen ausgeführt:

:desc-listing-maven-build-legacy: Maven-Befehl zum Build der {anwendung-ga} & {anwendung-batch}
[id="listing-maven-build-legacy",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-maven-build-legacy}
[source]
----
mvn -Dbuild.number=<Build-Nummer> -Dtest=false -DfailIfNoTests=false clean package
----

TIP: Die Build-Nummer (Argument `-Dbuild.number`) wird üblicherweise mit der Lieferungsnummer belegt.
Das bedeutet z. B.: `1.0.0_14` wird zu `14`, oder allgemein: `1.0.0_x` wird zu `x`.

Nach erfolgreichem Build befinden sich im Ordner `{it-system-ga}-deployment/target/RPMS/noarch` folgende RPM-Pakete:

* `{it-system-ga}-<VERSION>.noarch.rpm`: {anwendung-ga},
* `{it-system-batch}-<VERSION>.noarch.rpm`: {anwendung-batch}.

In den folgenden Kapiteln wird die Installation der einzelnen Pakete näher beschrieben.

====
Inhalt::
_Für weitere Build-Schritte ggf. weitere Unterkapitel anlegen. +
Die Anleitung soll hier vollständig sein und darf nicht auf andere Dokumente der IsyFact verweisen._

Quelle::
_Entwicklerhandbuch_

Dokumentationsform::
_Freitext_
====

[[bau-ga-batches]]
=== Bau der {anwendung-ga} und {anwendung-batch}

NOTE: *Falls die Anwendung den neuen RPM Build (via Maven-Plugin) nicht verwendet, kann dieser Abschnitt entfallen.*

Zum Erzeugen der RPM-Pakete wird ein Maven-Plugin benutzt.
Dies setzt ein Artefakt-Repository zum Auflösen von Paketabhängigkeiten voraus.

Der Build wird folgendermaßen ausgeführt:

:desc-listing-maven-build: Maven-Befehl zum Build der {anwendung-ga} & {anwendung-batch}
[id="listing-maven-build",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-maven-build}
[source]
----
mvn -Drpm.release=<Build-Nummer> -Dtest=false -DfailIfNoTests=false clean package
----

TIP: Das Feld `release` (Argument `-Drpm.release`) wird üblicherweise mit der Lieferungsnummer belegt.
Das bedeutet z. B.: `1.0.0_14` wird zu `14`, oder allgemein: `1.0.0_x` wird zu `x`.

Nach erfolgreichem Build befinden sich im jeweiligen Modul unter `target` die RPM-Pakete:

* `{it-system-ga}-<VERSION>.noarch.rpm`: {anwendung-ga},
* `{it-system-batch}-<VERSION>.noarch.rpm`: {anwendung-batch}.

In den folgenden Kapiteln wird die Installation der einzelnen Pakete näher beschrieben.

====
Inhalt::
_Für weitere Build-Schritte ggf. weitere Unterkapitel anlegen. +
Die Anleitung soll hier vollständig sein und darf nicht auf andere Dokumente der IsyFact verweisen._

Quelle::
_Entwicklerhandbuch_

Dokumentationsform::
_Freitext_
====

[[bau-sgw]]
=== Bau des {anwendung-sgw}

====
Inhalt::
_Build beschreiben, sofern er sich maßgeblich vom Build der GA und der Batches unterscheidet. +
Die Anleitung soll auch hier vollständig sein und darf nicht auf andere Dokumente der IsyFact verweisen._

Quelle::
_Entwicklerhandbuch_

Dokumentationsform::
_Freitext_
====


[[vorbereitung-systemumgebung]]
== Vorbereitung der Systemumgebung

Dieses Kapitel beschreibt, welche Vorbereitungen für den Betrieb der Anwendung {anwendung} in der Systemumgebung nötig sind.

====
Inhalt::
_Beschreibung grundsätzlicher Konfigurationen der Systemumgebung.
Dazu gehören Systembenutzer, sofern sie für mehrere Systeme benötigt werden._
+
_Ebenso werden in eigenen Kapiteln die Einrichtung bzw. Konfiguration von technischen Systemen bzw. von benötigten Nachbarsystemen beschrieben._
+
_Sofern Lizenz-Dateien o.Ä. benötigt werden, sollen diese ebenfalls hier aufgeführt werden. +
Falls einzelne technische Systeme von sehr vielen Verfahren benötigt werden, ist es zweckmäßig, diese in eigene Dokumente auszulagern._

Quelle::
_Entwicklerhandbuch, Systementwurf_

Dokumentationsform::
_Freitext_
====

[[anlegen-betriebssystemnutzer-gruppen]]
=== Anlegen der Betriebssystemnutzer und -gruppen

Die Anwendungen {anwendung-ga} und {anwendung-sgw} benötigen den Betriebssystemnutzer `tomcat` in der Benutzergruppe `tomcat`.
Die Batch-Anwendung {anwendung-batch} benötigt den Betriebssystemnutzer `batch` in der Benutzergruppe `batch`.

Die Erzeugung der Nutzer und Gruppen ist abhängig vom verwendeten Betriebssystem.
Das Kennwort wird vom Betrieb vergeben.
Der Tomcat-Nutzer und der Batch-Nutzer dürfen nicht das Recht besitzen, sich am System anzumelden.

[[einrichten-datenbank]]
=== Einrichten der Datenbank

Im Folgenden wird beschrieben, wie die Datenbank für die Anwendung {anwendung} vorbereitet wird.

Die DB-Skripte liegen im Verzeichnis

:desc-listing-pfad-datenbankskripte: Pfad für die Datenbankskripte
[id="listing-pfad-datenbankskripte",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-pfad-datenbankskripte}
[source,subs="attributes"]
----
{it-system-ga}/src/main/skripte/sql/
----

Zum Anlegen des Datenbankschemas steht das Skript `install-db-schema.sh` zur Verfügung.
Vorher müssen jedoch die Inhalte des Skripts, das die Umgebungsvariablen lädt (`01_environment.sql`), auf die jeweilige Umgebung angepasst werden.

Zur Aktualisierung des Datenbankschemas steht das Skript `update-db-schema.sh` bereit.
Auch hier gibt es ein Skript für die Umgebungsvariablen (`01_environment.sql`), das angepasst werden muss.

====
Ausfüllhinweise::
_Benutzt die Anwendung die Versionierung von Datenbankschemas *nicht*, muss statt der Kurzzusammenfassung der genaue Ablauf zum Anlegen bzw. Aktualisieren des Datenbankschemas beschrieben werden._
====

[[konfiguration-benutzer-behoerdenverzeichnis]]
=== Konfiguration Benutzer- und Behördenverzeichnis

Zur Nutzung des Verfahrens werden diverse Nutzer benötigt.
Im Folgenden wird beschrieben wie die Nutzer mit den benötigten Rollen im BBV angelegt werden.
Die Anpassungen erfolgen über die Kommandozeile.
Die benötigten Dateien befinden sich im Verzeichnis `{it-system-ga}/src/main/skripte/bbv/`.

Es wird angenommen, dass diese Dateien in ein Verzeichnis kopiert wurden, das nachfolgend mit `BBV_FILES` bezeichnet wird.

:desc-listing-benutzerverzeichnis-rollen: Benutzerverzeichnisrollen anlegen
[id="listing-benutzerverzeichnis-rollen",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-benutzerverzeichnis-rollen}
[source,subs="attributes"]
----
cd /opt/isy-benutzerverzeichnis-batch/bin

./batch-benutzerverzeichnis-import.sh –ExcelDatei BBV_FILES/xxx-rollen.xls -ignoriereRestart

./batch-benutzerverzeichnis-import.sh –ExcelDatei BBV_FILES/xxx-benutzer.xls -ignoriereRestart
----

Sollten die Passwörter für die Benutzer geändert werden, sind folgende Punkte zu beachten:

* Bei Änderung der Passwörter für externe Behörden müssen diese entsprechend in den Anfragen an {anwendung-sgw} von den Behörden angepasst werden.
* Das Passwort des Nutzers `XXX_Batch_Launcher` muss mit dem Konfigurationsparameter `batch.benutzer.passwort` in der Datei `/etc/{it-system-ga}/{it-system-ga}.properties` übereinstimmen.

====
Ausfüllhinweise::
_Spezifische Änderungen an den Dateien (z.B. Entfernen von Testbenutzern oder Anpassungen an das konkrete Deployment) müssen beschrieben werden._
====

[[schluesselverzeichnis]]
=== Schlüsselverzeichnis

Die Schlüssel und Mappings der Anwendung {anwendung} müssen in das Schlüsselverzeichnis importiert werden.
Die entsprechende Datei ist mit den Schlüsseln und Mappings im Releaseletter der {anwendung-ga} angegeben.


[[mail-server-konfiguration]]
=== Mail-Server Konfiguration

====
Inhalt::
_Beschreibung der Einrichtung des Mail-Servers, z.B. benötigte Postfächer etc._

Quelle::
_Entwicklerhandbuch, Systementwurf_

Dokumentationsform::
_Freitext_
====


[[installation-anwendung]]
== Installation der Anwendung

Als Ablageort und Stammverzeichnis der relativen Pfade in diesem Kapitel dient das Quellcode-Repository der Anwendung {anwendung}.

[[installation-default-tomcat]]
=== Installation der Default-Tomcats

Es müssen Tomcat-Basisinstallationen für die Anwendung vorliegen.

:desc-table-tomcat-installationspfade: Installationspfade der Tomcats
[id="table-tomcat-installationspfade",reftext="{table-caption} {counter:tables}"]
.{desc-table-tomcat-installationspfade}
[cols="1m,2m",options="header"]
|===
|IT-System | Tomcat-Installationspfad
|{anwendung-ga} | /opt/{it-system-ga}/tomcat
|{anwendung-sgw} | /opt/{it-system-sgw}/tomcat
|===

Die Tomcat-Basisinstallation kann nur von einem Benutzer mit Root-Rechten vorgenommen werden.

Für die Erstinstallation muss der zum {anwendung} gehörende Default-Tomcat installiert werden:

:desc-listing-tomcat-install: Installation der Tomcats via RPM
[id="listing-tomcat-install",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-tomcat-install}
[source,subs="attributes"]
----
rpm -i {it-system-ga}-tomcat-(version).x86_64.rpm
rpm -i {it-system-sgw}-tomcat-(version).x86_64.rpm
----

Nach der Installation muss ggf. die Konfiguration des Wrappers angepasst werden.
Dazu ist die Datei `/opt/{it-system-ga}/tomcat/conf/wrapper.conf` anzupassen.

Wichtige Einstellungen umfassen:

* das Setzen der Umgebungsvariable `JAVA<X>_HOME` auf den korrekten Wert (vor allem, wenn mehrere Java-Versionen installiert sind),
* das Setzen von sinnvollen Werten für die Heap-Size (siehe Parameter `wrapper.java.initmemory` und `wrapper.java.maxmemory`).

[[installation-it-systeme]]
=== Installation der IT-Systeme

NOTE: *Falls die Anwendung den traditionellen RPM Build (via `ant` und `rpmbuild`) verwendet, liegen die RPMs in einem zentralen Deployment-Modul.*

Die RPM-Pakete können direkt über Kommandozeile installiert werden.
Hierzu sind Root-Rechte erforderlich.
Ein laufender Tomcat muss gegebenenfalls zuvor gestoppt werden.

:desc-listing-rpm-install: Manuelle Installation der IT-Systeme
[id="listing-rpm-install",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-rpm-install}
[source,subs="attributes"]
----
rpm -fUhv {it-system-ga}/target/RPMS/noarch/{it-system-ga}-(version).noarch.rpm
rpm -fUhv {it-system-sgw}/target/RPMS/noarch/{it-system-sgw}-(version).noarch.rpm
rpm -fUhv {it-system-batch}/target/RPMS/noarch/{it-system-batch}-(version).noarch.rpm
----

TIP: Die Option `-U` kann auch für die erstmalige Installation, nicht nur für Upgrades, verwendet werden.

:desc-table-rpm-installationspfade: Installationspfade der IT-Systeme
[id="table-rpm-installationspfade",reftext="{table-caption} {counter:tables}"]
.{desc-table-rpm-installationspfade}
[cols="3m,4m,1m",options="header"]
|===
|IT-System | RPM-Installationspfad | Owner
|{anwendung-ga} |/opt/{it-system-ga} | tomcat
|{anwendung-sgw} |/opt/{it-system-sgw} | tomcat
|{anwendung-batch} |/opt/{it-system-batch} | batch
|===


[[konfiguration-anwendung]]
== Konfiguration der Anwendung

Als Ablageort und Stammverzeichnis der relativen Pfade in diesem Kapitel dient das Quellcode-Repository der Anwendung {anwendung}.

[[konfiguration-ga]]
=== Konfiguration der {anwendung-ga}

Nach der Installation liegen die Konfigurationsdateien der {it-system-ga} unter `/etc/{it-system-ga}`.

Folgende Konfigurationsdateien müssen für die Konfiguration angepasst werden:

* `logback.xml`,
* `{it-system-ga}.properties`,
* `jpa.properties`,
* (Liste der Konfigurationsdateien der Tomcat-Anwendung).

Änderungen an den Konfigurationsdateien müssen bei heruntergefahrener Anwendung durchgeführt werden.

IMPORTANT: Dieses Verhalten gilt nicht für die Konfigurationsdatei `logback.xml`.
Änderungen an dieser Konfigurationsdatei können bei laufender Anwendung ausgeführt werden.

[[konfigurationsdatei-logback]]
==== Konfigurationsdatei `logback.xml`

Die Konfigurationsdatei `logback.xml` enthält die Logging-Einstellungen und ist nach den Logging-Vorgaben aufgebaut.
Nach der Installation muss dort der Name der künftigen Log-Datei angegeben werden.
Dazu ist in den folgenden Zeilen der `HOSTNAME` durch den tatsächlichen Hostnamen zu ersetzen.

:desc-listing-logging-konfiguration-dateiname: {anwendung-ga}: Log-Dateiname
[id="listing-logging-konfiguration-dateiname",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-logging-konfiguration-dateiname}
[source,xml,subs="verbatim,attributes"]
----
<property name="LOGFILE_PATH" value="/var/log/{it-system-ga}/HOSTNAME_{it-system-ga}" />
----

Die Logs werden nach `/var/log/{it-system-ga}` geschrieben.

[[konfigurationsdatei-ga]]
==== Konfigurationsdatei `{it-system-ga}.properties`

Die Datei `{it-system-ga}.properties` enthält alle weiteren Konfigurationseinstellungen der {anwendung-ga}.

Eine ausführliche Erläuterung der einzelnen Parameter ist ebenfalls in der Datei selbst enthalten.

Folgende Werte müssen nach der Erstinstallation angepasst werden:

:desc-table-parameter-ga-properties: Konfigurationsparameter {anwendung-ga}
[id="table-parameter-ga-properties", reftext = "{table-caption} {counter:tables}"]
.{desc-table-parameter-ga-properties}
[cols="2m,3a",options="header"]
|===
|Konfigurationsparameter |Beschreibung
|\{nachbarsystem}.\{endpunkt}.url
|URL des Endpunkts (Service / UI) des Nachbarsystems.

|batch.benutzer.kennung
|System-Benutzer zum Ausführen der Batches.

|batch.benutzer.passwort
|Passwort des System-Benutzers zum Ausführen der Batches.

|...
|...
|===

====
Inhalt::
_Weitere Möglichkeiten der Konfiguration werden ab hier beschrieben, thematisch abgegrenzt und jeweils mit einer eigenen Tabelle dokumentiert._

Quelle::
_Systementwurf._

Dokumentationsform::
_Freitext & Tabellen_
====

Die Anbindung an den IAM-Service wird wie folgt konfiguriert:

:desc-table-config-ga-keycloak: Konfiguration des IAM-Service
[id="table-config-ga-keycloak", reftext = "{table-caption} {counter:tables}"]
.{desc-table-config-ga-keycloak}
[cols="2m,3a",options="header"]
|===
|Konfigurationsparameter |Beschreibung

|sic.keycloak.auth-server-url.0
|Basis-URL des IAM-Service. +
Schema: `http(s)://<keycloak-host>:<keycloak-port>/auth/`

|sic.keycloak.realm.0
|Realm der Client zur Anmeldung. +
Schema: `<realm-name>`

|sic.keycloak.resource.0
|Name des Clients, der die Authentifizierung des Benutzers durchführen wird. +
Schema: `<client-name>`

|sic.keycloak.bearer-only.0
|Auf `false` gesetzt, da ein "Bearer"-Client keine Authentifizierung für andere vornehmen darf. +
Default: `false`

|sic.keycloak.credentials-secret.0
|Per Vorgabe sind Clients vertrauenswürdig ("confidential"), weswegen ein "client secret" angegeben werden muss. +
Schema: `<client-secret>`
|===

[[konfigurationsdatei-jpa]]
==== Konfigurationsdatei jpa.properties

Die Datei `jpa.properties` enthält die Konfiguration der Datenbank-Verbindung.

Folgende Werte müssen nach der Erstinstallation angepasst werden:

:desc-table-parameter-jpa-properties: Konfigurationsparameter jpa.properties
[id="table-parameter-jpa-properties", reftext = "{table-caption} {counter:tables}"]
.{desc-table-parameter-jpa-properties}
[cols="2m,3a",options="header"]

|===
|Konfigurationsparameter |Beschreibung
|database.url
|URL der Datenbankverbindung

|database.username
|Name des technischen Benutzers für den Zugriff auf die Datenbank.

|database.password
|Name des Passworts des technischen Benutzers für die Datenbank.
Das Passwort ist nicht verschlüsselt.

|database.schema.default
|Name des Datenbank-Schemas.
|===

[[konfigurationsdatei-isalive]]
==== Konfigurationsdatei isAlive

Für Wartungszwecke kann es notwendig sein, dass die Anwendung keine weiteren Anfragen vom Loadbalancer mehr zugewiesen bekommt.

Dazu überprüft das Loadbalancer-Servlet regelmäßig, ob die folgende (leere) Datei existiert.

[source,subs="attributes"]
----
/opt/{it-system-ga}/etc/isAlive
----

Nach der Erstinstallation ist diese Datei noch nicht vorhanden. Sie muss so angelegt werden, dass der Nutzer `tomcat` die Datei lesen kann, z. B. wie folgt:

[source,subs="attributes"]
----
touch /opt/{it-system-ga}/etc/isAlive
----

Im Regelbetrieb ist das Loadbalancer-Servlet unter folgender URL erreichbar:

 http(s)://<host>:<port>/Loadbalancer

[[konfiguration-batch]]
=== Konfiguration der {anwendung-batch}

Nach der Installation liegen die Konfigurationsdateien der Batch-Anwendung unter `/etc/{it-system-batch}`.

Die Konfiguration der {anwendung-batch} erfolgt analog zur <<konfiguration-ga>>:
Allein die Logging-Konfiguration unterscheidet sich minimal.
Es ist daher möglich, die bereits angepassten Konfigurationsdateien der {anwendung-ga} in die Konfigurationsverzeichnisse der {anwendung-batch} zu kopieren.
Anschließend müssen dort nur noch die abweichenden Einstellungen angepasst werden.

[[konfigurationsdatei-logging-batch]]
==== Konfigurationsdatei `logback-batch.xml`

Diese Konfigurationsdatei ist analog zur Datei `logback.xml` aufgebaut.
Sie wird für das Logging der Batches verwendet.
Die Unterschiede zur `logback.xml` der {anwendung-ga} liegen darin:

* dass ein eigener Pfad für das Logging verwendet wird und,
* dass die Batch-Id an den Namen der Log-Datei angehängt wird.

Außerdem ist für die Batches keine Log-Rotation aktiviert.

[[konfigurationsdatei-ga-batch]]
==== Konfigurationsdatei `{it-system-ga}.properties`

====
Inhalt::
_Beschreibung der Unterschiede bei der Konfiguration der Batch-Anwendung_

Quelle::
_Systementwurf_

Dokumentationsform::
_Freitext_
====

[[konfiguration-sgw]]
=== Konfiguration des {anwendung-sgw}

Nach der Installation liegen die Konfigurationsdateien des {anwendung-sgw} unter `/etc/{it-system-sgw}`.

Folgende Konfigurationsdateien müssen für die Konfiguration angepasst werden:

* `logback.xml`,
* `servicegateway.properties`.

Änderungen an den Konfigurationsdateien müssen bei heruntergefahrener Anwendung durchgeführt werden.

IMPORTANT: Dieses Verhalten gilt nicht für die Konfigurationsdatei `logback.xml`.
Änderungen an dieser Konfigurationsdatei können bei laufender Anwendung ausgeführt werden.

[[konfigurationsdatei-logback-sgw]]
==== Konfigurationsdatei `logback.xml`

Die Konfigurationsdatei `logback.xml` enthält die Logging-Einstellungen und ist nach den Logging-Vorgaben aufgebaut.
Nach der Installation muss dort der Name der künftigen Log-Datei angegeben werden.
Dazu ist in den folgenden Zeilen der `HOSTNAME` durch den tatsächlichen Hostnamen zu ersetzen.

:desc-listing-logging-konfiguration-dateiname-sgw: {anwendung-sgw}: Log-Dateiname
[id="listing-logging-konfiguration-dateiname-sgw",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-logging-konfiguration-dateiname-sgw}
[source,xml]
----
<property name="LOGFILE_PATH" value="/var/log/{it-system-sgw}/HOSTNAME_{it-system-sgw}" />
----

Die Logs werden nach `/var/log/{it-system-sgw}` geschrieben.

[[konfigurationsdatei-sgw]]
==== Konfigurationsdatei servicegateway.properties

Die Datei `servicegateway.properties` enthält alle weiteren Konfigurationseinstellungen von {anwendung-sgw}.

Eine ausführliche Erläuterung der einzelnen Parameter ist ebenfalls in der Datei selbst enthalten.

Folgende Werte müssen nach der Erstinstallation angepasst werden:

:desc-table-parameter-servicegateway-properties: Konfigurationsparameter servicegateway.properties
[id="table-parameter-servicegateway-properties", reftext = "{table-caption} {counter:tables}"]
.{desc-table-parameter-servicegateway-properties}
[cols="2m,3a",options="header"]
|===
|Konfigurationsparameter |Beschreibung
|ga.service.url
|Die Adresse der {anwendung-ga}.

Beispiel: +
`http(s)://isy.local.vm:50001/{it-system-ga}`

|...
|...
|===

[[konfigurationsdatei-isalive-sgw]]
==== Konfigurationsdatei isAlive

Für Wartungszwecke kann es notwendig sein, dass die Anwendung keine weiteren Anfragen vom Loadbalancer mehr zugewiesen bekommt.
Dazu überprüft das Loadbalancer-Servlet regelmäßig, ob die folgende (leere) Datei existiert.

[source,subs="attributes"]
----
/opt/{it-system-sgw}/etc/isAlive
----

Nach der Erstinstallation ist diese Datei noch nicht vorhanden. Sie muss so angelegt werden, dass der Nutzer `tomcat` die Datei lesen kann, z. B. wie folgt:

[source,subs="attributes"]
----
touch /opt/{it-system-sgw}/etc/isAlive
----

Im Regelbetrieb ist das Loadbalancer-Servlet unter folgender URL erreichbar:

 http(s)://<host>:<port>/Loadbalancer

[[regulaerer-wirkbetrieb]]
== Regulärer Wirkbetrieb

[[log-konfigurationsdateien]]
=== Log- und Konfigurationsdateien

.Log-Dateien
[id="table-log-dateien", reftext = "{table-caption} {counter:tables}"]
[cols="2m,1", options="header"]
|===
|Log-Datei |Inhalt / Bemerkung
2+^d|*{anwendung-ga}* (`/var/log/{it-system-ga}`)
|HOSTNAME_{it-system-ga}.log |Log-Datei
|HOSTNAME_{it-system-ga}_ZEITSTEMPEL.log |Rotierte Log-Datei
2+^d|*{anwendung-sgw}* (`/var/log/{it-system-sgw}`)
|HOSTNAME_{it-system-sgw}.log |Log-Datei
|HOSTNAME_{it-system-sgw}_ZEITSTEMPEL.log |Rotierte Log-Datei
|===

Der Platzhalter `HOSTNAME` im Dateinamen steht für den Namen des Servers, auf dem das IT-System ausgeführt wird.
Die `ZEITSTEMPEL` werden durch die Log-Rotation erzeugt und markieren ältere Log-Dateien.

.Konfigurationsdateien
[id="table-konfigurationsdateien", reftext = "{table-caption} {counter:tables}"]
[cols="1m,1", options="header"]
|===
|Konfigurationsdatei |Inhalt / Bemerkung
2+^d|*{anwendung-ga}* (`/etc/{it-system-ga}`)
|isAlive |Steuerdatei für Loadbalancer
|{it-system-ga}.properties |Konfiguration der Anwendung
|jpa.properties |Konfiguration der Datenbank-Verbindung
|logback.xml |Logging-Konfiguration
2+^d|*{anwendung-sgw}* (`/etc/{it-system-sgw}`)
|isAlive |Steuerdatei für Loadbalancer
|{it-system-sgw}.properties |Konfiguration der Anwendung
|jpa.properties |Konfiguration der Datenbank-Verbindung
|logback.xml |Logging-Konfiguration
|===

[[datenbankschema]]
=== Datenbankschema

NOTE: *Falls die Anwendung kein Datenbankschema enthält, kann dieser Abschnitt entfallen.*
Andernfalls ist der Verweis auf den Systementwurf der Anwendung zu korrigieren.

Das Datenbankschema ist vollständig im xref:vorlage-systementwurf/master.adoc[Systementwurf] dokumentiert.

NOTE: *Falls die Anwendung ein Datenbankschema enthält, kann dieser Abschnitt entfallen.*

Die Anwendung {anwendung} enthält kein Datenbankschema.

[[start-stopp-statuspruefung-server-prozesse]]
=== Start, Stopp, Statusprüfung der Server-Prozesse

Das Starten, Stoppen und die Statusüberprüfung der Tomcat-Installationen wird über ein Skript in `/etc/init.d` durchgeführt.

[id="table-start-stop-script", reftext = "{table-caption} {counter:tables}"]
.Funktionen des Start-/Stopp-Skripts
[cols="1m,1", options="header"]
|===
|Befehl |Beschreibung

|/etc/init.d/{it-system-ga}-tomcat start
|Start der {anwendung-ga}

|/etc/init.d/{it-system-ga}-tomcat stop
|Stopp der {anwendung-ga}

|/etc/init.d/{it-system-ga}-tomcat status
|Statusüberprüfung der {anwendung-ga}

|/etc/init.d/{it-system-sgw}-tomcat start
|Start des {anwendung-sgw}

|/etc/init.d/{it-system-sgw}-tomcat stop
|Stopp des {anwendung-sgw}

|/etc/init.d/{it-system-sgw}-tomcat status
|Statusüberprüfung des {anwendung-sgw}
|===

Die Aufrufe werden in der Produktionsumgebung über die Batch-Steuerung in die betrieblichen Abläufe integriert.
Das Skript wird dabei nicht in die Runlevel des Betriebssystems integriert.
Die Tomcats werden ausschließlich über die betriebliche Batch-Steuerung gestartet und gestoppt.

In allen anderen Umgebungen wird das Skript von Hand aufgerufen.
Ein Eintrag in die Runlevel kann bei Bedarf erfolgen.

Eine weitere Möglichkeit zur Überprüfung der Tomcat-Prozesse bietet folgender Befehl:

 ps -u tomcat -f

[[batch-prozesse]]
=== Batch-Prozesse

In diesem Abschnitt wird das Ausführen der Batch-Anwendung beschrieben.
Die Batches sind unabhängig voneinander, d.h. sie können in beliebiger Reihenfolge ausgeführt werden.

Die Batch-Anwendungen werden auf der Kommandozeile über ein Startskript gestartet.
Das Startskript `batch-ausfuehren.sh` liegt in dem Verzeichnis:

[source,subs="attributes"]
----
/opt/{it-system-batch}/bin/
----

IMPORTANT: Eine wichtige Voraussetzung für die Ausführung von Batches ist das Setzen der Variable `JAVA<X>_HOME`.
Dieser Schritt ist in <<installation-default-tomcat>> beschrieben.

====
*_Ausfüllhinweise_*

Inhalt::
_Beschreibung aller Batches zu den einzelnen IT-Systemen. +
Wichtig ist, Abhängigkeiten zwischen den Batches zu beschreiben.
Komplexere Abläufe sollen in Form von Batch-Ketten beschrieben werden._ +
+
_In der Regel wird pro Batch ein Unterkapitel angelegt._

Quelle::
_Systementwurf_

Dokumentationsform::
_Tabelle, Freitext, Diagramme_
====

[[batch-beispiel]]
==== Batch: Beispiel
====
*_Ausfüllhinweise_*

Inhalt::
_Kurze Beschreibung was der Batch macht. Genaue Dokumentation der Start-Parameter, Ausgaben bzw. und Return-Codes des Batches. +
Hinweise für den Betrieb, was ist bei einem Restart zu beachten?_

Quelle::
_Systementwurf_

Dokumentationsform::
_Tabelle, Freitext_
====

_Bezug zur Spezifikation: Batch BAT__...

Dieser Batch prüft …

===== Aufruf

 batch-ausfuehren.sh STARTART KONFIGURATION [ERGEBNIS]

===== Parameter

STARTART:: `-start` oder `–restart`

Gibt an, ob das Skript neu gestartet wird oder ein abgebrochener Batch-Lauf fortgesetzt werden soll.

KONFIGURATION:: `-cfg /resources/batch/beispiel.properties`

Gibt den auszuführenden Batch an.

ERGEBNIS:: `-Batchrahmen.Ergebnisdatei <ergebnisdatei.xml>`

Gibt die XML-Datei an, in der die Ergebnisse gespeichert werden. Diese Angabe ist optional.

===== Rückgabewerte

:desc-listing-rueckgabe-batch: Rückgabewerte des Beispiel-Batches
[id="listing-rueckgabe-batch",reftext="{listing-caption} {counter:listings}"]
.{desc-listing-rueckgabe-batch}
[source,xml,subs="verbatim,attributes"]
----
    0: Verarbeitung ohne Fehler durchgeführt
    1: Verarbeitung mit Fehlern durchgeführt
    2: Verarbeitung mit Fehlern abgebrochen
    3: Batch konnte wegen Fehlern in den Aufrufparametern
       nicht gestartet werden
    4: Batch konnte wegen Fehlern in der Batch-Konfiguration
       nicht gestartet werden
  143: Batch wurde vom Benutzer abgebrochen.
----

===== Ergebnis

Die Ergebnisdatei mit dem Verarbeitungsergebnis liegt im Ordner:

[source,subs="verbatim,attributes"]
----
/opt/{it-system-batch}/out/batch-beispiel_out.xml
----

Datei(en) mit Log-Informationen liegen im Ordner:

[source,subs="verbatim,attributes"]
----
/var/log/{it-system-batch}
----

oder an dem in der <<konfigurationsdatei-logging-batch>> definierten Ort.


[[monitoring]]
=== Monitoring

====
*_Ausfüllhinweise_*

Inhalt:::
_In diesem Kapitel wird beschrieben, welche Monitoring-Schnittstellen das System für den Betrieb anbietet.
Im Wesentlichen sind dies die von der IsyFact über Micrometer bereitgestellten Metriken.
Nicht beschrieben werden soll die konkrete Einbindung des Systems in die betriebliche Überwachung._

Quelle:::
_Systementwurf_

Dokumentationsform:::
_Tabelle, Freitext_
====

[[monitoring-tomcat-anwendungen]]
==== Standard-Metriken

Die Anwendung {anwendung} stellt folgende Standard-Metriken über den Endpunkt `/actuator/metrics` zur Verfügung.

:desc-table-standard-metriken: Standard-Metriken
[id="table-standard-metriken", reftext = "{table-caption} {counter:tables}"]
.{desc-table-standard-metriken}
[cols="1s,2,2m", options="header"]
|===
|Metriken
|Beschreibung
|Namespace

|JVM
|Metriken zum Speicherverbrauch, zur Garbage Collection, Threads und geladenen Klassen.
|jvm.

|System
|Metriken zur CPU-Auslastung, dem Dateisystem und der Uptime der Anwendung.
|system. +
process. +
disk.

|Application Startup
|Metriken zur Startzeit der Anwendung.
|application.

|Logger
|Metriken zu Logging-Events.
|logback.events.

|Task Scheduling
|Metriken zu ausgeführten Tasks.
|...

|REST Services
|Metriken zu aufgerufenen REST-Services.
|http.server.requests

|HTTP Client
|Metriken zum Aufruf Services via HTTP.
|http.client.requests

|Cache
|Metriken zu applikationsspezifischen Caches.
|cache

|Hibernate
|Metriken zu Datenbankzugriffen.
|hibernate

|Spring Data
|Metriken zu Zugriffen über Repositories.
|spring.data.repository.invocations
|===

====
Ausfüllhinweise::
_Metriken, die nicht angeboten werden, müssen aus der Tabelle entfernt werden._
_Ebenso müssen Lücken gefüllt werden, da sie anwendungsspezifisch sind._
====

[[monitoring-batches]]
==== Monitoring Batches

Die Batch-Anwendungen werden durch die Skripte zunächst ohne JMX gestartet.
Wenn diese mit JMX verwaltet und beobachtet werden, so muss *vor* dem Aufruf des Startskriptes auf der Kommandozeile folgendes aufgerufen werden:

 export JAVA_OPTS= "-Dcom.sun.management.jmxremote.port=28000"

Obiges Beispiel startet einen JMX-Agenten für den Port 28000.
Der Port kann vom Betrieb frei gewählt werden.

Nach dem Aufruf des Skriptes sollte die Variable `JAVA_OPTS` auf leer gesetzt werden.
Damit wird verhindert, dass andere Java-Programme die ggf. die gleiche Variable verwenden, automatisch ebenfalls über JMX gesteuert werden können.

 export JAVA_OPTS=

Nach Aktivierung von JMX stellt jeder Batch-Prozess folgende Informationen per JMX bereit:

:desc-table-ueberwachungsinformation-batches: Überwachungsinformation der Batches
[id="table-ueberwachungsinformation-batches", reftext = "{table-caption} {counter:tables}"]
.{desc-table-ueberwachungsinformation-batches}
[cols="2m,6", options="header"]
|===
|Bezeichnung |Beschreibung
2+d|{set:cellbgcolor:#F6F4F4}de.bund.bva.visa.common:type=Batchrahmen,name="Batchrahmen-Verarbeitung"
|{set:cellbgcolor}SaetzeGesamt |Die Gesamtanzahl der zu bearbeitenden Sätze. Falls diese nicht bekannt ist: -1
|SaetzeVerarbeitet |Die Anzahl bereits verarbeiteter Sätze.
|SchluesselLetzterSatz |Schlüssel des letzten verarbeiteten Satzes.
|ZeitSeitLetztemSatz |Zeitraum in Millisekunden, der bereits für den aktuellen Satz benötigt wurde.
|BatchId |Die ID des aktuellen Batches.
|===

[[backup-recovery]]
=== Backup und Recovery

====
*_Ausfüllhinweise_*

Inhalt:::
_Auflistung von Dateien, Datenbank-Schemata, die zum Verfahren gehören und die mit in das Backup einbezogen werden müssen.
Dateien, die durch eine Neuinstallation des Verfahrens wiederhergestellt werden können, sind hier nicht aufzuführen._
+
_Die Informationen in diesem Kapitel dienen als Grundlage für die Erstellung des Datensicherungskonzeptes, in dem dann
Details zu Sicherungsintervallen, Abhängigkeiten zu anderen Systemen usw. beschrieben werden._

Quelle:::
_Systementwurf_

Dokumentationsform:::
_Tabelle, Freitext_
====

[[hinweise-stoerungsdiagnose-behandlung]]
== Hinweise für Störungsdiagnose und -behandlung

[[verfuegbare-hilfsmittel]]
=== Verfügbare Hilfsmittel

[[smoke-test]]
==== Smoke-Test

Folgender Test kann ausgeführt werden, um zu prüfen, ob die Anwendung läuft:

In der Log-Datei (siehe Kapitel <<log-konfigurationsdateien>>) kann der Start des Systems nachvollzogen werden.
Außerdem werden Fehlermeldungen des Selbsttests der Anwendung dort ausgegeben.

:desc-table-smoketest: Fehlercodes Smoke-Tests
[id="table-smoketest", reftext = "{table-caption} {counter:tables}"]
.{desc-table-smoketest}
[cols="4a,^1", options="header"]
|===
|Smoke-Test Checkliste |Erledigt
|*Prüfen der Log-Datei:* +
Die Log-Datei der Anwendung darf nach dem Starten des Tomcats keine Fehler enthalten.
Außerdem sollte die Wrapper-Log-Datei als letzte Zeile folgenden Hinweis enthalten: +
`INFO: Server startup in <ZAHL> ms`
|

|*Verfügbarkeit der Services prüfen:* +
Mit einem REST-Client den Endpunkt `/actuator/health` aufrufen. +
Die Health muss `UP` betragen.
|

|*Test der Batches:* +
Alle Batches ausführen.
Die Log-Datei der Batch-Anwendung darf keine Fehler enthalten.
|
|===

[[debug-logging]]
==== Debug-Logging

Die Konfiguration wird mit Log-Level `INFO` ausgeliefert, d.h. das Loggen von Debug-Ausgaben ist ausgeschaltet.
Es kann aber wie folgt eingeschaltet werden:

Die Konfigurationsdatei `logback.xml` (bzw. `logback-batch.xml`) enthält folgende Zeile:

 <root level="INFO">

Wird der Eintrag `INFO` auf `DEBUG` umgestellt, so werden auch Debug-Meldungen geschrieben.

CAUTION: Das Logging sollte auf der Produktiv-Umgebung nie auf `DEBUG` gestellt werden.
Aufgrund der umfangreichen Datenausgabe könnte es zu Performance-Problemen kommen.
Gleichzeitig ist nicht sichergestellt, dass keine sicherheitsrelevanten Daten ausgegeben werden.

[[fehler-fehlerbehebungsmassnahmen]]
=== Fehler und Fehlerbehebungsmaßnahmen

Die folgenden Abschnitte enthalten Tabellen, die bei der Identifikation und Behandlung von betrieblich relevanten Fehlern helfen.
Die Tabellen geben sowohl Hilfestellung auf Basis von einzelnen Fehlercodes als auch in Form von wahrscheinlichen Fehlerszenarien.

[[fehlercodes]]
==== Fehlercodes

Die folgende Tabelle beschreibt alle betrieblich relevanten Fehlercodes, mögliche Ursachen und Hinweise zur Identifikation des dahinter liegenden Fehlers und seiner Behebung.

IMPORTANT: Eine Übersicht aller Fehlercodes der IT-Systeme findet sich im <<anhang-fehlercodes>>.

.Fehlercodes {anwendung-ga}
[id="table-fehlercodes", reftext = "{table-caption} {counter:tables}"]
[cols="1s,2,2",options="header"]
|===
|Fehler |Mögliche Ursachen |Identifikation und Behebung
|XXXXX50000
|_Die Datenbank ist nicht erreichbar._
|_Log-Datei analysieren._

|...
|...
|...

|===

====
*_Ausfüllhinweise_*

Inhalt::
_Auflistung der Fehler, die von den IT-Systemen der Anwendung auf den Log-Levels `WARN` und `ERROR` ausgegeben werden.
Diese Fehler müssen nach den Vorgaben des Bausteins Logging betriebliche Relevanz besitzen!_ +
_Fehler auf dem Log-Level `INFO`, z.B. regulär vorkommende Fehler bei der fachlichen Bearbeitung oder in querschnittlicher Funktionalität, werden im Anhang beschrieben._ +
_Es ist eine Tabelle pro IT-System anzulegen._

Quelle::
_Systementwurf, Entwicklung_

Dokumentationsform::
_Tabelle_
====

[[fehlerszenarien]]
==== Fehlerszenarien

Die folgende Tabelle beschreibt alle betrieblich relevanten Fehlersituationen, ihre Entstehungsorte sowie Hinweise darauf, wie die IT-Systeme mit diesem Fehlerszenario umgehen und reagieren.

.Fehlerszenarien {anwendung}
[id="table-fehlerszenarien", reftext = "{table-caption} {counter:tables}"]
[cols="^1,3,3,4", options="header"]
|===
|Nr.
|Fehlersituation
|Ort der Entstehung
|Behandlung und Reaktion des Systems

|1
| _Nachbarsystem nicht erreichbar_
|_{anwendung-ga}, +
{anwendung-batch}_
|_Das System schreibt den Fehler in die Log-Datei und gibt den für den Anwender maskierten Fehler als XXXXX99999 über die Außenschnittstelle an den Aufrufer zurück._ +
_Interne Fehlercodes: ..._

|2
|_Konfigurationsfehler_
|_{anwendung-ga}, +
{anwendung-batch}_
|_Die Anwendung startet nicht. Fehlercode: ..._

|3
|_Konfigurationsfehler_
|_{anwendung-ga}, +
{anwendung-batch}_
|_Die Anwendung startet.
Zur Laufzeit kommt es vermehrt zum Fehlercode ..._

|4
|_Technischer Fehler in der Verarbeitung_
|_{anwendung-ga}, +
{anwendung-batch}_
|_Das System schreibt den Fehler in die Log-Datei und gibt den für den Anwender maskierten Fehler als XXXXX99999 über die Außenschnittstelle an den Aufrufer zurück._ +
_Interne Fehlercodes: ..._
|===

====
*_Ausfüllhinweise_*

Inhalt::
_Auflistung von Fehlerszenarien, die zu betrieblich lösbaren Fehlern führen._ +
_"Behandlung und Reaktion des Systems" meint nicht die Fehlerbehandlung durch den Betrieb, sondern wie die IT-Systeme mit dem Fehlerszenario umgehen und auf welchen Kanälen (z.B. über Schnittstellen oder Logs) sie wie reagieren._

Quelle::
_Systementwurf, Entwicklung_

Dokumentationsform::
_Tabelle_
====

:!sectnums:

[[anhang]]
== Anhang

[[anhang-historie]]
=== Anhang A: Historie

Die folgende Tabelle zeigt eine grobe Historie der Anwendung {anwendung}.

.Historie {anwendung}
[id="table-historie"]
[cols="1s,1,3", options="header"]
|===
|Version
|Datum des Release
|Wichtige Änderungen

|3.0.0
|04.03.2020
|Neue Schnittstelle für mehr Beispiele hinzugefügt. +
Tech-Update auf IsyFact 2.1.

|...
|...
|...
|===

====
Inhalt::
_Auflistung der wichtigsten Versionen der Anwendung und der zugehörigen Änderungen.
In der Tabelle sollten, falls Semantic Versioning eingehalten wird, hauptsächlich Major Releases aufgeführt sein. +
Es reicht aus, die dargestellten Versionen auf die im Wesentlichen unterstützten Versionen zu begrenzen.
Veraltete (d.h. nicht mehr in Weiterentwicklung befindliche) Versionen der Anwendung müssen nicht aufgeführt werden._

Dokumentationsform::
_Tabelle_
====

[[anhang-fachliches-glossar]]
=== Anhang B: Fachliches Glossar

====
Inhalt::
_Auflistung der wichtigsten fachlichen Begriffe, die betrieblich relevant sind.
Dies sind z.B. Begriffe, die für das Verständnis im Zuge der Konfiguration oder Fehlerbehandlung erforderlich oder hilfreich sind._ +
_Ein reiner Verweis auf die Systemspezifikation reicht nicht aus, auch wenn dies ggf. zu redundanten Inhalten führt.
Für ein tiefergehendes Verständnis darf hingegen gern auf die Systemspezifikation verwiesen werden._

Quelle::
_Systemspezifikation_

Dokumentationsform::
_Tabelle, Liste, Freitext_
====

[[anhang-fehlercodes]]
=== Anhang C: Vollständige Liste der Fehlercodes

.Fehlercodes {anwendung-ga}
[id="table-fehlercodes-referenz", reftext = "{table-caption} {counter:tables}"]
[cols="2s,3,3", options="header"]
|===
|Fehler
|Mögliche Ursachen
|Identifikation und Behebung

|XXXXX12345
|Ungültige Parameter für interne Berechnung.
|Entwicklung kontaktieren.

|...
|...
|...
|===

====
Inhalt::
_Auflistung aller Fehler, die ein IT-System ausgeben kann.
Die Tabelle geht über die Tabelle in <<fehlercodes>> hinaus, da sie auch Fehler beinhaltet, die betrieblich nicht relevant sind.
Solche Fehler können auf unvorhergesehene fachliche und technische Konstellationen oder auf Programmierfehler hinweisen._ +
_Es ist eine Tabelle pro IT-System anzulegen._ +
_Der Hauptnutzen dieser Tabelle in Verbindung mit der Tabelle in <<fehlercodes>> ist, dass schnell klar ist, ob der Fehler betrieblich behoben werden kann und, falls nicht, wer zu informieren ist._

Quelle::
_Entwicklung_

Dokumentationsform::
_Tabelle_
====

// end::inhalt[]

// tag::quellen[]

[[quellen]]
== Quellen
Dieses Kapitel gehört nicht zum Inhalt und listet die Dokumente auf, auf die das Systemhandbuch verweist.

=== Systemspezifikation & Systementwurf

ifeval::["{backend}" == "html5"]
Die Dokumentation der IsyFact enthält ebenfalls xref:methodik:vorlagen.adoc#dokumentation-anwendung[Vorlagen zu diesen Dokumenten].
endif::[]

ifeval::["{backend}" == "pdf"]
Die Dokumentation der IsyFact enthält ebenfalls https://isyfact.github.io[Vorlagen zu diesen Dokumenten].
Folgen Sie hierzu den Menüpunkten "Methodik" und dann "Vorlagen".
endif::[]

// end::quellen[]