= Referenzarchitektur Backend

include::documentation-guide::partial$licence.adoc[]

include::glossary::terms-definitions.adoc[tag=backend-definition]

Backends sind technisch gleichartig aufgebaut.
Sie setzen auf eine https://de.wikipedia.org/wiki/Schichtenarchitektur#Drei-Schichten-Architektur[Drei-Schichten-Architektur], ergänzt um eine "Säule" querschnittlicher Funktionalität.

[[systemarchitektur-backend]]
.Systemarchitektur eines Backends
image:software-technisch/backend/architektur-backend.dn.svg[width=80%, align=center]

[[uebergreifende-technische-konzeption]]
== Übergreifende Aspekte

Die Schichten beinhalten einen Großteil der Funktionalität eines Backends.
Trotzdem gibt es Aspekte, die übergreifend geregelt sind, damit die Schichten zusammen ein lauffähiges Backend ergeben.

=== Strukturierung des Backends

Die Schichten des Backends sind maßgeblich in _Fachkomponenten_ strukturiert.
Die Fachkomponenten entsprechen den durch das Backend umgesetzten Anwendungskomponenten.
Neben den Fachkomponenten enthält jede Schicht ein Framework, das maßgeblich zur Umsetzung ihrer Kernaufgabe beiträgt.

Backends setzen für die Verwaltung, xref:software-technisch/backend/konfiguration.adoc[] und Kopplung der Fachkomponenten nach dem Prinzip der _Dependency Injection_ Spring Boot und weitere Bestandteile von Spring ein.
Details hierzu werden über die Vorgaben zur xref:software-technisch/backend/spring.adoc[] festgelegt.

=== Transaktionssteuerung

Die Veränderung des Datenbestands gehört zur Kernaufgabe eines Backends.
Hierzu setzen Backends Transaktionen ein.
Transaktionen müssen die https://de.wikipedia.org/wiki/ACID[ACID-Eigenschaften] erfüllen, um grundlegende Anforderungen an Datenqualität zu erfüllen.

In Backends ist der Anwendungskern für die xref:software-technisch/backend/anwendungskern.adoc#transaktionssteuerung[Transaktionssteuerung] zuständig.
In Ausnahmefällen kann die Transaktionssteuerung auch über die xref:software-technisch/backend/serviceschicht.adoc#transaktionssteuerung[Serviceschicht] erfolgen.

=== Caching

Anwendungsspezifische Caches sind mit der Spring Cache Abstraction und einem geeigneten Caching Provider zu implementieren.

Die https://docs.spring.io/spring-framework/reference/integration/cache.html[Spring Cache Abstraction] bietet eine effiziente und flexible Möglichkeit, Caching in Anwendungen zu implementieren.
Durch ihre Verwendung wird das Hinzufügen von Caching, zum Beispiel über die Nutzung von Annotationen, zu bestehenden Methoden erleichtert.
Der zugrundeliegende Code ist nicht wesentlich zu verändern.

Mit dem so abstrahierten Caching ist die Cache-Implementierung unabhängig vom genutzten Cache-Provider.
Die Wahl des Cache-Providers ist gemäß einer notwendigen Skalierung und betrieblichen Gegebenheiten abzustimmen.
Der xref:einstieg:produktkatalog/technologiestackJavaSpring.adoc#Entwicklung[Produktkatalog] empfiehlt EHCache.
Weitere Informationen zu EHCache sind in der https://www.ehcache.org/documentation/[offiziellen Dokumentation] einzusehen.


[[anwendungskern]]
== Anwendungskern

include::backend/anwendungskern.adoc[tags=anwendungskern-definition]

[[awk-fachkomponenten]]
=== Fachkomponenten

include::backend/anwendungskern.adoc[tags=fachkomponente-definition]

[[awk-framework]]
=== Anwendungskern-Framework

include::backend/anwendungskern.adoc[tags=awk-framework-definition]

[[awk-service-consumer]]
=== Service Consumer

include::backend/anwendungskern.adoc[tags=service-consumer-definition]

[[awk-umsetzung]]
=== Umsetzung

Zur Konzeption und Umsetzung des Anwendungskerns definiert die Referenzarchitektur xref:software-technisch/backend/anwendungskern.adoc[weitere Vorgaben].

[[persistenz]]
== Persistenz

include::backend/persistenzschicht.adoc[tags=persistenzschicht-definition]

[[persistenz-fachkomponenten]]
=== Fachkomponenten

include::backend/persistenzschicht.adoc[tags=fachkomponente-definition]

.icon:university[title=Architekturregel] Persistente Entitäten im Anwendungskern
****
Persistente Entitäten dürfen nicht über den Anwendungskern hinaus herausgegeben werden.
Sie haben im Anwendungskern zu verbleiben.
****

Andernfalls ist nicht sichergestellt, dass andere Komponenten keine Änderungen an den persistenten Entitäten vornehmen.
Für den Transfer über Komponentengrenzen hinweg - oder aus dem Anwendungskern hinaus - müssen alle Komponenten des Anwendungskerns persistente Entitäten auf Geschäftsobjekte abbilden.

[[persistenz-framework]]
=== Persistenz-Framework

include::backend/persistenzschicht.adoc[tags=persistenz-framework-definition]

[[persistenz-umsetzung]]
=== Umsetzung

Zur Konzeption der Persistenzschicht definiert die Referenzarchitektur xref:software-technisch/backend/persistenzschicht.adoc[weitere Vorgaben].
Die Umsetzung geschieht mithilfe des xref:isy-persistence:konzept.adoc[Bausteins JPA/Hibernate].

[[serviceschicht]]
== Serviceschicht

include::backend/serviceschicht.adoc[tags=serviceschicht-definition]

[[serviceschicht-fachkomponenten]]
=== Fachkomponenten

include::backend/serviceschicht.adoc[tags=fachkomponente-definition]

[[serviceschicht-framework]]
=== Service-Framework

include::backend/serviceschicht.adoc[tags=service-framework-definition]

[[serviceschicht-umsetzung]]
=== Umsetzung

Zur Konzeption von Services definiert die Referenzarchitektur xref:software-technisch/services.adoc[weitere Vorgaben].
Die Umsetzung der xref:software-technisch/backend/serviceschicht.adoc[] geschieht mithilfe des xref:isy-service-rest:konzept/master.adoc[Bausteins REST].

[[querschnitt]]
== Querschnitt

Neben der Geschäftslogik müssen Backends ebenso querschnittliche Funktionalität bereitstellen.

[[systemarchitektur-querschnitt]]
.Einbettung des Querschnitts in die Systemarchitektur
image::software-technisch/backend/querschnitt.dn.svg[width=80%,align=center]

Die IsyFact hilft hierbei durch eigens entwickelte xref:bausteine:bausteine.adoc[] sowie durch den Einsatz von Standard-Produkten aus dem xref:einstieg:produktkatalog/technologiestackJavaSpring.adoc[].

Fehlerbehandlung::
Vorgaben und Umsetzung mithilfe des xref:isy-exception-core:konzept/master.adoc[Bausteins Fehlerbehandlung]

Konfiguration::
xref:software-technisch/backend/konfiguration.adoc#konfiguration-arten[Vorgaben] aus der Referenzarchitektur, xref:software-technisch/backend/konfiguration.adoc#umsetzung[Umsetzung] mithilfe von Spring

Logging & Tracing::
Vorgaben und Umsetzung mithilfe des xref:isy-logging:konzept/master.adoc[Bausteins Logging]

Autorisierung::
Vorgaben und Umsetzung mithilfe des xref:isy-security:konzept/master.adoc[Bausteins Security]

Monitoring::
Vorgaben und Umsetzung mithilfe des xref:isy-ueberwachung:konzept/master.adoc[Bausteins Überwachung]
