= Referenzarchitektur IT-System

include::documentation-guide::partial$licence.adoc[]

include::documentation-guide::partial$content-revised-page.adoc[]

include::glossary::terms-definitions.adoc[tag=backend-definition]

Backends sind technisch gleichartig aufgebaut.

Sie setzen auf eine https://de.wikipedia.org/wiki/Schichtenarchitektur#Drei-Schichten-Architektur[Drei-Schichten-Architektur], ergänzt um eine "Säule" querschnittlicher Funktionalität.

[[image-RAITSys]]
.Systemarchitektur eines Backends
image::software-technisch/backend/architektur-backend.dn.svg[]

[[uebergreifende-technische-konzeption]]
== Übergreifende Aspekte

Die Schichten beinhalten einen Großteil der Funktionalität eines Backends.
Trotzdem gibt es Aspekte, die übergreifend geregelt sind, damit die Schichten zusammen ein lauffähiges Backend ergeben.

=== Strukturierung des Backends

Backends können, je nach Umfang der an sie gestellten Anforderungen, sehr komplex werden.
Um diese Komplexität beherrschen zu können, wird ein Backend in _Fachkomponenten_ zerlegt, die jeweils genau festgelegte Teilfunktionalitäten erfüllen.

Backends setzen für die Verwaltung, xref:software-technisch/backend/konfiguration.adoc[] und Kopplung der Fachkomponenten nach dem Prinzip der _Dependency Injection_ Spring Boot und weitere Bestandteile von Spring ein.
Details hierzu werden über die xref:blaupausen:detailkonzept-komponente-anwendungskern/master.adoc#verwendung-des-spring-frameworks[Vorgaben zur Verwendung des Spring-Frameworks] festgelegt.

Technisch lässt sich ein IT-System in Schichten unterteilen, fachlich in Teilanwendungen.
Details hierzu werden im xref:blaupausen:detailkonzept-komponente-anwendungskern/master.adoc[Anwendungskern] beschrieben.

=== Transaktionssteuerung

Veränderungen am Datenbestand gehören zur Kernaufgabe von Informationssystemen.
Diese Veränderungen können jedoch nicht beliebig erfolgen – sie müssen gewisse Eigenschaften haben, damit die Datenbestände nicht an Qualität verlieren: Sie müssen atomar, konsistent, isoliert und dauerhaft (https://de.wikipedia.org/wiki/ACID[ACID]) sein.
Dazu werden die Veränderungen zu einer logischen Einheit zusammengefasst: einer Transaktion.

In Backends ist der xref:blaupausen:detailkonzept-komponente-anwendungskern/master.adoc[Anwendungskern] für die Transaktionssteuerung zuständig.
Ausnahmen hiervon sind in den Beschreibungen der Schichten beschrieben.

=== Caching

Anwendungsspezifische Caches sind mit der Spring Cache Abstraction und einem geeigneten Caching Provider zu implementieren.

Die https://docs.spring.io/spring-framework/reference/integration/cache.html[Spring Cache Abstraction] bietet eine effiziente und flexible Möglichkeit, Caching in Anwendungen zu implementieren.
Durch ihre Verwendung wird, z.B. über die Nutzung von Annotationen, das Hinzufügen von Caching zu bestehenden Methoden erleichtert.
Der zugrundeliegende Code ist nicht wesentlich zu verändern.

Mit dem so abstrahierten Caching ist die Cache-Implementierung unabhängig vom genutzten Cache-Provider.
Die Wahl des Cache-Providers ist gemäß einer notwendigen Skalierung und betrieblichen Gegebenheiten abzustimmen.
Der xref:einstieg:produktkatalog/technologiestackJavaSpring.adoc#Entwicklung[Produktkatalog] empfiehlt EHCache.
Weitere Informationen zu EHCache sind in der https://www.ehcache.org/documentation/[offiziellen Dokumentation] einzusehen.


[[der-anwendungskern]]
== Anwendungskern

include::blaupausen:detailkonzept-komponente-anwendungskern/inhalt.adoc[tags=anwendungskern-definition]

=== Fachkomponenten

include::blaupausen:detailkonzept-komponente-anwendungskern/inhalt.adoc[tags=fachkomponente-definition]

=== Komponenten-Framework

include::blaupausen:detailkonzept-komponente-anwendungskern/inhalt.adoc[tags=awk-framework-definition]

=== Externe Services

include::blaupausen:detailkonzept-komponente-anwendungskern/inhalt.adoc[tags=externer-service-definition]

Weitere Details können dem xref:blaupausen:detailkonzept-komponente-anwendungskern/master.adoc[Detailkonzept Komponente Anwendungskern] entnommen werden.

[[persistenz]]
== Persistenz

In der Persistenzschicht sind die Fachkomponenten ebenfalls gemäß den Komponenten aus der fachlichen Architektur strukturiert.
Die Komponenten des Anwendungskerns besitzen die Datenhoheit auf die Entitäten, die ihnen eindeutig zuzuordnen sind.
Diese Entitäten stammen aus den korrespondierenden Komponenten in der Persistenzschicht.
Nur die korrespondierende Anwendungskern-Komponente darf Änderungen an den entsprechenden persistenten Entitäten vornehmen.

.icon:university[title=Architekturregel] Persistente Entitäten im Anwendungskern
****
Persistente Entitäten dürfen nicht über den Anwendungskern hinaus herausgegeben werden. Sie haben im Anwendungskern zu verbleiben.
****

Andernfalls ist nicht sichergestellt, dass andere Komponenten keine Änderungen an den persistenten Entitäten vornehmen.
Für den Transfer über Komponentengrenzen hinweg - oder aus dem Anwendungskern hinaus - müssen alle Komponenten des Anwendungskerns die ihnen zugeordneten persistenten Entitäten auf Geschäftsobjekte abbilden.
Wenn Entitäten von mehreren Komponenten genutzt werden und keiner einzelnen Komponente zugeordnet werden können, sollten sie in einem eigenen querschnittlichen Package abgelegt werden.

[[service]]
== Service

Backends können Funktionen des Anwendungskerns über die Serviceschicht anderen IT-Systemen zur Verfügung stellen.
Der Aufbau der Serviceschicht sowie ihre Kommunikation mit anderen Schichten ist in <<image-TeileServ,folgender Grafik>> dargestellt.

[[image-TeileServ]]
.Einbettung der Serviceschicht in die Systemarchitektur
image::software-technisch/backend/service.dn.svg[]

Die Serviceschicht besteht aus zwei Teilen: dem Service-Framework und der Servicelogik.

Das *Service-Framework* bezeichnet die konkrete Technologie, mit der die Services des Anwendungskerns zur Verfügung gestellt werden.

Die *Servicelogik* gliedert sich, wie der Anwendungskern, in Fachkomponenten.
Die Fachkomponenten setzen im wesentlichen Service-Schnittstellen um.
Zu ihren Aufgaben gehört:

* Validierung von Transportobjekten,
* Transformation von Transportobjekten in Geschäftsobjekte und umgekehrt,
* Fehlerbehandlung,
* Autorisierung,
* Logging.

Weiterführende technische Details zu Services sind im xref:blaupausen:detailkonzept-komponente-service/master.adoc[Detailkonzept Komponente Service] beschrieben.


[[querschnitt]]
== Querschnitt

Neben dem fachspezifischen Teil enthält ein Backend ebenso auch querschnittliche Funktionalitäten.
Diese querschnittlichen Funktionalitäten sind in jeweils eigenen Bausteinen beschrieben.
Eine Übersicht dazu liefern die Beschreibungen der Bausteine der xref:einstieg:vorstellung/isyfact-standards.adoc#bausteine-der-isyfact-standards[IsyFact-Standards] sowie der xref:einstieg:vorstellung/isyfact-erweiterungen.adoc#bausteine-der-isyfact-erweiterungen[IsyFact-Erweiterungen].
