= IT-Systeme

include::glossary:licence:partial$licence.adoc[]

== Abbildung von Anwendungen auf IT-Systeme

Die software-technische Referenzarchitektur bildet Anwendungen auf IT-Systeme ab.
Für diese Abbildung gelten die folgenden, fundamentalen Eigenschaften:

* Die Abbildung geschieht unabhängig vom Anwendungstyp.
Sie ist für alle Anwendungstypen gleich.
* Die Zerlegung in IT-Systeme geschieht anhand der fachlichen Zerlegung der Anwendung in der xref:methodik:vorlagen.adoc#dokumentation-anwendung[Systemspezifikation].
* Spezialisierungen der IT-Systeme spiegeln die (technische) Rolle des IT-Systems bei der Umsetzung der Anwendung wider.

Das *IT-System* bildet einen Oberbegriff für die technische Umsetzung eines Teils der Anwendung.
Seine wichtigste Eigenschaft ist, dass es eine in sich abgeschlossene, ausführbare Einheit (vgl. _deployment unit_) darstellt.
Spezialisierungen des IT-Systems, auch *IT-Systemtypen* genannt, besitzen eine jeweils eigene Systemarchitektur und einen eigenen Technologie-Stack, um die jeweiligen Teile der Anwendung möglichst effizient umsetzen zu können.
Die software-technische Referenzarchitektur kennt drei IT-Systemtypen: das *Backend*, das *Frontend* und den *Batch*.

Die nachfolgende Abbildung verdeutlicht den Zusammenhang zwischen den Begrifflichkeiten Anwendung und IT-System.
Sie geht auch auf die jeweiligen Spezialisierungen (d.h. Anwendungstypen und IT-Systemtypen) ein und benennt den Teil der Referenzarchitektur, in dem die Begriffe definiert und beschrieben sind.

.Zusammenhang zwischen Anwendung und IT-System
image::software-technisch/beziehung-anwendung-it-system.dn.svg[]

Grob gesagt besteht eine Anwendung, egal welchem Anwendungstyp sie entspricht, immer aus mindestens einem IT-System.
Dabei muss dieses IT-System entweder ein Backend oder ein Frontend sein.
Die Frage, in wie viele IT-Systeme eine Anwendung zerlegt wird, ist eine Entwurfsentscheidung, die im xref:methodik:vorlagen.adoc#dokumentation-anwendung[Systementwurf] dokumentiert wird.


== IT-Systemtypen

IT-Systemtypen fokussieren sich auf einen bestimmten Teil der Fachlichkeit einer Anwendung und sind maßgeblich für dessen Umsetzung.
Zwischen den IT-Systemtypen gibt es keine Überschneidungen.
Das bedeutet: Anhand der spezifizierten Fachlichkeit einer Anwendung kann direkt abgelesen werden, welche IT-Systemtypen zur Umsetzung der Anwendung notwendig sind.

.Abbildung von IT-Systemtypen auf ihre maßgeblich umgesetzte Fachlichkeit
[cols="1s,3",options="header"]
|===
|IT-Systemtyp
|Maßgeblich umgesetzte Fachlichkeit

|Backend
|Anwendungskomponenten (AWK), Nachbarsystemschnittstellen (NST)

|Frontend
|Dialoge (DIA), Masken (MAS)

|Batch
|Batch (BAT)
|===

IT-Systemtypen setzen neben ihrer maßgeblichen Fachlichkeit in der Regel auch weitere Fachlichkeit (z.B. Datenmodelle oder Akteure bzw. Rollen) um.
Diese Bestandteile der fachlichen Zerlegung erzwingen allerdings nicht, dass sie von einem bestimmten IT-Systemtyp umgesetzt werden.

=== Backend

* Was macht den IT-Systemtyp aus?
* Welchen Technologie-Stack verwendet er?
* Wo gibt es weitere Informationen hierzu?

...

=== Frontend

...

=== Batch

...

== Beispiel: Zerlegung einer Anwendung in IT-Systeme

.Beispiel: Zerlegung einer Anwendung in IT-Systeme
image::software-technisch/abbildung-anwendung-it-system.dn.svg[]

