= Services

In einer Systemlandschaft ist Kommunikation ein Element, das die technische Architektur prägt.
Die Art und Weise, wie IT-Systeme miteinander kommunizieren, bestimmt maßgeblich ihre _Effizienz_, _Wartbarkeit_ und _Zuverlässigkeit_.
Ein technischer Blick auf die Kommunikation schafft Klarheit über:

* die Kopplungsgrade zwischen Systemen, und damit über die Flexibilität bei sich ändernden Anforderungen,
* die Fehlertoleranz und Resilienz, etwa durch die Wahl zwischen synchronen und asynchronen Kommunikationsmustern, und
* das Lastverhalten und Antwortzeiten, entscheidend für die Nutzererfahrung und Stabilität.

Die Festlegungen hinsichtlich der Kommunikation sind strategische Architekturentscheidungen für die Umsetzung einer Systemlandschaft.
Werden die Entscheidungen nicht oder implizit getroffen, erhöht sich das Risiko schwer wartbarer Abhängigkeiten, ineffizienter Schnittstellen und insgesamt einer Architektur, die den Anforderungen an moderne, behördliche Informationssysteme nicht gerecht wird.

[[grundlagen]]
== Grundlagen

IT-Systeme kommunizieren auf Basis von Services.
Wenn ausschließlich IT-Systeme innerhalb der Systemlandschaft miteinander kommunizieren, spricht die Referenzarchitektur von *interner Servicekommunikation*.
Wenn die Kommunikation auch Systeme einschließt, die außerhalb liegen, verwendet die Referenzarchitektur den Begriff *externe Servicekommunikation*.

[[servicekommunikation-intern-extern]]
.Interne und externe Servicekommunikation
image::software-technisch/servicekommunikation.dn.svg[]

[[metadaten-nutzdaten]]
=== Metadaten und Nutzdaten

IT-Systeme tauschen in der Kommunikation untereinander Daten aus.
Diese lassen sich in Metadaten und Nutzdaten unterteilen.

*Metadaten* können technischer oder fachlicher Natur sein.
Sie sind nicht mit einer konkreten Anfrage verknüpft und werden in der Regel mit jedem Aufruf einer Schnittstelle übertragen.
Zu den Metadaten gehören u.a.:

* Daten zu übergreifenden Aspekten der Servicekommunikation wie z.B. Caching oder das Aushandeln von Formaten,
* IDs zum Tracing von Service-Aufrufen,
* Daten zur Authentifizierung und Autorisierung, oder
* Metadaten dritter Systeme, die durchgeschleift werden.

Metadaten werden in der Regel in Klartext übertragen und nicht verschlüsselt oder anderweitig kodiert.

[IMPORTANT]
====
Die Verwendung von externen Standards bleibt davon unberührt.
So überträgt der Standard OAuth 2 beispielsweise Informationen zur Autorisierung einer Anfrage BASE64-kodiert.
====

Die Übertragung von Metadaten geschieht in der Regel über Schlüssel-Wert-Paare (_key-value pairs_), z.B. in HTTP-Headern oder JMS-Properties.

.icon:university[title=Architekturregel] Benennung von Metadaten
****
Metadaten sind, egal über welches Protokoll sie übertragen werden, *einheitlich benannt*.
Gibt es eine durch einen Standard vorgegebene Benennung, ist diese zu verwenden.
****

Die <<standardisierte-metadaten,folgende Tabelle>> zeigt, welche Metadaten in der IsyFact standardisiert übertragen werden.

[[standardisierte-metadaten]]
.Benennung standardisierter Metadaten
[cols="1s,1m,2",options="header"]
|===
|Metadaten|Benennung|Herleitung

//|Korrelations-ID
//|X-Trace-ID
//|Neue Benennung in Vorbereitung zur Nutzung eines Standardprodukts für Tracing.

|Korrelations-ID +
//(deprecated)
|X-Correlation-Id
|ID zur Nachverfolgung von Aufrufen innerhalb einer Anwendungslandschaft.
//Alte Benennung. +
//*Wichtig:* Anwendungen müssen in der Übergangszeit beide Namen auflösen können.

|Bearer Token
|Authorization
|Vorgabe des Standards OAuth 2.0.
|===

*Nutzdaten* auf der anderen Seite beinhalten alle Daten, die zur Verarbeitung eines konkreten Service-Aufrufs benötigt werden.
Sie bilden die eigentliche, fachliche Schnittstelle und beschreiben sowohl die Daten der Anfrage sowie der Antwort.

Die IsyFact standardisiert die Art und Weise, wie Nutzdaten spezifiziert, dokumentiert und technisch verarbeitet werden.

[[kommunikationsarten]]
=== Kommunikationsarten

Ein zentrales Element der technischen Architektur ist die Wahl geeigneter Kommunikationsmuster zwischen IT-Systemen.
Kommunikationsmuster ordnen sich *synchroner Kommunikation* und *asynchroner Kommunikation* zu.
Die Wahl der Kommunikationsmuster beeinflusst direkt die technische Architektur und Umsetzung der IT-Systeme.
Die gewählten Kommunikationsmuster tragen ebenso maßgeblich dazu bei, die Qualitätskriterien der Architektur und der IT-Systeme zu erfüllen.

Die IsyFact empfiehlt grundsätzlich den Einsatz asynchroner Kommunikation, insbesondere bei der Umsetzung verteilter Systeme, zeitkritischer Prozesse, der Verarbeitung großer Datenmengen und der Realisierung skalierbarer und resilienter Architekturen.
Die Entscheidung für ein Kommunikationsmuster muss jedoch kontextabhängig und anhand der geforderten Qualitätskriterien der Architektur und der IT-Systeme erfolgen.

[[synchrone-kommunikation]]
==== Synchrone Kommunikation

Synchrone Kommunikation eignet sich besonders gut zur Umsetzung von vergleichsweise einfachen, gut überblickbaren und stark gekoppelten Abläufen oder Anwendungen bei denen eine einfache Implementierung das zentrale Kriterium ist.
Aufgrund der Tatsache, dass der Sender auf die Antwort des Empfängers wartet, sind Transaktionen, die mehrere IT-Systeme umfassen, bis zu einem gewissen Grad beherrschbar.

Synchrone Kommunikation ist häufig in Form des <<request-reponse>>-Musters umgesetzt.
Dies befähigt Sender und Empfänger, querschnittliche Aspekte wie Sicherheit, Logging oder Fehlerbehandlung direkt und vollumfänglich umzusetzen.
Dies wiederum wirkt sich positiv auf die _Sicherheit_, _Zuverlässigkeit_ und _Wartbarkeit_ der IT-Systeme aus.

Synchron kommunizierende IT-Systeme sind ebenso einfacher in eine Systemlandschaft zu integrieren, da sie in der Regel keine zusätzlichen Infrastrukturkomponenten benötigen.
Sie sind, geeignete Kommunikationsstandards vorausgesetzt, _interoperabel_ und besitzen eine hohe _Kompatibilität_.

[[synchron-herausforderungen]]
===== Herausforderungen

Die Tatsache, dass der Sender auf die Antwort des Empfängers wartet, kann zu Wartezeiten und, letztendlich, zu Skalierungsproblemen führen.
Dieser Effekt verstärkt sich durch verschachtelte Aufrufe oder Kaskaden.
Er steht hohen Anforderungen an die _Effizienz_ von IT-Systemen entgegen.

Ebenso wirken sich Fehler oder Ausfälle des Empfängers direkt auf den Sender aus.
Geschehen Fehler oder Ausfälle an viel genutzten Stellen, oder innerhalb einer Verkettung von Aufrufen, kann sich dies auf weite Teile der Systemlandschaft auswirken und erhebliche Auswirkungen auf deren _Zuverlässigkeit_ besitzen.

[[asynchrone-kommunikation]]
==== Asynchrone Kommunikation

Asynchrone Kommunikation ermöglicht die Umsetzung komplexer und voneinander entkoppelter Abläufe.
Die Wahl des Kommunikationsmusters entscheidet darüber, ob die Verantwortung der Verwaltung von Nachrichten bei dafür spezialisierten Infrastrukturkomponenten liegt, und ob sich Sender und Empfänger gegenseitig kennen.

Die Entkopplung von Sender und Empfänger ermöglicht eine bessere Lastverteilung und Skalierbarkeit.
Dies wirkt sich positiv auf die _Effizienz_ der IT-Systeme aus.

Asynchrone Kommunikationsflüsse sind robuster gegenüber temporären Ausfällen einzelner IT-Systeme, da Nachrichten zwischengespeichert und später verarbeitet werden können.
Dies erhöht die _Zuverlässigkeit_ der gesamten Systemlandschaft.

[[asynchron-herausforderungen]]
===== Herausforderungen

Aufgrund des hohen Grades an Entkopplung herrscht in einer asynchron kommunizierenden Systemlandschaft _eventual consistency_ als eine Form schwacher Konsistenz vor.
Dies müssen alle asynchron kommunizierenden IT-Systeme berücksichtigen.

Asynchron kommunizierende IT-Systeme benötigen in der Regel zusätzliche Infrastrukturkomponenten und integrieren sich daher nicht so leicht in eine bestehende Systemlandschaft.
Zur Nachrichtenübermittlung ist meist eine Infrastrukturkomponente für Messaging oder Event Streaming vorhanden.
Die Nachvollziehbarkeit von Abläufen ist komplexer, da Kommunikationsflüsse nicht linear verlaufen und Zustände verteilt sein können, und erfordert ein geeignetes Tracing und Monitoring.
Die zusätzlichen Infrastrukturkomponenten müssen in die Umsetzung querschnittlicher Aspekte wie _Sicherheit_, _Zuverlässigkeit_ und _Wartbarkeit_ einbezogen werden.

[[kommunikationsmuster]]
== Kommunikationsmuster

include::documentation-guide::partial$content-revised.adoc[]

[[request-reponse]]
=== Request-Response

Das Request-Response-Muster bietet die Möglichkeit der direkten Kommunikation zwischen zwei IT-Systemen.
Hierbei schickt der Sender eine Anfrage (englisch: _request_) an den Empfänger.
Der Empfänger bearbeitet die Anfrage und schickt eine Antwort (englisch: _response_) an den Sender zurück.
Je nachdem, ob Sender oder Empfänger synchron oder asynchron miteinander kommunizieren, wartet der Sender auf die Antwort, bevor er seine Verarbeitung fortsetzt, oder nimmt die Verarbeitung erst durch die Antwort des Empfängers wieder auf, z.B. in Form eines Callbacks.

[[service-aufruf-synchron]]
.Ablauf des Request-Response-Musters (links: synchron, rechts: asynchron)
image::software-technisch/request-response.dn.svg[]

Ob zwei IT-Systeme synchron oder asynchron über Request-Response miteinander kommunizieren, muss anhand der zu erfüllenden Qualitätskriterien abgewogen werden.
Das Request-Response-Muster ermöglicht so asynchrone Kommunikation, wo trotzdem direkte Antworten benötigt werden.
Die Abwägung muss während der Erstellung des Systementwurfs geschehen.

==== Protokoll für Request-Response

.icon:university[title=Architekturregel] Verwendung von HTTP für Request-Response
****
Aufrufe nach dem Request-Response-Muster finden über das Protokoll *HTTP* statt und werden sowohl zur internen als auch externen Servicekommunikation genutzt.
HTTP-Anfragen bzw. HTTP-Antworten erlauben es an drei Stellen, anwendungsspezifische Daten zu übertragen: in der URL, in den Headern sowie im Body.

[[http-message-aufbau]]
.Aufbau von HTTP-Anfragen bzw. HTTP-Antworten
image::referenzarchitektur:software-technisch/http-messages-aufbau.dn.svg[]
Header enthalten Metadaten.
Der Body enthält Nutzdaten.
Bei Anfragen mittels `GET` und `DELETE`, die keinen Body erwarten, enthalten URL-Parameter Nutzdaten.
****

Allerdings gilt zu beachten, dass URLs (und damit auch die URL-Parameter) an vielen Stellen aufgezeichnet und in Logs geschrieben oder in Caches gehalten werden.
Hierbei sind z.B. datenschutzrechtliche Aspekte zu prüfen, wenn URL-Parameter personenbezogene Daten enthalten.
Im Zweifelsfall ist die Methode `POST` die empfohlene Alternative, um solche Nutzdaten im Body zu übertragen.

[[queueing]]
=== Queueing

Beim Queueing baut ein Message-Broker eine Punkt-zu-Punkt-Verbindung zwischen zwei IT-Systemen auf.
Dies geschieht in Form einer Queue.
Ein IT-System tritt fest als Sender auf, eines als Empfänger.
Der Sender ist nun in der Lage, dem Empfänger über die Queue Nachrichten zu schicken.
Die Nachrichten sind anhand eines zentral definierten Formats strukturiert.
Der Sender enthält keine direkte Antwort vom Empfänger.

[[service-aufruf-queueing]]
.Ablauf der Kommunikation beim Queueing
image::software-technisch/queueing.dn.svg[]

Für das Queueing infrage kommende Message-Broker müssen *JMS* (Jakarta Messaging, ehemals _Java Message Service_) unterstützen.
Queueing wird ausschließlich in der internen Servicekommunikation eingesetzt.

JMS-Nachrichten bestehen aus Header, Properties und einem Body.
Die Properties unterteilen sich noch einmal in applikationsspezifische Properties, die nur für Publisher und Subscriber Bedeutung haben, sowie provider-spezifische und Standard-Properties, die zur Verarbeitung der JMS-Nachrichten durch den Message-Broker gedacht sind.

[[jms-message-aufbau]]
.Aufbau einer JMS-Nachricht
image::software-technisch/jms-message-aufbau.dn.svg[]

Applikationsspezifische Properties enthalten Metadaten.
Der Body enthält Nutzdaten.
Nutzdaten werden im XML-Format übertragen und mittels XSD spezifiziert.

Diese Vorgabe steht vollständig in Einklang mit der JMS-Spezifikation.
Für die Übertragung von Nutzdaten sieht die JMS-Spezifikation fünf Formate vor.
Die Architekturvorgabe sieht die alleinige Nutzung der Ausprägung `TextMessage` vor, die Nutzdaten als Zeichenkette erwartet.

[NOTE]
====
Weitere Details zu JMS-Nachrichten finden sich in der JMS-Spezifikation im Kapitel https://jakarta.ee/specifications/messaging/3.0/jakarta-messaging-spec-3.0.html#jakarta-messaging-message-model[3. Jakarta Messaging message model].
Besonders relevant für die Referenzarchitektur sind die Abschnitte https://jakarta.ee/specifications/messaging/3.0/jakarta-messaging-spec-3.0.html#jakarta-messaging-messages[3.3. Jakarta Messaging messages] sowie https://jakarta.ee/specifications/messaging/3.0/jakarta-messaging-spec-3.0.html#jakarta-messaging-message-body[3.11. Jakarta Messaging message body].
====

== Kommunikation mit externen Systemen

Die Kommunikation mit xref:glossary::terms-definitions.adoc#externes-system[externen Systemen] basiert auf Webservices.
Wird ein Service von einem externen System angeboten, wird er als *externer Service* bezeichnet.
Im Folgenden werden zwei Szenarien betrachtet:

*Aufruf von Services der Systemlandschaft*: Durch die Systemlandschaft wird externen Systemen die Schnittstelle eines Backends in Form eines Webservices zur Verfügung gestellt.
Hierbei definiert das Backend selbst keinen Webservice.
Vielmehr definiert das Backend, wie bei der internen Kommunikation auch, eine Schnittstelle.
Diese Schnittstelle wird dann durch ein eigenständiges IT-System als Webservice exportiert.
Dies geschieht mittels eines xref:glossary::terms-definitions.adoc#glossar-service-gateway[Service-Gateways], das als *Service-Provider* bezeichnet wird.
Für jede Schnittstelle, die als Webservices exportiert werden soll, muss ein eigener Service-Provider definiert werden.

*Nutzung von externen Services*: Ähnlich wie im vorigen Fall ruft das interne IT-System den externen Service nicht direkt auf.
Es ruft ein eigenständiges IT-System auf, welches den externen Service als Schnittstelle in die Systemlandschaft importiert.
Dies geschieht ebenfalls mittels eines xref:glossary::terms-definitions.adoc#glossar-service-gateway[Service-Gateways], das als *Service-Consumer* bezeichnet wird.
Das interne IT-System ruft dann lediglich die Schnittstelle des Service-Consumers auf.
Für das interne IT-System ist dieser Aufruf nicht von einem Aufruf zu einem anderen internen IT-System zu unterscheiden.
Für jeden Webservice, der in die Systemlandschaft importiert werden soll, muss ein eigener Service-Consumer definiert werden.

Die Service-Gateways stellen somit die Schnittstelle einer Systemlandschaft zur Außenwelt dar.

.Nutzung von Service Gateways zur Kommunikation mit externen Systemen
image::software-technisch/services/kommunikation-externe-systeme.dn.svg[]

