CREATE TABLE BATCH_STATUS
(
    BATCH_ID                   VARCHAR2(255) NOT NULL,
    BATCH_NAME                 VARCHAR2(255),
    BATCH_STATUS               VARCHAR2(255),
    SATZ_NUMMER_LETZTES_COMMIT NUMBER(19, 0),
    SCHLUESSEL_LETZTES_COMMIT  VARCHAR2(255),
    DATUM_LETZTER_START        TIMESTAMP,
    DATUM_LETZTER_ABBRUCH      TIMESTAMP,
    DATUM_LETZTER_ERFOLG       TIMESTAMP,
    CONSTRAINT BATCH_STATUS_PK PRIMARY KEY (BATCH_ID)
);

CREATE TABLE BATCH_STATUS_KONFIGURATIONS_PARAMETER
(
    BATCH_STATUS_BATCH_ID     VARCHAR2(255) NOT NULL,
    KONFIGURATIONS_PARAMETER  BLOB,
    CONSTRAINT FK_BS_KONFIGURATIONS_PARAMETER FOREIGN KEY (BATCH_STATUS_BATCH_ID) REFERENCES BATCH_STATUS (BATCH_ID)
);
