
CREATE TABLE BATCH_STATUS
(
    BATCH_ID                   VARCHAR2(255) NOT NULL,
    BATCH_NAME                 VARCHAR2(255),
    BATCH_STATUS               VARCHAR2(255),
    SATZ_NUMMER_LETZTES_COMMIT NUMBER(19, 0),
    SCHLUESSEL_LETZTES_COMMIT  VARCHAR2(255),
    DATUM_LETZTER_START        TIMESTAMP,
    DATUM_LETZTER_ABBRUCH      TIMESTAMP,
    DATUM_LETZTER_ERFOLG       TIMESTAMP,
    CONSTRAINT BATCH_STATUS_PK PRIMARY KEY (BATCH_ID)
);
