= Nutzungsvorgaben Sicherheit: Anhänge

// tag::inhalt[]
== Anhang

//Sicherstellung, dass Verlinkung funktioniert mit anchor konfigurationsdatei
[[konfigurationsdateien]]
[[standard-cache-konfiguration]]
=== Anhang A: Standard-Cache-Konfiguration

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ehcache xsi:noNamespaceSchemaLocation="ehcache.xsd" updateCheck="false" monitoring="autodetect" dynamicConfig="true">
  <!--
  Pflicht: Standard-Einstellungen fuer Caches.
  Diese Einstellungen werden verwendet,
  sofern Caches programmatisch erzeugt werden mithilfe von
  CacheManager.add(String cacheName).
  Der defaultCache hat den impliziten Namen "default",
  welcher einer reservierter
  Cache-Name ist.
  -->
  <defaultCache
    maxEntriesLocalHeap="1000"
    eternal="false"
    timeToLiveSeconds="300"
    timeToIdleSeconds="0"
    overflowToDisk="false"
    memoryStoreEvictionPolicy="LRU" />
  <cache
    name="authentifizierungen"
    maxEntriesLocalHeap="1000"
    eternal="false"
    timeToLiveSeconds="300"
    timeToIdleSeconds="0"
    overflowToDisk="false"
    memoryStoreEvictionPolicy="LRU" />
</ehcache>
----

[[anhang-rollen-rechte-schema]]
=== Anhang B: Rollen-Rechte-Schema

Im Folgenden ist der Inhalt der Datei `RollenRechteSchema.xsd` wiedergegeben, die das Format der Konfigurationsdatei für Rollen und Rechte (`rollenrechte.xml`) festlegt.

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.isyfact.de/RollenRechteSchema"
    xmlns:tns="http://www.isyfact.de/RollenRechteSchema"
    elementFormDefault="qualified">
  <include schemaLocation=""></include>
  <complexType name="Rolle">
    <sequence>
      <element name="rechtId" type="tns:RechtId" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="RolleId" type="string" use="required"/>
  </complexType>
  <complexType name="Recht">
    <sequence>
      <element name="rechtId" type="tns:RechtId" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>
  <element name="Anwendung" type="tns:Anwendung"/>
  <complexType name="Anwendung">
    <sequence>
      <element name="rollen" type="tns:Rolle" minOccurs="1" maxOccurs="unbounded"/>
      <element name="rechte" type="tns:Recht" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="AnwendungsId" type="string" use="required"/>
  </complexType>
  <complexType name="RechtId">
    <attribute name="Id" type="string" use="required"/>
  </complexType>
</schema>
----

[[verwaltung-von-rollen-im-benutzerverzeichnis]]
=== Anhang C: Verwaltung von Rollen im Benutzerverzeichnis

Damit Rollen auch an Benutzer im Benutzerverzeichnis vergeben werden können, müssen die Rollen in das Benutzerverzeichnis eingespielt werden.

Dies erfolgt für Testsysteme und das Produktivsystem (im Rahmen von Inbetriebnahmen) per Import-Batch, bei dem ein Excel-Dokument mit zu importierenden Rollen in das Benutzerverzeichnis geladen wird.
Der Import ist der einzige Weg, um Rollen hinzuzufügen.

Mit dem Batch ist es möglich Rollen hinzuzufügen (`Add`), zu verändern (`Upd`) oder zu löschen (`Del`).

Das Excel-Dokument zum Einspielen von Rollen benötigt ein Arbeitsblatt „Rollen“ und hat folgendes Format:

:desc-table-EinspielenVonRollen: Einspielen von Rollen in das Benutzerverzeichnis (Beispiel)
[id="table-EinspielenVonRollen",reftext="{table-caption} {counter:tables}"]
.{desc-table-EinspielenVonRollen}
[cols="1,2,2,2,3",options="header"]
|====
|*Aktion* |*Rollenlabel* |*Rollenname* |*Rollentyp* |*Unterrollen*
|Add |BNVZ_Rolle1 |BNVZ_Rolle1 |fachlich |BHVZ_Schnittstellennutzer
|Upd |BNVZ_Rolle2 |BNVZ_Rolle2 |fachlich |BHVZ_Schnittstellennutzer, +
SVZ_Schnittstellennutzer
|Del | |BNVZ_Rolle3 |  | 
|====

Zusätzlich zu den oben abgebildeten Spalten enthält das Excel-Dokument die folgenden weiteren Spalten, deren Inhalt bereits im Dokument xref:nutzungsvorgaben/master.adoc#einleitung[Sicherheit - Konzept] beschrieben wurde:

* *Rollenbeschreibung*
* *SichtbarkeitAnwender*
* *SichtbarkeitSystemeExtern*
* *SichtbarkeitSystemeIntern*

Nach der letzten zu importierenden Zeile des Arbeitsblatts sollte eine Zeile mit der Aktion `End` eingefügt werden.
Dies verbessert die Performance beim Import.
Bei allen anderen Werten in der Spalte „Aktion“ wird die Zeile ignoriert.

Zusätzlich kann das Excel-Dokument ein weiteres Tabellenblatt „Systeme“ enthalten.
Dieses folgt demselben Schema zum Hinzufügen (`Add`), Ändern (`Upd`) und Löschen (`Del`) von Einträgen.
Es dient dazu, die Systeme (interne und ggf. auch externe) zu pflegen, wie im Dokument xref:nutzungsvorgaben/master.adoc#einleitung[Sicherheit - Konzept] beschrieben.
Systeme sind im Benutzerverzeichnis spezialisierte Benutzer.
Sie haben daher alle Attribute der Entitäten `ETY_Benutzer`, `ETY_System` und `ETY_Rollenträger`.

Das Tabellenblatt „Systeme“ enthält die folgenden Spalten, deren Inhalte in den Attributbeschreibungen im Datenmodell des Benutzerverzeichnisses erklärt werden:

* *Aktion*: `Add`, `Upd`, `Del` oder `End`
* *InterneKennung*
* *Name*
* *Status*: `gueltig` oder `ungueltig`
* *BHKNZ*: Kennzeichen der Organisation (Behördenkennzeichen) durch die das System genutzt wird.
* *Anbieter*
* *Intern*: `true` oder `false`
* *PasswortPlain*: Passwort im Klartext, wird beim Import verschlüsselt
* *Anlagedatum*
* *PasswortLaeuftAb*: `true` oder `false` (für Systeme sinnvollerweise `false`)
* *PasswortLetzteAenderung*
* *PasswortMussGeaendertWerden*: `true` oder `false`
* *Beschreibung*
* *LetzteAenderung*
* *LetzteAenderungDurch*
* *RollenDirekt*: Kommaseparierte Liste der direkt zugeordneten fachlichen Rollen des Systems

*Motivation für die Updatefunktion*

Die Löschung einer bereits verwendeten Rolle kann große Auswirkungen auf die Rollenzuordnung des Benutzerbestandes haben, da diese allen besitzenden Benutzern weggenommen werden muss.
Eine nachträgliche hinzugefügte Ersatzrolle müsste dann manuell administrativ den Benutzern wieder zugeordnet werden.
Das ist nicht praktikabel.
Daher wird für eine Aktualisierung einer Rolle das Ändern einer Rolle (`Upd`) angeboten.
Die Rollendefinition wird dabei verändert, während die Rolle allen Benutzern und Nutzergruppen zugeordnet bleibt.

*Einschränkungen für den Rollenimport*

Folgende Einschränkungen bestehen beim Import von Rollen:

* Erzeugen einer Rolle:
** Der Name der Rolle darf noch nicht vergeben sein.
** Eine fachliche Rolle darf nur technische Unterrollen haben.
Im Excel-Dokument referenzierte Unterrollen müssen im Datenbestand bereits bekannt sein, bzw.
im Excel-Dokument weiter oben stehen.
* Ändern einer Rolle
** Der Typ der Rolle (fachlich, technisch) kann nicht geändert werden.
** Der (neue) Name der Rolle darf nicht bereits an eine andere Rolle vergeben sein.
* Löschen der Rolle: Handelt es sich um eine technische Rolle, so darf diese Rolle zum Zeitpunkt der Löschung nicht mehr in einer anderen Rolle als Unterrolle verwendet werden.
Die fachliche Rolle ist zunächst explizit zu löschen.

[[verwaltung-des-rollen-masters]]
==== Verwaltung des Rollen-Masters

Die Rollendefinition der Anwendungslandschaft (in Form eines Excel-Dokuments) ist ein zentral zu verwaltendes Dokument, welches zur Befüllung von Testumgebungen verwendet wird.
Es repräsentiert den insgesamt verfügbaren Rollenvorrat über alle Anwendungssysteme.
Das Dokument trägt den Namen **Rollen-Master**.

Änderungen am Rollenmodell im Rahmen von Wartungsarbeiten werden in dieses Dokument übertragen.
Zum Einspielen einer Rollenänderung in ein produktiv- oder Testsystem wird jedoch ein passendes *Rollen-Delta* (ebenfalls Excel) verwendet, welches nach einer Inbetriebnahme gelöscht wird.

Die Koordination der Änderungen am Rollen-Master obliegt dem Release-Verantwortlichen.

[[releases-und-rollen-deltas]]
==== Releases und Rollen-Deltas

Für jedes Release, welches Änderungen an dem Rollenbestand der Anwendungslandschaft vornimmt, werden ein oder mehrere Rollen-Deltas aufbauend auf dem Rollen-Master erstellt, die das Rollenmodell vom Ist-Zustand in den Soll-Zustand überführen.
Die Rollen-Deltas werden in den Quellen des zugehörigen IT-Systems im Verzeichnis `/src/main/skripte/sicherheit` abgelegt

Diese Rollen-Deltas werden auf Testumgebungen im Rahmen der Integrationstests getestet und mit dem Release ausgeliefert.
Die Reihenfolge, in der sie eingespielt werden müssen, wird im Releaseletter für die Rollen-Deltas definiert.
Sie hängt von den Abhängigkeiten der Systeme ab, die in den Releaselettern der jeweiligen Systeme beschrieben sind.

// end::inhalt[]
