= Nutzungsvorgaben Sicherheit: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Das Dokument xref:nutzungsvorgaben/master.adoc#einleitung[Sicherheit - Konzept] konzentriert sich auf die konzeptionellen Aspekte der Authentifizierung und Autorisierung.

Dieses Dokument beschreibt, wie der Baustein Sicherheit und die von ihm bereitgestellte Bibliothek `isy-sicherheit` verwendet werden, um die Autorisierung innerhalb von IT-Systemen umzusetzen.
Es richtet sich an Entwickler, die ein xref:glossary:glossary:master.adoc#glossar-it-system>[IT-Systeme] gemäß den Vorgaben der IsyFact mit der Fähigkeit zur Autorisierung ausstatten müssen und beschreibt, wie und in welchen Teilen einer Anwendung die Autorisierung umzusetzen ist.

Dazu beschreibt das Kapitel xref:nutzungsvorgaben/master.adoc#grundkonzepte-und-konfiguration[Grundkonzepte und Konfiguration] zunächst die grundlegenden Konfiguration, um den Baustein in ein IT-System einzubinden.

Die folgenden Kapitel leiten durch die Funktionen des Bausteins Sicherheit.
Zuerst wird die wichtigste Funktion - die xref:nutzungsvorgaben/master.adoc#autorisierung[Autorisierung] in IT-Systemen - erklärt.
Dann folgen weitere Themen:

* siehe xref:nutzungsvorgaben/master.adoc#aufrufen-von-nachbarsystemen[Aufrufen von Nachbarsystemen],
* siehe xref:nutzungsvorgaben/master.adoc#verwendung-der-korrelations-id[Verwendung der Korrelations-Id],
* siehe xref:nutzungsvorgaben/master.adoc#verwenden-anwendungsspezifischer-aufrufkontexte[Verwenden anwendungsspezifischer Aufrufkontexte],
* siehe xref:nutzungsvorgaben/master.adoc#ueberwachung-baustein-sicherheit[Überwachung Baustein Sicherheit].

Schließlich beschreibt das letzte Kapitel, wie siehe xref:nutzungsvorgaben/master.adoc#entwickeln-und-testen[Entwickeln und Testen] mit dem Baustein Sicherheit möglich ist.

Viele der in diesem Dokument beschriebenen Vorgaben sind in der xref:glossary:literaturextern:inhalt.adoc#litextern-vorlageanwendung[Vorlageanwendung] umgesetzt.

// end::inhalt[]
