= Tutorial: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Dokument dient als Einstieg in die technischen Grundlagen der IsyFact.
Es enthält in Kurzform die wesentlichen Designvorgaben und beschreibt, wie einzelne Aspekte in Anwendungen umzusetzen sind, die
gemäß der Referenzarchitektur der IsyFact gebaut werden.
Das Dokument unterstützt damit Entwickler und technische Chefdesigner bei der Konstruktion und Realisierung von Anwendungen
einer zur IsyFact konformen Anwendungslandschaft.
Im Sinne einer Referenz enthält es jedoch nicht alle Details der zugrunde liegenden Konzepte.
Der Fokus liegt darauf, einen schnellen Überblick über die einzelnen Themen zu geben und die wichtigsten Realisierungsaufgaben
zusammenfassend darzustellen.
An vielen Stellen bezieht sich das Tutorial auf die <<Vorlageanwendung>>, die eine kleine Geschäftsanwendung beispielhaft implementiert sind.

Zunächst beschreibt das Kapitel *<<bezug-isyfact>>*, wie sich die IsyFact in Entwicklungsprojekte einbinden lässt.
Danach beleuchten die Kapitel *<<datenhaltung>>* , *<<fachkomponenten-der-anwendung>>* und *<<anwendungsnutzung>>* jeweils einzelne Kernthemen der Anwendungsentwicklung.
Kapitel *<<querschnitt>>* fasst alle Querschnittsthemen zusammen.
Jedes Teilkapitel beginnt in der Regel mit der Auflistung der wichtigsten Designvorgaben und einem Klassendiagramm.
Es folgt eine Realisierungsanleitung, die alle wesentlichen Schritte zur Umsetzung in Kurzform enthält.
// end::inhalt[]