[[changelog]]
= Changelog

// *Änderungen IsyFact 2.2.0*

// tag::release-2.2.0[]
// end::release-2.2.0[]

*Änderungen IsyFact 2.1.0*

// tag::release-2.1.0[]
- `IFS-324`: Umzug des Tasks für Konfigurations-Updates von isy-task zu isy-konfiguration
// end::release-2.1.0[]

*Änderungen IsyFact 2.0.0*

// tag::release-2.0.0[]
- `IFS-228`: Einführung von Spring Boot
- `IFS-32`: Package-Name auf de.bund.bva.isyfact geändert
// end::release-2.0.0[]

// *Änderungen IsyFact 1.8.0*

// tag::release-1.8.0[]
// end::release-1.8.0[]

*Änderungen IsyFact 1.7.0*

// tag::release-1.7.0[]
// Interne alte Version: 1.8.0
- `IFS-262`: `isyfact-masterpom` deprecated (Abschaffung mit IsyFact 2.0), `isyfact-masterpom-lib` aufgelöst, Bibliotheken benutzen `isyfact-standards` als Parent-POM
// end::release-1.7.0[]

*Änderungen IsyFact 1.6.0*

// tag::release-1.6.0[]
// Interne alte Version: 1.7.0
- `IFS-189`: Repositories der IsyFact-Standards zusammengeführt, Bibliotheken benutzen wieder gemeinsames Produkt-BOM und werden zentral über das POM isyfact-standards versioniert
- `IFS-273`: Task zur Aktualisierung der Konfiguration muss Korrelations-ID setzen
// end::release-1.6.0[]

// *Änderungen IsyFact 1.5.0*

// tag::release-1.5.0[]
// end::release-1.5.0[]

*Änderungen IsyFact 1.4.0*

// tag::release-1.4.0[]
// Interne alte Version: 1.5.2
- `IFS-98`: Sortierung von Dateien darf nur bei Konfiguration als Ordnerstruktur verwendet werden
- `RF-161`: Bibliotheken binden genutzte Bibliotheken direkt ein und nicht mehr über BOM-Bibliotheken
- `IFS-26`: Konfigurationsaktualisierung via Timertask nun mit Korrelations-ID
- `IFS-59`: Konfiguration kann beliebige Konfigurationsdateien lesen
- `RF-107`: Beim Reload von properties wurden gelöschte properties nicht erfolgreich entfernt.
// end::release-1.4.0[]

// *Änderungen IsyFact 1.3.5*

// tag::release-1.3.5[]
// end::release-1.3.5[]

// *Änderungen IsyFact 1.3.0*

// tag::release-1.3.0[]
// end::release-1.3.0[]

