= Historisierung

include::glossary:licence:partial$licence.adoc[]

Unter *Historisierung* (auch https://de.wikipedia.org/wiki/Temporale_Datenhaltung[temporale Datenhaltung] genannt) versteht man das Festhalten der zeitlichen Entwicklung von Daten durch Speichern in einer Datenbank.
Bei den Datensätzen gibt es zwei relevante Aspekte: den Gültigkeitszeitraum eines Datensatzes und den Bearbeitungszeitpunkt eines Datensatzes.

Der *Gültigkeitszeitraum* gibt an, wie lange ein Datensatz gültig ist.
Während der Beginn des Gültigkeitszeitraumes meistens genau bekannt ist, so kann das Ende der Gültigkeit so lange unbekannt sein, bis der Datensatz ungültig wird.

.Gültigkeitszeitraum
====
Der Preis einer Ware oder Dienstleistung ist so lange gültig, bis er neu festgelegt wird.
====

Der *Bearbeitungszeitpunkt* definiert den Zeitpunkt, wann eine Entscheidung getroffen wurde und ist in vielen Fällen identisch mit dem Beginn des Gültigkeitszeitraumes.
Er kann jedoch auch davon abweichen, wenn z. B. für eine Ware eine Preisänderung zu einem bestimmten Datum im Voraus festgelegt wird.

Eine Historisierung von Datensätzen wird durchgeführt, wenn Fragen über den Wert eines Datensatzes zu einem vergangenen Zeitpunkt beantwortet werden müssen (z. B. was eine Ware zu einem bestimmten Zeitpunkt in der Vergangenheit kostete), oder wenn der Verlauf eines Wertes über die Zeit beobachtet werden muss (z. B. wann und warum eine Änderung durchgeführt wurde).

== Abgrenzungen

Die Historisierung grenzt sich wie folgt von den Themen Archivierung, Datensicherung, Protokollierung und Logging ab.

[[abgrenzung-archivierung]]
=== Abgrenzung Archivierung

Bei der Archivierung handelt es sich um die Aufbewahrung eines Datensatzes über eine längere Zeit hinweg.
Dies ist meist aus rechtlichen Gründen notwendig z. B. wegen gesetzlicher Aufbewahrungsfristen.
Bei der Archivierung sind dementsprechend Randbedingungen wie Integrität, Unveränderlichkeit und Vertraulichkeit einzuhalten (s. https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/it-grundschutz_node.html[IT-Grundschutz BSI]).

[[abgrenzung-datensicherung-backup]]
=== Abgrenzung Datensicherung (Backup)

Bei der Datensicherung handelt es sich um das redundante Aufbewahren von Datensätzen.
Das Ziel ist es, bei Verlust oder ungewünschter Manipulation von Datensätzen diese Datensätze auf den gespeicherten Stand zurücksetzen zu können.

[[abgrenzung-protokollierung]]
=== Abgrenzung Protokollierung

Ziel der Protokollierung ist das Nachvollziehen von Änderungen und Auskünften.
Dazu werden je nach Bedarf die Suchschlüssel und Nettodaten von Aufrufen gespeichert.

[[abgrenzung-logging]]
=== Abgrenzung Logging

Beim Logging werden Notizen zu technischen Aufrufen innerhalb eines Systems oder zwischen Anwendungen in Dateien abgelegt.
Das Logging hat einen technischen Fokus und dient in der Regel als Hilfsinstrument zur Fehlerbehebung.

[[anforderungen-festlegungen]]
== Anforderungen & Festlegungen

Die beabsichtigte Nutzung der Historisierung lässt sich mit Blick auf die Referenzarchitektur zu Anforderungen verallgemeinern, die in diesem Abschnitt dargestellt werden.

Für die Historisierung von Datensätzen in einer Anwendung gelten folgende Anforderungen und Grundsätze:

* Es dürfen nur solche Daten historisiert werden, die auch angezeigt werden.
* Die Speicherung von historischen Daten wird durch individuelle Löschfristen von Datensätzen begrenzt.
* Datensätze müssen beim Eintreten bestimmter Ereignisse komplett, d.h. inklusive aller historisierten Datensätze, gelöscht werden.
* Für die meisten Daten ist eine Historisierung weder notwendig noch erlaubt.
Dies ist durch Vorgaben des Datenschutzes und der Geheimhaltung begründet.

Diese Anforderungen führen zu folgenden Festlegungen:

* Eine automatische Historisierung von Daten, bei der jeder Datensatz in mehreren Versionen vorgehalten ist, wird nicht realisiert.
* Eine Historisierung wird, fachlich begründet, für die betroffenen Datensätze explizit realisiert.
