== Namenskonventionen: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Die umfassenden Konzepte der IsyFact automatisieren und vereinheitlichen den Bau von Anwendungen.
Um dies zu erreichen ist es wichtig, dass Namen und Benennungen über die gesamte xref:glossary:glossary:master.adoc#glossar-anwendungslandschaft[Anwendungslandschaft] hinweg einheitlich sind.
Es existiert daher eine Vielzahl von Namenskonventionen in den verschiedenen Konzepten der IsyFact.
Dieses Dokument ist Teil der xref:glossary:glossary:master.adoc#glossar-ifs[IsyFact Standards].

[[kurzueberblick]]
=== Kurzüberblick

Dieses Dokument sammelt die Namenskonventionen der IsyFact an einem zentralen Ort.
In den jeweiligen Konzepten wird die Vorgabe nochmals erwähnt.

Nach der Einleitung, die einen kurzen Abschnitt über generelle Anforderungen an Namen enthält, befasst sich das Kapitel
xref:namenskonventionen/master.adoc#namenskonventionen[Namenskonventionen] mit den Namenskonventionen der IsyFact.
Es ist dabei unterteilt in allgemeine Konventionen sowie Konventionen in der Entwicklung von Anwendungen.

Jede Namenskonvention ist in Tabellenform dargestellt.
Es ist jeweils das Namensschema der Konvention mit Beispielen zu sehen.
Ergänzt wird diese Darstellung durch eine Erklärung der genutzten Variablen und ihrer möglichen Ausprägungen.
// end::inhalt[]
