= Nutzungsvorgaben Umgang mit Sonderzeichen: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

In Anwendungen nach den IsyFact-Standards werden Daten in internationaler Schreibweise erfasst und gespeichert.
Dies sind z.B. die Namen von Personen und Orten.
Während die Eingabe von internationalen Sonderzeichen über eine deutsche Tastatur nur einen beschränkten Umfang an Sonderzeichen erlaubt, werden möglicherweise auch Daten abgelegt, die international landesspezifisch erfasst wurden.
Hierin können alle landestypischen Sonderzeichen enthalten sein.
Insbesondere also auch solche, die nicht über eine deutsche Tastatur eingegeben werden können.

Eine auf den IsyFact-Standards aufsetzende Architektur umfasst mehrere technische Systeme in einer Umgebung.
Für jedes dieser Systeme muss sichergestellt werden, dass die benötigten Sonderzeichen durchgängig verarbeitet werden können und beim Datenaustausch zwischen diesen Systemen einheitlich durchgereicht und korrekt interpretiert werden.

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

In diesem Dokument wird zunächst wird der Zeichensatz festgelegt, der innerhalb der Anwendungen verwendet werden soll.
Abschließend wird für die technischen Systeme angegeben, wo die entsprechenden Konfigurationseinträge zur Verwendung des Zeichensatzes vorgenommen werden müssen.

Internationalisierung bedeutet, ein Programm so zu entwerfen und umzusetzen, dass die Anpassung an andere Sprachen möglich ist, ohne den Quellcode zu ändern.
Jedoch ist Internationalisierung nicht Bestandteil dieses Dokuments.
// end::inhalt[]