[[changelog]]
= Changelog

// *Änderungen IsyFact 2.2.0*

// tag::release-2.2.0[]
// end::release-2.2.0[]

*Änderungen IsyFact 2.1.0*

// tag::release-2.1.0[]
- `IFS-156`: Sonderlogik, die Underscores aus dem Attribut durchfuehrenderSachbearbeiterName des Aufrufkontextes entfernt, erneut ausgebaut.
// end::release-2.1.0[]

*Änderungen IsyFact 2.0.0*

// tag::release-2.0.0[]
- `IFS-228`: Einführung von Spring Boot
- `IFS-32`: Package-Name auf de.bund.bva.isyfact geändert
- `IFS-318`: Cache-Implementierung über JCache-API abstrahiert
// end::release-2.0.0[]

// *Änderungen IsyFact 1.8.0*

// tag::release-1.8.0[]
// end::release-1.8.0[]

*Änderungen IsyFact 1.7.0*

// tag::release-1.7.0[]
// Interne alte Version: 1.8.0
- `IFS-262`: `isyfact-masterpom` deprecated (Abschaffung mit IsyFact 2.0), `isyfact-masterpom-lib` aufgelöst, Bibliotheken benutzen `isyfact-standards` als Parent-POM
// end::release-1.7.0[]

*Änderungen IsyFact 1.6.0*

// tag::release-1.6.0[]
// Interne alte Version: 1.7.0
- `IFS-189`: Repositories der IsyFact-Standards zusammengeführt, Bibliotheken benutzen wieder gemeinsames Produkt-BOM und werden zentral über das POM isyfact-standards versioniert
// end::release-1.6.0[]

*Änderungen IsyFact 1.5.0*

// tag::release-1.5.0[]
// Interne alte Version: 1.5.1
- `RF-161`: Bibliotheken binden genutzte Bibliotheken direkt ein und nicht mehr über BOM-Bibliotheken
// end::release-1.5.0[]

*Änderungen IsyFact 1.4.0*

// tag::release-1.4.0[]
// Interne alte Version: <= 1.4.6
- Sonderlogik, die Underscores aus dem Attribut durchfuehrenderSachbearbeiterName des Aufrufkontextes entfernt, wieder eingebaut, da Ausbau erst für später relevant.
- Sonderlogik, die Underscores aus dem Attribut durchfuehrenderSachbearbeiterName des Aufrufkontextes entfernt, ausgebaut.
- Für Anwendungen, in die die neue Version eingebunden werden soll, muss vorher geprüft, ob Underscores im Attribut durchfuehrenderSachbearbeiterName des Aufrufkontextes verarbeitet werden können.
// end::release-1.4.0[]

// *Änderungen IsyFact 1.3.5*

// tag::release-1.3.5[]
// end::release-1.3.5[]

// *Änderungen IsyFact 1.3.0*

// tag::release-1.3.0[]
// end::release-1.3.0[]
