= Detailkonzept Service: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Entsprechend der xref:referenzarchitektur-it-system/master.adoc[] stellen IT-Systeme Services über die technische Komponente „Service“ zur Verfügung.
Das vorliegende Dokument beschreibt die Aufgaben und die Architektur dieser technischen Komponente.
Zu beachten ist, dass die Komponente „Service“ die Services eines IT-Systems lediglich innerhalb der Systemlandschaft verfügbar macht.
Um diese Services auch externen Anwendungen zur Verfügung zu stellen, müssen die Services durch ein sogenanntes Service-Gateway exportiert werden.

Das Dokument gliedert sich wie folgt:
Im Abschnitt xref:detailkonzept-komponente-service/master.adoc#ueberblick[Überblick] wird kurz beschrieben, wie sich Services als eigene Komponente "Service" in ein IT-System integrieren.
Im Abschnitt xref:detailkonzept-komponente-service/master.adoc#servicelogik[Servicelogik] werden dann  Aufgaben und Aufbau der Servicelogik beschrieben.
Die restlichen Abschnitte widmen sich fortgeschrittenen Aspekten wie xref:detailkonzept-komponente-service/master.adoc#transaktionssteuerung[Transaktionssteuerung], xref:detailkonzept-komponente-service/master.adoc#versionierung[Versionierung] und xref:detailkonzept-komponente-service/master.adoc#verfuegbarkeit[Verfügbarkeit].
// end::inhalt[]
