= Detailkonzept Service: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Entsprechend der Referenzarchitektur (siehe <<IsyFactReferenzarchitektur>>) stellen IT-Systeme Services über die technische Komponente „Service“ zur Verfügung.
Das vorliegende Dokument beschreibt die Aufgaben und die Architektur dieser technischen Komponente.
Zu beachten ist, dass die Komponente „Service“ die Services eines IT-Systems lediglich innerhalb der Systemlandschaft verfügbar macht.
Um diese Services auch externen Anwendungen zur Verfügung zu stellen, müssen die Services durch ein sogenanntes Service-Gateway exportiert werden.
Dies ist jedoch nicht Inhalt des vorliegenden Dokuments, sondern wird im Dokument <<SystemdokumentationServiceGateway>> ausführlich beschrieben.

Das Dokument gliedert sich wie folgt.
In Abschnitt <<ueberblick>> wird kurz beschrieben, wie sich Services als eigene Komponente “Service“ in ein IT-System integrieren.
In Abschnitt <<aufgaben-der-service-logik>> werden dann die Aufgaben der Komponente erläutert und Abschnitt <<aufbau-der-service-logik>> stellt den Standard-Aufbau der Komponente dar.
Die restlichen Abschnitte widmen sich fortgeschrittenen Aspekten wie <<transaktionssteuerung>>, <<versionierung>> und <<verfuegbarkeit>>.
// end::inhalt[]