= Versionierung

Die Notwendigkeit, Services in mehreren Versionen anbieten zu können, ist bedingt durch die Vielzahl an Service-Nutzern, die bei Änderung an einem Service nicht alle zeitgleich auf die neue Version eines Service umschalten können.
Daher ist es notwendig, dass in einem – möglichst klein zu haltenden – Übergangszeitraum mehrere Versionen eines Service parallel betrieben werden können.

Die Versionierung wird auf der Ebene von Services, nicht Service-Operationen ausgeführt, da diese Ebene von ihrer Granularität zu den üblichen fachlichen Änderungen passt.

Es kann vorkommen, dass in _einem_ Systemrelease neue Versionen von _mehreren_ Services ausgeliefert werden.

[[architektur]]
== Architektur

Backends bieten pro Service-Version eine eigene Service-Schnittstelle an.
Die unterschiedlichen Versionen des Services verwenden alle denselben xref:referenzarchitektur:software-technisch/backend/anwendungskern.adoc[Anwendungskern].
Die für die Versionierung notwendigen Transformationen sind Teil der jeweiligen Service-Schnittstelle (z.B. das Einfügen eines Standardwerts für neu hinzugefügte Attribute).
In komplexen Fällen kann es auch notwendig sein, den Anwendungskern zu erweitern und die Versionierung dort zu behandeln.
Die Entscheidung dafür ist im Systementwurf zu dokumentieren.

Externe Services werden durch xref:glossary::terms-definitions.adoc#glossar-service-gateway[Service-Gateways] bereitgestellt.
Die Versionierung eines Services muss also auch auf Ebene des Service-Gateways durchgeführt werden.

****
Ein Service-Gateway ist ein technischer Zugriffspunkt zwischen externen Systemen und internen Services.
Hauptaufgaben können Routing, Security, Lastverteilung und Mapping auf die entsprechenden Service-Schnittstellen der angebundenen Backends sein.
Fachlogik oder komplexe Orchestrierungen finden im Gateway nicht statt.
****

Der Ausgleich der Versionsunterschiede erfolgt ausschließlich im Backend und nicht im Service-Gateway.
Es ist möglich, pro Service-Version ein eigenes Service-Gateway zu erstellen.

[[image-archversServ]]
.Architektur versionierter Services
image::referenzarchitektur:software-technisch/services/versionierung.dn.svg[]

[[abwaertskompatible-erweiterung]]
== Abwärtskompatible Erweiterung eines Services

Ein Backend stellt einen Service bereit, mit dem Personendaten gemeldet werden können.
Parameter dieser Meldung sind Vor- und Nachname sowie das Geburtsdatum.
Dazu gibt es einen Meldung-Service in der Version 1.0.
Dieser wird in der Serviceschicht des Backends implementiert.
Ab einem Stichtag soll zusätzlich noch der Geburtsort gemeldet werden.
Im bisherigen Datenbestand wird dieses neue Attribut auf den Wert "unbekannt" gesetzt.
Der bestehende Service wird um dieses Attribut erweitert und erhält die Versionsnummer 1.1.
Anwendungskern und Persistenzschicht müssen ebenfalls erweitert werden.
Aus Gründen der Rückwärtskompatibilität soll aber weiterhin die Version 1.0 des Service angeboten werden.
Dazu wird ein neuer Service innerhalb der Serviceschicht implementiert, der die Meldung entgegennimmt, das fehlende Attribut mit dem Wert "unbekannt" ergänzt und dann den Anwendungskern aufruft.

Werden die beiden Services durch ein Service-Gateway nach außen verfügbar gemacht, existieren dort zwei parallele Mappings auf die jeweiligen Services des Backends.
Innerhalb des Service-Gateways existiert keine Geschäftslogik, d.h. die Abbildung von Version 1.0 auf 1.1 findet erst im Backend statt.

[[inkompatible-veraenderung]]
== Inkompatible Veränderung eines Services

In einem komplexeren Fall kann es passieren, dass Services von Backends so umgestaltet werden, dass die Aufrufe nicht mehr aufeinander abgebildet werden können.
Wird in so einem Fall ein neuer Service eingeführt, während der alte Service noch verfügbar bleiben muss, müssen die inkompatiblen Verarbeitungslogiken im Anwendungskern parallel unterstützt werden.
Auch hier enthält das Service-Gateway keine Geschäftslogik.

IMPORTANT: Eine Versionierung ist nur dann sinnvoll, wenn kleine Änderungen an der Schnittstelle zwischen den Versionen auftreten.
Für den Fall, dass sich die Schnittstelle sowohl syntaktisch als auch semantisch grundlegend ändert, sollte anstatt einer neuen Version besser eine eigenständige, neue Schnittstelle entstehen.

