= Versionierung

include::documentation-guide::partial$content-revised-page.adoc[]

Die Notwendigkeit, Services in mehreren Versionen anbieten zu können, ist bedingt durch die Vielzahl an Service-Nutzern, die bei Änderung an einem Service nicht alle zeitgleich auf die neue Version eines Service umschalten können.
Daher ist es notwendig, dass in einem – möglichst klein zu haltenden – Übergangszeitraum mehrere Versionen eines Service parallel betrieben werden können.

Die Versionierung wird auf der Ebene von Services, nicht Service-Operationen ausgeführt, da diese Ebene von ihrer Granularität zu den üblichen fachlichen Änderungen passt.

Es kann vorkommen, dass in _einem_ Systemrelease neue Versionen von _mehreren_ Services ausgeliefert werden.

[[abwaertskompatibilitaet]]
== Abwärtskompatibilität

Als Abwärtskompatibilität wird die Verwendbarkeit bzw. Kompatibilität neuerer oder erweiterter Versionen eines Services bzw. einer Nachricht oder eines Events zu den Anwendungsbedingungen einer früheren Version bezeichnet.

NOTE: Diese Definition basiert auf dem Wikipedia-Artikel zur https://de.wikipedia.org/wiki/Kompatibilit%C3%A4t_(Technik)#Abw%C3%A4rtskompatibilit%C3%A4t[Abwärtskompatibilität].

Abwärtskompatibilität ermöglicht Übergangszeiträume, in denen sich die Kommunikationsteilnehmer schrittweise an die Änderungen anpassen können, ohne dass es zu Unterbrechungen oder Fehlern in der Kommunikation kommt.

Die Verantwortung für Änderungen - und damit auch für die Abwärtskompatibilität - liegt in der Regel beim Provider von Services bzw. beim Producer/Publisher von Nachrichten und Events, da diese die Schnittstelle bzw. das Format der Nachrichten und Events definieren und somit für die Consumer festlegen.
Ausnahmen bilden Szenarien, in denen ein Consumer viele Producer/Publisher orchestriert und aus diesem Grund das Format der Nachrichten oder Events vorgibt, zum Beispiel im Bereich Telemetrie oder Protokollierung.

Inkompatible Änderungen (englisch: _breaking changes_) sind dagegen Änderungen an der Schnittstelle eines Services bzw. am Format einer Nachricht oder eines Events, welche die Anwendungsbedingungen einer früheren Version verletzen.
Sie führen zu Fehlern oder Unterbrechungen in der Kommunikation, wenn die Kommunikationsteilnehmer nicht gleichzeitig auf die neue Version wechseln können und sollten daher genau geplant und kommuniziert werden.

=== Abwärtskompatible Änderungen

Die folgenden Beispiele stellen häufig vorkommende, abwärtskompatible Änderungen dar.

[cols="1,2",options="header"]
|===
|Änderungstyp
|Auswirkung auf die Kommunikation

|Optionales Feld hinzufügen
|Die Kommunikationsteilnehmer können das Feld bei Bedarf setzen.

|Neues Feld mit Standardwert hinzufügen
|Die Kommunikationsteilnehmer können das Feld bei Bedarf mit einem eigenen Wert belegen.

|Optionale neue Operation / Nachricht / Event hinzufügen
|Die Kommunikationsteilnehmer können die Operation bei Bedarf aufrufen, bzw. die Nachricht oder das Event produzieren oder konsumieren.
|===

=== Inkompatible Änderungen

Die folgenden Beispiele stellen häufig vorkommende, inkompatible Änderungen (auch: Breaking Changes) dar.

[cols="1,2",options="header"]
|===
|Änderungstyp
|Auswirkung auf die Kommunikation

|Neues Pflichtfeld hinzufügen
|Die Kommunikationsteilnehmer müssen sich anpassen, und das neue Feld setzen.
Eine Übergangsphase mit einer frühzeitigen Einführung des Feldes als optional kann die Auswirkungen dieses Breaking Changes abfedern.

|Feld umbenennen / entfernen
|Die Kommunikationsteilnehmer können Services ggf. nicht mehr nutzen oder keine Nachrichten / Event mehr produzieren oder konsumieren.
Flexible Validierungen und Verarbeitungslogiken können die Auswirkungen eines solchen Breaking Changes abfedern.

|Typ oder Semantik eines Felds ändern
|Werte werden von den Kommunikationsteilnehmern falsch interpretiert oder führen zu Konvertierungsfehlern.
Diese Änderungen sollte vermieden werden, da sie schwer zu kommunizieren und abzufedern ist.
Stattdessen sollte ein neues Feld eingeführt und das alte Feld zu einem späteren Zeitpunkt entfernt werden.
|===


[[architektur]]
== Architektur

Backends bieten pro Service-Version eine eigene Service-Schnittstelle an.
Die unterschiedlichen Versionen des Services verwenden alle denselben xref:referenzarchitektur:software-technisch/backend/anwendungskern.adoc[Anwendungskern].
Die für die Versionierung notwendigen Transformationen sind Teil der jeweiligen Service-Schnittstelle (z.B. das Einfügen eines Standardwerts für neu hinzugefügte Attribute).
In komplexen Fällen kann es auch notwendig sein, den Anwendungskern zu erweitern und die Versionierung dort zu behandeln.
Die Entscheidung dafür ist im Systementwurf zu dokumentieren.

Externe Services werden durch xref:glossary::terms-definitions.adoc#glossar-service-gateway[Service-Gateways] bereitgestellt.
Die Versionierung eines Services muss also auch auf Ebene des Service-Gateways durchgeführt werden.

****
Ein Service-Gateway ist ein technischer Zugriffspunkt zwischen externen Systemen und internen Services.
Hauptaufgaben können Routing, Security, Lastverteilung und Mapping auf die entsprechenden Service-Schnittstellen der angebundenen Backends sein.
Fachlogik oder komplexe Orchestrierungen finden im Gateway nicht statt.
****

Der Ausgleich der Versionsunterschiede erfolgt ausschließlich im Backend und nicht im Service-Gateway.
Es ist möglich, pro Service-Version ein eigenes Service-Gateway zu erstellen.

[[image-archversServ]]
.Architektur versionierter Services
image::referenzarchitektur:software-technisch/services/versionierung.dn.svg[]

[[abwaertskompatible-erweiterung]]
== Abwärtskompatible Erweiterung eines Services

Ein Backend stellt einen Service bereit, mit dem Personendaten gemeldet werden können.
Parameter dieser Meldung sind Vor- und Nachname sowie das Geburtsdatum.
Dazu gibt es einen Meldung-Service in der Version 1.0.
Dieser wird in der Serviceschicht des Backends implementiert.
Ab einem Stichtag soll zusätzlich noch der Geburtsort gemeldet werden.
Im bisherigen Datenbestand wird dieses neue Attribut auf den Wert "unbekannt" gesetzt.
Der bestehende Service wird um dieses Attribut erweitert und erhält die Versionsnummer 1.1.
Anwendungskern und Persistenzschicht müssen ebenfalls erweitert werden.
Aus Gründen der Rückwärtskompatibilität soll aber weiterhin die Version 1.0 des Service angeboten werden.
Dazu wird ein neuer Service innerhalb der Serviceschicht implementiert, der die Meldung entgegennimmt, das fehlende Attribut mit dem Wert "unbekannt" ergänzt und dann den Anwendungskern aufruft.

Werden die beiden Services durch ein Service-Gateway nach außen verfügbar gemacht, existieren dort zwei parallele Mappings auf die jeweiligen Services des Backends.
Innerhalb des Service-Gateways existiert keine Geschäftslogik, d.h. die Abbildung von Version 1.0 auf 1.1 findet erst im Backend statt.

[[inkompatible-veraenderung]]
== Inkompatible Veränderung eines Services

In einem komplexeren Fall kann es passieren, dass Services von Backends so umgestaltet werden, dass die Aufrufe nicht mehr aufeinander abgebildet werden können.
Wird in so einem Fall ein neuer Service eingeführt, während der alte Service noch verfügbar bleiben muss, müssen die inkompatiblen Verarbeitungslogiken im Anwendungskern parallel unterstützt werden.
Auch hier enthält das Service-Gateway keine Geschäftslogik.

IMPORTANT: Eine Versionierung ist nur dann sinnvoll, wenn kleine Änderungen an der Schnittstelle zwischen den Versionen auftreten.
Für den Fall, dass sich die Schnittstelle sowohl syntaktisch als auch semantisch grundlegend ändert, sollte anstatt einer neuen Version besser eine eigenständige, neue Schnittstelle entstehen.

