= Versionierung

include::documentation-guide::partial$content-revised-page.adoc[]

Die Notwendigkeit, Services in mehreren Versionen anbieten zu können, ist bedingt durch die Vielzahl an Service-Nutzern, die bei Änderung an einem Service nicht alle zeitgleich auf die neue Version eines Service umschalten können.
Daher ist es notwendig, dass in einem, wenn möglich, kurz zu haltenden Übergangszeitraum mehrere Versionen eines Service parallel betrieben werden können.

Die Versionierung wird auf der Ebene von Services, nicht Service-Operationen ausgeführt, da diese Ebene von ihrer Granularität zu den üblichen fachlichen Änderungen passt.

Es kann vorkommen, dass in _einem_ Systemrelease neue Versionen von _mehreren_ Services ausgeliefert werden.

IMPORTANT: Eine Version beschreibt die evolutionäre Weiterentwicklung desselben fachlichen Konzepts.
Wird ein anderes fachliches Konzept umgesetzt, ist keine Versionierung, sondern eine neue Schnittstelle erforderlich.

[[abwaertskompatibilitaet]]
== Abwärtskompatibilität

Als Abwärtskompatibilität wird die Verwendbarkeit bzw. Kompatibilität neuerer oder erweiterter Versionen eines Services bzw. einer Nachricht oder eines Events zu den Anwendungsbedingungen einer früheren Version bezeichnet.
Diese liegt vor, wenn bestehende Kommunikationsteilnehmer eine neue Version eines Services, einer Nachricht oder eines Events ohne Anpassung ihres Codes oder ihrer Konfiguration weiterhin korrekt nutzen können

NOTE: Diese Definition basiert auf dem Wikipedia-Artikel zur https://de.wikipedia.org/wiki/Kompatibilit%C3%A4t_(Technik)#Abw%C3%A4rtskompatibilit%C3%A4t[Abwärtskompatibilität].

Abwärtskompatibilität umfasst sowohl technische als auch fachliche Aspekte.
Technische Kompatibilität liegt vor, wenn die Struktur und Datentypen weiterhin verarbeitet werden können.
Fachliche Kompatibilität liegt vor, wenn die Semantik der Daten unverändert bleibt.
Eine Änderung kann technisch kompatibel, aber fachlich inkompatibel sein und stellt in diesem Fall einen Breaking Change dar.
Abwärtskompatibilität ermöglicht Übergangszeiträume, in denen sich die Kommunikationsteilnehmer schrittweise an die Änderungen anpassen können, ohne dass es zu Unterbrechungen oder Fehlern in der Kommunikation kommt.

Die Verantwortung für Änderungen und damit für die Abwärtskompatibilität liegt in der Regel beim Provider von Services bzw. beim Producer/Publisher von Nachrichten und Events, da diese die Schnittstelle bzw. das Format der Nachrichten und Events definieren und somit für die Consumer festlegen.
Ausnahmen bilden Szenarien, in denen ein Consumer viele Producer/Publisher orchestriert und aus diesem Grund das Format der Nachrichten oder Events vorgibt, zum Beispiel im Bereich Telemetrie oder Protokollierung.

Inkompatible Änderungen (englisch: _breaking changes_) sind dagegen Änderungen an der Schnittstelle eines Services bzw. am Format einer Nachricht oder eines Events, welche die Anwendungsbedingungen einer früheren Version verletzen.
Sie führen zu Fehlern oder Unterbrechungen in der Kommunikation, wenn die Kommunikationsteilnehmer nicht gleichzeitig auf die neue Version wechseln können und müssen daher genau geplant und kommuniziert werden.

[[abwaertskompatible-aenderungen]]
=== Abwärtskompatible Änderungen

Für die Gewährleistung von Abwärtskompatibilität wird ein tolerantes Verhalten der Kommunikationsteilnehmer vorausgesetzt:

- Consumer müssen unbekannte Felder ignorieren können.
- Producer dürfen bestehende Felder nicht entfernen oder in ihrer Bedeutung verändern.

Bei asynchroner Kommunikation ist Abwärtskompatibilität dann gegeben, wenn bestehende Consumer Nachrichten oder Events weiterhin verarbeiten können, ohne dass Fehlverhalten entsteht.

Diese Grundsätze gelten auch für synchrone Kommunikation.
Bei asynchroner Kommunikation ist ein tolerantes Verhalten der Consumer zwingend erforderlich, da Producer und Consumer zeitlich und technisch entkoppelt sind.

Bei synchroner Kommunikation wird Abwärtskompatibilität dadurch erreicht, dass bestehende Service-Nutzende neue Versionen ohne Anpassung weiterhin korrekt nutzen können.
Dies setzt insbesondere voraus, dass zusätzliche Felder die Verarbeitung bestehender Clients nicht beeinträchtigen.
Die Schnittstelle muss so gestaltet sein, dass bestehende Clients weiterhin funktionieren.

Die folgenden Beispiele stellen häufig vorkommende, abwärtskompatible Änderungen dar.

[cols="1,2",options="header"]
|===
|Änderungstyp
|Auswirkung auf die Kommunikation

|Optionales Feld hinzufügen
|Die Kommunikationsteilnehmer können das Feld bei Bedarf setzen bzw. berücksichtigen.

|Neues Feld mit Standardwert hinzufügen
|Die Kommunikationsteilnehmer können das Feld bei Bedarf mit einem eigenen Wert belegen bzw. berücksichtigen.

|Optionale neue Operation / Nachricht / Event hinzufügen
|Die Kommunikationsteilnehmer können die Operation bei Bedarf aufrufen, bzw. die Nachricht oder das Event produzieren oder konsumieren.
|Zusätzliche Response-Felder
|Die Kommunikationsteilnehmer können zusätzliche Felder ignorieren, sofern sie diese nicht auswerten.
|===

[[inkompatible-aenderungen]]
=== Inkompatible Änderungen

Die folgenden Beispiele stellen häufig vorkommende, inkompatible Änderungen (Breaking Changes) dar.

[cols="1,2",options="header"]
|===
|Änderungstyp
|Auswirkung auf die Kommunikation

|Neues Pflichtfeld hinzufügen
|Die Kommunikationsteilnehmer müssen das neue Feld verwenden.
Eine Übergangsphase mit einer frühzeitigen Einführung des Feldes als optional kann die Auswirkungen dieses Breaking Changes mindern.

|Feld umbenennen / entfernen
|Die Kommunikationsteilnehmer können Services nicht mehr nutzen oder keine Nachrichten / Event mehr produzieren oder konsumieren.

Flexible Validierungen und Verarbeitungslogiken können die Auswirkungen eines solchen Breaking Changes mindern.

|Typ oder Semantik eines Felds ändern
|Werte werden von den Kommunikationsteilnehmern falsch interpretiert oder führen zu Konvertierungsfehlern, auch wenn die Struktur gleich bleibt.
Diese Änderungen sollten vermieden werden, da sie schwer zu kommunizieren und zu behandeln sind.

Stattdessen sollte ein neues Feld eingeführt und das alte Feld zu einem späteren Zeitpunkt entfernt werden.

|Änderung des Fehlerverhaltens oder von Statuscodes
|Die Kommunikationsteilnehmer können auf unerwartete Fehler reagieren oder bestehende Fehlerbehandlungen greifen nicht mehr.
|===

[[entscheidungsmodell-versionierung]]
== Entscheidungsmodell zur Versionierung

Aufbauend auf der Definition der Abwärtskompatibilität legt die Referenzarchitektur ein verbindliches Entscheidungsmodell für die Versionierung von Services, Nachrichten und Events fest.

Das Entscheidungsmodell beantwortet, wann

- eine bestehende Schnittstelle erweitert werden sollte und wann eine neue Version bereitzustellen ist,
- ein neuer Kanal erforderlich ist und
- ein neues Backend sinnvoll ist.

Die Entscheidung über die Notwendigkeit einer neuen Version ist von ihrer technischen Umsetzung zu trennen.
Eine neue Service-Version bedeutet nicht zwingend eine neue Serviceschnittstelle oder ein neues Backend.
Die Einführung einer neuen Service-Version erzwingt also keine bestimmte technische Realisierungsform.
Sie kann beispielsweise innerhalb derselben Serviceschicht und desselben Backends umgesetzt werden.
In der Regel wird eine neue Service-Version als eigene Serviceschnittstelle innerhalb derselben Serviceschicht realisiert.

=== Entscheidungsregeln
==== Abwärtskompatible Änderungen

Ist eine Änderung abwärtskompatibel, so wird die bestehende Schnittstelle erweitert.
Dies bedeutet:

- keine neue Service-Version,
- kein neuer Kanal,
- kein neues Backend.

Abwärtskompatible Änderungen sollen innerhalb derselben Version weiterentwickelt werden, um unnötige Parallelität und Versionsvielfalt zu vermeiden.

==== Nicht abwärtskompatible Änderungen an synchronen Services
Ist eine Änderung an einem synchronen Service nicht abwärtskompatibel, so ist eine neue Service-Version bereitzustellen.
Die bestehende Version bleibt für einen Übergangszeitraum parallel verfügbar, sofern bestehende Service-Nutzende nicht zeitgleich migriert werden können.

==== Nicht abwärtskompatible Änderungen an Nachrichten und Events
Ist eine Änderung an einer Nachricht oder einem Event nicht abwärtskompatibel, so ist eine neue Version des Formats bereitzustellen.
Können bestehende Consumer mehrere Versionen nicht sicher parallel verarbeiten, ist zusätzlich ein neuer Kanal vorzusehen, zum Beispiel eine eigene Queue, ein eigenes Topic oder ein eigener Event-Typ.
Dieser Kanal ist dann fpr die neue Version der Consumer vorgesehen.
Dies bedeutet: Wenn bestehende Consumer eine geänderte Nachricht oder ein Event nicht mehr korrekt verarbeiten können, dann darf das bestehende Format nicht einfach verändert werden, vielmehr muss ein neues, getrenntes Nachrichtenformat definiert werden.

==== Neues Backend
Ein neues Backend ist nicht die Standardmaßnahme bei Versionierung.
Es ist dann sinnvoll, wenn

- sich die fachliche Verarbeitung zwischen den Versionen nicht mehr mit vertretbarem Aufwand gemeinsam abbilden lässt,
- mehrere inkompatible Versionen langfristig parallel betrieben werden müssen oder
-  nicht-funktionale Anforderungen eine getrennte Bereitstellung erfordern.

In allen anderen Fällen sollen mehrere Versionen durch dasselbe Backend unterstützt werden.

=== Entscheidungsraster

[cols="2,2,4",options="header"]
|===
|Kommunikationsmuster
|Änderungstyp
|Empfohlene Maßnahme

|Synchroner Service
|abwärtskompatibel
|Bestehende Schnittstelle erweitern

|Synchroner Service
|nicht abwärtskompatibel
|Neue Service-Version bereitstellen (In der Regel über eine zusätzliche Service-Schnittstelle realisiert.)

|Nachricht/ Event
|abwärtskompatibel
|Bestehendes Nachrichtenformat/ Event erweitern

|Nachricht/ Event
|nicht abwärtskompatibel
|Neue Version des Event-/ Nachrichtenformats bereitstellen; bei fehlender Parallelverarbeitbarkeit zusätzlicher neuer Kanal
|===

=== Einordnung in die Referenzarchitektur
Gemäß der xref:referenzarchitektur:fachlich.adoc[Referenzarchitektur] der IsyFact werden Versionierungsentscheidungen für synchrone Services in der Regel innerhalb einer Serviceschicht umgesetzt.

Daraus folgen für synchrone Services die folgenden Grundsätze:

- Eine neue Service-Version wird in der Regel als eigene Service-Schnittstelle in der Serviceschicht umgesetzt.
- Verschiedene Service-Versionen verwenden denselben Anwendungskern.
- Versionsspezifische Transformationen erfolgen grundsätzlich in der Service-Schnittstelle des Backends.
- Ein Service-Gateway übernimmt keine Fachlogik zur Behandlung unterschiedlicher Versionen.

[[versionierung-events]]
== Versionierung von Events

Dieses Kapitel beschreibt bewährte Praktiken im Umgang mit Änderungen von Nachrichten in eventbasierten Systemen wie z.B. Kafka.
Nach der Lektüre sollte der Leser in der Lage sein, mithilfe der definierten Entscheidungsmatrix die geeignete Vorgehensweise bei der Versionierung zu finden.

=== Nachrichtenvalidierung

Systeme tauschen Events in einem wohldefinierten Format untereinander aus. Wie die Struktur einer Nachricht konkret aufgebaut ist (Syntax), wird in einem Schema festgehalten. 
Das vereinbarte Schema wird von Producern verwendet, um vor dem Versenden die Nachricht zu validieren.
Der Consumer verwendet es für die Validierung der empfangenen Nachricht (Design by Contract).

Die Verwendung von Schemata stellt die korrekte Kommunikation zwischen den Teilnehmern und damit die Funktion insbesondere von Consumern sicher.

Folgendes Listing in der Definitionssprache https://avro.apache.org[Avro] zeigt, wie das Event `BestellungErstellt` aufgebaut ist.
Darin ist z.B. das Feld `artikelId` als String definiert und ist verpflichtend in den daraus abgeleiteten Events.

[id="listing-schema-bestellung",source,json,reftext="{listing-caption} {listing-number} {counter:listings}"]
.Schema für den Event-Typ `BestellungErstellt` (Version 1)
----
{
  "type": "record",
  "name": "BestellungErstellt",
  "fields": [
    { "name": "artikelId", "type": "string" },
    { "name": "anzahl", "type": "int" }
  ]
}
----
NOTE: Avro wird wegen der leichten Verständlichkeit auch in den Folgebeispielen genutzt.
Die Version wird in Klammern als fortlaufende Ganzzahl zwecks Verweis angegeben.

==== Abwärts- vs. Vorwärtskompatibilität

In Literatur und Dokumentationen kommt es gelegentlich zu Verwechslungen zwischen  Abwärts- und Vorwärtskompatibilität.
Daher im Folgenden eine kurze Definition der beiden zur Abgrenzung.

Ein Schema ist _abwärtskompatibel_, wenn bestehende Consumer unter Verwendung der alten Schema-Version in der Lage sind, Nachrichten korrekt zu verarbeiten, die mit der neuen Schema-Version erzeugt wurden.
Vereinfacht formuliert: alte Consumer können neue Nachrichten lesen.

Ein Schema ist hingegen _vorwärtskompatibel_, wenn aktualisierte Consumer unter Verwendung der neuen Schema-Version in der Lage sind, Nachrichten korrekt zu verarbeiten, die mit der alten Schema-Version erzeugt wurden.
Vereinfacht formuliert: neue Consumer können alte Nachrichten lesen.

== Datenkonsistenz

In Event-basierten Systemen wie Kafka werden Nachrichten in Logdateien in der Regel für einen längeren Zeitraum persistiert (Event-Log).
Daher müssen im Vergleich zu Queue-basierten Systemen Consumer in der Lage sein, auch alte Nachrichten zu lesen, wenn sie wieder eingespielt werden (Replay), etwa beim Eintritt einer neuen Consumer-Group oder Zurücksetzen des Eventstroms (Offset Reset).

Eine standardisierte Schema-Verwaltung spielt für den Erhalt der Datenkonsistenz eine wichtige Rolle.

=== Replay und Idempotenz

Neue Versionen von Events müssen so aufgebaut sein, dass weiterhin ein Verarbeiten von alten Nachrichten (Replay) möglich ist.
Ein Event muss dazu in sich abgeschlossen und vollständig bleiben und es darf nicht von der externen Systemumgebung abhängen.
So wird sichergestellt, dass durch Replay keine fachlichen Inkonsistenzen entstehen.

Bei einer erneuten Nachrichtenzustellung muss die Verarbeitungslogik der neuen Consumer weiterhin Duplikate anhand einer eindeutigen Event-ID erkennen und ignorieren, um Mehrfachverarbeitungen zu vermeiden.

=== Schema Management

Schemata ändern sich fortlaufend mit neuen Anforderungen.
Um Wildwuchs von Versionen zu vermeiden, werden sie an einer zentralen Stelle z.B. Wiki oder git-Repository von Entwicklerteams gemeinsam verwaltet.

In der Praxis hat sich der Einsatz von Schema Registries wie https://www.apicur.io/registry/[Apicurio Registry] oder https://docs.confluent.io/platform/current/schema-registry/index.html[Confluent Schema Registry] bewährt.
Der große Vorteil den Schema Registries mit sich bringen ist die Erkennung von Schemabrüchen während der Schema-Validierung. Damit sind Breaking Changes durch Anpassungen am Schema praktisch ausgeschlossen, weil  nur kompatible Änderungen zugelassen werden.

Die Vorteile von Schema Registries erkauft man sich u.a. durch die gestiegene Komplexität und Aufwände für den Betrieb eines zusätzlichen Systems in der Anwendungslandschaft.

IMPORTANT: Ob Entwicklerteams sich für ein einfaches Schema Management mit Wiki oder einer Schema Registry entscheidet, ist Abwägungssache.
Wichtig ist nur, dafür eine zentrale Stelle zu verwenden, um Schemabrüche und Versionswildwuchs zu vermeiden.

=== Schema Evolution vs. Schemabruch

In den meisten Fällen handelt es sich bei den Änderungen an Event-Typen um <<abwaertskompatible-aenderungen,abwärtskompatible Änderungen>>.
Kommt beispielsweise das optionale Feld `kommentar` zur <<listing-schema-bestellung,Version 1>> des Event-Typs `BestellungErstellt` hinzu, entsteht eine <<listing-schema-bestellung-feld-optional,neue Version>> aber kein neuer Event-Typ.
Eine fortschreitende Versionierung von Event-Typen, die im Rahmen der Kompatibilität bleibt, wird als Schema Evolution bezeichnet.

Im Beispiel verwenden alte Consumer das Schema in der <<listing-schema-bestellung,Version 1>> beim Lesen von Nachrichten. Nachrichten, welche mit der <<listing-schema-bestellung-feld-optional,Version 2>> erzeugt wurden, enthalten zusätzlich das Feld `kommentar`.
Da der alte Consumer dieses nicht kennt, wird es einfach ignoriert und die Verarbeitung geht normal weiter.

In Nachrichten, die mit der alten Schema-Version erzeugt wurden, fehlt das Feld `kommentar`.
Das ist aber für neue Consumer kein Problem, da es optional ist und einfach mit dem Wert `null` belegt wird.

[id="listing-schema-bestellung-feld-optional",source,json,reftext="{listing-caption} {listing-number} {counter:listings}"]
.Schema für den Event-Typ `BestellungErstellt` mit optionalem Kommentarfeld (Version 2)
----
{
  "type": "record",
  "name": "BestellungErstellt",
  "fields": [
    { "name": "artikelId", "type": "string" },
    { "name": "anzahl", "type": "int" },
    { "name": "kommentar", "type": ["null" ,"string"], "default": null }
  ]
}
----

In Fällen bei denen Änderungen zum Bruch der Kompatibilität führen (<<abwaertskompatibilitaet,Breaking Change>>) reicht eine neue Schema-Version nicht mehr aus, d.h. es liegt ein Schemabruch vor.
Als Folge muss ein neues Schema für einen neuen Event-Typ erstellt werden.

Im <<listing-schema-bestellung,Beispiel-Event `BestellungErstellt`>> könnte ein neues Pflichtfeld `preis` dazukommen. Bei fortschreitender Versionierung könnten neue Consumer neue Nachrichten zwar lesen, aber bei den alten Nachrichten würde der Preis fehlen und der Consumer wüsste nicht, welcher Wert gemeint ist. Deswegen gibt es ein neues Schema für den Event-Typ `BestellungMitPreisErstellt`.

WARNING: Im Falle von Breaking Changes wird dringend empfohlen, für das neue Schema auf generische Namen wie "BestellungErstelltV1" zu verzichten, um eine Vermischung von verschiedenen Versionskonzepten zu vermeiden, insbesondere wenn fortschreitende Versionen manuell z.B. über Header gesetzt werden.

[id="listing-schema-bestellung-pflichtfeld-dazu",source,json,reftext="{listing-caption} {listing-number} {counter:listings}"]
.Schema für den neuen Event-Typ `BestellungMitPreisErstellt` mit neuem Pflichtfeld (Version 1)
----
{
  "type": "record",
  "name": "BestellungMitPreisErstellt",
  "fields": [
    { "name": "artikelId", "type": "string" },
    { "name": "anzahl", "type": "int" },
    { "name": "preis", "type": "float" }
  ]
}
----

=== Fachliche Änderungen

Die in diesem Kapitel bisher besprochenen Änderungen sind technischer Natur und können durch syntaktische Prüfung gegen das zugehörige Schema erkannt werden.
Fachliche Änderungen beeinflussen die Semantik und können nicht automatisch erkannt werden.

Der Event-Typ <<listing-schema-bestellung,`BestellungErstellt`>> hätte innerhalb der Bestandsverwaltung eine ganz andere Bedeutung als ursprünglich im Bestellsystem vorgesehen, wenn auch die Syntax dieselbe ist.
Statt den Bestand zu aktualisieren, würden Consumer weiterhin einen Versand von Artikeln auslösen, d.h. die Verarbeitungslogik wäre aus fachlicher Sicht falsch implementiert.
Die Semantik kann sich genauso auf feingranularer auf Feldebene ändern, die Auswirkungen sind dieselben.

Fachliche Änderungen führen in der Regel immer zu Breaking Changes. Im letzten Beispiel kann das Schema <<listing-schema-bestellung,`BestellungErstellt`>> durch Kopieren unter einem anderen Namen (z.B. `LieferungEingetroffen`) "wiederverwendet" werden, allerdings werden damit  neuartige Events erzeugt, die eine passende Verarbeitungslogik in den neuen Consumern erfordern.

=== Entscheidungsmatrix neuer Event-Typ vs. Versionierung

Folgende Tabelle führt als Entscheidungshilfe auf, wann ein neuer Event-Typ in Abhängigkeit der Änderung nötig ist oder eine neue Version ausreicht.

.Entscheidungsmatrix neuer Event-Typ nötig
|===
|Änderung | Abwärtskompatibel | Konsequenz

| fachlich | egal | neuer Event-Typ
| technisch | nein | neuer Event-Typ
| technische | ja | neue Version (Schema Evolution)

|===

Folgende Aussagen treffen zu:

- Fachliche Änderungen erfordern immer einen neuen Event-Typ
- Breaking Changes erfordern immer einen neuen Event-Typ
- Nur kompatible technische Änderungen können mit Schema Evolution versioniert werden

[[architektur]]
== Architektur

Die in <<entscheidungsmodell-versionierung>> beschriebenen Entscheidungen werden für synchrone Services in der Referenzarchitektur der IsyFact in der Regel innerhalb einer Service-Schicht umgesetzt.

Erfordert eine nicht abwärtskompatible Änderung eine neue Service-Version, so wird diese im Regelfall als eigene Service-Schnittstelle in der Serviceschicht des Backends bereitgestellt.
Mehrere Service-Versionen können dabei denselben xref:referenzarchitektur:software-technisch/backend/anwendungskern.adoc[Anwendungskern] verwenden, sofern sich die fachliche Verarbeitung mit vertretbarem Aufwand gemeinsam abbilden lässt.

Die für die Versionierung notwendigen Transformationen sind Teil der jeweiligen Service-Schnittstelle.
Hierzu gehören insbesondere das Ergänzen von Standardwerten, die Abbildung unterschiedlicher Datenstrukturen sowie die Behandlung versionsspezifischer Unterschiede.
Fachlogik des Anwendungskerns soll dabei nicht dupliziert werden.

Eine Trennung innerhalb des Anwendungskerns oder die Bereitstellung eines eigenen Backends kann sinnvoll sein, wenn sich die fachliche Semantik zwischen den Versionen wesentlich unterscheidet, mehrere inkompatible Verarbeitungslogiken langfristig parallel unterstützt werden müssen oder die gemeinsame Realisierung zu unverhältnismäßig ist.

Die Entscheidung hierfür ist im Systementwurf zu dokumentieren.

Externe Services werden durch xref:glossary::terms-definitions.adoc#glossar-service-gateway[Service-Gateways] bereitgestellt.

****
Ein Service-Gateway ist ein technischer Zugriffspunkt zwischen externen Systemen und internen Services.
Fachlogik oder komplexe Orchestrierungen finden im Gateway nicht statt.
Die Behandlung von Versionsunterschieden erfolgt daher grundsätzlich im Backend und nicht im Service-Gateway.
****

Es ist möglich, pro Service-Version ein eigenes Service-Gateway zu erstellen, sofern dies aus technischen oder betrieblichen Gründen erforderlich ist.

NOTE: Für den Standardfall einer nicht abwärtskompatible Änderung, bei gleichbleibender fachlicher Logik, die kein neues Backend erforderlich macht, ergibt sich folgende Architektur:

[[image-archversServ]]
.Standardfall für die Architektur versionierter Services
image::referenzarchitektur:software-technisch/services/versionierung.dn.svg[]

[[abwaertskompatible-erweiterung]]
== Abwärtskompatible Erweiterung eines Services

Ein Backend stellt einen Service bereit, mit dem Personendaten gemeldet werden können.
Parameter dieser Meldung sind Vor- und Nachname sowie das Geburtsdatum.
Dazu gibt es einen Meldung-Service in der Version 1.0.
Dieser wird in der Serviceschicht des Backends implementiert.
Ab einem Stichtag soll zusätzlich noch der Geburtsort gemeldet werden.
Im bisherigen Datenbestand wird dieses neue Attribut auf den Wert "unbekannt" gesetzt.
Der bestehende Service wird um dieses Attribut erweitert.
Da es sich um eine abwärtskompatible Änderung handelt, bleibt es bei derselben Service-Version.
Anwendungskern und Persistenzschicht müssen ebenfalls erweitert werden.

Die Serviceschicht stellt sicher, dass Aufrufe ohne Angabe des Geburtsorts weiterhin korrekt verarbeitet werden können, indem für das fehlende Attribut der Wert "unbekannt" ergänzt wird.

Werden die beiden Services durch ein Service-Gateway nach außen verfügbar gemacht, existieren dort zwei parallele Mappings auf die jeweiligen Services des Backends.
Innerhalb des Service-Gateways existiert keine Geschäftslogik, d.h. die Abbildung von Version 1.0 auf 1.1 findet erst im Backend statt.

[[inkompatible-veraenderung]]
== Inkompatible Veränderung eines Services

Ist eine Änderung an einem Service nicht abwärtskompatibel, ist gemäß dem <<entscheidungsmodell-versionierung>> eine neue Service-Version bereitzustellen.
Kann die neue Version mit vertretbarem Aufwand auf dieselbe fachliche Verarbeitung abgebildet werden, so können mehrere Service-Versionen denselben Anwendungskern nutzen.
In diesem Fall enthält die Serviceschicht für jede Version eine eigene Service-Schnittstelle mit der jeweils erforderlichen Transformationslogik.

Wird in so einem Fall ein neuer Service eingeführt, während der alte Service noch verfügbar bleiben muss, müssen die inkompatiblen Verarbeitungslogiken im Anwendungskern parallel unterstützt werden.
Bei starken fachlichen oder technischen Unterschieden kann es sinnvoll sein, die neue Version in einem eigenen Backend bereitzustellen.
Auch in diesem Fall enthält das Service-Gateway keine Fachlogik.

IMPORTANT: Eine neue Version ist dann erforderlich, wenn eine Änderung nicht abwärtskompatibel ist und bestehende Nutzende nicht ohne Anpassung weiterarbeiten können.

Führen Änderungen zu einer wesentlichen fachlichen Neuauslegeung der Schnittstelle, soll keine weitere Version derselben Schnittstelle entstehen.
In diesem Fall ist zu prüfen, ob es sich fachlich noch um dasselbe Konzept handelt.
Wenn Versionen nicht mehr durch einfache Transformation verbunden werden können, handelt es sich nicht mehr um Versionen desselben fachlichen Konzepts, sondern die Einführung eines neuen fachlichen Konzepts.
In diesem Fall ist zu prüfen, ob eine eigenständige neue Schnittstelle oder ein eigenes Backend die fachlich und technisch sauberere Lösung darstellt.


