// tag::inhalt[]

[[anhang]]
== Anhang

[[glossar]]
=== Glossar

_Das Glossar definiert die wichtigen fachlichen und technischen Begriffe und Abkürzungen des Projekts.
Zudem werden häufig verwendete fremdsprachige Begriffe übersetzt und erläutert.
Das Glossar klärt somit Begriffsbedeutungen und beugt Missverständnissen vor.
Es erleichtert das gemeinsame Verständnis von Fachlichkeit und Technik, sowie die Einarbeitung der Projektbeteiligten.
Schließlich etabliert das Glossar eine gemeinsame Sprache aller Projektbeteiligten, sowohl im Entwicklungsprojekt wie auch auf Kundenseite._

_Beispielhaft ein Glossar zu den in diesem Dokument verwendeten Begriffen:_

[[table-glossar]]
[cols="1,1,2e,1", options="header"]
|===
|Begriff |Kategorie |Erläuterung |Synonym(e) oder Übersetzung(en)
|_Anwendungskomponente_ |_Architektur_ |Eine Anwendungskomponente beschreibt eine Menge funktional zusammenhängender Anwendungsfälle. |
|_Anwendungslandschaft_ |_Architektur_ |Die Anwendungslandschaft einer Organisation ist bestimmt durch die Menge der von der Organisationseinheit betriebenen Anwendungen. |
|_Anwendung_ |_Architektur_ |
include::glossary::terms-definitions.adoc[tag="anwendung-definition"]
|
|_Attribut_ |_Daten_ |Als „Attribut“ versteht man eine dem Entitätstyp zugeordnete Information. |
|_Entität_ |_Daten_ |Als Entität wird ein eindeutig zu bestimmendes Objekt bezeichnet, dem Informationen zugeordnet werden.
Die Objekte können materiell oder immateriell sein. |_Informationsobjekt, Objekt_
|_Entitätstyp_ |_Daten_ |Jede Entität (das einzelne Objekt) wird einem Entitätstyp zugeordnet.
Entitäten sind konkrete Ausprägungen eines Entitätstyps. |_Klasse_
|_Fachlicher Datentyp_ |_Daten_ |
Ein fachlicher Datentyp beschreibt das Format und den Wertebereich eines Nachbarsystemschnittstellen-Attributs.
Die Namen der fachlichen Datentypen beginnen mit dem Präfix +„DTY_“+.

Datentypen, die eine Liste von Schlüsselwertpaaren repräsentieren, heißen Aufzählungstypen.
Namen von Aufzählungstypen beginnen mit dem Präfix +„DTY_“+ und enden mit dem Suffix „Code“.

|_Datentyp_
|_Nachbarsystem_ |_Architektur_ |Ein externes System, mit dem über eine Schnittstelle kommuniziert wird. |
|_Nachbarsystemschnittstelle_ |_Architektur_ |Die Nachbarsystemschnittstelle eines Systems ermöglicht es anderen Systemen, Daten mit diesem zu einem bestimmten fachlichen Zweck auszutauschen.
Die Namen von Nachbarsystemschnittstellen sind in der fachlichen Schnittstellenbeschreibung durch den Präfix +"NST_"+ gekennzeichnet. |_Schnittstellen_
|_Nachbarsystemschnittstellen-Attribut_ |_Daten_ |Ein Nachbarsystemschnittstellen-Attribut entspricht einer einzelnen fachlichen Information, die über die Nachbar­systemschnittstelle ausgetauscht wird.
Die Namen der Nachbarsystemschnittstellen-Attribute beginnen mit dem Präfix +„NSA_“+.
Zum Beispiel enthält das Attribut NSA_Staat der Entität NSE_Geburtsort den Staat des Geburtsorts. |
|_Nachbarsystemschnittstellen-Entitätstyp_ |_Daten_ |Nachbarsystemschnittstellen-Entitätstypen gruppieren einzelne, fachliche Attribute der Nachbarsystem-schnittstelle.
Nachbarsystemschnittstellen-Entitäten sind konkrete Ausprägungen eines Entitätstyps.
Die Namen der Nachbarsystemschnittstellen-Entitätstypen beginnen mit dem Präfix +"NSE_“+. |
|_Projekt_ |_Vorgehen_ |Ein Projekt ist ein Vorhaben, bei dem innerhalb einer definierten Zeitspanne ein definiertes Ziel erreicht werden soll, und das sich dadurch auszeichnet, dass es im Wesentlichen ein einmaliges Vorhaben ist. |_IT-Projekt_
|_Protokollierung_ |_Nichtfunktionale Anforderungen_ |
Die Protokollierung erfasst Informationen zu fachlichen Abläufen, um diese zu einem späteren Zeitpunkt nachvollziehbar zu machen.

Es handelt sich nicht um Logging!

|
|_UML-Klassendiagramm_ |_Methodik_ |Ein Klassendiagramm ist in der Informatik eine grafische Darstellung von Entitätstypen sowie der Assoziationen zwischen diesen Entitätstypen. |
|_UML-Komponenten­diagramm_ |_Methodik_ |Das Komponentendiagramm ist ein Strukturdiagramm.
Es zeigt eine bestimmte Sicht auf die Struktur der modellierten Anwendung. |
|Unified Modelling Language (UML)_ |_Methodik_ |Die Unified Modeling Language (UML) ist eine von der Object Management Group (OMG) entwickelte und standardisierte Sprache für die Modellierung von Software und anderen Anwendungen. |
|===

[[fehlercodes-fehlertexte]]
=== Fehlercodes und Fehlertexte

_In diesem Kapitel werden alle Fehlercodes und dazugehörige Fehlertexte aufgelistet, die die Schnittstellen zurückliefern können._

In der folgenden Tabelle sind alle Fehlercodes mit den zugehörigen Fehlertexten als Nachschlagewerk aufgelistet.

[[table-fehlercode-fehlertext]]
[cols="1,1", options="header"]
|===
|*Fehlercode* |*Fehlertext*
|_ABCXY0123_ |_Die Anfrage konnte nicht verarbeitet werden, da die Anfragenachricht nicht vollständig ist.
Es fehlt: Organisation._
| |
| |

|===

[[weiterfuehrende-dokumente]]
=== Weiterführende Dokumente

_Liste mit Referenzen auf weiterführende Dokumentation._

[[table-weiterfuehrende-dokumentation]]
[cols="1,1,1", options="header"]
|===
|*Kürzel* |*Beschreibung* |*Ablage*
|_[Kürzel]_ |_Eine Beschreibung des Dokuments_ |_Verweis auf den Ablageort des Dokuments, z.B. eine URL._
|===


// end::inhalt[]
