= Verwendung von Spring Boot

include::documentation-guide::partial$licence.adoc[]

Spring und das auf ihm basierende Spring Boot sind leichtgewichtige, Java-basierte Anwendungsframeworks.
Sie implementieren Konzepte wie https://en.wikipedia.org/wiki/Inversion_of_control[Inversion of Control (IoC)], https://en.wikipedia.org/wiki/Dependency_injection[Dependency Injection (DI)] und zahlreiche, häufig benötigte Funktionen, um die Entwicklung von Anwendungen zu beschleunigen.

_Spring Beans_ sind Java-Objekte (POJOs), die durch den https://docs.spring.io/spring-framework/reference/core/beans.html[IoC Container] von Spring instanziiert und verwaltet werden.
Der IoC Container erstellt Spring Beans anhand einer Bean-Definition in Form von Annotationen.

Die folgenden Inhalte beschreiben die allgemeine Nutzung von Spring und Spring Boot für die Umsetzung von Backends und Batches.
Die Nutzung spezifischer Features sind Bestandteile der folgenden Bausteine:

* Konfiguration der Persistenzschicht: beschrieben in den xref:isy-persistence:nutzungsvorgaben/umsetzung-persistenzschicht.adoc[Nutzungsvorgaben JPA/Hibernate],
* Konfiguration des Logging: beschrieben in den xref:isy-logging:nutzungsvorgaben/master.adoc[],
* Bereitstellung von Metriken zur Überwachung: beschrieben im xref:isy-ueberwachung:konzept/master.adoc[].

[[konfiguration]]
== Vorgaben zur Konfiguration
Das Prinzip _Convention over Configuration_ in Spring Boot vereinfacht die Einrichtung und Entwicklung durch sinnvolle Voreinstellungen.

https://docs.spring.io/spring-boot/reference/using/build-systems.html#using.build-systems.starters[Starter POMs]:: Vereinfachte Verwaltung von Abhängigkeiten.

https://docs.spring.io/spring-boot/reference/using/auto-configuration.html[Auto-Konfiguration]:: Automatische Konfiguration auf der Grundlage der hinzugefügten Abhängigkeiten.

https://docs.spring.io/spring-boot/how-to/properties-and-configuration.html[Konfiguration]:: Externalisierte Konfigurationsdateien in Form von Properties oder YAML.

https://docs.spring.io/spring-boot/how-to/webserver.html[Eingebetteter Server]:: Eingebetteter Server (u.a. Tomcat) ohne explizite Einrichtung für die Entwicklung.

[[Konfiguration-der-Applikationsklasse]]
=== Konfiguration der Applikationsklasse

Der zentrale Ausgangspunkt für die Spring-Konfiguration ist die Applikationsklasse.

Diese wird im Package des Backends oder Batches (`<org>.<domäne>.<anwendung>.<it-system>`) erstellt.

Die Annotation `@SpringBootApplication` markiert eine Konfigurationsklasse, die eine oder mehrere `@Bean`-Methoden deklariert und außerdem die automatische Konfiguration und das Scannen von Komponenten auslöst.
Die Klasse `SpringApplication` startet eine Spring-Anwendung aus einer Java-Hauptmethode heraus.
Sie erstellt automatisch den https://docs.spring.io/spring-framework/reference/core/beans/context-introduction.html[Application Context] aus dem Klassenpfad, scannt die Konfigurationsklassen und startet schließlich die Anwendung.

[[listing-applikationsklasse]]
.Applikationsklasse eines Backends
[source, java]
----
package de.organisation.bsp.backend;

@SpringBootApplication //<.>
public class BspBackend {

    public static void main(String[] args) {
		SpringApplication.run(BspBackend.class, args);
	}

}
----
<1> Äquivalent zur gleichzeitigen Nutzung von `@SpringBootConfiguration`, `@EnableAutoConfiguration` und `@ComponentScan`.

Ist eine feinere Kontrolle gewünscht, so können mit `exclude`-Attributen Komponenten von der automatischen Konfiguration https://docs.spring.io/spring-boot/reference/using/auto-configuration.html#using.auto-configuration.disabling-specific[ausgeschlossen] werden.

Für ein Deployment in einem Servlet-Container muss die Applikationsklasse wie im <<listing-applikationsklasse-servlet,folgenden Listing>> aussehen.

[[listing-applikationsklasse-servlet]]
.Applikationsklasse eines Backends (Servlet-Container)
[source, java]
----
package de.organisation.bsp.backend;

@SpringBootApplication
public class BspBackend extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(BspBackend.class);
	}

}
----

NOTE: Sind mehrere Optionen zum Deployment gewünscht, können die Ansätze https://docs.spring.io/spring-boot/how-to/deployment/traditional-deployment.html#howto.traditional-deployment.convert-existing-application[kombiniert] werden.

=== Konfiguration von Schichten

Für jede xref:software-technisch/backend.adoc#systemarchitektur-backend[Schicht] wird im Package der Schicht (`<org>.<domäne>.<anwendung>.<it-system>.<schicht>`) parallel zu den Interfaces der Komponentenschnittstellen eine mit `@Configuration` annotierte <<listing-konfigurationsklasse,Konfigurationsklasse>> erstellt.
Externe Klassen, die keine Spring-Annotationen besitzen, werden in der Konfigurationsklasse der Schicht per `@Bean`-Methoden konfiguriert.


[[listing-konfigurationsklasse]]
.Konfigurationsklasse des Anwendungskerns
[source,java]
----
package de.organisation.bsp.backend.core;

@Configuration
public class CoreConfig {

    @Bean
    public BeispielBean beispielBean() {
        // ...
    }

}
----

[[konfiguration-von-spring-beans]]
=== Konfiguration von Komponenten
Die Spring Beans der Komponenten werden mit der Annotation `@Component` bzw. deren Spezialisierungen (`@Repository`, `@Service`, `@Controller` etc.) versehen.
Die Annotation `@Component` markiert eine Klasse als Spring Bean.
Sie wird für jede Klasse verwendet, die als Spring Bean verwaltet werden soll, unabhängig von ihrer Funktion oder Verantwortung.

TIP: Es ist gute Praxis, spezifische Ableitungen für Komponenten zu verwenden, um Ihre Absicht klarer auszudrücken und die Codebasis besser zu organisieren.


==== Annotation `@Service`
Die Annotation `@Service` ist eine spezielle Form von `@Component`.
Es ist eine semantische Annotation, die verwendet wird, um Klassen zu kennzeichnen, die Geschäftsfunktionen implementieren.

Die xref:software-technisch/backend/anwendungskern.adoc#fachkomponenten[Fachkomponenten des Anwendungskerns] werden mit der Annotation @Service ausgezeichnet.

==== Annotationen `@Controller` und `@RestController`
Die Annotation `@Controller` ist eine Spezialisierung der Annotation `@Component`.
Sie wird typischerweise in Kombination mit annotierten Handler-Methoden verwendet, die auf der Annotation `@RequestMapping` basieren.
Die Annotation `@Controller` kann nur auf Klassen angewendet werden.
Sie wird verwendet, um eine Klasse als Web-Request-Handler zu markieren.
Sie wird meist im Kontext von Spring MVC verwendet.

Die Annotation `@RestController` ist eine "Komfort-Annotation", die selbst mit `@Controller` und `@ResponseBody` annotiert ist.
Diese Annotation wird verwendet, um eine Klasse als Request-Handler für REST-Endpunkte zu kennzeichnen.

Die xref:software-technisch/backend/serviceschicht.adoc#fachkomponenten[Fachkomponenten der Serviceschicht] werden mit den Annotationen `@Controller` und `@RestController` ausgezeichnet.

==== Annotation `@Repository`
Die Annotation `Repository` ist eine Spezialisierung der Annotation `@Component`.
Sie wird verwendet, um anzuzeigen, dass die Klasse einen Mechanismus für Speicherung, Abruf, Suche, Aktualisierung und Löschung von persistenten Objekten bereitstellt.

Die xref:software-technisch/backend/persistenzschicht.adoc#fachkomponenten[Fachkomponenten der Persistenzschicht] werden dieser Annotation ausgezeichnet.

[[bean-scopes]]
=== Spring Bean Scopes

Der Bean Scope definiert den Lebenszyklus und die Sichtbarkeit einer Bean innerhalb eines Backends oder Batches.
Er teilt Spring mit, wie viele Instanzen einer bestimmten Bean erstellt werden sollen und wie lange sie verfügbar sein sollen.

NOTE: Eine genaue Beschreibung der Scopes bietet die https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html[offizielle Spring-Dokumentation].

[[instanziierung-spring-beans-minimieren]]
==== Instanziierung von Spring Beans minimieren

Der Bean Scope ist so zu wählen, dass eine Spring Bean nicht unnötig oft instanziiert wird.
Insbesondere in den Fachkomponenten der xref:software-technisch/backend/persistenzschicht.adoc#fachkomponenten[Persistenzschicht] und des xref:software-technisch/backend/anwendungskern.adoc#fachkomponenten[Anwendungskerns] sind die meisten Spring Beans deswegen https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-singleton[_Singletons_].
In den Fachkomponenten der xref:software-technisch/backend/serviceschicht.adoc#fachkomponenten[Serviceschicht] gibt es hingegen auch Spring Beans, die im Kontext einzelner HTTP-Anfragen existieren.
Sie nutzen den https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-request[_request scope_].


[[dependency-injection]]
== Vorgaben zur Dependency Injection

Dependency Injection ist in Spring so umgesetzt, dass Spring Beans ihre Abhängigkeiten über Konstruktoren oder Setter-Methoden definieren.
Der IoC Container injiziert die passenden Abhängigkeiten während der Erstellung der Spring Beans.

NOTE: Eine genaue Beschreibung der Dependency Injection bietet die https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html[offizielle Spring-Dokumentation].

.icon:university[title=Architekturregel] Verwendung von Dependency Injection
****
Spring Beans nutzen Konstruktor-basierte Dependency Injection für zwingende Abhängigkeiten und Setter-basierte Dependency Injection für optionale Abhängigkeiten.
****

Die Auflösung von Spring Beans geschieht im Normalfall im Zuge der Dependency Injection.
Dabei sind die folgenden Best Practices zu beachten:

* Spring Beans werden bevorzugt anhand ihres Typs anstatt ihres Namens aufgelöst.
Insbesondere gilt dies für das manuelle Auflösen von Spring Beans über den Application Context.
* Spring Beans des gleichen Typs können anhand der https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired-qualifiers.html[Annotation `@Qualifier`] oder von https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/generics-as-qualifiers.html[Generics] voneinander unterschieden werden.


[[spring-aop]]
== Vorgaben zu Spring AOP

https://docs.spring.io/spring-framework/reference/core/aop.html[Spring AOP] ist ein Ansatz, der dabei hilft, übergreifende Belange von fachlichem Code zu trennen.
Beispiele hierfür sind Funktionen, die sich über mehrere Module erstrecken, wie Logging, Sicherheit, Transaktionsmanagement und Ausnahmebehandlung.
Spring und die IsyFact selbst verwenden Spring AOP genau zu diesem Zweck und bieten den auf ihnen basierenden Anwendungen entsprechenden Mehrwert.

.icon:university[title=Architekturregel] Verwendung von Spring AOP
****
IT-Systeme verwenden kein Spring AOP zur Implementierung von Fachkomponenten.
****

Die Nutzung von Funktionen von Spring, Spring Boot und der IsyFact, die auf Spring AOP oder AOP generell beruhen, bleibt davon unberührt.
Ebenso können technische Komponenten Spring AOP nutzen.
