= Vorlage Anforderungsliste

include::glossary:licence:partial$licence.adoc[]

[[vorlage-anforderungsliste]]
== Überblick Vorlage Anforderungsliste

Die Anforderungsliste ist ein Instrument, um die Übersicht und die Nachvollziehbarkeit des Umsetzungsstatus aller Anforderungen an ein System im gesamten Projektlebenszyklus zu erhalten. Die Anforderungsliste beschreibt mit jeder Anforderung eine Eigenschaft, die eine Anwendung haben soll. Dies kann eine bestimmte Funktionalität oder auch eine Anforderung in Hinblick auf die Qualität sein, zum Beispiel die maximale Reaktionszeit bei einer Eingabe. Die Anforderungsliste ist bei ihrer Erstellung und bei jeder Versionierung ein Mittel der Kommunikation zwischen Auftraggeber und Auftragnehmer.

[[download-spezifikation]]
== Download Vorlage Anforderungsliste

An dieser Stelle kann das Dokument _Vorlage Anforderungsliste_ heruntergeladen werden.

xref:methodik:attachment$spezifikation/IsyFact-Vorlage-Anforderungsliste.xlsx[Vorlage Anforderungsliste - Download icon:file-excel-o[]]
