= Kopiervorlage für neue Seiten

include::glossary:licence:partial$licence.adoc[]

Der folgende Quelltext dient als Kopiervorlage für neue Seiten.

[[kopiervorlage]]
.Kopiervorlage für neue Seiten
[source,asciidoc]
....
= Titel der Seite

\include::glossary:licence:partial$licence.adoc[]

// tag::template[]
[[formatierung]]
== Formatierung

Der Quelltext einer Seite bricht gemäß der Regel _one sentence per line_ nach jedem Satz um.

Mehr zu xref:werkzeuge:dokumentation/master.adoc#ein-satz-pro-zeile[Zeilenumbrüchen im Handbuch der Dokumentation].

[[formatierung-verweise]]
=== Verweise

Es folgen Beispiele für seiteninterne Verweise auf eine <<formatierung,Überschrift>>, ein <<beispiel-abbildung>>, ein <<beispiel-tabelle>> oder ein <<beispiel-listing>>.

Verweise auf Seiten innerhalb derselben Dokumentation sind auf drei Ebenen möglich: innerhalb desselben Moduls, zwischen zwei Modulen und zwischen zwei Komponenten.
Verweise enthalten nur die absolut nötigsten Informationen, um das Ziel aufzulösen.

Es folgt ein Beispiel für einen Verweis:

* innerhalb desselben Moduls: xref:kopiervorlage.adoc[],
* zwischen zwei Modulen: xref:einstieg:erste-schritte.adoc[Erste Schritte im Modul "Einstieg"],
* zwischen zwei Komponenten: xref:glossary:glossary:master.adoc[Glossar].

Alle Verweise auf andere Seiten derselben Dokumentation nutzen die Syntax des Xref-Makros von Antora.

[NOTE]
====
Die xref:glossary:literaturextern:inhalt.adoc#litextern-antora-xref-macro-structure[Beschreibung der Struktur des Xref-Makros] zeigt weitere, interessante Anwendungsfälle für diese Art von Verweisen.
====

Externe Verweise werden in einer xref:glossary:literaturextern:inhalt.adoc[zentralen Liste] gepflegt und müssen über diese angesprungen werden.
Ein Beispiel dafür gibt es in dem Admonition Block oberhalb dieses Absatzes.

Verweise auf das xref:glossary:glossary:master.adoc[Glossar] dürfen nur bei der ersten Verwendung eines entsprechenden Begriffs geschehen.
Alle weitere Vorkommen eines Begriffs werden aus Gründen des Leseflusses nicht mit einem Verweis hinterlegt.
Es folgt ein Beispiel für den Eintrag der xref:glossary:glossary:master.adoc#glossar-isyfact[IsyFact] im Glossar.

Mehr zu xref:werkzeuge:dokumentation/master.adoc#querverweise[Verweisen im Handbuch der Dokumentation]. +
{empty} +

[[formatierung-abbildungen]]
=== Abbildungen

[[beispiel-abbildung]]
.Beispiel einer Abbildung
image::einstieg:sf-saeulen.dn.svg[]

Mehr zu xref:werkzeuge:dokumentation/master.adoc#bilder[Abbildungen im Handbuch der Dokumentation].

[[formatierung-tabellen]]
=== Tabellen

[[beispiel-tabelle]]
.Beispiel einer Tabelle
[cols="1s,1,1,1",options="header"]
|===
|Spalte 1|Spalte 2|Spalte 3|Spalte 4

|Zelle 11|Zelle 12|Zelle 13|Zelle 14
|Zelle 21|Zelle 22|Zelle 23|Zelle 24
|Zelle 31|Zelle 32|Zelle 33|Zelle 34
|===

Mehr zu xref:werkzeuge:dokumentation/master.adoc#tabellen[Tabellen im Handbuch der Dokumentation].

[[formatierung-listings]]
=== Listings

[[beispiel-listing]]
.Beispiel eines Listings
[source,java]
----
public class HalloWelt {
    public static void main(String[] args) {
        System.out.println("Hallo Welt");
    }
}
----

Mehr zu xref:werkzeuge:dokumentation/master.adoc#listings[Listings im Handbuch der Dokumentation].

[[formatierung-admonitions]]
=== Admonition Blocks

[NOTE]
====
Optionale Ergänzungen des Textes wie weiterführende Links, Dokumente, Artikel, etc.
====

[TIP]
====
Optionale Inhalte, die eigene Erfahrungswerte (Good / Best Practices, Tipps & Tricks, ...) einbringen.
====

// tag::important[]

[IMPORTANT]
====
Allgemeine Vorgaben der IsyFact.
====

// end::important[]

[WARNING]
====
Typische Fallstricke bei der Nutzung der IsyFact.
====

[CAUTION]
====
Typische Fehler bei der Nutzung der IsyFact.
====

// tag::anwendungsanforderung[]

.icon:cogs[] Anwendungsanforderung: Anforderung
****
Anforderungen an die Entwicklung von Anwendungen und IT-Systemen.
****

// end::anwendungsanforderung[]
// tag::architekturregel[]

.icon:university[] Architekturregel: Vorgabe
****
Regeln für die Architektur von Anwendungen und IT-Systemen.
****

// end::architekturregel[]
// tag::sicherheit[]

.icon:shield[] Sicherheit: Vorgabe
****
Regeln für die Sicherheit von IT-Systemen.
****

// end::sicherheit[]
// tag::styleguide[]

.icon:paint-brush[] Styleguide: Vorgabe
****
Regeln zur Gestaltung von grafischen Oberflächen.
****

// end::styleguide[]

Mehr zu xref:werkzeuge:dokumentation/master.adoc#admonition-blocks[Admonition Blocks im Handbuch der Dokumentation].

// end::template[]
....
