= Seitenvorlage

include::glossary:licence:partial$licence.adoc[]

[TIP]
====
Zum schnellen Anlegen einer neuen Seite steht eine xref:kopiervorlage.adoc[Kopiervorlage] bereit.
====

[[struktur-thema]]
== Struktur eines Themas

*Eine Seite behandelt ein bestimmtes, in sich selbst abgeschlossenes Thema.*
Führt die Beschreibung des Themas zu einer zu langen Seite, sollten einzelne Teilaspekte auf in sich selbst abgeschlossene Seiten ausgelagert werden.
_In sich selbst abgeschlossen_ bedeutet, dass zum grundlegenden Verständnis des Themas selbst (abzüglich der ausgelagerten Teilaspekte) nur die Seite selbst notwendig ist.

[[dateien-thema]]
.Dateiablage eines Themas
----
📄 thema.adoc <.>
📂 thema
  📄 teilaspekt-1.adoc <.>
  📄 teilaspekt-2.adoc
  📂 teilaspekt-2
      📄 teilaspekt-2-1.adoc
      📄 teilaspekt-2-2.adoc
  📄 ...
  📄 teilaspekt-n.adoc
----
<.> Hauptseite eines Themas.
<.> Seite zu einem Teilaspekt des Themas.

Diese Struktur kann rekursiv angewendet werden.
Allerdings ist zu beachten, dass der Navigationsbaum hierdurch schnell unübersichtlich wird.
Daher sollte es maximal zwei Ebenen unterhalb eines Themas geben.

[[navigation-thema]]
.Navigationsbaum eines Themas
----
▼ Thema
    Teilaspekt 1
  ▼ Teilaspekt 2
        Teilaspekt 2-1
        Teilaspekt 2-2
    ...
    Teilaspekt n
----

[[struktur-seite]]
== Struktur einer Seite

*Innerhalb einer Seite sollten nicht mehr als drei Gliederungsebenen benutzt werden.*
Eine tiefere Gliederung deutet darauf hin, dass die Seite:

* zu umfangreich ist und aufgeteilt werden sollte, oder
* dass Inhalte zu fein zerteilt werden.

*Eine Seite enthält keine Beschreibung über sich selbst (z.B. in Form einer Einleitung).*
Das Inhaltsverzeichnis der Seite muss als "roter Faden" durch das Thema führen.

[[struktur-seitentitel]]
=== Seitentitel

Antora zeigt den Seitentitel an drei Stellen an:

* als Überschrift der Seite,
* im Breadcrumb darüber,
* im Navigationsmenü am linken Rand.

*Seitentitel sollten daher so kurz wie möglich und so lang wie nötig sein.*
Ist der Seitentitel für das Navigationsmenü zu lang, sollte in der Navigationsdatei (`nav.adoc`) des Antora-Moduls ein abgekürzter Seitentitel gesetzt werden.

[[struktur-lizenzhinweis]]
=== Lizenzhinweis

Direkt nach dem Seitentitel steht der Lizenzhinweis.
Dieser ist zentral definiert und kann einfach in die Seite eingebettet werden.

 include::glossary:licence:partial$licence.adoc[]

[[struktur-verweise]]
=== Verweise auf andere Seiten

Verweise auf andere Seiten dienen in der Regel einem der folgenden Zwecke:

* Sie verknüpfen Teilaspekte des Themas mit der entsprechenden Seite.
* Sie machen auf Verbindungen zu anderen Themen aufmerksam.
* Sie benennen externe Seiten, die der Vertiefung des Themas dienen.

Verweise sollten mit Bedacht eingesetzt werden.
Zu viele Verweise stören den Lesefluss der Seite und lenken vom eigentlichen Thema ab.
Ein gutes Format für optionale Verweise sind <<formatierung-admonitions>>.

include::kopiervorlage.adoc[tags=template]