= Konzept Sicherheit: Einleitung

// tag::inhalt[]

:linkaktuell: xref:isy-security:konzept/master.adoc[Konzept Security]
include::glossary:miscellaneous:partial$deprecated-baustein.adoc[]

[[einleitung]]
== Einleitung

Sicherheit ist ein zentrales Thema einer jeder  xref:glossary:glossary:master.adoc#glossar-geschaeftsanwendung[Geschäftsanwendung].
Bei der Umsetzung von Geschäftsanwendungen in IT-Systeme werden ein Gutteil der Anforderungen an die Sicherheit durch Maßnahmen der IT-Sicherheit abgedeckt.
Die IsyFact richtet sich beim Thema Sicherheit nach behördlichen Standards sowie De-Facto-Standards aus der Industrie:

* xref:literaturextern:inhalt.adoc#litextern-it-grundschutz-bsi[IT-Grundschutz]
* xref:literaturextern:inhalt.adoc#litextern-owasp[OWASP Top Ten Project]

Dieses Dokument konzentriert sich auf die konzeptionellen Aspekte der Authentifizierung und Autorisierung.
Es sorgt dafür, dass Authentifizierung und Autorisierung in allen IT-Systemen gleichartig umgesetzt wird und grundlegende Anforderungen an die IT-Sicherheit eingehalten werden.
Es richtet sich vor allem an Software-Architekten, die eine Geschäftsanwendung gemäß den Vorgaben der IsyFact absichern müssen und beschreibt, wie und in welchen Teilen eines IT-Systems die Authentifizierung und Autorisierung stattfindet.

Dazu erläutert das Kapitel xref:konzept/master.adoc#prinzipien-der-sicherheitsarchitektur[Prinzipien der Sicherheitsarchitektur] zunächst, wie sich die Sicherheitsarchitektur auf Ebene der Systemlandschaft und auf Ebene eines einzelnen IT-Systems darstellt.

Danach beleuchtet das Kapitel xref:konzept/master.adoc#sicherheitsarchitektur-eines-it-systems[Sicherheitsarchitektur eines IT Systems] die Einbettung des Bausteins Sicherheit in ein konkretes xref:glossary:glossary:master.adoc#glossar-it-system[IT-System].
Zentrale Schnittstellen beschreibt das Kapitel xref:konzept/master.adoc#aussensicht-der-komponente-sicherheit[Aussensicht der Komponente Sicherheit].

Das Kapitel xref:konzept/master.adoc#rollen-und-rechte[Rollen und Rechte] beschreibt dann, wie Rollen und Rechte für eine neue Geschäftsanwendung spezifiziert werden.
// end::inhalt[]
