= Migrationsleitfaden IsyFact {page-component-display-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Für die IsyFact gibt es hiermit drei Versionszweige: IsyFact 1, IsyFact 2 und seit Q1/2023 das neue Major-Release IsyFact 3.0.

Die auf dieser Seite aufgeführten Hinweise sollen IsyFact Anwendungsentwicklern bei der Umstellung einer auf IsyFact 2 basierenden Anwendung auf IsyFact {page-component-display-version} helfen.

[[kapitel-geschaeftsanwendung]]
== Geschäftsanwendung

[[kapitel-bausteine]]
== Bausteine

[[kapitel-batchrahmen]]
=== Batchrahmen

In IsyFact 3.0 wurde mit der Umstellung auf `isy-security` das Detailkonzept zur xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#authentifizierung-und-autorisierung[Authentifizierung und Autorisierung] aktualisiert.
Statt Benutzer, Passwort und BHKNZ muss in der Batch-Konfiguration eine `oauth2ClientRegistrationId` konfiguriert werden (siehe xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#table-CharBatUse[Eigenschaften eines Batchbenutzers])

[[batch-configuration-isy-sicherheit]]
.Batch-Konfiguration zur Verwendung von isy-sicherheit in IsyFact 2
[source,properties]
----
batch.benutzer=TestUser
batch.passwort=TestPasswort
batch.bhknz=TestBHKNZ

# [...]
----

[[batch-configuration-isy-security]]
.Batch-Konfiguration zur Verwendung von isy-security in IsyFact 3
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die Batch-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen Migration von technischen Nutzern zu Confidential Clients den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Batch-Konfiguration mit technischen Nutzer
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe registrationId abgebildet
isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Batch-Konfiguration nach Umstellung von _technischem Nutzer_ auf _technischen Client_
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

Die Bausteine `isy-sicherheit` und `isy-sicherheit-keycloak` werden durch `isy-security` abgelöst.

[[sicherheit-konfiguration]]
==== Konfiguration

Eine Beschreibung der Parameter findet sich in den xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Nutzungsvorgaben Security] und der xref:glossary:literaturextern:inhalt.adoc#litextern-spring-security-properties[Dokumentation von Spring Security].

<<table-sicherheit-konfiguration>> gibt eine Übersicht über die zu ändernden Parameter.
Die `instances[n]` Notation aus den isy-sicherheit-keycloak Properties wird in isy-security nicht länger unterstützt.
Jede Instanz soll durch einen sprechenden und eindeutigen `provider-name` bzw. eine `registration-id` ersetzt werden.

Aus Platzgründen wurde in der ersten Spalte auf das `isy.sicherheit.keycloak` Präfix verzichtet.
Analog wurde bei allen Properties der zweiten Spalte, die mit einem Punkt beginnen, auf das Präfix `spring.security.oauth2.client` verzichtet.

:table-sicherheit-konfiguration: Änderung der Konfigurationsparameter

[id="table-sicherheit-konfiguration",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-konfiguration}
[cols="1,1,1"]
|===
|isy-sicherheit(-keycloak)|isy-security|Bemerkung
|`.auth-server-url`|`.provider.<provider-name>.issuer-uri`| für die Verwendung in Kombination mit einer Spring Client Registration, an den bisherigen Wert wird `/realms/<realm-name>` angehängt
|`.auth-server-url`| `spring.security.resourceserver.jwt.issuer-uri`| für die Verwendung in Kombination mit _@Secured_, an den bisherigen Wert wird `/realms/<realm-name>` angehängt
|`.realm`|-|entfällt, da Teil der `issuer-uri`
|-|`.registration.<registration-id>.provider`|neu, verbindet die Spring Client Registration und Provider Definition
|`.resource`|`.registration.<registration-id>.client-id`|
|`.credentials-secret`|`.registration.<registration-id>.client-secret`|
|-|`.registration.<registration-id>.authorization-grant-type=password`| neu, da ein zusätzlicher OAuth Flow unterstützt wird
|`.bearer-only`|-|entfällt
|`.standard-zertifikat-ou`|`isy.security.oauth2.client.default-certificate-ou`|
|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
|`.default-instance`|-|entfällt
|`.ext-auth-server-url`|-|entfällt
|`.expected-realm-type`|-|entfällt
|`.expected-realm`|-|entfällt
|`.cert-header-name`|-|entfällt
|`.cert-dn-header-name`|-|entfällt
|===

[[sicherheit-annotation-gesichert]]
==== @Gesichert

Die Annotation `@Gesichert` wird ersetzt durch die Spring-Annotation `@Secured`.
Analog wird die Klasse `GesichertInterceptor` abgelöst durch `SecuredInterceptor`.

`@Secured` akzeptiert in `isy-security` nur Parameter, die mit `PRIV_` beginnen.
Beim Abbilden von Rollen auf Rechte wird in `isy-security` das Präfix `PRIV_` automatisch gesetzt.
Dies verdeutlicht die Abgrenzung zu Rollen, für die Spring das Präfix `ROLE_` verwendet.

`@Gesichert("RECHT_A")` muss daher geändert werden zu `@Secured("PRIV_Recht_A")`.

[WARNING]
====
Werden mehrere Rechte an die Annotation übergeben, so sind sie bei `@Gesichert` konjunktiv verknüpft (= alle übergebenen Rechte müssen vorhanden sein).
Bei der Verwendung von `@Secured` sind die übergebenen Rechte hingegen disjunktiv verknüpft (= es genügt, wenn eines der Rechte vorhanden ist).

Um konjunktive Verknüpfungen auch weiterhin umzusetzen, sollte `@PreAuthorize`  verwendet werden.
`@PreAuthorize` ist für die Prüfung eines einzigen Rechtes äquivalent zu `@Secured`, nutzt aber die Spring Expression Language.
Daher sind Ausdrücke möglich wie

[source]
----
@PreAuthorize("hasAuthority('PRIV_Recht_A') and hasAuthority('PRIV_Recht_B')")
----
In `isy-security` ist die Verwendung von `@PreAuthorize` nicht aktiviert.
Falls `@PreAuthorize` verwendet werden soll, muss die Verwendung im aufrufenden Projekt mit der Konfiguration `@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled=true)` erlaubt werden.
Alternativ kann in diesem Fall auch die neuere Annotation `@EnableMethodSecurity` verwendet werden, bei der `prePostEnabled=true` standardmäßig aktiviert ist.
====

[[sicherheit-berechtigungsmanager]]
==== Berechtigungsmanager

Im Interface `Berechtigungsmanager` ändern sich die Rückgabewerte der Methoden `getRechte()` und `getRollen()` zu `Set<String>`.
Grund dafür ist, dass die POJOs `Recht` und `Rolle` abgeschafft und durch `String`-Werte ersetzt wurden.

[[sicherheit-interface-sicherheit]]
==== Interface Sicherheit

Das Interface `Sicherheit` wird abgelöst durch das Interface `Security`.
Folgende Änderungen sind dabei relevant:

* Die Methode `getBerechtigungsManagerUndAuthentifiziere()` wird entfernt und durch zwei neue Methoden im Interface `Security` ersetzt. Die Aufgaben sind hierbei wie folgt verteilt:
** Die Methode `getAuthentifizierungsmanager()` ermöglicht Zugang zum Interface `Authentifizierungsmanager`, über das eine Authentifizierung über Keycloak durchgeführt werden kann.
Nach erfolgreicher Authentifizierung wird das Bearer Token im Spring Security Context hinterlegt (siehe Nutzungsvorgaben zu `Authentifizierungsmanager`).
** Die Methode `getBerechtigungsmanager()` gibt Zugang zum Interface `Berechtigungsmanager`, über das das Bearer Token verarbeitet kann.
Konkret bietet das Interface `Berechtigungsmanager` Methoden an, um Berechtigungen und Rollen abzufragen (siehe xref:isy-security:nutzungsvorgaben/inhalt.adoc#attr-token-abfragen[Nutzungsvorgaben isy-security]).
* Die Methode `leereCache()` entfällt.
* Wie in Abschnitt <<Berechtigungsmanager>> beschrieben, ändert sich der Rückgabewerte der Methode `Set<Rolle>` zu `Set<String>`.

[[sicherheit-annotation-nutzerauth]]
==== @NutzerAuthentifizierung

Die Annotation `@NutzerAuthentifizierung` wird entfernt und durch eine neue Annotation `@Authenticate` ersetzt.

Der Annotation `@Authenticate` wird die Client-Registration-ID eines OAuth2.0-Clients übergeben.
Der entsprechende Client muss dafür gemäß den xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Nutzungsvorgaben Security] konfiguriert sein.
Hierfür werden die `OAuth2ClientProperties` verwendet, sodass bei der Nutzung von `@Authenticate` gegenüber `@NutzerAuthentifizierung` die Notwendigkeit für das
Erstellen der `NutzerAuthentifizierungProperties` entfällt.
Entsprechend muss allerdings die `spring-security-oauth2-client`-Dependency eingebunden sein.

Zusätzliche für die Aktivierung der Annotation notwendige Beans müssen nicht mehr definiert werden,
da diese durch die `IsyOAuth2ClientAutoConfiguration` erstellt werden, solange die Gegebenheiten für die Erstellung von ClientRegistrations vorhanden sind.

Beispiel für die Konfiguration mit `@NutzerAuthentifizierung`:

[source]
----
@NutzerAuthentifizierung(benutzer = "test-benutzer")
----

[source, properties]
----
<property-prefix>.benutzer.test-benutzer.kennung = benutzer-name
<property-prefix>.benutzer.test-benutzer.passwort = super_secret_password
<property-prefix>.benutzer.test-benutzer.bhknz = 123456
----

Beispiel für die Konfiguration mit `@Authenticate`:

[source]
----
@Authenticate(oauth2ClientRegistrationId = "test-client") // fest
----
oder
[source]
----
@Authenticate(oauth2ClientRegistrationId = "${test-project.client-id}") // mit Property-Platzhalter
----

Die Client-ID kann sowohl fest als auch in Form eines Property-Platzhalters an die Annotation gegeben werden.
Beispiele für weitere Schreibweisen sind in den
xref:isy-security:nutzungsvorgaben/master.adoc#annotation-method-auth[Nutzungsvorgaben Security]
// this reference should be resolvable after merging with ISY-83 (adds @Authenticate annotation and documentation)
zu finden.

[source, properties]
----
# Property-Platzhalter
test-project.client-id = test-client

spring.security.oauth2.client.provider.testrealm.issuer-uri = http://localhost:12345/auth/realms/testrealm

spring.security.oauth2.client.registration.test-client.client-id = client-credentials-test-client
spring.security.oauth2.client.registration.test-client.client-secret = super_secret_password
spring.security.oauth2.client.registration.test-client.authorization-grant-type = client_credentials
spring.security.oauth2.client.registration.test-client.provider = testrealm
----

[[sicherheit-accessmanager]]
==== AccessManager und zugehörige Klassen

Das Interface `AccessManager` sowie zugehörige Interfaces entfallen.
Genauer wurden folgende Interfaces entfernt:

[source]
----
de.bund.bva.isyfact.sicherheit.accessmgr.AccessManager
de.bund.bva.isyfact.sicherheit.SicherheitAdmin
de.bund.bva.isyfact.sicherheit.accessmgr.AuthentifizierungsErgebnis
----

[[sicherheit-exceptions]]
==== Exceptions

Die Exceptions aus dem Paket `de.bund.bva.isyfact.sicherheit.common.exception` entfallen.
Sie werden durch Exceptions aus xref:glossary:literaturextern:inhalt.adoc#litextern-spring-security[Spring Security] ersetzt.

Eine Ausnahme davon bildet die Exception

[source]
----
de.bund.bva.isyfact.sicherheit.common.exception.RollenRechteMappingException,
----

die ersetzt wird durch:

[source]
----
de.bund.bva.isyfact.security.xmlparser.RolePrivilegesMappingException
----

[[sicherheit-test-mock]]
==== Mock für Testumgebungen

Der Baustein `isy-security-test` stellt zum Erstellen von (automatisierten) Tests einen OpenId Connect Provider Mock bereit.
Dieser löst den Keycloak Mock aus `isy-sicherheit-keycloak-test` ab.

Die Klassen und Interfaces

[source]
----
de.bund.bva.isyfact.sicherheit.keycloak.test.EmbeddedKeycloakStub
de.bund.bva.isyfact.sicherheit.keycloak.test.KeycloakMockBase
de.bund.bva.isyfact.sicherheit.keycloak.test.EmbeddedKeycloakMock
de.bund.bva.isyfact.sicherheit.keycloak.test.RemoteKeycloakMock
de.bund.bva.isyfact.sicherheit.keycloak.test.RsaKeyGenerator

----

werden ersetzt durch:

[source]
----
de.bund.bva.isyfact.security.test.oidcprovider.EmbeddedOidcProviderStub
de.bund.bva.isyfact.security.test.oidcprovider.OidcProviderMockBase
de.bund.bva.isyfact.security.test.oidcprovider.EmbeddedOidcProviderMock
de.bund.bva.isyfact.security.test.oidcprovider.RemoteOidcProviderMock
de.bund.bva.isyfact.security.test.RsaKeyGenerator
----

Dabei haben sich die Konstruktoren, Felder und Methodensignaturen leicht geändert.

*Konstruktoren*

* Die Konstruktoren haben keinen Parameter vom Typ `RsaKeyGenerator` mehr.
Falls bisher ein Konstruktor verwendet wurde, der als einen der Parameter ein Objekt vom Typ `RsaKeyGenerator` empfängt, kann dieser Parameter bei der Umstellung gestrichen werden.
* Konstruktoren, die bisher zwei Objekte vom `java.security.PrivateKey` und `java.security.PublicKey` empfangen haben, wurden zusammengefasst in einem Objekt vom Typ `java.security.KeyPair`.

*Felder*

Die Änderungen der Felder sind in den nachfolgenden Tabellen beschrieben.
Die Namen der zugehörigen Getter-Methoden wurden angepasst.

:table-sicherheit-test-fields-EmbeddedKeycloakMock: Änderung der Felder in EmbeddedKeycloakMock

[id="table-sicherheit-test-fields-EmbeddedKeycloakMock",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-fields-EmbeddedKeycloakMock}
[cols="1,1"]
|===
|EmbeddedKeycloakMock (IFS 2)|EmbeddedOidcProviderMock (IFS 3)

|`WireMockServer keycloakServer`|`WireMockServer oidcServerStub`
|===

:table-sicherheit-test-fields-EmbeddedKeycloakStub: Änderung der Felder in EmbeddedKeycloakStub

[id="table-sicherheit-test-fields-EmbeddedKeycloakStub",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-fields-EmbeddedKeycloakStub}
[cols="1,1"]
|===
|EmbeddedKeycloakStub (IFS 2)|EmbeddedOidcProviderStub (IFS 3)

|`String realm`|`URI issuer`
|===

*Methodensignaturen*

Die Änderungen der Methodensignaturen sind in den nachfolgenden Tabellen beschrieben.

:table-sicherheit-test-methods-KeycloakMockBase: Änderung der Methodensignaturen in KeycloakMockBase

[id="table-sicherheit-test-methods-KeycloakMockBase",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-methods-KeycloakMockBase}
[cols="2,2,1"]
|===
|KeycloakMockBase (IFS 2)|OidcProviderMockBase (IFS 3)|Änderung

|`addUser(String username, String password, String bhknz, Set<String> roles)`|`addUser(String clientId, String secret, String username, String password, Optional<String> bhknz, Set<String> roles)`|neue Parameter `String clientId` und `String secret`
|===

:table-sicherheit-test-methods-EmbeddedKeycloakStub: Änderung der Methodensignaturen in EmbeddedKeycloakStub

[id="table-sicherheit-test-methods-EmbeddedKeycloakStub",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-methods-EmbeddedKeycloakStub}
[cols="2,2,1"]
|===
|EmbeddedKeycloakStub (IFS 2)|EmbeddedOidcProviderStub (IFS 3)|Änderung

|`public JWK getJwk()`|`public JWKSet getJwkSet()`|geänderter Methodenname und Rückgabetyp
|`public String getRealmKey()`|`public String getPublicKey()` | geänderter Methodenname
|`public String getOIDCConfigResponse(String jwksEndpoint, String tokenEndpoint)` | `public String getOIDCConfigResponse(String jwksEndpoint, String authorizationEndpoint, String tokenEndpoint)` | zusätzlicher Parameter `String authorizationEndpoint`
|`public AccessToken getAccessToken(UUID userId, String userName, Optional<String> bhknz, Set<String> roles)`|`public JwtClaimsSet getAccessToken(UUID userId, String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`, geänderter Rückgabetyp
|`public AccessToken getAccessToken(UUID userId, String userName, Optional<String> bhknz, Set<String> roles, int newTokenLifespan)` | `public JwtClaimsSet getAccessToken(UUID userId, String clientId, String userName, Optional<String> bhknz, Set<String> roles, int newTokenLifespan)` |zusätzlicher Parameter `String clientId`, geänderter Rückgabetyp
|`public String getAccessTokenString(String userName, Optional<String> bhknz, Set<String> roles)`|`public String getAccessTokenString(String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`
|`public String getAccessTokenString(UUID userId, String userName, Optional<String> bhknz, Set<String> roles)`|`public String getAccessTokenString(UUID userId, String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`
|`public String getAccessTokenString(AccessToken token)`|`public String getAccessTokenString(JwtClaimsSet claims)`|geänderter Parametertyp
|`public String getAccessTokenResponse(String userName, Optional<String> bhknz, Set<String> roles)`|`public String getAccessTokenResponse(String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`
|`public String getAccessTokenResponse(AccessToken accessToken)`|`public String getAccessTokenResponse(JwtClaimsSet claims)`|geänderter Parametertyp

|===

[[kapitel-task-scheduler]]
=== Task Scheduler

In IsyFact 3.0 wurden mit der Umstellung auf `isy-security` die Nutzungsvorgaben zur xref:isy-task:nutzungsvorgaben/master.adoc#spring-konfiguration[Authentifizierung von Tasks] aktualisiert.
Statt Benutzer, Passwort und BHKNZ (siehe <<task-properties-isy-sicherheit>>) muss in den Task Properties eine `oauth2ClientRegistrationId` konfiguriert werden (siehe <<task-properties-isy-security>>).

[[task-properties-isy-sicherheit]]
.Properties mit isy-sicherheit in IsyFact 2
[source,properties]
----
isy.task.tasks.halloWeltTask.benutzer=TestUser
isy.task.tasks.halloWeltTask.passwort=TestPasswort
isy.task.tasks.halloWeltTask.bhkz=TestBHKNZ

# [...]
----

[[task-properties-isy-security]]
.Properties mit isy-security in IsyFact 3
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[ Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die TaskScheduler-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen User-Migration von einem _natürlichen User_ auf ein _technischen Nutzer_ den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Properties mit technischem Nutzer
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe oauth2ClientRegistrationId abgebildet

isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Properties nach Umstellung von _technischem Nutzer_ auf _technischen Client_
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

[[kapitel-service, Bausteine/Service]]
=== Service

[WARNING]
====
Ab IsyFact 3 ist die *Verwendung von REST-Schnittstellen* für die Neuentwicklung verbindlich.
Spring HTTP-Invoker ist deprecated und wird ab sofort als Schnittstellenformat durch REST abgelöst.
Die Verwendung von REST-Schnittstellen wird im Baustein REST (siehe xref:isy-service-rest:konzept/master.adoc[] und xref:isy-service-rest:nutzungsvorgaben/master.adoc[]) erläutert.
====

[WARNING]
====
Mit der Verwendung von `isy-security` in der IsyFact 3 wird standardmäßig anstelle von IsyFacts `AufrufKontext` Springs `SecurityContext` verwendet.

Damit dennoch alte HTTP-Invoker Schnittstellen aufgerufen werden können (welche einen gefüllten AufrufKontext benötigen), wird eine spezielle `RemoteInvocationFactory` eingesetzt, welche Springs `SecurityContext` in ein `AufrufKontextTo` ad hoc per Request umwandelt.

Weitere Informationen können unter
xref:isy-serviceapi-core:nutzungsvorgaben/inhalt.adoc#kompatibilitaet_if1_2_3[Nutzungsvorgaben HTTP-Invoker] nachgelesen werden.
====

[[kapitel-sicherheit]]
=== Sicherheit


[[kapitel-dokumentation]]
== Dokumentation

[[kapitel-frondend-technologien]]
=== Frontend Technologien

[[kapitel-isyfact-Referenzarchitektur]]
=== IsyFact Referenzarchitektur


