= Migrationsleitfaden IsyFact {page-component-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Für die IsyFact gibt es hiermit drei Versionszweige: IsyFact 1, IsyFact 2 und seit Q1/2023 das neue Major-Release IsyFact 3.0.

Die auf dieser Seite aufgeführten Hinweise sollen IsyFact Anwendungsentwicklern bei der Umstellung einer auf IsyFact 2 basierenden Anwendung auf IsyFact {page-component-version} helfen.

[[kapitel-geschaeftsanwendung]]
== Geschäftsanwendung

[[kapitel-bridge-module]]
=== Bridge-Module
Die drei in IsyFact 2 eingeführten Bridge-Module

* `isy-serviceapi-core-bridge`
* `isy-serviceapi-sst-bridge`
* `isy-exception-sst-bridge`

entfallen in IsyFact 3.
In einer Anwendung, die bisher Bridge-Module verwendet und auf IsyFact 3 umgestellt werden soll, müssen daher Anpassungen vorgenommen werden.
Die Tabelle <<table-bridge-module>> zeigt für jedes der drei Bridge-Module, durch welches Modul es ersetzt wird.
Dabei ist zu beachten, dass zwei der Ersatzmodule eine Abhängigkeit zu IsyFact-1.x haben.

[[table-bridge-module]]
.Abhängigkeiten in IsyFact 2 vs. IsyFact 3
[cols="1,1",options="header"]
|===
|Abhängigkeit in IsyFact 2 | Abhängigkeit in IsyFact 3

|`isy-serviceapi-core-bridge`|`isy-serviceapi-core`
|`isy-serviceapi-sst-bridge`|`isy-serviceapi-sst`, Version `1.11.1`
|`isy-exception-sst-bridge`|`isy-exception-sst`, Version `1.11.1`
|===


Zudem wird die Klasse
[source]
----
de.bund.bva.isyfact.exception.service.bridge.util.BridgeExceptionMapper
----
ersetzt durch:
[source]
----
de.bund.bva.isyfact.serviceapi.common.exception.ExceptionMapper
----

[[kapitel-ueberwachung]]
=== Überwachung
Es sind die xref:isy-ueberwachung:nutzungsvorgaben/master.adoc[] zu IsyFact 3 zu verwenden.

[[kapitel-bausteine]]
== Bausteine

[[kapitel-aufrufkontext]]
=== Aufrufkontext
[WARNING]
====
Der Baustein `isy-aufrufkontext` ist mit der Version 3.1 als deprecated gekennzeichnet und wird nicht mehr weiterentwickelt.
Mit der Version 4 wird er endgültig aus dem Projekt entfernt.
====

Mit dem Umstieg auf `isy-security` und der Verwendung von REST Schnittstellen wird `isy-aufrufkontext` nicht länger benötigt.

[[kapitel-konfiguration]]
=== Konfiguration

[WARNING]
====
Der Baustein `isy-konfiguration` ist mit der Version 3.1 als deprecated gekennzeichnet und wird nicht mehr weiterentwickelt.
Mit der Version 4 wird er endgültig aus dem Projekt entfernt.
====

Hintergrund der Deprecation und der Entfernung des Bausteines ist, dass `isy-konfiguration` schon seit IsyFact 2 nicht mehr weiterentwickelt wird und stattdessen von Springframework bereit gestellte Mechanismen genutzt werden sollen.

Die Dokumentation der Konfiguration mit Spring ist unter folgender Adresse zu finden:

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config

[[kapitel-batchrahmen]]
=== Batchrahmen

In IsyFact 3.0 wurde mit der Umstellung auf `isy-security` das Detailkonzept zur xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#authentifizierung-und-autorisierung[Authentifizierung und Autorisierung] aktualisiert.
Statt Benutzer, Passwort und BHKNZ muss in der Batch-Konfiguration eine `oauth2ClientRegistrationId` konfiguriert werden (siehe xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#table-CharBatUse[Eigenschaften eines Batchbenutzers])

[[batch-configuration-isy-sicherheit]]
.Batch-Konfiguration zur Verwendung von isy-sicherheit in IsyFact 2
[source,properties]
----
batch.benutzer=TestUser
batch.passwort=TestPasswort
batch.bhknz=TestBHKNZ

# [...]
----

[[batch-configuration-isy-security]]
.Batch-Konfiguration zur Verwendung von isy-security in IsyFact 3
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die Batch-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen Migration von technischen Nutzern zu Confidential Clients den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Batch-Konfiguration mit technischen Nutzer
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe registrationId abgebildet
isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Batch-Konfiguration nach Umstellung von _technischem Nutzer_ auf _technischen Client_
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

Die Bausteine `isy-sicherheit` und `isy-sicherheit-keycloak` werden durch `isy-security` abgelöst.

[[kapitel-task-scheduler]]
=== Task Scheduler

In IsyFact 3.0 wurden mit der Umstellung auf `isy-security` die Nutzungsvorgaben zur xref:isy-task:nutzungsvorgaben.adoc#absicherung-von-tasks[Authentifizierung von Tasks] aktualisiert.
Statt Benutzer, Passwort und BHKNZ (siehe <<task-properties-isy-sicherheit>>) muss in den Task Properties eine `oauth2ClientRegistrationId` konfiguriert werden (siehe <<task-properties-isy-security>>).

[[task-properties-isy-sicherheit]]
.Properties mit isy-sicherheit in IsyFact 2
[source,properties]
----
isy.task.tasks.halloWeltTask.benutzer=TestUser
isy.task.tasks.halloWeltTask.passwort=TestPasswort
isy.task.tasks.halloWeltTask.bhkz=TestBHKNZ

# [...]
----

[[task-properties-isy-security]]
.Properties mit isy-security in IsyFact 3
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[ Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die TaskScheduler-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen User-Migration von einem _natürlichen User_ auf ein _technischen Nutzer_ den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Properties mit technischem Nutzer
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe oauth2ClientRegistrationId abgebildet

isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Properties nach Umstellung von _technischem Nutzer_ auf _technischen Client_
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

[[kapitel-service, Bausteine/Service]]
=== Service

[WARNING]
====
Ab IsyFact 3 ist die *Verwendung von REST-Schnittstellen* für die Neuentwicklung verbindlich.
Spring HTTP-Invoker ist deprecated und wird ab sofort als Schnittstellenformat durch REST abgelöst.
Die Verwendung von REST-Schnittstellen wird im Baustein REST (siehe xref:isy-service-rest:konzept/master.adoc[] und xref:isy-service-rest:nutzungsvorgaben/master.adoc[]) erläutert.
Desweiteren wurden die Bridge-Module `isy-serviceapi-core-bridge`, `isy-serviceapi-sst-bridge` und `isy-exception-sst-bridge` entfernt.

====

[WARNING]
====
Mit der Verwendung von `isy-security` in der IsyFact 3 wird standardmäßig anstelle von IsyFacts `AufrufKontext` Springs `SecurityContext` verwendet.

Damit dennoch alte HTTP-Invoker Schnittstellen aufgerufen werden können (welche einen gefüllten AufrufKontext benötigen), wird eine spezielle `RemoteInvocationFactory` eingesetzt, welche Springs `SecurityContext` in ein `AufrufKontextTo` ad hoc per Request umwandelt.

Weitere Informationen können unter
xref:isy-serviceapi-core:nutzungsvorgaben/inhalt.adoc#kompatibilitaet_if1_2_3[Nutzungsvorgaben HTTP-Invoker] nachgelesen werden.
====

[[kapitel-sicherheit]]
=== Sicherheit

[[sicherheit-konfiguration]]
==== Konfiguration

Eine Beschreibung der Parameter findet sich in den xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Nutzungsvorgaben Security] und der xref:literaturextern:inhalt.adoc#litextern-spring-security-properties[Dokumentation von Spring Security].

<<table-sicherheit-konfiguration>> gibt eine Übersicht über die zu ändernden Parameter.
Die `instances[n]` Notation aus den isy-sicherheit-keycloak Properties wird in isy-security nicht länger unterstützt.
Jede Instanz soll durch eine sprechende und eindeutige `registration-id` ersetzt werden.
Falls mehrere Instanzen für das gleiche Realm konfiguriert wurden, kann der `provider-name` pro Realm einmalig konfiguriert und für mehrere OAuth 2.0 Client Registrations (`registration-id`) wiederverwendet werden.

[WARNING]
====
Falls Keycloak als Identity Provider verwendet wird, müssen für die Clients zusätzlich ein "Realm Role Mapper", der die Realm-Rollen in den in `isy.security.roles-claim-name` konfigurierten Claim schreibt (Default: `roles`), sowie ein "Audience Mapper",
welcher das `aud`-Claim auf den Namen des verwendeten Clients setzt, konfiguriert werden.
====

Aus Platzgründen wurde in der ersten Spalte auf das `isy.sicherheit.keycloak` Präfix verzichtet.
Analog wurde bei allen Properties der zweiten Spalte, die mit einem Punkt beginnen, auf das Präfix `spring.security.oauth2.client` verzichtet.

:table-sicherheit-konfiguration: Änderung der Konfigurationsparameter

[id="table-sicherheit-konfiguration",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-konfiguration}
[cols="1,1,1"]
|===
|isy-sicherheit(-keycloak) |isy-security |Bemerkung
|`.auth-server-url` |`spring.security.resourceserver.jwt.issuer-uri` |Issuer, gegen den einkommende Bearer Tokens validiert werden sollen. An den bisherigen Wert wird `/realms/<realm-name>` angehängt.
|`.auth-server-url` |`.provider.<provider-name>.issuer-uri` |Für die Verwendung in Kombination mit einer Spring Client Registration. An den bisherigen Wert wird `/realms/<realm-name>` angehängt.
|`.realm` |- |Entfällt, da Teil der `issuer-uri`.
|- |`.registration.<registration-id>.provider` |Neu, verbindet die Spring Client Registration und Provider Definition.
|`.resource` |`.registration.<registration-id>.client-id` |Neu, Authentifizierungsidentifier der _ConfidentialClient_-Applikation im Autorisierungsserver.
|`.credentials-secret` |`.registration.<registration-id>.client-secret` | Neu, Authentifizierungs-Secret, das nur der ConfidentialClient-Anwendung und dem Autorisierungsserver bekannt ist.
|- |`.registration.<registration-id>.authorization-grant-type=password` |Neu, da ein zusätzlicher OAuth Flow unterstützt wird. Der Wert `password` entspricht dem bisherigen Flow in `isy-sicherheit-keycloak`.
|`.bearer-only` |- |entfällt
|`.standard-zertifikat-ou` |`isy.security.oauth2.client.default-certificate-ou` |
|`.bhknz-header-name` |`isy.security.oauth2.client.bhknz-header-name` |
|- |`isy.security.oauth2.registration.<registration-id>.username` |Neu, für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `username`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
|- |`isy.security.oauth2.registration.<registration-id>.password` |Neu,  für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `password`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
|- |`isy.security.oauth2.registration.<registration-id>.bhknz` |Neu, für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `bhknz`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
|`.default-instance` |- |entfällt
|`.ext-auth-server-url` |- |entfällt
|`.expected-realm-type` |- |entfällt
|`.expected-realm` |- |entfällt
|`.cert-header-name` |- |entfällt
|`.cert-dn-header-name` |- |entfällt
|===

[WARNING]
====
Bei der Verwendung von `isy-sicherheit-keycloak` wurde die Absicherung gegen CSRF-Angriffe standardmäßig deaktiviert, da dies den Zugriff auf interne REST- und HTTP-Invoker-Schnittstellen vereinfacht.
Dies ist mit `isy-security` nicht mehr der Fall, weshalb der automatisch von Spring Security konfigurierte CSRF-Filter mglw. deaktiviert werden muss.
====

[[sicherheit-annotation-gesichert]]
==== @Gesichert

Die Annotation `@Gesichert` wird ersetzt durch die Spring-Annotation `@Secured`.
Analog wird die Klasse `GesichertInterceptor` abgelöst durch `SecuredInterceptor`.

`@Secured` akzeptiert in `isy-security` nur Parameter, die mit `PRIV_` beginnen.
Beim Abbilden von Rollen auf Rechte wird in `isy-security` das Präfix `PRIV_` automatisch gesetzt.
Dies verdeutlicht die Abgrenzung zu Rollen, für die Spring das Präfix `ROLE_` verwendet.

`@Gesichert("RECHT_A")` muss daher geändert werden zu `@Secured("PRIV_Recht_A")`.

[WARNING]
====
Werden mehrere Rechte an die Annotation übergeben, so sind sie bei `@Gesichert` konjunktiv verknüpft (= alle übergebenen Rechte müssen vorhanden sein).
Bei der Verwendung von `@Secured` sind die übergebenen Rechte hingegen disjunktiv verknüpft (= es genügt, wenn eines der Rechte vorhanden ist).

Um konjunktive Verknüpfungen auch weiterhin umzusetzen, sollte die Annotation `@PreAuthorize` aus Spring Security verwendet werden.
`@PreAuthorize` ist für die Prüfung eines einzigen Rechtes äquivalent zu `@Secured`, nutzt aber die Spring Expression Language (SpEL).

Dadurch sind Ausdrücke möglich wie

[source,java]
----
@PreAuthorize("hasAuthority('PRIV_Recht_A') and hasAuthority('PRIV_Recht_B')")
----
====

[[sicherheit-berechtigungsmanager]]
==== Berechtigungsmanager

Im Interface `Berechtigungsmanager` ändern sich die Rückgabewerte der Methoden `getRechte()` und `getRollen()` zu `Set<String>`.
Grund dafür ist, dass die POJOs `Recht` und `Rolle` abgeschafft und durch `String`-Werte ersetzt wurden.

[[sicherheit-interface-sicherheit]]
==== Interface Sicherheit

Das Interface `Sicherheit` wird abgelöst durch das Interface `Security`.
Folgende Änderungen sind dabei relevant:

* Die Methode `getBerechtigungsManagerUndAuthentifiziere()` wird entfernt und durch zwei neue Methoden im Interface `Security` ersetzt. Die Aufgaben sind hierbei wie folgt verteilt:
** Die Methode `getAuthentifizierungsmanager()` liefert das Interface `Authentifizierungsmanager` zurück, über dessen Implementierung dann eine Authentifizierung mit dem konfigurierten OpenID Connect Provider (bspw. Keycloak) durchgeführt werden kann.
Nach erfolgreicher Authentifizierung wird das Bearer Token im Spring Security Context hinterlegt (siehe Nutzungsvorgaben zu `Authentifizierungsmanager`).
** Die Methode `getBerechtigungsmanager()` liefert das Interface `Berechtigungsmanager` zurück, über dessen Implementierung dann auf die im _Bearer Token_ enthaltenen _Autorisierungsinformationen_ zugegriffen werden kann.
Konkret sind in dem Interface `Berechtigungsmanager` Methoden definiert, über dessen Implementierung Berechtigungen und Rollen abgefragt werden können (siehe xref:isy-security:nutzungsvorgaben/inhalt.adoc#attr-token-abfragen[Nutzungsvorgaben isy-security]).
* Die Methode `leereCache()` entfällt.
* Wie in Abschnitt <<Berechtigungsmanager>> beschrieben, ändert sich der Rückgabewerte der Methode `Set<Rolle>` zu `Set<String>`.

[[sicherheit-annotation-nutzerauth]]
==== @NutzerAuthentifizierung

Die Annotation `@NutzerAuthentifizierung` wird entfernt und durch eine neue Annotation `@Authenticate` ersetzt.

Der Annotation `@Authenticate` wird die Client-Registration-ID eines OAuth2.0-Clients übergeben.
Der entsprechende Client muss dafür gemäß den xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Nutzungsvorgaben Security] konfiguriert sein.
Hierfür werden die `OAuth2ClientProperties` verwendet, sodass bei der Nutzung von `@Authenticate` gegenüber `@NutzerAuthentifizierung` die Notwendigkeit für das
Erstellen der `NutzerAuthentifizierungProperties` entfällt.
Entsprechend muss allerdings die `spring-security-oauth2-client`-Dependency eingebunden sein.

Zusätzliche für die Aktivierung der Annotation notwendige Beans müssen nicht mehr definiert werden,
da diese durch die `IsyOAuth2ClientAutoConfiguration` erstellt werden, solange die Gegebenheiten für die Erstellung von ClientRegistrations vorhanden sind.

Beispiel für die Konfiguration mit `@NutzerAuthentifizierung`:

[source]
----
@NutzerAuthentifizierung(benutzer = "test-benutzer")
----

[source, properties]
----
<property-prefix>.benutzer.test-benutzer.kennung = benutzer-name
<property-prefix>.benutzer.test-benutzer.passwort = super_secret_password
<property-prefix>.benutzer.test-benutzer.bhknz = 123456
----

Beispiel für die Konfiguration mit `@Authenticate`:

[source]
----
@Authenticate(oauth2ClientRegistrationId = "test-client") // fest
----
oder
[source]
----
@Authenticate(oauth2ClientRegistrationId = "${test-project.client-id}") // mit Property-Platzhalter
----

Die Client-ID kann sowohl fest als auch in Form eines Property-Platzhalters an die Annotation gegeben werden.
Beispiele für weitere Schreibweisen sind in den
xref:isy-security:nutzungsvorgaben/master.adoc#annotation-method-auth[Nutzungsvorgaben Security]
// this reference should be resolvable after merging with ISY-83 (adds @Authenticate annotation and documentation)
zu finden.

[source, properties]
----
# Property-Platzhalter
test-project.client-id = test-client

spring.security.oauth2.client.provider.testrealm.issuer-uri = http://localhost:12345/auth/realms/testrealm

spring.security.oauth2.client.registration.test-client.client-id = client-credentials-test-client
spring.security.oauth2.client.registration.test-client.client-secret = super_secret_password
spring.security.oauth2.client.registration.test-client.authorization-grant-type = client_credentials
spring.security.oauth2.client.registration.test-client.provider = testrealm
----

[[sicherheit-accessmanager]]
==== AccessManager und zugehörige Klassen

Das Interface `AccessManager` sowie zugehörige Interfaces entfallen.
Genauer wurden folgende Interfaces entfernt:

[source]
----
de.bund.bva.isyfact.sicherheit.accessmgr.AccessManager
de.bund.bva.isyfact.sicherheit.SicherheitAdmin
de.bund.bva.isyfact.sicherheit.accessmgr.AuthentifizierungsErgebnis
----

[[sicherheit-exceptions]]
==== Exceptions

Die Exceptions aus dem Paket `de.bund.bva.isyfact.sicherheit.common.exception` entfallen.
Sie werden durch Exceptions aus xref:literaturextern:inhalt.adoc#litextern-spring-security[Spring Security] ersetzt.

Eine Ausnahme davon bildet die Exception

[source]
----
de.bund.bva.isyfact.sicherheit.common.exception.RollenRechteMappingException,
----

die ersetzt wird durch:

[source]
----
de.bund.bva.isyfact.security.xmlparser.RolePrivilegesMappingException
----

[[sicherheit-test-mock]]
==== Mock für Testumgebungen

Der Baustein `isy-security-test` stellt zum Erstellen von (automatisierten) Tests einen OpenId Connect Provider Mock bereit.
Dieser löst den Keycloak Mock aus `isy-sicherheit-keycloak-test` ab.

Die Klassen und Interfaces

[source]
----
de.bund.bva.isyfact.sicherheit.keycloak.test.EmbeddedKeycloakStub
de.bund.bva.isyfact.sicherheit.keycloak.test.KeycloakMockBase
de.bund.bva.isyfact.sicherheit.keycloak.test.EmbeddedKeycloakMock
de.bund.bva.isyfact.sicherheit.keycloak.test.RemoteKeycloakMock
de.bund.bva.isyfact.sicherheit.keycloak.test.RsaKeyGenerator

----

werden ersetzt durch:

[source]
----
de.bund.bva.isyfact.security.test.oidcprovider.EmbeddedOidcProviderStub
de.bund.bva.isyfact.security.test.oidcprovider.OidcProviderMockBase
de.bund.bva.isyfact.security.test.oidcprovider.EmbeddedOidcProviderMock
de.bund.bva.isyfact.security.test.oidcprovider.RemoteOidcProviderMock
de.bund.bva.isyfact.security.test.RsaKeyGenerator
----

Dabei haben sich die Konstruktoren, Felder und Methodensignaturen leicht geändert.

*Konstruktoren*

* Die Konstruktoren haben keinen Parameter vom Typ `RsaKeyGenerator` mehr.
Falls bisher ein Konstruktor verwendet wurde, der als einen der Parameter ein Objekt vom Typ `RsaKeyGenerator` empfängt, kann dieser Parameter bei der Umstellung gestrichen werden.
* Konstruktoren, die bisher zwei Objekte vom `java.security.PrivateKey` und `java.security.PublicKey` empfangen haben, wurden zusammengefasst in einem Objekt vom Typ `java.security.KeyPair`.

*Felder*

Die Änderungen der Felder sind in den nachfolgenden Tabellen beschrieben.
Die Namen der zugehörigen Getter-Methoden wurden angepasst.

:table-sicherheit-test-fields-EmbeddedKeycloakMock: Änderung der Felder in EmbeddedKeycloakMock

[id="table-sicherheit-test-fields-EmbeddedKeycloakMock",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-fields-EmbeddedKeycloakMock}
[cols="1,1"]
|===
|EmbeddedKeycloakMock (IFS 2)|EmbeddedOidcProviderMock (IFS 3)

|`WireMockServer keycloakServer`|`WireMockServer oidcServerStub`
|===

:table-sicherheit-test-fields-EmbeddedKeycloakStub: Änderung der Felder in EmbeddedKeycloakStub

[id="table-sicherheit-test-fields-EmbeddedKeycloakStub",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-fields-EmbeddedKeycloakStub}
[cols="1,1"]
|===
|EmbeddedKeycloakStub (IFS 2)|EmbeddedOidcProviderStub (IFS 3)

|`String realm`|`URI issuer`
|===

*Methodensignaturen*

Die Änderungen der Methodensignaturen sind in den nachfolgenden Tabellen beschrieben.

:table-sicherheit-test-methods-KeycloakMockBase: Änderung der Methodensignaturen in KeycloakMockBase

[id="table-sicherheit-test-methods-KeycloakMockBase",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-methods-KeycloakMockBase}
[cols="2,2,1"]
|===
|KeycloakMockBase (IFS 2)|OidcProviderMockBase (IFS 3)|Änderung

|`addUser(String username, String password, String bhknz, Set<String> roles)`|`addUser(String clientId, String secret, String username, String password, Optional<String> bhknz, Set<String> roles)`|neue Parameter `String clientId` und `String secret`
|===

:table-sicherheit-test-methods-EmbeddedKeycloakStub: Änderung der Methodensignaturen in EmbeddedKeycloakStub

[id="table-sicherheit-test-methods-EmbeddedKeycloakStub",reftext = "{table-caption} {counter:tables}"]
.{table-sicherheit-test-methods-EmbeddedKeycloakStub}
[cols="2,2,1"]
|===
|EmbeddedKeycloakStub (IFS 2)|EmbeddedOidcProviderStub (IFS 3)|Änderung

|`public JWK getJwk()`|`public JWKSet getJwkSet()`|geänderter Methodenname und Rückgabetyp
|`public String getRealmKey()`|`public String getPublicKey()` | geänderter Methodenname
|`public String getOIDCConfigResponse(String jwksEndpoint, String tokenEndpoint)` | `public String getOIDCConfigResponse(String jwksEndpoint, String authorizationEndpoint, String tokenEndpoint)` | zusätzlicher Parameter `String authorizationEndpoint`
|`public AccessToken getAccessToken(UUID userId, String userName, Optional<String> bhknz, Set<String> roles)`|`public JwtClaimsSet getAccessToken(UUID userId, String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`, geänderter Rückgabetyp
|`public AccessToken getAccessToken(UUID userId, String userName, Optional<String> bhknz, Set<String> roles, int newTokenLifespan)` | `public JwtClaimsSet getAccessToken(UUID userId, String clientId, String userName, Optional<String> bhknz, Set<String> roles, int newTokenLifespan)` |zusätzlicher Parameter `String clientId`, geänderter Rückgabetyp
|`public String getAccessTokenString(String userName, Optional<String> bhknz, Set<String> roles)`|`public String getAccessTokenString(String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`
|`public String getAccessTokenString(UUID userId, String userName, Optional<String> bhknz, Set<String> roles)`|`public String getAccessTokenString(UUID userId, String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`
|`public String getAccessTokenString(AccessToken token)`|`public String getAccessTokenString(JwtClaimsSet claims)`|geänderter Parametertyp
|`public String getAccessTokenResponse(String userName, Optional<String> bhknz, Set<String> roles)`|`public String getAccessTokenResponse(String clientId, String userName, Optional<String> bhknz, Set<String> roles)`|zusätzlicher Parameter `String clientId`
|`public String getAccessTokenResponse(AccessToken accessToken)`|`public String getAccessTokenResponse(JwtClaimsSet claims)`|geänderter Parametertyp

|===

[[kapitel-persistence]]
=== Persistence
In IsyFact 3 werden `DataSourceProperties` von Spring Boot verwendet und lediglich um die Attribute `schemaVersion` und `schemaInvalidVersionAction` erweitert.
Hierdurch haben sich die Namen der Konfigurationsschlüssel geändert und müssen angepasst werden.
Details zur Konfiguration sind in den xref:isy-persistence:nutzungsvorgaben/konfiguration.adoc#konfiguration-der-datasource[Nutzungsvorgaben Persistence] zu finden.

[[kapitel-dokumentation]]
== Dokumentation

[[kapitel-frondend-technologien]]
=== Frontend Technologien

[[kapitel-isyfact-Referenzarchitektur]]
=== IsyFact Referenzarchitektur
