= Migrationsleitfaden IsyFact {page-component-display-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Für die IsyFact gibt es hiermit drei Versionszweige: IsyFact 1, IsyFact 2 und seit Q1/2023 das neue Major-Release IsyFact 3.0.

Die auf dieser Seite aufgeführten Hinweise sollen IsyFact Anwendungsentwicklern bei der Umstellung einer auf IsyFact 2 basierenden Anwendung auf IsyFact {page-component-display-version} helfen.

[[kapitel-geschaeftsanwendung]]
== Geschäftsanwendung

[[kapitel-bridge-module]]
=== Bridge-Module
Die drei in IsyFact 2 eingeführten Bridge-Module

* `isy-serviceapi-core-bridge`
* `isy-serviceapi-sst-bridge`
* `isy-exception-sst-bridge`

entfallen in IsyFact 3.
In einer Anwendung, die bisher Bridge-Module verwendet und auf IsyFact 3 umgestellt werden soll, müssen daher Anpassungen vorgenommen werden.
Die Tabelle <<table-bridge-module>> zeigt für jedes der drei Bridge-Module, durch welches Modul es ersetzt wird.
Dabei ist zu beachten, dass zwei der Ersatzmodule eine Abhängigkeit zu IsyFact-1.x haben.

[[table-bridge-module]]
.Abhängigkeiten in IsyFact 2 vs. IsyFact 3
[cols="1,1",options="header"]
|===
|Abhängigkeit in IsyFact 2 | Abhängigkeit in IsyFact 3

|`isy-serviceapi-core-bridge`|`isy-serviceapi-core`
|`isy-serviceapi-sst-bridge`|`isy-serviceapi-sst`, Version `1.11.1`
|`isy-exception-sst-bridge`|`isy-exception-sst`, Version `1.11.1`
|===


Zudem wird die Klasse
[source]
----
de.bund.bva.isyfact.exception.service.bridge.util.BridgeExceptionMapper
----
ersetzt durch:
[source]
----
de.bund.bva.isyfact.serviceapi.common.exception.ExceptionMapper
----

[[kapitel-ueberwachung]]
=== Überwachung
Es sind die xref:isy-ueberwachung:nutzungsvorgaben/master.adoc[] zu IsyFact 3 zu verwenden.

[[kapitel-bausteine]]
== Bausteine

[[kapitel-batchrahmen]]
=== Batchrahmen

In IsyFact 3.0 wurde mit der Umstellung auf `isy-security` das Detailkonzept zur xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#authentifizierung-und-autorisierung[Authentifizierung und Autorisierung] aktualisiert.
Statt Benutzer, Passwort und BHKNZ muss in der Batch-Konfiguration eine `oauth2ClientRegistrationId` konfiguriert werden (siehe xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#table-CharBatUse[Eigenschaften eines Batchbenutzers])

[[batch-configuration-isy-sicherheit]]
.Batch-Konfiguration zur Verwendung von isy-sicherheit in IsyFact 2
[source,properties]
----
batch.benutzer=TestUser
batch.passwort=TestPasswort
batch.bhknz=TestBHKNZ

# [...]
----

[[batch-configuration-isy-security]]
.Batch-Konfiguration zur Verwendung von isy-security in IsyFact 3
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die Batch-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen Migration von technischen Nutzern zu Confidential Clients den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Batch-Konfiguration mit technischen Nutzer
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe registrationId abgebildet
isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Batch-Konfiguration nach Umstellung von _technischem Nutzer_ auf _technischen Client_
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

[[kapitel-task-scheduler]]
=== Task Scheduler

In IsyFact 3.0 wurden mit der Umstellung auf `isy-security` die Nutzungsvorgaben zur xref:isy-task:nutzungsvorgaben/master.adoc#spring-konfiguration[Authentifizierung von Tasks] aktualisiert.
Statt Benutzer, Passwort und BHKNZ (siehe <<task-properties-isy-sicherheit>>) muss in den Task Properties eine `oauth2ClientRegistrationId` konfiguriert werden (siehe <<task-properties-isy-security>>).

[[task-properties-isy-sicherheit]]
.Properties mit isy-sicherheit in IsyFact 2
[source,properties]
----
isy.task.tasks.halloWeltTask.benutzer=TestUser
isy.task.tasks.halloWeltTask.passwort=TestPasswort
isy.task.tasks.halloWeltTask.bhkz=TestBHKNZ

# [...]
----

[[task-properties-isy-security]]
.Properties mit isy-security in IsyFact 3
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[ Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die TaskScheduler-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen User-Migration von einem _natürlichen User_ auf ein _technischen Nutzer_ den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Properties mit technischem Nutzer
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe oauth2ClientRegistrationId abgebildet

isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Properties nach Umstellung von _technischem Nutzer_ auf _technischen Client_
[source,properties]
----
isy.task.tasks.halloWeltTask.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

[[kapitel-service, Bausteine/Service]]
=== Service

[WARNING]
====
Ab IsyFact 3 ist die *Verwendung von REST-Schnittstellen* für die Neuentwicklung verbindlich.
Spring HTTP-Invoker ist deprecated und wird ab sofort als Schnittstellenformat durch REST abgelöst.
Die Verwendung von REST-Schnittstellen wird im Baustein REST (siehe xref:isy-service-rest:konzept/master.adoc[] und xref:isy-service-rest:nutzungsvorgaben/master.adoc[]) erläutert.
Desweiteren wurden die Bridge-Module `isy-serviceapi-core-bridge`, `isy-serviceapi-sst-bridge` und `isy-exception-sst-bridge` entfernt.

====

[WARNING]
====
Mit der Verwendung von `isy-security` in der IsyFact 3 wird standardmäßig anstelle von IsyFacts `AufrufKontext` Springs `SecurityContext` verwendet.

Damit dennoch alte HTTP-Invoker Schnittstellen aufgerufen werden können (welche einen gefüllten AufrufKontext benötigen), wird eine spezielle `RemoteInvocationFactory` eingesetzt, welche Springs `SecurityContext` in ein `AufrufKontextTo` ad hoc per Request umwandelt.

Weitere Informationen können unter
xref:isy-serviceapi-core:nutzungsvorgaben/inhalt.adoc#kompatibilitaet_if1_2_3[Nutzungsvorgaben HTTP-Invoker] nachgelesen werden.
====

[[kapitel-sicherheit]]
=== Sicherheit


[[kapitel-dokumentation]]
== Dokumentation


[[kapitel-frondend-technologien]]
=== Frontend Technologien



[[kapitel-isyfact-Referenzarchitektur]]
=== IsyFact Referenzarchitektur


