= Migrationsleitfaden IsyFact {page-component-display-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Für die IsyFact gibt es hiermit drei Versionszweige: IsyFact 1, IsyFact 2 und seit Q1/2023 das neue Major-Release IsyFact 3.0.

Die auf dieser Seite aufgeführten Hinweise sollen IsyFact Anwendungsentwicklern bei der Umstellung einer auf IsyFact 2 basierenden Anwendung auf IsyFact {page-component-display-version} helfen.

[[kapitel-geschaeftsanwendung]]
== Geschäftsanwendung

[[kapitel-bausteine]]
== Bausteine

[[kapitel-batchrahmen]]
=== Batchrahmen

In IsyFact 3.0 wurde mit der Umstellung auf `isy-security` das Detailkonzept zur xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#authentifizierung-und-autorisierung[Authentifizierung und Autorisierung] aktualisiert.
Statt Benutzer, Passwort und BHKNZ muss in der Batch-Konfiguration eine `oauth2ClientRegistrationId` konfiguriert werden (siehe xref:blaupausen:detailkonzept-komponente-batch/inhalt.adoc#table-CharBatUse[Eigenschaften eines Batchbenutzers])

[[batch-configuration-isy-sicherheit]]
.Batch-Konfiguration zur Verwendung von isy-sicherheit in IsyFact 2
[source,properties]
----
batch.benutzer=TestUser
batch.passwort=TestPasswort
batch.bhknz=TestBHKNZ

# [...]
----

[[batch-configuration-isy-security]]
.Batch-Konfiguration zur Verwendung von isy-security in IsyFact 3
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die Batch-Konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen Migration von technischen Nutzern zu Confidential Clients den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Batch-Konfiguration mit technischen Nutzer
[source,properties]
----
batch.registrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe registrationId abgebildet
isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Batch-Konfiguration nach Umstellung von technischem Nutzer auf Confidential Client
[source,properties]
----
batch.oauth2ClientRegistrationId=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

[[kapitel-sicherheit]]
=== Sicherheit

[[kapitel-task-scheduler]]
=== Task Scheduler

In IsyFact 3.0 wurden die Nutzungsvorgaben zur authentifizierung von Tasks aktualisiert, da der Task Scheduling Baustein auf `isy-security` umgestellt wurde.
Statt Benutzer, Passwort und BHKNZ (siehe <<task-properties-isy-sicherheit>>) muss in den Task Properties nur noch eine `registration-id` konfiguriert werden (siehe <<task-properties-isy-security>>).

[[task-properties-isy-sicherheit]]
.Properties mit isy-sicherheit in IsyFact 2
[source,properties]
----
isy.task.tasks.halloWeltTask.benutzer=TestUser
isy.task.tasks.halloWeltTask.passwort=TestPasswort
isy.task.tasks.halloWeltTask.bhkz=TestBHKNZ

# [...]
----

[[task-properties-isy-security]]
.Properties mit isy-security in IsyFact 3
[source,properties]
----
isy.task.tasks.halloWeltTask.registration-id=TestClient

# [...]
----

Eine entsprechende Spring Security ClientRegistration wird durch `isy-security` xref:isy-security:nutzungsvorgaben/master.adoc#konfigurationsparameter[ Konfigurationsparameter] bereitgestellt.
Die folgenden Beispiele zeigen wie Konfigurationen nach der Migration aussehen können.
Für die Task Scheduler konfiguration ist nicht relevant, ob die ClientRegistration den Resource-Owner-Password-Credentials Flow (`authorization-grant-type: password`) oder nach der empfohlenen Migration von technischen Nutzern zu Confidential Clients den Client-Credentials Flow (`authorization-grant-type: client_credentials`) nutzt.

.Properties mit technischem Nutzer
[source,properties]
----
isy.task.tasks.halloWeltTask.registration-id=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=password
spring.security.oauth2.client.registration.TestClient.provider=TestRealm

# Benutzer, Passwort und BHKNZ werden auf die selbe registration-id abgebildet

isy.security.oauth2.client.registration.TestClient.username=TestUser
isy.security.oauth2.client.registration.TestClient.password=TestPasswort
isy.security.oauth2.client.registration.TestClient.bhknz=TestBHKNZ
----

.Properties nach Umstellung von technischem Nutzer auf Confidential Client
[source,properties]
----
isy.task.tasks.halloWeltTask.registration-id=TestClient

# [...]

spring.security.oauth2.client.provider.TestRealm.issuer-uri=http://localhost:9095/auth/realms/testrealm
spring.security.oauth2.client.registration.TestClient.client-id=test-user-client-id
spring.security.oauth2.client.registration.TestClient.client-secret=test-user-client-secret
spring.security.oauth2.client.registration.TestClient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.TestClient.provider=TestRealm
----

[[kapitel-service, Bausteine/Service]]
=== Service

[WARNING]
====
Ab IsyFact 3 ist die *Verwendung von REST-Schnittstellen* für die Neuentwicklung verbindlich.
Spring HTTP-Invoker ist deprecated und wird ab sofort als Schnittstellenformat durch REST abgelöst.
Die Verwendung von REST-Schnittstellen wird im Baustein REST (siehe xref:isy-service-rest:konzept/master.adoc[] und xref:isy-service-rest:nutzungsvorgaben/master.adoc[]) erläutert.
====

[WARNING]
====
Mit der Verwendung von `isy-security` in der IsyFact 3 wird standardmäßig anstelle von IsyFacts `AufrufKontext` Springs `SecurityContext` verwendet.

Damit dennoch alte HTTP-Invoker Schnittstellen aufgerufen werden können (welche einen gefüllten AufrufKontext benötigen), wird eine spezielle `RemoteInvocationFactory` eingesetzt, welche Springs `SecurityContext` in ein `AufrufKontextTo` ad hoc per Request umwandelt.

Weitere Informationen können unter
xref:isy-serviceapi-core:nutzungsvorgaben/inhalt.adoc#kompatibilitaet_if1_2_3[Nutzungsvorgaben HTTP-Invoker] nachgelesen werden.
====

[[kapitel-dokumentation]]
== Dokumentation


[[kapitel-frondend-technologien]]
=== Frontend Technologien



[[kapitel-isyfact-Referenzarchitektur]]
=== IsyFact Referenzarchitektur


