= Release Notes Version {page-component-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]


*Übersicht über die Änderungen*

[[kapitel-aenderungen]]
== Allgemeine Änderungen

[[kapitel-umstellung-dokumentation]]
=== Umstellung der Dokumentation

Online Dokumentation über  Asciidoc / Antora:: Die Bereitstellung der Dokumentation der IsyFact (Open Source) erfolgt nicht mehr über PDF Dokumente, sondern über die xref:literaturextern:inhalt.adoc#litextern-url-isyfact-online-docs[Online-Dokumentation]. 
Als Werkzeug zur Generierung der Dokumentation wird das Produkt Antora eingesetzt. 
Vorgaben zur Dokumentation:: Die xref:documentation-guide:ROOT:index.adoc[Vorgaben zur Dokumentation für technische Autoren] wurden ergänzt.
Darüber hinaus werden Abbildungen sukzessive in editierbare SVGs gewandelt und in der Dokumentation abgelegt. Eine xref:methodik:diagrammerstellung/diagramsnet.adoc[Beschreibung zum Vorgehen] wurde ergänzt. 
Auszeichnung von Deprecations:: Deprecations werden im Code und der Dokumentation kenntlich gemacht. 
Produktkatalog als Teil der Dokumentation:: Der xref:einstieg:produkte.adoc[Produktkatalog] wurde von Excel nach Asciidoc / CSV migriert und ist nun Teil dieser Dokumentation.
Externe Links:: Die Dokumentation verwendet keine Liste für externe Links mehr, sondern das https://docs.asciidoctor.org/asciidoc/latest/macros/url-macro/[URL-Makro] von AsciiDoc.
Glossar & Leitfaden Dokumentation:: Das xref:glossary:glossary:master.adoc[] und der xref:documentation-guide:ROOT:index.adoc[] werden parallel zu den Releases der IsyFact gepflegt.
Sie besitzen keine Version und sind damit über alle Releases hinweg gültig.
Inhalte für spezifische Releases werden ausdrücklich ausgezeichnet.

[[kapitel-spring-boot]]
=== Spring Boot
Spring Boot wurde auf Version 2.7.15 angehoben. Die Versionen sämtlicher Produkte werden ebenfalls von Spring verwaltet (s. https://docs.spring.io/spring-boot/docs/2.7.15/reference/html/dependency-versions.html).

[[kapitel-java]]
=== Java

Java Runtime:: Die Java Runtime Environment wurde auf Version 17 gehoben.
Es ist aber weiterhin mit Version 8 zu kompilieren (Language Level).
Java Vendor:: Der Java Vendor wurde geändert auf Eclipse Temurin satt Oracle RedHat.

[[kapitel-rest-interne-externe-schnittstelle]]
=== REST als Nachfolger der HTTPInvoker-Technologie

REST Schnittstellen:: Sowohl interne als auch externe REST-Schnittstellen sind ab sofort einheitlich nach dem xref:isy-service-rest:konzept/master.adoc[REST-Konzept] zu realisieren.
Spring HTTPInvoker deprecated icon:ban[title=Deprecation]:: Die Verwendung von xref:isy-serviceapi-core:konzept/master.adoc[HTTPInvoker Schnittstellen] gilt als deprecated und wird mit einem nachfolgenden Release entfernt.
Metadaten im HTTP-Header statt im Datensatz/Aufrufkontext icon:ban[title=Deprecation]:: Metadaten sind über HTTP-Header zur realisieren.
Eine Verwendung von Metadaten über HTTPInvoker und Aufrufkontext gilt als deprecated und wird mit einem nachfolgenden Release entfernt.
REST-Baustein als http-Invoker Nachfolger:: Der REST-Baustein wird als Nachfolger des HTTPInvoker-Bausteins (isy-serviceapi-core) veröffentlicht.

[[kapitel-sles]]
=== Suse Linux Enterprise Server (SLES)

Der Standard schreibt nun statt eines Betriebssystems diejenigen Produkte vor, die zum Bau und zum Betrieb der Anwendungen nötig sind.

Suse Linux Enterprise Server (SLES) entfernt:: Das Betriebssystem wurde aus dem Produktkatalog und der Dokumentation entfernt.
Eclipse Temurin als JVM aufgenommen:: siehe <<kapitel-java>>

[[kapitel-liquibase]]
=== Liquibase

Liquibase in Produktkatalog aufgenommen:: Einführung und Umstellung auf Liquibase.
Ausblick:: Die konzeptionelle Integration erfolgt in einem nachfolgenden Release.

[[kapitel-optimierung-dependeny-management]]
=== Optimierung Dependency Management
Abhängigkeiten wurden überprüft und reduziert.


[[kapitel-referenzarchitektur]]
== Referenzarchitektur

=== Software-technische Sicht
Datenzugriff:: Für die Überführung von persistenten Entitäten in Geschäftsobjekte sollen keine gesonderten Schnittstellenobjekte mehr genutzt werden.
Die Komponente Datenzugriff übergibt persistente Entitäten an den Anwendungskern.
Der Anwendungskern darf keine persistenten Entitäten mehr herausgeben, auch nicht zwischen seinen Fachkomponenten.
Entsprechende Ausnahmen wurden gestrichen.


[[kapitel-bausteine]]
== Isyfact Bausteine

[[kapitel-baustein-sicherheit-deprecated]]
=== Baustein Sicherheit deprecated icon:ban[title=Deprecation]
Der xref:isy-sicherheit:konzept/master.adoc[Baustein Sicherheit] und damit die Verwendung des Aufrufkontextes zur Authentifizierung ist ab IsyFact-Version 3.0 als deprecated markiert und wird mit einem folgenden Release entfernt. Als Nachfolger zum Thema Sicherheit gibt es mit IsyFact-Version 3.0 den xref:isy-security:konzept/master.adoc[Baustein Security].

[[kapitel-neuer-baustein-security]]
=== Neuer Baustein Security
Das Konzept zum Schutz der Daten und IT-Systeme vor unberechtigter Nutzung wurde überarbeitet und ist nun im neuen xref:isy-security:konzept/master.adoc[Baustein Security] beschrieben.
Er ist der Nachfolger des xref:isy-sicherheit:konzept/master.adoc[Bausteins Sicherheit], der mit IsyFact-Version 3.0 deprecated ist.

Ziel:: Nutzung von Standardfähigkeiten der eingesetzten Produkte und Reduzierung der Eigenentwicklung.

Folgende Änderungen ergeben sich:

OAuth2.0::
Im neuen xref:isy-security:konzept/master.adoc[Baustein Security] wird das Protokoll OAuth2.0 verwendet, um ein Single Sign On (SSO) zur Authentifizierung und Autorisierung des Nutzers gegenüber einem zentralen IAM-System umzusetzen.
Das neue Konzept des xref:isy-security:konzept/master.adoc#oauth2.0-und-openidconnect[Bausteins Security] beschreibt die Verwendung von OAuth2.0.

Ablösung des Sicherheits-Transportobjekts 'AufrufKontext'::
Im neuen xref:isy-security:konzept/master.adoc[Baustein Security] werden die sicherheitsrelevanten Daten, statt wie bisher im IsyFact-eigenen Transportobjekt 'AufrufKontext', nun im 'SecurityContext' des Spring-Frameworks und bei Aufrufen von Nachbarsystemen als JWT-Access-Token im Http-Header transportiert.

Ablösung von sicherheitsrelevanten IsyFact-Annotationen::
Die von Spring Security bereitgestellte Annotation `@secured` löst die Annotation `@gesichert` ab und ist analog dazu zu verwenden.

[[kapitel-neue-endpoints-ueberwachung]]
=== Baustein Überwachung
==== Neue Endpoints in Baustein Überwachung
Liveness, Readiness und Availability zur Überwachung:: Liveness und Readiness bieten ein feingranulares Monitoring der health eines Systems. 
Diese Endpoints stehen zusätzlich zu den vorhandenen Health-Endpoints zur Verfügung und sind im xref:isy-ueberwachung:konzept/master.adoc[Konzept des Bausteins Überwachung] definiert.
Die xref:isy-ueberwachung:nutzungsvorgaben/master.adoc[Nutzungsvorgaben des Bausteins Überwachung] wurden um  Implementierungshinweise erweitert. 
Availability wird als erweiterte Überwachungsmetrik aufbauend auf Liveness und Readiness Probes definiert und Umsetzungsempfehlungen gegeben.
Änderungen an Nachbarsystemchecks und Loadbalancer:: Aktuell bauen Nachbarsystemchecks und Loadbalancer auf die bisherigen Health-Checks. 
Diese fachlichen Möglichkeiten funktionieren auch mit Liveness und Readiness Probes. 
Damit sind differenzierte Reaktionen auf Fehler in den Systemen möglich.

==== Refactoring der `ServiceStatistik`
Die Klasse `ServiceStatistik` ist nun ein Interface und ermöglicht es, Klassen zum Sammeln von Metriken zu erstellen.
Alle `ServiceStatistik` implementierenden Beans werden automatisch der Micrometer-Registry hinzugefügt.
Details finden sich in den xref:isy-ueberwachung:nutzungsvorgaben/master.adoc[Nutzungsvorgaben des Bausteins Überwachung].

[[kapitel-task-scheduling]]
=== Baustein Task Scheduling

Umstellung auf Spring Boot:: Das Task Scheduling wurde auf Spring Boot umgestellt und hat Auswirkungen auf den xref:isy-konfiguration:konzept/master.adoc[Baustein Konfiguration] und den xref:isy-konfiguration:konzept/master.adoc[Baustein Überwachung].

Verwendung des Bausteins isy-security zur Authentifizierung:
Für die Authentifizierung nutzt der Baustein Task Scheduling die xref:isy-security:konzept/master.adoc#aussensicht-der-komponente-security[Schnittstelle zur Authentifizierung] aus dem xref:isy-security:konzept/master.adoc#absicherung-task[Baustein Security].
Die bisherige Art der Authentifizierung des Tasks als 'technischer Nutzer' (mit Nutzername und Passwort) wird perspektivisch durch eine Authentifizierung als 'Client' (mit Client-ID und Client-Secret, vergeben vom IAM-System) abgelöst.
Für eine weiche Migration bietet die Konfiguration von Tasks dazu die Möglichkeit, alternativ die Authentifizierungs-Credentials Nutzername und Passwort zusätzlich zu Client-ID und Client-Secret zu setzen um vorübergehend den Resource Owner Password Flow zu nutzen.

[[kapitel-batchrahmen]]
=== Baustein Batchrahmen
Verwendung des Bausteins isy-security zur Authentifizierung:
Für die Authentifizierung nutzt der Batchrahmen die xref:isy-security:konzept/master.adoc#aussensicht-der-komponente-security[Schnittstelle zur Authentifizierung] aus dem xref:isy-security:konzept/master.adoc#absicherung-task[Baustein Security].
Die bisherige Art der Authentifizierung des Tasks als 'technischer Nutzer' (mit Nutzername und Passwort) wird perspektivisch durch eine Authentifizierung als 'Client' (mit Client-ID und Client-Secret, vergeben vom IAM-System) abgelöst.
Für eine weiche Migration bietet die Konfiguration von Batches dazu die Möglichkeit, alternativ die Authentifizierungs-Credentials Nutzername und Passwort zusätzlich zu Client-ID und Client-Secret zu setzen um vorübergehend den Resource Owner Password Flow zu nutzen.

Breaking Change: Methode `getAuthenticationCredentials` entfernt::
Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations. Batches müssen nur noch eine `oauth2ClientRegistrationId` zur Authentifizierung bereitstellen. Die Methode `getAuthenticationCredentials` der `BatchAusfuehrungsBean` wurde entfernt.


[[kapitel-sonderzeichen]]
=== Baustein Sonderzeichen
Sonderzeichen Transformator::
Es wurde ein Sonderzeichen Transformator eingeführt um Zeichenketten, welche aus normativen Buchstaben (Datentyp C) der DIN SPEC 91379 bestehen, auf die Grundbuchstaben A-Z abzubilden.
Für unterschiedliche Anwendungsfälle kann es erforderlich sein, die in Namen enthaltenden Buchstaben auf die Grundbuchstaben A-Z abzubilden.
Dies ist bspw. der Fall in der maschinenlesbaren Zone (MRZ) amtlicher Reisedokumente, für die der Standard [ICAO 9303-3] einschlägig ist, da nur diese Grundbuchstaben für die Repräsentation von Namen zur Verfügung stehen.
Wenn Datensätze und Suchanfragen unter Anwendung der Suchform normalisiert werden, ist es auch möglich, Namen trotz unterschiedlicher Schreibweisen zu identifizieren.

String-Latin-1.1 Transformatoren sind nun deprecated icon:ban[title=Deprecation]::
Der Zeichensatz für String Latin 1.1 wurde korrigiert. Dies kann zu Kompatibilitätsproblemen in der Kommunikation
mit Anwendungen führen, die den unkorrigierten Zeichensatz verwenden (IsyFact-Versionen kleiner als IF 3).

Breaking Change: Getter eingeführt::
Die Klassen `stringlatin1_1/core/transformation/ZeichenKategorie.java` und `dinspec91379/transformation/ZeichenKategorie.java` bieten für den Abruf aller Möglichkeiten nun einen `getter` anstelle einer `public static Variable` an.

Außerdem wurden die fehlenden Zeichen 0110 und 0111 zum Mapping hinzugefügt.


=== Baustein Persistence
In `isy-persistence` gibt es nun eine Autokonfiguration mit initialisierbarer Datenbank.
Für die Konfiguration der `DataSource` wurde zu den `DataSourceProperties` von Spring Boot gewechselt.

Breaking Change: Property `DataSource`::
Der Konfigurationsschlüssel für die `DataSource` heißt nun `isy.persistence.datasource` statt `isy.persistence.oracle.datasource`.

[[kapitel-restrukturierung-bedienkonzept]]
=== Styleguide
Der Styleguide bzw. das Bedienkonzept ist deprecated icon:ban[title=Deprecation]::
Das bestehende Konzept soll bei der Entwicklung neuer Anwendungen nicht mehr berücksichtigt werden.
Das neue, restrukturierte Bedienkonzept wird an anderer Stelle veröffentlicht.

=== Baustein Konfiguration deprecated icon:ban[title=Deprecation]

Anstatt des Bausteins werden die Standardfunktionen von Spring Boot genutzt.

[[kapitel-weitere-deprecations]]
== Weitere Deprecations

* Baustein JSF

[[kapitel-entfernt]]
== Entfernt

[[kapitel-vorlageanwendungen]]
=== Vorlageanwendungen

Die Vorlageanwendungen wurden aus der Dokumentation entfernt.

=== Bridge-Module

Die Bridge zwischen Isyfact 1 und 2 ist obsolet weshalb folgende Module entfernt wurden:

* isy-serviceapi-sst
* isy-exception-sst
* isy-sst-bridge

=== Vorlagen

Die Vorlage zum Tailoring Dokument wurde entfernt.

[[kapitel-produkte]]
== Produktkatalog

Es gab einige Updates im Produktkatalog. Diese können der xref:einstieg:produktkatalog/changelog.adoc[Änderungshistorie] entnommen werden.
