-- Dieses Skript führt alle Operationen aus, die sich auf die bisher angelegten Datenbankobjekte beziehen.
-- Das können bspw. Stammdaten-Importe oder das abschließende Setzen von Rechten auf Objekten sein, die es
-- vorher nicht gab.
-- ----------------------------------------------------------------------------------------------------------------
-- This script performs all operations relevant to the database objects created so far.
-- This may be Stammdaten imports or the final setting of rights on objects which did not exist before.
