= Handbuch für technische Autoren: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Handbuch dient technischen Autoren von IsyFact-Dokumenten als Wegweiser.

Festgelegte Struktur::

IsyFact bietet eine strukturierte Sammlung vielfältiger Dokumente, um die Entwicklung von xref:glossary:glossary:master.adoc#glossar-IsyFact[IsyFact]-basierenden Anwendungen zu beschreiben.
Für jeden Teilbereich, sei es für den Einstieg, über die xref:glossary:glossary:master.adoc#glossar-Konzept[Konzepte] bis hin zu den xref:glossary:glossary:master.adoc#glossar-Nutzungsvorgaben[Nutzungsvorgaben] einzelner Module, wird jeweils ein eigenes Dokument bereitgestellt.
Zur Vereinheitlichung werden alle Dokumente gemäß festgelegten Regeln und nach einem bestimmten Grundschema angefertigt.
Beispielsweise zeichnet sich jedes Dokument durch einen ähnlichen Aufbau aus, um dem Nutzer eine intuitive Handhabe zu gewährleisten.
Weil IsyFact häufig aktualisiert wird und immer wieder auch neue IsyFact-Module hinzugefügt werden, müssen regelmäßig Änderungen in die vorhandenen Dokumente eingepflegt und auch stetig neue Dokumente zur Gesamtdokumentation beigefügt werden.
Dabei sollen nicht nur vorhandene Dokumente, sondern auch neue Dokumente dem gleichen Grundschema und derselben spezifizierten Form gerecht werden, damit die festgelegte Struktur weiterhin beibehalten bleibt.

AsciiDoc::

Die IsyFact-Dokumentation wird in der vereinfachten Auszeichnungssprache AsciiDoc verfasst.
Eine AsciiDoc-Datei ist nicht binär, sondern besteht aus Klartext, ganz ohne proprietäre Technologie.
Einer der Vorteile der AsciiDoc-Syntax ist die leichte Erlernbarkeit, denn AsciiDoc benötigt denkbar wenige Markups.
AsciiDoc lässt sich zudem problemlos in moderne Versionsverwaltungssysteme integrieren, so dass alle Vorteile solcher Systeme wie z.B. paralleles Arbeiten in Branches, Pull/Merge Requests oder Continuous Integration nun auch auf Dokumente anwendbar sind.

VS Code (Visual Studio Code)::

Zum Erstellen und Bearbeiten von AsciiDoc-Dateien wird ein Texteditor benötigt.
Für die Dokumentation der IsyFact wird VS Code als Editor empfohlen.
VS Code ist ein Texteditor, der von Microsoft entwickelt wird und plattformübergreifend für die Betriebssysteme Windows, macOS und Linux verfügbar ist.
Neben den ausgereiften Plugins für die Bearbeitung von AsciiDoc-Dokumenten unterstützt VS Code Git-basierte Projekte von Haus aus mit vielfältigen Funktionen.

Ausgabeformate HTML und PDF::

AsciiDoc-Dokumente können in verschiedenen Ausgabeformaten wie beispielsweise HTML oder PDF ausgegeben werden.
Bei der IsyFact-Dokumentation sorgen Skripte dafür, dass die erstellten HTML- und PDF-Dateien automatisch auch über ein Literaturverzeichnis, ein Glossar, ein Abbildungsverzeichnis und ein Tabellenverzeichnis verfügen.

[[aufbau-und-zweck-des-dokuments]]
=== Aufbau und Zweck des Dokuments

Dieses Dokument ist eine Anleitung für technische Autoren.
Es ermöglicht ihnen, die vorhandene IsyFact-Dokumentation gemäß der festgelegten Struktur zu aktualisieren und zu erweitern.
Gleichzeitig geht es auf die Besonderheiten ein, die bei der Verwendung der Auszeichnungssprache AsciiDoc im Rahmen der IsyFact-Dokumentation zu beachten sind.

Das Handbuch ist in folgende Bereiche untergliedert:

- Architekturbeschreibung der Dokumentation
- Die Arbeitsumgebung einrichten
- Ein neues Dokument anlegen
- Ein Dokument bearbeiten
- Ein Dokument als HTML- und PDF-Datei erzeugen
// end::inhalt[]
