:doctitle: Vorlagen Übersicht

:sectnums:

include::glossary:licence:partial$licence.adoc[]

// tag::inhalt[]
[[einleitung]]
== Einleitung

An dieser Stelle werden Vorlagen für den Systementwurf und das Systemhandbuch angeboten.
Die Vorlagen können sowohl direkt aufgerufen als auch heruntergeladen werden.

Im Folgenden wird beschrieben, wie aus den heruntergeladenen gezippten Vorlagen PDF-Dokumente erstellt werden können.

Für Entwickler wird außerdem beschrieben, wie die herunterladbaren zip-Vorlagen erstellt werden können.
Das ist wichtig, wenn Änderungen am Text der Vorlage vorgenommen werden.

[[erstellung-pdf]]
== Erstellung von PDF-Dokumenten aus den gezippten Vorlagen

Die gezippten Vorlagen enthalten Asciidoc-Dateien, die projektspezifisch ergänzt werden müssen.
Nach Bedarf kann aus den Asciidoc-Dateien für jede Vorlage ein PDF erstellt werden.
Das Modul `isy-documentation` bietet diese Erstellung an, die Vorgehensweise wird anhand der Vorlage für den Systementwurf beschrieben.
Analoges gilt für das Systemhandbuch.

Zunächst wird die heruntergeladene Datei entzippt.
Die zwei Asciidoc-Dateien master.adoc und inhalt.adoc sowie der images-Ordner samt Inhalt werden in `isy-documentation` unter den Pfad `src/docs/vorlagen/isyfact-vorlage-systementwurf` kopiert.
Danach wird `mvn generate-resources` ausgeführt.
Der generierte PDF-Systementwurf befindet sich nun unter `target/doc/pdf/vorlagen/isyfact-vorlage-systementwurf`.


[[erzeugung-zip]]
== Erzeugung gezippte Vorlagen

Wenn der Text der Vorlagen in isyfact-standards geändert wird, müssen die Vorlagen auch neu gezippt werden zum Herunterladen.

Dazu wird unter dem Maven Submodul `isyfact-standards-doc` der Maven-Befehl `mvn package` ausgeführt.
Die gezippten Vorlagen befinden sich nun in `isyfact-standards-doc` unter `src/docs/antora/modules/methodik/attachments/vorlage-generated`.

// end::inhalt[]
