= PDF- und HTML-Dokumente erzeugen

include::glossary:licence:partial$licence.adoc[]

Ist das zu bearbeitende Dokument fertiggestellt, so kann daraus eine PDF- und HTML-Datei generiert werden.
Dies geschieht mithilfe des Asciidoctor Maven Plugins und der `isy-asciidoctorj-extensions`.
`isy-asciidoctorj-extensions` ist eine Sammlung von verschiedenen xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoctorj-extensions[AsciidoctorJ Extensions], welche die Wartung der IsyFact-Dokumentation erleichtern.
Eine Liste aller IsyFact Extensions befindet sich im Abschnitt <<isy-asciidoctorj-extensions>>.

[[asciidoc-in-pom-einbinden]]
== Maven-Konfiguration

Die `isy-asciidoctorj-extensions` können über das `asciidoctor-maven-plugin` in der pom.xml eingebunden werden.
Zunächst sind folgende Properties dem Element `<properties></properties>` hinzuzufügen:

*Properties*

.Hinzuzufügende Properties
[id="listing-pom-properties",reftext="{listing-caption} {counter:listings }"]
[source,xml]
----
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <html-output-base-directory>${project.build.directory}/doc/html</html-output-base-directory>
    <pdf-output-base-directory>${project.build.directory}/doc/pdf</pdf-output-base-directory>
    <maven.build.timestamp.format>dd.MM.yyyy</maven.build.timestamp.format>
    <asciidoctorj-extensions.version>2.3.0</asciidoctorj-extensions.version>
</properties>
----

Folgendes Listing zeigt die Konfiguration für einen lauffähigen Asciidoctor Build inklusive `isy-asciidoctorj-extensions`.

*Integration Asciidoctor Maven Plugin*

[[listing-pom-asciidoc]]
.Integration der `isy-asciidoctorj-extensions` in das Asciidoctor Maven Plugin
[source,xml,subs="attributes+"]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctor-maven-plugin</artifactId>
            <version>2.1.0</version> <1>
            <dependencies>
                <dependency>
                    <groupId>org.asciidoctor</groupId>
                    <artifactId>asciidoctorj-pdf</artifactId>
                    <version>1.5.3</version>
                </dependency>
                <dependency>
                    <groupId>de.bund.bva.isyfact</groupId> <2>
                    <artifactId>isy-asciidoctorj-extensions</artifactId>
                    <version>${isy-asciidoctorj-extensions.version}</version>
                </dependency>
            </dependencies>

            <configuration>
                <outputDirectory>${project.build.directory}</outputDirectory>
                <attributes>
                    <revnumber>IF-${project.version}</revnumber>
                    <revdate>${maven.build.timestamp}</revdate>
                    <version-ifs>${project.version}</version-ifs>
                    <vs-einstufung>offen</vs-einstufung> <3>
                </attributes>
            </configuration>

            <executions>
                <execution> <4>
                    <id>html-build</id>
                    <phase>generate-resources</phase>
                    <goals>
                        <goal>process-asciidoc</goal>
                    </goals>
                    <configuration>
                        <backend>html</backend>
                        <sourceDirectory>src/docs/OrdnerDokument</sourceDirectory>
                        <sourceDocumentName>master.adoc</sourceDocumentName>
                        <outputFile>${project.build.directory}/doc/Dokument.html</outputFile>
                    </configuration>
                </execution>
                <execution>
                    <id>pdf-build</id>
                    <phase>generate-resources</phase>
                    <goals>
                        <goal>process-asciidoc</goal>
                    </goals>
                    <configuration>
                        <backend>pdf</backend>
                        <sourceDirectory>src/docs/OrdnerDokument</sourceDirectory>
                        <sourceDocumentName>master.adoc</sourceDocumentName>
                        <outputFile>${project.build.directory}/doc/Dokument.pdf</outputFile>
                        <attributes>
                            <pdf-style>isyfact-closed</pdf-style>
                        </attributes>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----
<1> Es wird die aktuellste Version des Maven Plugins benötigt.
<2> Einfügen der `isy-asciidoctorj-extensions` als Dependency des Maven Plugins.
<3> Die Angabe der `vs-einstufung` ist an dieser Stelle optional und gilt für alle Dokumente.
Üblicherweise wird die `vs-einstufung` in xref:dokumentation/erstellung/erstellung-asciidoctorj.adoc#master.adoc[`master.adoc`] gesetzt.
Dort ist sie verpflichtend, wenn sie nicht schon wie hier in der `pom.xml` gesetzt wurde.
<4> Es ist zu beachten, dass die Konfigurationen im Element `<executions></executions>` zu editieren sind, siehe <<dokument-pom-aufnehmen>>.


[[dokument-pom-aufnehmen]]
== Integration in den Build-Prozess

Jedes Dokument, das während des Build-Prozesses generiert werden soll, muss dafür in die `pom.xml` aufgenommen werden.

Innerhalb von `<executions></executions>` werden die zu generierenden Dokumente definiert.
Für jedes zu generierende Dokument müssen zwei `<execution>`-Elemente vorhanden sein.
Das erste `<execution>`-Element definiert die Erzeugung der HTML-Datei.
Das zweite `<execution>`-Element definiert die Erzeugung der PDF-Datei.

<<listing-pom-asciidoc>> zeigt ein Beispiel.

Folgende Parameter müssen angepasst werden:

[[table-pom_parameter]]
.Anzupassende Parameter
[options="header"]
|====
|Parameter|Beschreibung|Beispiel
|<id></id>| Eine eindeutige Kennung des Dokuments. Sollte Aufschluss über das Dokument und das Ausgabeformat geben.| `mein-dokument-pdf` oder `mein-dokument-html`
|<sourceDirectory></sourceDirectory>| Definiert den Pfad zum Verzeichnis, in dem die `master.adoc` Datei liegt.| `src/docs/OrdnerDokument`
|<outputFile></outputFile>| Definiert Pfad und Dateinamen der Ausgabedatei. | `${project.build.directory}/doc/Dokument.pdf`
|====

Anschließend kann der Build-Vorgang ausgeführt und die PDF- und HTML Dokumente erzeugt werden.

[[dokument-generieren]]
== Dokument generieren

Um den Build-Vorgang zu starten, wird in der Konsole in das Verzeichnis gewechselt, in dem auch die bearbeitete `pom.xml` liegt.
Anschließend wird mit dem Befehl `mvn install` der Build-Vorgang gestartet.
Aufgrund der Vielzahl der zu generierenden Dokumente und auszuführenden Skripte kann der Build-Vorgang einige Zeit in Anspruch nehmen.
Für Test-Zwecke können in der `pom.xml` nicht relevante Dokumente übersprungen werden, indem die zugehörigen Ausführungsdefinitionen (`<execution></execution>`) auskommentiert werden.

=== Fehlerszenarien beim Generieren

[[table-table-asciidoc-fehler]]
.Fehlerszenarien, Ursachen und Lösungen bei der Generierung
[options="header"]
[cols="3,8a",options="header"]
|====
|Fehler|Mögliche Ursachen und Lösungen
|`OutOfMemoryException` (max. HeapSize exceeded) |
Mögliche Ursache:: Bei der Generierung von PDF-Dokumenten werden Rastergrafiken in ein PNM-Format (PPM, PGM oder PBM) konvertiert.
Dies führt bei Dokumenten mit vielen Grafiken oder Grafiken mit sehr hoher Auflösung zu Speicherproblemen.

Problemlösungen::
. *Vektorgrafiken verwenden:* Bei Vektorgrafiken (z. B. im SVG-Format) entfällt die Konvertierung.
. *Herabsetzen der Auflösung:* Bei Bildern mit einer Auflösung von 2000 Pixeln und mehr (egal ob Länge oder Breite) wird empfohlen, die Auflösung nach Möglichkeit zu reduzieren.
Selbst bei der Verwendung vieler kleinerer Bilder kann es zu einer `OutOfMemoryException` kommen.
Der Grund hierfür ist, dass der vom System zur Verfügung gestellte Speicher nach und nach vollläuft.
Tritt der Fehler deswegen auf, sollten Bilder nach Möglichkeit in Vektorgrafiken umgewandelt bzw. neu gezeichnet werden.
|====

[[isy-asciidoctorj-extensions]]
== AsciidoctorJ-Extensions der IsyFact

Die IsyFact Extensions `isy-asciidoctorj-extensions` sind eine Sammlung von verschiedenen AsciidoctorJ-Extensions, welche die Wartung der IsyFact-Dokumentation erleichtern.
Die IsyFact bietet derzeit folgende AsciidoctorJ-Extensions an:

|===
|Extension/Klasse |Beschreibung |Referenzbeispiel

|<<IsyAttributesPreprocessor,IsyAttributesPreprocessor>>

`de.bund.bva.isyfact.attributes` `.IsyAttributesPreprocessor`
|Erzeugt Metainformationen am Anfang eines Dokuments. Erzeugt den Titel und wählt das passende Theme für ein Dokument.
|siehe xref:dokumentation/erstellung/erstellung-asciidoctorj.adoc#master.adoc[master.adoc]
|BibliographyPreprocessor

`de.bund.bva.isyfact.bibliography` `.BibliographyPreprocessor`
|Erzeugt ein Literaturverzeichnis aus allen bekannten Quellen, die im Dokument enthalten und als Referenz markiert sind.
|siehe xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc#literaturverzeichnis[Literaturverzeichnis]
|<<ColophonBlockMacroProcessor,ColophonBlockMacroProcessor>>

`de.bund.bva.isyfact.colophon` `.ColophonBlockMacroProcessor`
|Erzeugt allgemeine Dokumentinformationen durch Verarbeiten des `colophon::[]` Blocks.
|`colophon::[]`
|IsyGlossaryBlockMacroProcessor

`de.bund.bva.isyfact.glossary` `.IsyGlossaryBlockMacroProcessor`
|Erkennt `isy-glossary::[]` im AsciiDoc-Dokument und fügt an der Stelle des Blocks das zentrale Glossar der IsyFact als Tabelle ein.
|`isy-glossary::[]`
|GlossaryPreprocessor

`de.bund.bva.isyfact.glossary` `.GlossaryPreprocessor`
|Erzeugt ein Glossar für das jeweilige Dokument mit allen bekannten Begriffen, die im Dokument enthalten und als Referenz markiert sind.
|siehe xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc#glossar[Glossar]
|ListOfPreprocessor

`de.bund.bva.isyfact.listof` `.ListOfPreprocessor`
|Erzeugt ein Abbildungs-, Tabellen- und Listenverzeichnis für das jeweilige Dokument für alle Elemente im Dokument, die entsprechend markiert sind.
|siehe xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc#bilder[Bilder], xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc#tabellen[Tabellen] und xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc#listings[Listings]
|===

[[isy-attributes-preprocessor]]
=== IsyAttributesPreprocessor

Der `IsyAttributesPreprocessor` wertet alle IsyFact Attribute am Anfang eines `master.adoc` aus (Leerzeichen und Kommentare werden ignoriert) und fügt die entsprechenden Metainformationen in jedes Dokument ein.

Mithilfe der Attribute wird der Titel mit optionalem Untertitel generiert, sowie das passende Theme für das Dokument
ausgewählt. Dabei können xref:dokumentation/erstellung/erstellung-asciidoctorj.adoc#table-master-attributes[folgende Attribute] angepasst werden.

Standardmäßig sind die Extensions auf den Bau von IsyFact-Standards Bausteinen mit einer Open-Source-Lizenz konfiguriert.

[[colophon-block]]
=== ColophonBlockMacroProcessor

Der `ColophonBlockMacroProcessor` erkennt `colophon::[]` Blöcke im AsciiDoc-Dokument und ersetzt diese durch die allgemeinen
Dokumentinformationen der IsyFact.
Die Seite xref:dokumentation/erstellung/erstellung-asciidoctorj.adoc#master.adoc["Neue Dokumente anlegen"] zeigt die  Verwendung des Kolophons in einem AsciiDoc-Dokument.
