// tag::inhalt[]

[[asccidoc-zu-html]]
== HTML-Dokumente erzeugen

Ist das zu bearbeitende Dokument fertiggestellt, so kann es als HTML-Datei als Teil der Gesamtdokumentation generiert werden.
Dies geschieht mithilfe von Antora, einem Open-Source-Tool zur Generierung von HTML-Dokumentation aus Asciidoc-Dateien.
Die Asciidoc-Dateien dürfen in verschiedenen Repositories liegen.

[NOTE]
====
Für die lokale Generierung der Gesamtdokumentation mit Antora steht für interne Nutzer das Repository `isy-antora-playbook` zur Verfügung, das die erforderliche Konfiguration enthält.
Die Vorgehensweise ist in der dort vorhandenen Readme-Datei beschrieben.
Für interne Nutzer ist deshalb die auf dieser Seite beschriebene Anleitung eine Zusatzinformation, die Tätigkeiten sind jedoch nicht notwendig.
====

Für externe Nutzer werden auf dieser Seite die zur Generierung notwendigen Schritte kurz vorgestellt, allerdings auch auf die externe Literatur verwiesen.
Ein paar Besonderheiten bei der Generierung der IsyFact-Gesamtdokumentation werden dennoch vorgestellt.

[[antora-werkzeuge]]
=== Installation der benötigten Werkzeuge

Node.js und Antora müssen auf dem lokalen Rechner installiert werden.
Eine gute Anleitung bietet die xref:glossary:literaturextern:inhalt.adoc#litextern-Antora-Installationen[Antora-Dokumentation].

Eine andere Möglichkeit besteht darin, über das `frontend-maven-plugin` Node.js und Antora im lokalen Projekt zu installieren und über das `exec-maven-plugin` die Generierung der Gesamtdokumentation mit Antora auszuführen.
Eine Anleitung findet sich in xref:glossary:literaturextern:inhalt.adoc#litextern-Antora-Maven[Antora mit Maven].

=== Antora Konfigurationsdatei playbook.yml

Die offizielle Antora-Dokumentation beschreibt die xref:glossary:literaturextern:inhalt.adoc#litextern-Antora-Playbook[Konfigurationsdatei playbook.yml].
Deshalb wird hier nur auf die IsyFact-Besonderheiten eingegangen.

[[listing-playbook]]
.Playbook der IsyFact Standards Dokumentation
[source,yaml]
----
site:
  title: IsyFact Dokumentation
  url: https://github.com/isyfact
  start_page: isyfact-standards-doku:einstieg:vorstellung.adoc
content:
  sources:
    - url: ../isy-documentation   <1>
      branches: HEAD              <2>
      start_path: src/docs/antora
    - url: ../isyfact-standards   <1>
      branches: HEAD
      start_path: isyfact-standards-doc/src/docs/antora

runtime:
  fetch: true
asciidoc:
  attributes:
    version-ifs: 2.5-SNAPSHOT  <3>
    page-toctitle: Inhalt
    sectnums: true             <4>
    sectnumlevels: 5           <5>
    caution-caption: Achtung   <6>
    important-caption: Wichtig
    note-caption: Hinweis
    tip-caption: Tip
    warning-caption: Warnung
    appendix-caption: Anhang
    example-caption: Beispiel
    figure-caption: Abbildung
    table-caption: Tabelle
    listing-caption: Listing
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable              <7>
    snapshot: false                       <8>
  supplemental_files: ./supplemental-ui   <9>
output:
  dir: ./public
----
<1> Die Git-Repositories `isy-documentation` und `isyfact-standards` enthalten xref:glossary:glossary:master.adoc#glossar-Antora-Dokumentations-Komponente[Antora-Komponenten] für die Gesamtdokumentation.
<2> Auf dem lokal ausgecheckten Branch des angegebenen Repositories wird nach Antora-Komponenten gesucht.
<3> Selbstdefiniertes Attribut.
<4> Abschnitte sollen nummeriert werden.
<5> Die Abschnitte dürfen bis Level 5 geschachtelt sein (möglich, aber nicht empfohlen).
<6> Vordefinierte Captions auf deutsch.
<7> Standard-UI von Antora.
<8> Ein stabiles UI ist hilfreich.
<9> Ergänzungen der IsyFact zum Standard-UI.


=== Supplemental UI

Unter dem im Playbook unter `supplemental_files` angegebenen Pfad kann das Standard-UI von Antora leicht mit CSS und JavaScript überschrieben werden.
Dies sollte jedoch nur bei kleineren Änderungen genutzt werden, bei größeren Änderungen empfiehlt es sich, ein eigenes UI zu schreiben, ggf. auf Basis des Standard-UIs.

Eine wichtige Änderung der IsyFact am Standard-UI ist die Verwendung von xref:glossary:literaturextern:inhalt.adoc#litextern-Font-Awesome[Font Awesome]. Eine weitere nützliche CSS-Änderung betrifft den standardmäßigen Nichtumbruch in Listings, der durch folgendes CSS trotzdem durchgeführt wird:

[[listing-css]]
.Zeilenumbruch in Listings
[source,css]
----
div.listingblock pre {
    white-space: pre-wrap;
    font-size: .75rem;
}
----

// end::inhalt[]

