// tag::inhalt[]

[[dokuseite-bearbeiten]]
== Dokumentationsseite bearbeiten

Im Folgenden wird beschrieben, wie Seiten bearbeitet werden müssen, damit sie per Antora generiert werden können.
Außerdem werden Konventionen zur Bearbeitung beschrieben, die es ermöglichen, die IsyFact Dokumentation in einem einheitlichen Stil zur Verfügung zu stellen.

Außerdem gibt es eine xref:seitenvorlage.adoc#seitenvorlage[Seitenvorlage], die kopiert werden kann, und exemplarisch alle gängigen Elemente einer Dokumentationsseite enthält.

Außer diesem Handbuch sind Kenntnisse der AsciiDoc-Syntax erforderlich.

[NOTE]
====
Dieses Handbuch erklärt die Grundlagen der AsciiDoc-Syntax nicht weiter.
Die folgenden Webseiten bieten ausführliche Tutorials und weiterführende Informationen an:

* xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoc[What is AsciiDoc? Why do we need it?] +
* xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoctor-usermanual[Asciidoctor User Manual] +
* xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoc-syntax[AsciiDoc Syntax Quick Reference] +
* xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoc-tutorial[Tutorial: Using AsciiDoc and Asciidoctor to write documentation]
====


[[ein-satz-pro-zeile]]
=== Zeilenumbrüche

Der Quelltext eines Dokuments bricht nach jedem Satz um.
Er orientiert sich nicht anhand einer fixen Spaltenbreite.
Diese Regel wird "ein Satz pro Zeile" (_one sentence per line_, s. xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoc-recommended-practices[AsciiDoc Recommended Practices]) genannt und orientiert sich an der Art und Weise, wie Quellcode organisiert ist (eine Anweisung pro Zeile).

Die Anwendung der Regel "ein Satz pro Zeile" bringt unter anderem folgende Vorteile mit sich:

* Änderungen am Anfang eines Absatzes führen nicht zu Veränderungen an den restlichen Zeilenumbrüchen des Absatzes.
* Einzelne Sätze können mit Leichtigkeit verschoben oder ausgetauscht werden.
* Absätze können durch das Einfügen oder Löschen von Leerzeilen mit Leichtigkeit verbunden oder auseinander gezogen werden.
* Einzelne Sätze können gut auskommentiert oder mit Kommentaren versehen werden.
* Eine Analyse der Zeilenlänge lässt schnell auf zu lange Sätze (z.B. Bandwurm- oder Schachtelsätze) oder andere Anomalien wie eine redundante Schreibweise (z.B. alle Sätze eines Absatzes beginnen gleich) schließen.

Die Regel passt außerdem sehr gut zur gleichzeitigen Verwendung eines modernen Versionsverwaltungssystems, das Branching sowie Merging unterstützt und Merges zeilenweise verarbeitet.
Neue oder gelöschte Sätze kann das Versionsverwaltungssystem leicht interpretieren und zusammenführen, da sie sich auf jeweils unterschiedliche Zeilen auswirken.
Merge-Konflikte passieren häufig auf Ebene eines Satzes.
Sie sind daher leicht verständlich, lokal begrenzt und daher in den meisten Fällen gut zu lösen.


[[ueberschriften]]
=== Überschriften

Überschriften können bei AsciiDoc auf unterschiedliche Weise gesetzt werden.
Bei einer IsyFact-Seite ist stets die Variante zu wählen, bei der die Anzahl der vorgesetzten Gleichheitszeichen die Ebene der Überschrift anzeigt.
Das folgende Beispiel definiert ein Kapitel und ein Unterkapitel.

[[listing-ueberschriften]]
.Syntax von Überschriften
[source,asciidoc]
----
== Hallo Welt Kapitel
Das ist ein Hallo Welt Text zum Kapitel.

=== Hallo Welt Unterkapitel
Das ist ein Hallo Welt Text zum Unterkapitel.
----

Die Überschrift auf der höchsten Ebene ist der xref:seitenvorlage.adoc#struktur-seitentitel[Seitentitel]:

[[listing-seitentitel]]
.Seitentitel
[source,asciidoc]
----
= Seitentitel
Das ist ein Text zum Seitentitel.
----


[[querverweise]]
=== Querverweise

Antora bietet die Möglichkeit, innerhalb einer Gesamtdokumentation beliebige Querverweise zu setzen, auch über xref:dokumentation/erstellung/erstellung-antora.adoc#antora-modul[Antora-Modul] - und xref:dokumentation/erstellung/erstellung-antora.adoc#antora-komponente[Antora-Komponenten] - Grenzen hinweg.
Davon sollte jedoch mit Bedacht Gebrauch gemacht werden, denn sehr starke Verlinkungen der Seiten untereinander bewirken auch eine starke Abhängigkeit.
Jegliche Umbenennungen oder Löschungen von Sprungzielen, dazu gehören auch Seitendatei-, Modul- und Komponentennamen, machen die Querverweise darauf ungültig.
Allerdings weist Antora bei der Generierung der Dokumentation im Log auf nicht auflösbare Querverweise hin.

Generelle Hinweise zur Verwendung von Verweisen siehe xref:seitenvorlage.adoc#struktur-verweise[Seitenvorlage Verweise].

[[anchors]]
==== Sprungziele (Anchor)

Für eine <<ueberschriften,Überschrift>> einer IsyFact-Seite fehlen noch die _Inline-Anchor_, damit durch Klick auf Verweise auf diese Inline-Anchor gesprungen werden kann.
Ein Inline-Anchor wird über eckige Klammern gesetzt.
Außerdem muss die ID des Anchors der xref:methodik:namenskonventionen/inhalt.adoc#dokumentation[Namenskonvention für Namen in Dokumenten] folgen.

[[listing-ueberschriften-final]]
.Überschriften mit Inline Anchors
[source,asciidoc]
----
[[beispiel-kapitel]]
== Beispiel-Kapitel
Das ist ein Beispieltext zum Kapitel.

[[beispiel-unterkapitel]]
=== Beispiel-Unterkapitel
Das ist ein Beispieltext zum Unterkapitel.
----

Auch Abbildungen, Tabellen und Listings müssen mit einem Anchor versehen werden, damit sie als Sprungziel dienen können.

Besonderheiten ergeben sich für Anchor für <<glossar,Glossareinträge>> und <<verweise-extern,externe Verweise>>.

[[verweise-lokal]]
==== Verweise innerhalb einer Seite

In diesem Abschnitt werden Verweise innerhalb einer Seite, d.h. innerhalb einer Asciidoc-Datei, beschrieben.

Ein Querverweis auf eine Überschrift wird über zwei Paare spitzer Klammern gesetzt.

[[listing-querverweis]]
.Querverweis auf eine Überschrift
[source,asciidoc]
----
Zum <<ueberschriften,Beispiel-Kapitel>> gelangen Sie über einen Mausklick.
Im Übrigen handelt es sich bei dem Beispiel-Kapitel um das Kapitel <<ueberschriften>>.
----

Der erste Parameter in dem Klammer-Paar referenziert die ID des Querverweises.
Der zweite Parameter kann gesetzt werden, wenn statt dem Namen des Kapitels ein eigener Text verwendet werden soll.
Der erzeugte Text sieht wie folgt aus:

_Zum <<ueberschriften,Beispiel-Kapitel>> gelangen Sie über einen Mausklick._
_Im Übrigen handelt es sich bei dem Beispiel-Kapitel um das Kapitel <<ueberschriften>>._

Verweise können auch auf andere Sprungziele zeigen als Überschriften, wie Abbildungen, Tabellen und Listings, siehe auch xref:seitenvorlage.adoc#formatierung-verweise[Beispiele für Verweise auf Abbildungen, Tabellen und Listings].


[[verweise-gesamtdoku]]
==== Verweise innerhalb der Antora-Dokumentation

In diesem Abschnitt werden Verweise auf Inline-Anchor beschrieben, die nicht innerhalb derselben Seite in derselben Datei liegen, sondern in anderen Seiten oder anderen xref:dokumentation/erstellung/erstellung-antora.adoc#antora-modul[Antora-Modulen] oder xref:dokumentation/erstellung/erstellung-antora.adoc#antora-komponente[Antora-Komponenten].
Diese Verweise nutzen die Syntax des Xref-Makros von Antora.

Ein xref-Verweis ist bei Antora immer gleich aufgebaut:

[[listing-xref]]
.Verweis Antora
[source,asciidoc]
----
xref:version@component:module:file.adoc#sprungziel[verweistext]
----

Ein Beispiel: +
[[listing-glossar-verweis]]
.Verweis auf einen Glossareintrag
[source,asciidoc]
----
xref:glossary:glossary:master.adoc#glossar-isyfact[IsyFact]
----

Für eine Erläuterung der einzelnen Abschnitte eines xref-Verweises wird auf die Antora-Dokumentation verwiesen:
xref:glossary:literaturextern:inhalt.adoc#litextern-antora-xref-macro-structure[Beschreibung der Struktur des Xref-Makros].
Hier werden dagegen die Konventionen für die Dokumentation der IsyFact beschrieben.

[WARNING]
====
Im xref-Verweis kann eine Version angegeben werden.
Dies darf jedoch in der IsyFact-Dokumentation nicht verwendet werden.
Stattdessen wird keine Version angegeben, wodurch immer die aktuellste Version des Sprungziels in der Antora-Dokumentation referenziert wird.
Explizit angegebene Versionen müssten bei Aktualisierungen angepasst werden, was in einer größeren Dokumentation wie derjenigen der IsyFact nicht mehr durchführbar wäre.
====

Anmerkung: Wenn absichtlich eine bestimmte Version referenziert werden soll und diese sich nie mehr ändert, kann von dieser Konvention abgewichen werden.
Allerdings wird der Verweis ungültig, wenn die referenzierte Version irgendwann als veraltete Version aus der Dokumentation herausgenommen wird.

Die Angaben component und module im xref-Verweis sind ebenfalls optional und sollten nur genutzt werden, wenn sie zur Referenzierung nötig sind, d.h. wenn auf eine andere Antora-Komponente oder ein anderes Antora-Modul verwiesen wird, siehe auch xref:seitenvorlage.adoc#struktur-verweise[Verweise auf andere Seiten].

Beispiele für die Verwendung von xref-Verweisen finden sich hier: xref:seitenvorlage.adoc#formatierung-verweise[Seitenvorlage Verweise].

Ein xref-Verweis könnte auch für Verweise auf derselben Seite in derselben Datei verwendet werden, ist aber aufwendiger und wird daher für diesen Zweck nicht empfohlen.
Stattdessen werden <<verweise-lokal>> empfohlen.


[[verweise-extern]]
==== externe Verweise

In diesem Abschnitt werden Verweise auf Ziele außerhalb der Antora-Dokumentation beschrieben.
I.d.R.handelt es sich um URLs von externen Webseiten, vereinzelt auch um konventionelle Bücher.

// tag::important[]
[IMPORTANT]
====
Damit die externen Verweise leichter auf ihre Gültigkeit überprüft werden können, werden sie an zentraler Stelle gesammelt in `isy-documentation` in der Antora-Komponente `glossary`, Antora-Modul `literaturextern`.
====

// end::important[]

Dort sind alle Einträge mit einem Sprungziel (Anchor) versehen.
In der Dokumentation müssen alle externen Verweise eines dieser Sprungziele referenzieren anstatt direkt die URL.
Der Anchor beginnt immer mit dem Bezeichner `litextern-`.

// tag::namenskonvention[]
[[table-litextern-anchor]]
.Namensschema für Anchor von externen Verweisen (externes Literaturverzeichnis in `isy-documentation`)
[cols="1s,4m",options="header"]
|====
2+|Namen für Anchor im externen Literaturverzeichnis
|Schema |litextern-<Name gemäß allgemeinem Namensschema für Dokumentation>
|Beispiel |litextern-isyfact
|====

// end::namenskonvention[]

Eine Referenz auf einen Eintrag des externen Literaturverzeichnisses erfolgt über einen <<listing-xref,Antora xref-Link>>, wobei der Eintrag nach dem `#` der Anchor im Literaturverzeichnis in `isy-documentation` ist.
Der Text innerhalb der eckigen Klammern definiert den Linktext.

Ein Beispiel: +
[[listing-literaturextern-verweis]]
.externer Verweis
[source,asciidoc]
----
xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoctor-usermanual[Asciidoctor User Manual]
----

Der Link auf einen Literatureintrag sieht wie folgt aus: xref:glossary:literaturextern:inhalt.adoc#litextern-asciidoctor-usermanual[Asciidoctor User Manual]
{empty} +

[[admonition-blocks]]
=== Admonition-Blocks

Mit Admonition Blocks können Inhalte in Dokumenten exponiert dargestellt werden, sodass ihnen besondere Aufmerksamkeit zuteilwird.
Standardmäßig werden fünf verschiedene Blöcke angeboten.
Die IsyFact-Dokumentation erweitert diese Liste um weitere Blöcke für verbindliche Regeln.

Es gibt zwei Möglichkeiten zur Definition von Admonition Blocks.
Die syntaktisch ausführlichere Variante funktioniert sowohl mit den vordefinierten als auch mit den selbst definierten Blöcken.

[[listing-admonition-block]]
.Definition eines Admonition Blocks (als Block)
[source,asciidoc]
----
[BLOCKTYP]
====
Hier steht der Text.
====
----

Die syntaktisch schlankere Variante funktioniert nur mit den vordefinierten Blöcken (NOTE, TIP, IMPORTANT, WARNING und CAUTION).

[[listing-admonition-inline]]
.Definition eines Admonition Blocks (inline)
[source,asciidoc]
----
BLOCKTYP: Hier steht der Text.
----

[[vordefinierte-admonitions]]
==== Vordefinierte Blöcke

Den folgenden, vordefinierten Blöcken fallen in der IsyFact-Dokumentation einheitliche Bedeutungen zu.
Sie helfen dabei, optionale oder ergänzende Inhalte zu markieren, geben Erfahrungswerte weiter und warnen vor typischen Fehlersituationen oder Fallstricken.

[NOTE]
====
Der Block NOTE enthält weiterführende Inhalte, die optionale Ergänzungen des Textes darstellen.
Dies können z.B. interessante Randnotizen oder weiterführende Links, Dokumente sowie Artikel sein.
Der Inhalt der Verweise ist in jedem Fall für die Nutzung der IsyFact optional.

Die Verwendung ist ähnlich zu einer Fußnote gedacht, wobei Verweise von einem erklärenden Satz begleitet sein sollten.
====

[TIP]
====
Der Block TIP enthält optionale Inhalte, die eigene Erfahrungswerte (Good / Best Practices, Tipps & Tricks, ...) einbringen.
Die Inhalte stellen Empfehlungen, aber keine verpflichtenden Regeln dar.
Allgemeine Vorgaben oder Regeln zur Anwendungsentwicklung, Architektur, Sicherheit oder das Styling müssen in jedem Fall über die jeweils dafür gedachten Blöcke formuliert werden!
====

[IMPORTANT]
====
Der Block IMPORTANT beschreibt allgemeine Vorgaben der IsyFact, die sich nicht einem der selbst definierten Blöcke zuordnen lassen.
Die Inhalte stellen verpflichtende Regeln oder Konventionen dar und können bei Nichtbeachtung, je nach Kontext, zu Fehlern, Workarounds oder eingeschränkter Funktionalität führen.
====

[WARNING]
====
Der Block WARNING beschreibt typische Fallstricke, die sich bei der Nutzung der IsyFact (z.B. der beschriebenen Blaupause oder eines Bausteins) ergeben können.
Er warnt davor und bietet Lösungsmöglichkeiten oder hilft, den Fallstrick aktiv zu vermeiden.
====

[CAUTION]
====
Der Block CAUTION beschreibt typische Fehler, die bei der Nutzung der IsyFact passieren können oder in der Vergangenheit häufiger aufgetreten sind.
Die Inhalte sollen diesen Fehlern vorbeugen, um Mehraufwände insbesondere durch subtile Unterschiede, "false friends" oder dergleichen zu vermeiden.

In der Abgrenzung zum Block WARNING stellen die Situationen, die in Blöcken des Typs CAUTION beschrieben werden, entweder eine größere Bedrohung für die korrekte oder rechtzeitige Umsetzung von Anforderungen dar, oder sind, gemessen an ihren Auswirkungen, in der Regel schwer oder erst (zu) spät zu erkennen.
====

[[selbst-definierte-admonitions]]
==== Selbst definierte Blöcke

Die folgenden, selbst definierten Blöcke, bilden Regeln und Vorgaben der IsyFact ab, die verpflichtend einzuhalten sind.
Sie bilden die Grundlage für eine zur IsyFact konforme Umsetzung von Anforderungen und definieren so maßgeblich, wie Konformität zur IsyFact erzielt wird.

.icon:cogs[] Anwendungsanforderung: Beispiel für Anwendungsanforderung
****
Der Block ANWENDUNGSANFORDERUNG beschreibt Anforderungen, welche die IsyFact an die Entwicklung von IT-Systemen stellt.
Die Anforderungen kommen typischerweise aus den Bereichen:

* Struktur des Quellcodes oder der Quellcodeablage,
* Format und Inhalt der Auslieferung,
* Detailaspekte der Verwendung von Bausteinen.

Sie bilden die Grundlage für eine einheitliche Umsetzung von Anforderungen, die in gleichartig strukturierten IT-Systemen münden.
****

.icon:university[] Architekturregel: Beispiel für Architekturregel
****
Der Block ARCHITEKTURREGEL beschreibt Regeln, welche die IsyFact an die Architektur von mit ihr entwickelten IT-Systemen stellt.
Die Regeln zielen somit vor allem auf eine korrekte Umsetzung der Referenzarchitektur ab und sind fast ausschließlich technischer Natur.
Sie bilden die Grundlage für eine einheitliche softwaretechnische Architektur der IT-Systeme.
****

.icon:shield[] Sicherheit: Beispiel für Sicherheitshinweis
****
Der Block SICHERHEIT beschreibt Regeln, welche die IsyFact an die IT-Sicherheit von mit ihr entwickelten IT-Systemen stellt.
Die Regeln stellen vor allem eine, vom festgestellten Schutzbedarf abhängige, sichere Umsetzung der IT-Systeme sicher.
****

.icon:paint-brush[] Styleguide: Beispiel für Styleguide
****
Der Block STYLEGUIDE beschreibt Regeln, welche die IsyFact an die Gestaltung der grafischen Oberflächen stellt.
Die Regeln kommen typischerweise aus den Bereichen:

* Allgemeine Gestaltungsrichtlinien,
* Grundlegender Aufbau von Masken,
* Vorgaben zur Ein- und Ausgabe von Daten sowie zu Interaktionsmustern,
* Barrierefreiheit und Usability.

Die Regeln stellen vor allem sicher, dass grafische Oberflächen ein einheitliches Look&Feel besitzen und gleichartig bedient werden.
****

[[tags-zur-kennzeichnung]]
==== Verwendung von Tags zur Kennzeichnung

Folgende Blöcke sind zusätzlich mit einem Tag zu kennzeichnen:

* IMPORTANT (Tag-Name: `important`)
* ANWENDUNGSANFORDERUNG (Tag-Name: `anwendungsanforderung`)
* ARCHITEKTURREGEL (Tag-Name: `architekturregel`)
* SICHERHEIT (Tag-Name: `sicherheit`)
* STYLEGUIDE (Tag-Name: `styleguide`)
* NAMENSKONVENTION (Tag-Name: `namenskonvention`)

Damit lassen sich die Regeln oder Anforderungen aus der gesamten Dokumentation zusammenziehen und gebündelt bereitstellen, z.B. als Checklisten oder zur Grundlage automatischer Überprüfungen.

Die Tags werden jeweils am Anfang und am Ende des Blocks gesetzt. Setzen des Tags am Beispiel einer Architekturregel:

[source,asciidoc,subs="+macros"]
----
+++// tag::architekturregel[]+++
+++.icon:university[] Architekturregel: Vorgabe+++
+++****+++
Hier steht der Text.
+++****+++

+++// end::architekturregel[]+++
----

WARNING: Die Leerzeile zwischen dem Block und dem Ende des Tags ist wichtig, damit die Bündelung der Inhalte korrekt funktioniert.

Zur Bündelung von Inhalten wird die entsprechende Datei eingebettet.
Über den Parameter `tags` werden nur die Inhalte eingefügt, die von den entsprechenden Tags umgeben sind.

[[listing-include-tags]]
.Bündelung von Inhalten anhand von Tags
[source,asciidoc]
----
\include::pfad_zum_dokument.adoc[tags=beispiel;...]
----

Beispiele für alle selbstdefinierten Admonitions-Blocks finden sich außerdem in xref:seitenvorlage.adoc#formatierung-admonitions[Seitenvorlage Admonitions]. +
{empty} +


[[bilder]]
=== Abbildungen

// tag::important[]
IMPORTANT: Abbildungen zu einer Seite werden stets im Unterordner `/images` unterhalb des Antora-Moduls abgelegt, in dem sich die Seite befindet, siehe auch xref:dokumentation/erstellung/erstellung-antora.adoc#struktur-dokuseite[Struktur Dokumentation].

// end::important[]

// tag::important[]
IMPORTANT: Abbildungen sollten mit diagrams.net als <Name Abbildung>.dn.svg erstellt werden, siehe auch xref:methodik:diagrammerstellung/diagramsnet.adoc#arbeiten-mit-diagrams.net[Arbeiten mit diagrams.net].

// end::important[]

Diagramme, die mit dem xref:methodik:diagrammerstellung/enterprise-architect.adoc[Enterprise Architect] erstellt werden, oder Screenshots, dürfen auch weiterhin als .png eingebunden werden.

// tag::namenskonvention[]
[[table-namenskonvention-bilder]]
.Namensschema für Namen von Abbildungen aus diagrams.net
[cols="1s,4m",options="header"]
|====
2+|Namen für Abbildungen
|Schema |<Name Abbildung gemäß allgemeinem Namensschema für Dokumentation>.dn.svg
|Beispiel |beispiel.dn.svg
|Hinweis | dn bedeutet: erstellt mit diagrams.net
|====

// end::namenskonvention[]

Wenn ein Antora-Modul sehr viele Bilder enthält, kann auch eine Unterstruktur unterhalb von /images angelegt werden, z.B. /images/unterordner.

In einem IsyFact-Dokument muss eine Abbildung:

* eine Beschreibung enthalten,
* eindeutig identifizierbar und referenzierbar sein.

Deswegen werden Abbildungen in IsyFact-Dokumenten wie folgt definiert:

[[image-beispiel]]
.Abbildung einfügen (IsyFact)
[source,asciidoc]
----
[[image-beispiel]]
.Beispiel
 image::beispiel.dn.svg

 image::unterordner/beispiel2.dn.svg
----

Eingebundene Abbildungen können wie üblich über einen Querverweis referenziert werden:

 <<image-beispiel>>

oder, wenn das eingebundene Bild in einer Seite in einem anderen Modul oder einer anderen Komponente liegt:

  xref:component:module:file.adoc#image-beispiel[Text].

Beispiele für Abbildungen finden sich außerdem in xref:seitenvorlage.adoc#formatierung-abbildungen[Seitenvorlage Abbildungen]. +
{empty} +

[[tabellen]]
=== Tabellen

In AsciiDoc wird eine Tabelle über folgende Syntax definiert:

[[listing-tabelle1]]
.Tabelle einfügen
[source,asciidoc]
----
|====
|Zelle 11|Zelle 12|Zelle 13|Zelle 14
|Zelle 21|Zelle 22|Zelle 23|Zelle 24
|Zelle 31|Zelle 32|Zelle 33|Zelle 34
|====
----

Das Ergebnis ist folgende Tabelle:

|====
|Zelle 11|Zelle 12|Zelle 13|Zelle 14
|Zelle 21|Zelle 22|Zelle 23|Zelle 24
|Zelle 31|Zelle 32|Zelle 33|Zelle 34
|====

In einem IsyFact-Dokument muss eine Tabelle aber auch:

- eine Tabellenüberschrift enthalten,
- eindeutig identifizierbar und referenzierbar sein und
- mit einer Kopfzeile beginnen.

Hierfür soll folgende Syntax verwendet werden:

[[listing-tabelle2]]
.Tabelle einfügen in IsyFact
[source,asciidoc,subs="attributes+"]
----
[[table-beispiel]]
.Beispiel einer Tabelle
[cols="1s,1,1,1",options="header"]
|====
|Spalte 1|Spalte 2|Spalte 3|Spalte 4

|Zelle 11|Zelle 12|Zelle 13|Zelle 14
|Zelle 21|Zelle 22|Zelle 23|Zelle 24
|Zelle 31|Zelle 32|Zelle 33|Zelle 34
|====
----

Das Ergebnis sieht dann so aus:

[[table-beispiel]]
.Beispiel einer Tabelle
[cols="1s,1,1,1",options="header"]
|====
|Spalte 1|Spalte 2|Spalte 3|Spalte 4

|Zelle 11|Zelle 12|Zelle 13|Zelle 14
|Zelle 21|Zelle 22|Zelle 23|Zelle 24
|Zelle 31|Zelle 32|Zelle 33|Zelle 34
|====

Die Tabelle kann im AsciiDoc-Text über ihren Anchor referenziert werden:

 <<table-beispiel>>

Beispiele für Tabellen finden sich außerdem in xref:seitenvorlage.adoc#formatierung-tabellen[Seitenvorlage Tabellen]. +
{empty} +

[[listings]]
=== Listings

Quelltexte können bei AsciiDoc auf folgende Weise mit Syntax-Highlighting angezeigt werden.

[[listing-quelltext1]]
.Quelltext einfügen
[source,asciidoc,indent=0]
----
 [source,java]
 ----
 public class HalloWelt {
    public static void main(String[] args) {
        System.out.println("Hallo Welt");
    }
 }
 ----
----

Die Ausgabe sieht wie folgt aus:

[source,java]
----
public class HalloWelt {
    public static void main(String[] args) {
        System.out.println("Hallo Welt");
    }
}
----

Auch hier wird noch eine Listing-Überschrift und ein Anchor benötigt:

[[listing-quelltext2]]
.Quelltext einfügen in IsyFact Dokumentation
[source,asciidoc,subs="attributes+",indent=0]
----
 [[listing-hallowelt]]
 .HalloWelt.java
 [source,java]
 ----
 public class HalloWelt {
     public static void main(String[] args) {
         System.out.println("Hallo Welt");
     }
 }
 ----
----

Das Listing kann im AsciiDoc-Text über seinen Anchor referenziert werden:

 <<listing-hallowelt>>

Beispiele für Listings finden sich außerdem in xref:seitenvorlage.adoc#formatierung-listings[Seitenvorlage Listings]. +
{empty} +


[[glossar]]
=== Glossar

Die IsyFact Dokumentation beinhaltet auch ein Glossar.
Es befindet sich im Repository `isy-documentation` in der xref:dokumentation/erstellung/erstellung-antora.adoc#antora-komponente[Antora-Komponente] `glossary`.
In der HTML-Dokumentation ist es über die Liste der Antora-Komponenten aufrufbar.

// tag::important[]
[IMPORTANT]
====
Neue Glossareinträge sollten alphabetisch einsortiert werden.
Dadurch werden auch doppelte Einträge verhindert.
====

// end::important[]

Im Glossar sind alle Einträge mit einem Sprungziel (Anchor) versehen.
Der Anchor beginnt immer mit dem Bezeichner `glossar-`.

// tag::namenskonvention[]
[[table-glossar-anchor]]
.Namensschema für Anchor von Glossareinträgen (Glossar in `isy-documentation`)
[cols="1s,4m",options="header"]
|====
2+|Namen für Anchor im Glossar
|Schema |glossar-<Name gemäß allgemeinem Namensschema für Dokumentation>
|Beispiel |glossar-isyfact
|====

// end::namenskonvention[]

Eine Referenz auf einen Begriff des Glossars erfolgt über einen <<listing-xref,Antora Verweis>>, wobei der Eintrag nach dem `#` der Anchor im Glossar in `isy-documentation` ist.
Der Text innerhalb der eckigen Klammern definiert den Linktext.

Ein Beispiel: +
[[listing-glossar-verweis-2]]
.Verweis auf Glossareintrag
[source,asciidoc]
----
xref:glossary:glossary:master.adoc#glossar-isyfact[IsyFact]
----

Der Link auf einen Glossareintrag sieht wie folgt aus: xref:glossary:glossary:master.adoc#glossar-isyfact[IsyFact]

// end::inhalt[]
