[[changelog]]
= Changelog

*Änderungen IsyFact 3.1.2*

// tag::release-3.1.2[]

- `IFS-4754`: Einführung von Caching im Authentifizierungsprozess

// end::release-3.1.2[]

*Änderungen IsyFact 3.1.0*

// tag::release-3.1.0[]

- `IFS-3763`: Dokumentation der Änderungen zu IFS-2248 (Tokenerneuerung isy-batchrahmen)

// end::release-3.1.0[]

*Änderungen IsyFact 3.0.0*

// tag::release-3.0.0[]

- `IFS-2302`: Rollen/Rechte-Konfiguration hinzugefügt
- `IFS-1850`: Einleitung zu den Nutzungsvorgaben Security hinzugefügt
- `IFS-1852`: Kapitel zur Authentifizierung eines Clients mit Client Credentials hinzugefügt
- `IFS-2403`: Abschnitt zum OpenId Connect Provider Mock aus isy-security-test hinzugefügt
- `IFS-1854`: Umsetzung des Berechtigungsmanagers
- `IFS-1884`: Umsetzung: Methodensicherheit
- `IFS-1959`: Abschnitt zum Auslesen des Behördenkennzeichens aus Security Context hinzugefügt
- `IFS-1960`: Kapitel zur Authentifizierung eines Clients mit Resource Owner Password Credentials hinzugefügt
- `IFS-1885`: Abschnitt zur Tokenweitergabe hinzugefügt

// end::release-3.0.0[]
