= Nutzungsvorgaben Security: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Dokument beschreibt, wie der Baustein Security und die von ihm bereitgestellte Bibliothek `isy-security` verwendet werden, um die Autorisierung innerhalb von IT-Systemen umzusetzen.
Es richtet sich an Entwickler, die ein IT-System gemäß den Vorgaben der IsyFact mit der Fähigkeit zur Autorisierung ausstatten müssen und beschreibt, wie und in welchen Teilen einer Anwendung die Autorisierung umzusetzen ist.
Der Baustein Security ist OAuth2.0 konform und greift hauptsächlich auf die Möglichkeiten von Spring Security zurück.

Die folgenden Kapitel leiten durch die Funktionen des Bausteins `isy-security`.

* xref:nutzungsvorgaben/master.adoc#software-architektur-security-baustein[Software-Architektur des Security-Bausteins]
* xref:nutzungsvorgaben/master.adoc#aufrufen-von-nachbarsystemen[Aufrufen von Nachbarsystemen]
* xref:nutzungsvorgaben/master.adoc#auth_sgw[Authentifizierung über das SGW am IAM-Service]
* xref:nutzungsvorgaben/master.adoc#absicherung_von_batches_tasks[Absicherung von Batches und Tasks]
* xref:nutzungsvorgaben/master.adoc#absicherung_von_service_schnittstellen[Absicherung von Service-Schnittstellen]

Schließlich beschreibt das letzte Kapitel xref:nutzungsvorgaben/master.adoc#testunterstuetzung[Testunterstützung], welche Hilfen der Baustein *isy-security* zum Erstellen von (automatisierten) Tests bereitstellt.

Die konzeptionellen Aspekte der Authentifizierung und Autorisierung werden im xref:isy-security:konzept/master.adoc[Security - Konzept] beschrieben.

// end::inhalt[]