= Dokumentation gemäß IsyFact

include::glossary:licence:partial$licence.adoc[]

[[einleitung]]
== Einleitung

Dieses Handbuch dient technischen Autoren von IsyFact-Dokumenten als Wegweiser.

Es gibt zwei wesentliche Arten der Dokumentation: <<generierung-antora,Projektseiten mit Antora>> sowie <<generierung-asciidoctorj,PDF- und HTML-Dokumente mit AsciidoctorJ>>.
Allen Versionen gemeinsam ist die Verwendung von AsciiDoc als Grundlage zur Dokumentation.

[[generierung-antora]]
=== Generierung mit Antora

Die Generierung von Projektseiten mit Antora bietet die Möglichkeit, aus Asciidoc-Dateien eine statische HTML-Seite zu erzeugen.

Einzelheiten zur Dokumentation mit Antora finden sich auf den Unterseiten:

* xref:dokumentation/erstellung/erstellung-antora.adoc[],
* xref:dokumentation/bearbeitung/bearbeitung-antora.adoc[],
* xref:dokumentation/generierung/generierung-antora.adoc[].

NOTE: Die <<zentrale-dokumentation,zentrale Dokumentation>> aus dem Repository `isy-documentation` wurde im Zuge der Migration xref:glossary:literaturextern:inhalt.adoc#litextern-url-isyfact-online-docs-source[in ein Submodul des Repositories `isyfact-standards`] verschoben.

Eine wichtige Änderung gegenüber der Generierung mit AsciidoctorJ besteht darin, dass keine Verzeichnisse wie z.B. ein Abbildungsverzeichnis am Ende eines Dokuments mehr erstellt werden.
Stattdessen werden die Inhalte stärker verlinkt, auch auf Inhalte in anderen Repositories.
Es wird z.B. auf ein zentrales Glossar verlinkt.

[[generierung-asciidoctorj]]
=== Generierung mit AsciidoctorJ

Die Generierung von Dokumenten mit AsciidoctorJ ist vor allem dann relevant, wenn als Ergebnis ein PDF-Dokument gefordert ist, oder wenn das Hosten einer Projektseite nicht möglich ist.

Einzelheiten zur Dokumentation mit AsciidoctorJ finden sich auf den Unterseiten:

* xref:dokumentation/erstellung/erstellung-asciidoctorj.adoc[],
* xref:dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc[],
* xref:dokumentation/generierung/generierung-asciidoctorj.adoc[].

AsciidoctorJ-Extensions sorgen dafür, dass die erstellten HTML- und PDF-Dateien automatisch auch über ein Literaturverzeichnis, ein Glossar, ein Abbildungsverzeichnis und ein Tabellenverzeichnis verfügen.

=== Festgelegte Struktur

IsyFact bietet eine strukturierte Sammlung vielfältiger Dokumente, um die Entwicklung von xref:glossary:glossary:master.adoc#glossar-isyfact[IsyFact]-basierenden Anwendungen zu beschreiben.
Für jeden Teilbereich, sei es für den Einstieg, über die xref:glossary:glossary:master.adoc#glossar-konzept[Konzepte] bis hin zu den xref:glossary:glossary:master.adoc#glossar-nutzungsvorgaben[Nutzungsvorgaben] einzelner Module, wird jeweils eine eigene Dokumentation bereitgestellt.
Zur Vereinheitlichung werden alle Dokumentenseiten gemäß festgelegten Regeln und nach einem bestimmten Grundschema angefertigt.
Beispielsweise zeichnet sich jede Dokumentseite durch einen ähnlichen Aufbau aus, um dem Nutzer eine intuitive Handhabe zu gewährleisten.
Weil IsyFact häufig aktualisiert wird und immer wieder auch neue IsyFact-Module hinzugefügt werden, müssen regelmäßig Änderungen in die vorhandenen Dokumentseiten eingepflegt und auch stetig neue Dokumentseiten zur Gesamtdokumentation beigefügt werden.
Dabei sollen nicht nur vorhandene Dokumentseiten, sondern auch neue Dokumentseiten dem gleichen Grundschema und derselben spezifizierten Form gerecht werden, damit die festgelegte Struktur weiterhin beibehalten bleibt.

=== AsciiDoc

Die IsyFact-Dokumentation wird in der vereinfachten Auszeichnungssprache AsciiDoc verfasst.
Eine AsciiDoc-Datei ist nicht binär, sondern besteht aus Klartext, ganz ohne proprietäre Technologie.
Einer der Vorteile der AsciiDoc-Syntax ist die leichte Erlernbarkeit, denn AsciiDoc benötigt denkbar wenige Markups.
AsciiDoc lässt sich zudem problemlos in moderne Versionsverwaltungssysteme integrieren, sodass alle Vorteile solcher Systeme wie z.B. paralleles Arbeiten in Branches, Pull/Merge Requests oder Continuous Integration nun auch auf Dokumente anwendbar sind.

[[werkzeuge]]
=== Erforderliche und empfohlene Werkzeuge

Als Arbeitsumgebung müssen Git und Git LFS installiert sein.
Für die Generierung mit AsciidoctorJ Extensions muss außerdem Maven installiert sein.
Für die Generierung mit Antora wird Maven empfohlen, da die Generierung im Repository `isy-antora-playbook` angestoßen wird und dort eine vorbereitete `pom.xml` dafür bereitgestellt wird.
Es ist aber auch möglich, die Generierung lokal durchzuführen, wenn die entsprechenden Werkzeuge lokal installiert sind.
Für die Generierung mit Antora müssen außerdem Node.js und Antora installiert werden, siehe xref:dokumentation/generierung/generierung-antora.adoc#antora-werkzeuge[Installation Antora Werkzeuge].

Zum Erstellen und Bearbeiten von AsciiDoc-Dateien wird ein Texteditor benötigt, empfohlen wird xref:glossary:literaturextern:inhalt.adoc#litextern-vs-code[Visual Studio Code (VS Code)], sofern nicht der Editor der Entwicklungsumgebung verwendet wird.
VS Code ist ein Texteditor, der von Microsoft entwickelt wird und plattformübergreifend für die Betriebssysteme Windows, macOS und Linux verfügbar ist.
Neben den ausgereiften Plugins für die Bearbeitung von AsciiDoc-Dokumenten: xref:glossary:literaturextern:inhalt.adoc#litextern-vs-code-asciidoc-erweiterung[AsciiDoc Erweiterung für VS Code] unterstützt VS Code Git-basierte Projekte mit vielfältigen Funktionen.


[[architektur-dokumentation]]
== Architektur der Dokumentation

Die Architektur der IsyFact-Dokumentation besteht aus zwei Kernbestandteilen:

. Zentrale Dokumentation
. Dokumentation der IsyFact Erweiterungen

Die zentrale Dokumentation befindet sich im Repository `isyfact-standards`.
Die Dokumentation der IsyFact Erweiterungen befindet sich im Repository, in dem sich der zu dokumentierende Baustein befindet, da die Dokumentation nah beim Code abgelegt werden soll.

Im Folgenden werden die Bestandteile erläutert.

[[zentrale-dokumentation]]
=== Zentrale Dokumentation

Die zentrale Dokumentation bietet Informationen, Nutzungsvorgaben und Anleitungen zu zentralen Themen der IsyFact.
Dazu zählt der Einstieg, das Whitepaper oder auch das Tutorial.

Die zentrale Dokumentation der IsyFact-Standards gliedert sich nach den Säulen der IsyFact.

Allgemein:: Einstiegsdokumente und Tutorials
Blaupausen:: Grundlagendokumente und Detailkonzepte für Architektur und Anwendungslandschaft
Bausteine:: Dokumente für die jeweils wiederverwendbaren Softwarelösungen
Methodik:: Methodische Dokumente, z.B. zu Programmierkonventionen und Systemhandbuch und -entwurf
Werkzeuge:: Dokumente zur Verwendung von Werkzeugen und der Einrichtung der Entwicklungsumgebung (hierzu gehört auch dieses Dokument)

[[baustein-dokumentation]]
==== Dokumentation der Bausteine

Jeder Baustein aus der Säule _Bausteine_ der IsyFact Standards enthält eine eigene Dokumentation.
Hierzu gehören die Nutzungsvorgaben zur Verwendung des Bausteins und das zugrundeliegende Konzept.
Die Nutzungsvorgaben richten sich in erster Linie an Entwickler, die die IsyFact nutzen.
Das Konzept richtet sich an Architekten und Entwickler, die die IsyFact weiterentwickeln.
Wird ein neuer Baustein angelegt, so muss auch eine entsprechende Dokumentation erstellt werden.

[[dokumentation-erweiterungen]]
=== Dokumentation der IsyFact-Erweiterungen

IsyFact-Erweiterungen können als Bausteine optional in einem xref:glossary:glossary:master.adoc#glossar-anwendungssystem[IsyFact Anwendungssystem] verwendet werden.
Sie enthalten ebenfalls ihre eigene Dokumentation, meist in der Form von architektonischen Konzepten sowie Nutzungsvorgaben für die Entwicklung.
