= Seiten anlegen

include::glossary:licence:partial$licence.adoc[]

Soll eine neue Dokumentation angelegt werden oder die bestehende Dokumentation um eine Seite erweitert werden, so muss zunächst das xref:dokumentation/einfuehrung.adoc#struktur-dokumentation[geeignete Repository zur Ablage] bestimmt und ggf. lokal geklont werden.

[[submodul]]
== Submodul

Als Beispiel dient das Repository https://github.com/IsyFact/isyfact-standards[icon:github[] isyfact-standards].
Es enthält ein Submodul zur Dokumentation.
In Repositories, die noch keine Dokumentation enthalten, muss ein derartiges Submodul angelegt werden.

[[verzeichnisstruktur-submodul]]
.Repository mit Submodul zur Dokumentation
----
📂 isyfact-standards
  📂 isyfact-standards-doc <.>
----
<.> Submodul für die Dokumentation.


[[antora-komponente]]
== Antora-Dokumentationskomponente

Innerhalb des Submoduls wird der Pfad `src/docs/antora` angelegt.
Unterhalb dieses Pfades liegt die Antora-Dokumentationskomponente, repräsentiert durch die Konfigurationsdatei `antora.yml`.
In Repositories, die noch keine Antora-Komponente enthalten, muss diese Konfigurationsdatei noch angelegt werden.
Ein Repository sollte jedoch nur eine Antora-Komponente enthalten.

TIP: Mehrere Antora-Komponenten hätten unterschiedliche Versionen, die eventuell nicht mehr synchron zum Versionsstand des Repositories gehalten werden können.


[[verzeichnisstruktur-antora-komponente]]
.Verzeichnisstruktur Antora-Komponente
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
      📂 docs
        📂 antora
          📄 antora.yml <.>
----
<.> Antora Konfigurationsdatei für die Antora-Komponente.

In der `antora.yml`-Datei wird mindestens der Name der https://docs.antora.org/antora/latest/component-version-descriptor/[Dokumentationskomponente] und ihre Version angegeben.

[[antora-modul]]
== Antora-Modul

Im gleichen Verzeichnis wie `antora.yml`, `src/docs/antora`, muss das https://docs.antora.org/antora/latest/standard-directories/[Verzeichnis für die Module] liegen.

In einem Antora-Modul wird die Dokumentation eines Bausteins abgelegt oder die Dokumentation einer Säule der IsyFact.
Unterhalb des Verzeichnisses `modules` wird ein Modul-Verzeichnis mit entsprechendem Namen abgelegt, sofern noch nicht vorhanden.

[[verzeichnisstruktur-antora-modul]]
.Verzeichnisstruktur Antora-Modul
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
      📂 docs
        📂 antora
          📄 antora.yml
          📂 modules <.>
            📂 isy-sonderzeichen <.>
----
<.> Obligatorisches Verzeichnis für Antora-Modul(e).
<.> Modul `isy-sonderzeichen`.

Ein Beispiel für die Aufteilung von Inhalten auf Module findet sich in der Beschreibung der xref:dokumentation/einfuehrung.adoc#struktur-dokumentation[Struktur der Quellen].


[[struktur-dokuseite]]
== Strukturierung innerhalb eines Antora-Moduls

Unterhalb des Modul-Verzeichnisses wird ein Verzeichnis mit Namen `pages` angelegt.
An diesem Ort werden die Dokumentationsseiten abgelegt.
Eine Dokumentationsseite enthält ein in sich abgeschlossenes Thema und entspricht damit in etwa einem Kapitel in konventionellen Dokumenten.
Der Aufbau einer Dokumentationsseite ist in der xref:seitenvorlage.adoc[Seitenvorlage] beschrieben.
Wenn unter `pages` viele Dokumentationsseiten abzulegen sind, können sie xref:seitenvorlage.adoc#dateien-thema[noch weiter strukturiert] werden.

Neben dem Verzeichnis `pages` kann es bei Bedarf https://docs.antora.org/antora/latest/standard-directories/[noch weitere Verzeichnisse], z.B. für Bilder oder Anhänge, geben.
Auch in diesen Verzeichnissen kann eine weitere Strukturierung erfolgen, die sich bestenfalls an der Struktur der Dokumentationsseiten orientiert.

[[verzeichnisstruktur-pages-images]]
.Verzeichnisstruktur innerhalb eines Antora-Moduls
----
📂 isy-sonderzeichen <1>
  📂 images <2>
    📂 konzept <3>
      🖻 sonderzeichen.dn.svg
  📂 pages <4>
    📂 konzept <5>
      📄 sonderzeichen.adoc <6>
    📂 nutzungsvorgaben <5>
      ...
  📄 nav.adoc <7>
----
<1> Modul `isy-sonderzeichen`.
<2> Verzeichnis zur Bildablage für das Modul `isy-sonderzeichen`.
<3> Die Bilder können analog zur Strukturierung unter `pages` abgelegt werden.
<4> Verzeichnis für die eigentlichen Dokumentationsseiten.
<5> Die Dokumentationsseiten können strukturiert abgelegt werden.
<6> Eigentliche Dokumentationsseite.
<7> Beitrag des Moduls zur Navigation.


[[linksnavigation-antora]]
== Navigationsdatei `nav.adoc`
Nach der Erstellung der Dokumentationsseiten muss dafür gesorgt werden, dass sie aufrufbar sind.
Dies geschieht üblicherweise über die Linksnavigation von Antora.
In der Datei `nav.adoc` legt jedes Modul fest, wie seine Dokumentationsseiten in der Linksnavigation bereitgestellt werden.

.Navigation der Online-Dokumentation der IsyFact
====
Die Linksnavigation der Online-Dokumentation spiegelt die Säulen der IsyFact wider.
Die Säulen sind eins zu eins als Antora-Module deklariert.
Diese strukturieren die Linksnavigation weiter.
Unter "Bausteine" befinden sich beispielsweise die Bausteine, die im Repository https://github.com/IsyFact/isyfact-standards[icon:github[] isyfact-standards] dokumentiert werden.
====

Die Navigationsdateien der Module werden in der Konfigurationsdatei der Dokumentationskomponente (`antora.yml`) aufgelistet, damit sie von Antora berücksichtigt werden kann.
Die Verweise aus jeder Navigationsdatei werden in der Reihenfolge der Erwähnung in der Konfigurationsdatei aufgelistet.

[[listing-antora-yml]]
.Beispiel: Linksnavigation der IsyFact
[source,yaml]
----
nav:
- modules/einstieg/nav.adoc
- modules/blaupausen/nav.adoc
- modules/bausteine/nav.adoc
- modules/plattform/nav.adoc
- modules/methodik/nav.adoc
- modules/werkzeuge/nav.adoc
- modules/release/nav.adoc
----

[[listing-nav-adoc]]
.Beispiel: Navigationsdatei `modules/werkzeuge/nav.adoc`
[source,asciidoc]
----
* xref:werkzeuge.adoc[]
** xref:dokumentation/einfuehrung.adoc[]
*** xref:dokumentation/erstellung-antora.adoc[]
**** xref:seitenvorlage.adoc[]
**** xref:kopiervorlage.adoc[]
*** xref:dokumentation/bearbeitung-antora.adoc[]
*** xref:dokumentation/generierung-antora.adoc[]
** xref:dokumentation/changelog-doku.adoc[Changelogs]
** xref:entwicklungsumgebung/master.adoc[Entwicklungsumgebung]
** xref:versionierungskontrolle/master.adoc[]
** xref:gui-tests/gui-tests-mit-selenium.adoc[]
----

Die durch das Beispiel generierte Navigation ist links dieser Seite aufgeklappt zu sehen.

[[konfiguration-antora]]
== Anpassung des Playbooks

Das Playbook befindet sich im Repository https://github.com/IsyFact/isyfact.github.io[icon:github[] isyfact.github.io].
Es steuert die Generierung der Projektseite, also z.B. welche Antora-Komponenten in welchen Repositories und Branches für die Generierung der Gesamtdokumentation verwendet werden sollen.
Das Playbook muss angepasst werden, wenn in einem Repository eine Dokumentation neu erstellt wird, und wenn weitere Branches zur Dokumentengenerierung herangezogen werden sollen.
