= Seiten anlegen

include::glossary:licence:partial$licence.adoc[]

Soll eine neue Dokumentation angelegt werden oder die bestehende Dokumentation um eine Seite erweitert werden, so muss zunächst das xref:dokumentation/einfuehrung.adoc#struktur-dokumentation[geeignete Repository zur Ablage] bestimmt und ggf. lokal geklont werden.

[[submodul]]
== Submodul

Als Beispiel dient das Repository https://github.com/IsyFact/isyfact-standards[icon:github[] isyfact-standards].
Es enthält ein Submodul zur Dokumentation.
In Repositories, die noch keine Dokumentation enthalten, muss ein derartiges Submodul angelegt werden.

[[verzeichnisstruktur-submodul]]
.Repository mit Submodul zur Dokumentation
----
📂 isyfact-standards
  📂 isyfact-standards-doc <.>
----
<.> Submodul für die Dokumentation.


[[antora-komponente]]
== Antora-Dokumentationskomponente

Innerhalb des Submoduls wird der Pfad `src/docs/antora` angelegt.
Unterhalb dieses Pfades liegt die Antora-Dokumentationskomponente, repräsentiert durch die Konfigurationsdatei `antora.yml`.
In Repositories, die noch keine Antora-Komponente enthalten, muss diese Konfigurationsdatei noch angelegt werden.
Ein Repository sollte jedoch nur eine Antora-Komponente enthalten.

TIP: Mehrere Antora-Komponenten hätten unterschiedliche Versionen, die eventuell nicht mehr synchron zum Versionsstand des Repositories gehalten werden können.


[[verzeichnisstruktur-antora-komponente]]
.Verzeichnisstruktur Antora-Komponente
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
        📂 docs
            📂 antora
                📄 antora.yml  <.>
----
<.> Antora Konfigurationsdatei für die Antora-Komponente.

In der `antora.yml`-Datei wird mindestens der Name der xref:glossary:literaturextern:inhalt.adoc#litextern-antora-komponente[Dokumentationskomponente] und ihre Version angegeben.

[[antora-modul]]
== Antora-Modul

Im gleichen Verzeichnis wie `antora.yml`, `src/docs/antora`, muss das xref:glossary:literaturextern:inhalt.adoc#litextern-antora-verzeichnisstruktur[Verzeichnis für die Module] liegen.

In einem Antora-Modul wird die Dokumentation eines Bausteins abgelegt oder die Dokumentation einer Säule der IsyFact.
Unterhalb des Verzeichnisses `modules` wird ein Modul-Verzeichnis mit entsprechendem Namen abgelegt, sofern noch nicht vorhanden.

Das folgende Listing <<verzeichnisstruktur-antora-modul>> zeigt die Verzeichnisstruktur bis zum Antora-Modul.

[[verzeichnisstruktur-antora-modul]]
.Verzeichnisstruktur Antora-Modul `isy-sonderzeichen`
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
        📂 docs
            📂 antora
                📄 antora.yml
                📂 modules               <.>
                    📂 isy-sonderzeichen <.>
----
<.> Obligatorisches Verzeichnis für Antora-Modul(e).
<.> Modul `isy-sonderzeichen`.

Ein Beispiel für die Aufteilung von Inhalten auf Module findet sich in der Beschreibung der xref:dokumentation/einfuehrung.adoc#struktur-dokumentation[Struktur der Quellen].


[[struktur-dokuseite]]
== Strukturierung innerhalb eines Antora-Moduls

Unterhalb des Modul-Verzeichnisses, z.B. `isy-sonderzeichen`, wird ein Verzeichnis mit Namen `pages` angelegt.
An diesem Ort werden die Dokumentationsseiten als `.adoc` abgelegt mit einem Namen, der ihren Inhalt widerspiegelt.

Außer dem Verzeichnis `pages` kann es bei Bedarf noch weitere Verzeichnisse geben wie `images` und `attachments`.
Siehe dazu ebenfalls xref:glossary:literaturextern:inhalt.adoc#litextern-antora-verzeichnisstruktur[Antora-Verzeichnisstruktur].
Unterhalb von `images` und `attachments` kann eine weitere Strukturierung erfolgen, die sich an der Struktur unter `pages` orientiert, siehe auch <<verzeichnisstruktur-pages-images>>.

Wenn unter `pages` viele Dokumentationsseiten abzulegen sind, können sie noch weiter strukturiert werden, siehe auch <<verzeichnisstruktur-pages-images>> und  xref:seitenvorlage.adoc#dateien-thema[Dateiablage].
Für Bausteine wird häufig die Strukturierung `konzept` und `nutzungsvorgaben` gewählt.

Das folgende <<verzeichnisstruktur-pages-images,Listing>> zeigt die Verzeichnisstruktur innerhalb eines Antora-Moduls.

[[verzeichnisstruktur-pages-images]]
.Verzeichnisstruktur innerhalb eines Antora-Moduls
----
📂 isyfact-standards
  📂 isyfact-standards-doc
    📂 src
        📂 docs
            📂 antora
                📄 antora.yml
                📂 modules
                    📂 isy-sonderzeichen <1>
                        📂 images <2>
                            📂 konzept <3>
                                sonderzeichen.dn.svg
                        📂 pages <4>
                            📂 konzept <5>
                                📄 sonderzeichen.adoc <6>
                            📂 nutzungsvorgaben <5>
                                ...
----
<1> Modul `isy-sonderzeichen`.
<2> Verzeichnis zur Bildablage für das Modul `isy-sonderzeichen`.
<3> Die Bilder können analog zur Strukturierung unter `pages` abgelegt werden.
<4> Verzeichnis für die eigentlichen Dokumentationsseiten.
<5> Die Dokumentationsseiten können strukturiert abgelegt werden.
<6> Eigentliche Dokumentationsseite.

[[aufbau-dokuseite]]
== Dokumentationsseite Aufbau

Eine Dokumentationsseite enthält ein in sich abgeschlossenes Thema und entspricht damit in etwa einem Kapitel in konventionellen Dokumenten.

Der Aufbau einer Dokumentationsseite ist in der xref:seitenvorlage.adoc[Seitenvorlage] beschrieben.

[[linksnavigation-antora]]
== Navigationsdatei `nav.adoc`
Nach der Erstellung der Dokumentationsseiten in `.adoc`-Dateien muss dafür gesorgt werden, dass sie aufrufbar sind, üblicherweise über die Linksnavigation von Antora.
In der Antora-Datei `nav.adoc` wird die Linksnavigation bezüglich einer xref:glossary:glossary:master.adoc#glossar-antora-dokumentations-komponente[Antora-Dokumentationskomponente] festgelegt, siehe auch xref:seitenvorlage.adoc#navigation-thema[Navigationsstruktur].

Die Top-Level Linksnavigation der Antora-Komponente `IsyFact Standards` spiegelt die Säulen der IsyFact wider.
Unter `Bausteine` befinden sich beispielsweise die Bausteine, die in `isyfact-standards` dokumentiert werden.
I.d.R. strukturiert sich die Dokumentation eines Bausteins in Konzept und Nutzungsvorgaben, was bei der Linksnavigation beibehalten wird.

Der Name des Bausteins in der Linksnavigation, z.B. "Sonderzeichen", kann nur der Strukturierung dienen, oder er kann auf eine Übersichtsseite für den Baustein verlinken, die kurze Informationen über den Baustein enthält, z.B. die Version.

Die Datei `nav.adoc` wird in `antora.yml` angegeben, damit sie von Antora berücksichtigt werden kann.
Eine Antora-Komponente kann mehrere `nav.adoc` enthalten.
Die Verweise aus jeder `nav.adoc` werden in der Reihenfolge der Erwähnung der `nav.adoc`-Dateien in `antora.yml` aufgelistet.

[[listing-antora-yml]]
.Beispiel `nav.adoc` in `antora.yml`
[source,yaml]
----
nav:
- modules/einstieg/nav.adoc
- modules/blaupausen/nav.adoc
- modules/bausteine/nav.adoc
- modules/plattform/nav.adoc
- modules/methodik/nav.adoc
- modules/werkzeuge/nav.adoc
- modules/changelog/nav.adoc
----

[[listing-nav-adoc]]
.Beispiel Modul `Werkzeuge`, Verlinkung in `nav.adoc`
[source,asciidoc]
----
* xref:werkzeuge.adoc[]
** xref:dokumentation/einfuehrung.adoc[]
*** xref:dokumentation/erstellung-antora.adoc[]
**** xref:seitenvorlage.adoc[]
**** xref:kopiervorlage.adoc[]
*** xref:dokumentation/bearbeitung-antora.adoc[]
*** xref:dokumentation/generierung-antora.adoc[]
** xref:dokumentation/changelog-doku.adoc[Changelogs]
** xref:entwicklungsumgebung/master.adoc[Entwicklungsumgebung]
** xref:versionierungskontrolle/master.adoc[]
** xref:gui-tests/gui-tests-mit-selenium.adoc[]
----

Die durch das Beispiel generierte Navigation ist links dieser Seite aufgeklappt zu sehen.

[[konfiguration-antora]]
== Anpassung des Playbooks

Das Playbook befindet sich im Repository https://github.com/IsyFact/isy-antora-playbook[icon:github[] isy-antora-playbook].
Es steuert die Generierung der Projektseite, also z.B. welche Antora-Komponenten in welchen Repositories und Branches verwendet werden sollen für die Generierung der Gesamtdokumentation.
Das Playbook muss angepasst werden, wenn in einem Repository eine Dokumentation neu erstellt wird, und wenn weitere Branches zur Dokumentengenerierung herangezogen werden sollen.
