= Projektseite erzeugen

include::glossary:licence:partial$licence.adoc[]

Die Generierung einer Projektseite erfolgt, falls das Repository xref:glossary:literaturextern:inhalt.adoc#litextern-isyfact-antora[icon:github[] isy-antora-playbook] verwendet wird, wie in vergleichbaren npm-Projekten.
Nachdem alle Abhängigkeiten installiert wurden, wird die Projektseite mit dem Befehl `npm build` erzeugt.

== Aufbau des Playbooks

Die offizielle Antora-Dokumentation beschreibt das xref:glossary:literaturextern:inhalt.adoc#litextern-antora-playbook[Playbook].
Deshalb wird hier nur auf die IsyFact-Besonderheiten eingegangen.

[[listing-playbook]]
.Playbook der Online-Dokumentation
[source,yaml]
----
site:
  title: IsyFact Dokumentation
  url: https://github.com/isyfact
  start_page: isyfact-standards-doku:einstieg:vorstellung.adoc
content:
  sources:
    - url: ../isy-documentation   <1>
      branches: HEAD              <2>
      start_path: src/docs/antora
    - url: ../isyfact-standards   <1>
      branches: HEAD
      start_path: isyfact-standards-doc/src/docs/antora

runtime:
  fetch: true
asciidoc:
  attributes:
    page-toctitle: Inhalt
    sectnums: true             <3>
    sectnumlevels: 5           <4>
    caution-caption: Achtung   <5>
    important-caption: Wichtig
    note-caption: Hinweis
    tip-caption: Tipp
    warning-caption: Warnung
    appendix-caption: Anhang
    example-caption: Beispiel
    figure-caption: Abbildung
    table-caption: Tabelle
    listing-caption: Listing
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable <6>
    snapshot: false                       <7>
  supplemental_files: ./supplemental-ui   <8>
output:
  dir: ./public
----
<1> Die Git-Repositories `isy-documentation` und `isyfact-standards` enthalten Antora-Komponenten für die Online-Dokumentation.
<2> Auf dem lokal ausgecheckten Branch des angegebenen Repositories wird nach Antora-Komponenten gesucht.
<3> Abschnitte sollen nummeriert werden.
<4> Die Abschnitte dürfen bis Level 5 geschachtelt sein (möglich, aber nicht empfohlen).
<5> Vordefinierte Captions auf Deutsch.
<6> Standard-UI von Antora.
<7> Ein stabiles UI ist hilfreich.
<8> Ergänzungen der IsyFact zum Standard-UI.


== Supplemental UI

Unter dem im Playbook unter `supplemental_files` angegebenen Pfad kann das Standard-UI von Antora leicht mit CSS und JavaScript überschrieben werden.
Dies sollte jedoch nur bei kleineren Änderungen genutzt werden, bei größeren Änderungen empfiehlt es sich, ein eigenes UI zu schreiben, ggf. auf Basis des Standard-UIs.
