[[changelog]]
= Changelog

*Änderungen IsyFact 4.0.0*

- `IFS-2786`: Migrationsleitfaden IsyFact 2 entfernt, da große Teile obsolet wurden.
- `IFS-2788`: Redundanten Leitfaden zum Enterprise Architect (Teil der Systemspezifikation) entfernt.



*Änderungen IsyFact 3.0.0*

- `IFS-2272`: Vorlage Systementwurf: SUSE Linux durch Linux 64bit Kernel >= 4.12 ersetzt
- `IFS-1941`: Dokumentationsvorgaben für IF Bestandteile initial festgeschrieben.
- `IFS-2271`: Entfernen von Oracle JDK, stattdessen Verweis auf Produktkatalog
- `IFS-1526`: Migration der Vorlage zur Produktauswahl in die Online-Dokumentation.
- `IFS-1524`: Migration der Vorlage der Schnittstellendokumentation in die Online-Dokumentation.
- `IFS-1521`: Migration der Vorlage der Anforderungsliste in die Online-Dokumentation.
- `IFS-1520`: Migration der Vorlage der Systemspezifikation in die Online-Dokumentation.
- `IFS-1519`: Migration der Vorlage für Datenflussdiagramme in die Online-Dokumentation.
- `IFS-1515`: Migration der Vorlage des Tailoring-Dokuments in die Online-Dokumentation.


