= Diagrammerstellung und Modellierung

:experimental:

include::glossary:licence:partial$licence.adoc[]

[[modellierung-und-diagrammerstellung]]
== Modellierung und Diagrammerstellung
Schaubilder, Diagramme und grafische Modelle unterstützen das Verständnis von Inhalten.
Die Ausprägungen von Diagrammen sind vielfältig:
Insbesondere grenzen sich durch Modelle getriebene, stark formalisierte Darstellungen und Diagramme von freieren Schaubildern ab.
Abhängig von den Anforderungen an die Diagrammerstellung kommen grundsätzlich unterschiedliche Werkzeugen mit ebenso unterschiedlichen Stärken und Schwächen infrage.

Die IsyFact empfiehlt die Verwendung von *diagrams.net* und *Enterprise Architect*.

[[table-anforderungen]]
.Entscheidungshilfe zur Auswahl eines Werkzeugs zur Diagrammerstellung
[cols="5,1,1",options="header"]
|===
|Anforderung an die Diagrammerstellung|Enterprise Architect|diagrams.net
|Einheitlichkeit der Diagramme (z.B. über Schablonen)|ja|eingeschränkt¹
|Diagramme können in AsciiDoc integriert werden|ja|ja
|Quelldateien können einzeln als Teil des Quellcodes abgelegt werden|ja²|ja
|Bilder für Diagramme können automatisch gebaut werden|nein³|ja
|Unterstützung von UML-Daten-Modellen|ja|nein
|Einfachheit der Bedienung|nein|ja
|Keine Abhängigkeiten zu Arbeitsplatzumgebungen|nein|ja
|===
¹ Bietet nur Grafikvorlagen - keine echten UML-Profile. +
² Möglich, aber widerspricht dem Modellansatz. +
³ Automatisches Bauen nur über Frameworks wie docToolchain; bisher kein Plan zur Standardisierung.

[[einsatzszenarien_diagrams_net]]
== Einsatzszenarien diagrams.net

https://diagrams.net[_diagrams.net_] eignet sich insbesondere für:

* Diagramme und Schaubilder, die nicht UML-konform sein müssen,
* Mockups und andere Diagrammtypen.

Eine wesentliche Stärke des Werkzeugs ist die Speicherung des editierbaren Quellmodells im Zielbild (in den Formaten PNG und SVG).
Durch direktes Ablegen der Datei beim Code ist keine getrennte Datenhaltung oder Generierung erforderlich.
Die Datei kann direkt eingebunden werden.

NOTE: Für das Wiki-System _Confluence_ sowie das Ticket-System _Jira_ der Firma _Atlassian_ gibt es das Add-on _draw.io_, welches das Erstellen und Bearbeiten von Diagrammen erlaubt und im Kern _diagrams.net_ entspricht.
Die Erstellung von Diagrammen im Kontext Wiki-getriebener Dokumentation erfolgt somit voll integriert.

Die IsyFact bietet xref:diagrammerstellung/diagramsnet.adoc[eine Konfiguration sowie vorgefertigte Elemente] für die Erstellung von Diagrammen mit diagrams.net.

[[einsatzszenarien_enterprise_architect]]
== Einsatzszenarien Enterprise Architect

https://sparxsystems.com/products/ea/[_Enterprise Architect_] wird häufig verwendet, um modellgetriebene Diagramme für Systemspezifikationen und Systementwürfe zu erstellen, da diese Dokumente:

* hauptsächlich UML- und ER-Diagramme enthalten,
* UML-Profil-fähig und konform sein sollen und,
* die Verwendung eines UML-Datenmodells die Wartung und Sicherstellung der Konsistenz der Daten und Diagramme gewährleistet.

Die Herausforderungen dieses Werkzeugs sind:

* die Trennung von zentralem Modell und i.d.R. manueller Generierung der erforderlichen Diagramme,
* die steile Lernkurve und komplexe Bedienung,
* Einschränkungen und längere Bearbeitungszeit bei freien Schaubildern.

Die IsyFact bietet xref:diagrammerstellung/enterprise-architect.adoc#uml-profile-einbinden[UML-Profile] an und unterstützt die xref:diagrammerstellung/enterprise-architect.adoc#vorgehen-zur-erstellung-der-spezifikationsdokumente[Erstellung von Systemspezifikationen] mit dem Enterprise Architect.
