= Konventionen und Vorgaben Dokumentation

include::glossary:licence:partial$licence.adoc[]


[[konventionen-vorgaben-zur-dokumentation]]
== Konventionen und Vorgaben zur Dokumentation der IsyFact

Die Dokumentation der IsyFact ist über die xref:einstieg:vorstellung.adoc#isyfact-aufbau[Säulen] bis auf die Ebene darunter strukturiert.
Bestimmte Bestandteile der IsyFact teilen dabei gemeinsame Merkmale.
Aus diesem Grund können Konventionen und Vorgaben zur Dokumentation von IsyFact-Bestandteilen die strukturell-inhaltliche Einheitlichkeit der Beschreibung gewährleisten.

Folgende Maßnahmen unterstützen die Standardisierung:

Methodik und Richtlinien für fachliche und technische Modellierung::
* xref:diagrammerstellung.adoc[]

Methodik zur Dokumentation von Anwendungen::
* xref:vorlagen.adoc#dokumentation-anwendung[Vorlagen zur Dokumentation von Anwendungen]

Methodik zur Dokumentation der IsyFact::
* xref:vorgaben-dokumentation/dokumentationstypen.adoc[]
* xref:documentation-guide:ROOT:index.adoc[]

[[dokumentation-saeulen]]
== Dokumentation der Säulen

Ein allgemeiner Überblick über die IsyFact findet sich im Hauptknoten *xref:einstieg:einstieg.adoc[]* und seinen Unterseiten.
Dazu zählen das xref:einstieg:tutorial/master.adoc[] und das xref:einstieg:whitepaper.adoc[Whitepaper].

Die xref:vorgaben-dokumentation/dokumentationstypen.adoc#saeule-referenzarchitektur[Dokumentation der *Referenzarchitektur*] enthält xref:vorgaben-dokumentation/dokumentationstypen.adoc#table-detailkonzept[_Detailkonzepte_].

Die xref:vorgaben-dokumentation/dokumentationstypen.adoc#saeule-bausteine[Dokumentation der *Bausteine*] erfolgt abhängig von ihrer Ausprägung (u.a. Software-Bibliothek, Querschnittsanwendung).
In der folgenden Abbildung können die xref:methodik:vorgaben-dokumentation/dokumentationstypen.adoc[Dokumentationstypen] abgelesen werden, mit denen ein Baustein dokumentiert wird. 

[[image-dokumentationstypen-bausteinauspraegung]]
.Dokumentationstypen je Bausteinausprägung
image::methodik:dokumentationstypen-bausteinauspraegung.dn.svg[]

Die xref:vorgaben-dokumentation/dokumentationstypen.adoc#saeule-plattform[Dokumentation der *Plattform*] enthält für jede von der IsyFact empfohlene oder eingesetzte Technologie zum Betrieb von IT-Systemen (z.B. HTTP- und Applikationsserver, Datenbanken) ein xref:vorgaben-dokumentation/dokumentationstypen.adoc#table-nutzungskonzept[_Nutzungskonzept_].

Die Dokumentation der *Methodik* bietet neben der Dokumentation des methodischen Vorgehens Vorlagen für  Dokumentationstypen sowie hilfreiche Arbeitsmittel zur Durchführung eines IsyFact-Projektes.

Schließlich umfasst die Dokumentation der *Werkzeuge* eine Beschreibung pro Werkzeug, welche die Nutzung begründet und Nutzungsvorgaben festlegt.
