= Vorlagen Übersicht
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

[[einleitung]]
== Einleitung

An dieser Stelle werden Vorlagen für den xref:vorlage-systementwurf/antora-master.adoc[Systementwurf] und das xref:vorlage-systemhandbuch/antora-master.adoc[Systemhandbuch] angeboten.
Die Vorlagen können sowohl direkt aufgerufen als auch im ZIP-Format heruntergeladen werden.

Die Seite beschreibt im Folgenden, wie aus den Vorlagen PDF-Dokumente erstellt werden und wie Änderungen an den Vorlagen selbst vorzunehmen sind.

[[erstellung-pdf]]
== Erstellung von PDF-Dokumenten

Die Vorlagen enthalten Asciidoc-Dateien, die projektspezifisch ergänzt werden müssen.
Nach Bedarf kann aus den Asciidoc-Dateien für jede Vorlage ein PDF erstellt werden.
Das Modul `isy-documentation` bietet diese Erstellung an.
Die Vorgehensweise wird anhand der Vorlage für den Systementwurf beschrieben.
Analoges gilt für das Systemhandbuch.

Zunächst wird die heruntergeladene Datei entpackt.
Der gesamte Inhalt des Archivs wird in `isy-documentation` in den Ordner `src/docs/vorlagen/isyfact-vorlage-systementwurf` kopiert.
Danach wird `mvn generate-resources` ausgeführt.
Der generierte Systementwurf im PDF-Format befindet sich nun unter `target/doc/pdf/vorlagen/isyfact-vorlage-systementwurf`.


[[erzeugung-zip]]
== Bearbeitung der Vorlagen

Wenn die Vorlagen in `isyfact-standards` geändert wird, müssen auch die Downloads im ZIP-Format erneut generiert werden.
Dazu wird im Maven Submodul `isyfact-standards-doc` der Maven-Befehl `mvn package` ausgeführt.
Die ZIP-Archive der Vorlagen befinden sich nun in `isyfact-standards-doc` im Ordner `src/docs/antora/modules/methodik/attachments/vorlage-generated`.
