= Vorlagen

include::glossary:licence:partial$licence.adoc[]

[[bearbeitung-vorlagen-projektspezifisch]]
== Allgemeines

Die Vorlagen unterstützen die Erstellung projektspezifischer Dokumentation wesentlich.
Sie enthalten Word-, Excel- oder AsciiDoc-Dateien, die im Projektverlauf gefüllt werden müssen.

Nach Bedarf können für die dauerhafte Ablage aus Word- und AsciiDoc-Vorlagen PDF-Dokumente erzeugt werden.
Für Word-Vorlagen wird hierzu die integrierte Funktion von Word genutzt.
Für AsciiDoc-Vorlagen kann https://docs.asciidoctor.org/pdf-converter/latest/[Asciidoctor PDF] verwendet werden.

Word- und Excel-Vorlagen können direkt von dieser Seite als Download bezogen werden.
AsciiDoc-Vorlagen können sowohl direkt aufgerufen als auch im ZIP- oder PDF-Format heruntergeladen werden.


[[dokumentation-anwendung]]
== Dokumentation einer Anwendung

Die Vorlagen zur Dokumentation einer Anwendung beschreiben diese aus den drei aus der Referenzarchitektur bekannten Sichten:

* Systemspezifikation: fachliche Sicht,
* Systementwurf: software-technische Sicht,
* Systemhandbuch: Sicht der technischen Infrastruktur.

Alle Vorlagen enthalten Ausfüllhinweise und Beispiele.

Die Vorlage Systemspezifikation enthält die Gliederung für eine V-Modell-konforme Gesamtsystemspezifikation (Pflichtenheft) eines Softwaresystems (Software-Entwicklungsprojekts).

[[table-dokumentation-anwendung]]
.Vorlagen zur Dokumentation einer Anwendung
[cols="1s,1,1,1,1",options="header"]
|====
.^|Vorlage
.^|Quelldatei +
(AsciiDoc)
3+^.^|Downloads (ZIP, PDF, Word)

|Systemspezifikation
|xref:vorlage-systemspezifikation/master.adoc[Ansehen icon:file-text-o[]]
2+|
|xref:methodik:attachment$spezifikation/IsyFact-Vorlage_Systemspezifikation.dotx[Download icon:file-word-o[]]

|Systementwurf
|xref:vorlage-systementwurf/antora-master.adoc[Ansehen icon:file-text-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systementwurf.zip[Download icon:file-archive-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systementwurf.pdf[Download icon:file-pdf-o[]]
|xref:methodik:attachment$entwurf-handbuch/IsyFact-Vorlage_Systementwurf.dotx[Download icon:file-word-o[]]

|Systemhandbuch
|xref:vorlage-systemhandbuch/antora-master.adoc[Ansehen icon:file-text-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systemhandbuch.zip[Download icon:file-archive-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systemhandbuch.pdf[Download icon:file-pdf-o[]]
|xref:methodik:attachment$entwurf-handbuch/IsyFact-Vorlage_Systemhandbuch.dotx[Download icon:file-word-o[]]

|====


[[fachliche-schnittstellendokumentation]]
== Fachliche Schnittstellendokumentation

Die Vorlage enthält die Gliederung für eine V-Modell-konforme Schnittstellendokumentation eines Softwaresystems (Software-Entwicklungsprojekts) mitsamt Ausfüllhinweisen und Beispielen.

[[table-schnittstellendokumentation]]
.Vorlage zur Schnittstellendokumentation
[cols="1s,1,1",options="header"]
|====
.^|Vorlage
.^|Quelldatei (AsciiDoc)
.^|Download (Word)

|Schnittstellendokumentation
|xref:methodik:vorlage-schnittstellendokumentation/master.adoc[Ansehen icon:file-text-o[]]
|xref:methodik:attachment$spezifikation/IsyFact-Vorlage_Schnittstellendokumentation.dotx[Download icon:file-word-o[]]
|====


[[datenflussdiagramm]]
== Datenflussdiagramm

Eine Anwendungslandschaft besteht aus mehreren Anwendungen, die Daten untereinander und mit ihren Anwendern austauschen.
Die Anleitung zu Datenflussdiagrammen hilft bei der Erstellung von Datenflussdiagrammen und gibt Best Practices zur strukturierten Beschreibung dieses Datenflusses.

[[table-datenflussdiagramm]]
.Vorlage zu Datenflussdiagrammen
[cols="1s,1,1",options="header"]
|====
.^|Vorlage
.^|Quelldatei (AsciiDoc)
.^|Download (Word)

|Datenflussdiagramm
|xref:methodik:anleitung-datenflussdiagramme/master.adoc[Ansehen icon:file-text-o[]]
|xref:methodik:attachment$spezifikation/Anleitung_zu_Datenflussdiagrammen.dotx[Download icon:file-word-o[]]
|====


[[anforderungsliste]]
== Anforderungsliste

Die Anforderungsliste ist ein Instrument, um die Übersicht und die Nachvollziehbarkeit des Umsetzungsstatus aller Anforderungen an ein System im gesamten Projektlebenszyklus zu erhalten.
Die Anforderungsliste beschreibt mit jeder Anforderung eine Eigenschaft, die eine Anwendung haben soll.
Dies kann eine bestimmte Funktionalität oder auch eine Anforderung in Hinblick auf die Qualität sein, zum Beispiel die maximale Reaktionszeit bei einer Eingabe.
Die Anforderungsliste ist bei ihrer Erstellung und bei jeder Versionierung ein Mittel der Kommunikation zwischen Auftraggeber und Auftragnehmer.

[[table-anforderungsliste]]
.Vorlage zur Anforderungsliste
[cols="1s,1",options="header"]
|====
.^|Vorlage
.^|Quelldatei (Excel)

|Anforderungsliste
|xref:methodik:attachment$spezifikation/IsyFact-Vorlage-Anforderungsliste.xlsx[Download icon:file-excel-o[]]
|====


[[produktauswahl]]
== Produktauswahl

Das Template Produktauswahl liefert eine Vorlage zur Beschreibung der Hintergründe zur Auswahl eines Produkts in Projekten.

[[table-produktauswahl]]
.Vorlage zur Produktauswahl
[cols="1s,1",options="header"]
|====
.^|Vorlage
.^|Quelldatei (Word)

|Produktauswahl
|xref:methodik:attachment$produktauswahl/Template_Produktauswahl.dotx[Download icon:file-word-o[]]
|====
