= Vorlagen
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

[[einleitung]]
== Einleitung

An dieser Stelle werden Vorlagen für den Systementwurf und das Systemhandbuch angeboten.
Die Vorlagen können sowohl direkt aufgerufen als auch im ZIP- oder PDF-Format heruntergeladen werden.

.Vorlagen
[id="table-Vorlagen",reftext="Vorlagen"]
[cols="1,1"]
|====
|xref:vorlage-systementwurf/antora-master.adoc[Systementwurf ansehen icon:file-text-o[]]
|xref:vorlage-systemhandbuch/antora-master.adoc[Systemhandbuch ansehen icon:file-text-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systementwurf.zip[Download Systementwurf icon:file-archive-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systemhandbuch.zip[Download Systemhandbuch icon:file-archive-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systementwurf.pdf[Download Systementwurf icon:file-pdf-o[]]
|xref:methodik:attachment$vorlage-generated/IsyFact-Vorlage-Systemhandbuch.pdf[Download Systemhandbuch icon:file-pdf-o[]]
|====

[[bearbeitung-vorlagen-projektspezifisch]]
== Projektspezifische Bearbeitung der Vorlagen

Die Vorlagen enthalten Asciidoc-Dateien, die projektspezifisch ergänzt werden müssen.
Nach Bedarf kann aus den Asciidoc-Dateien für jede Vorlage ein PDF erstellt werden.
Die PDF-Generierung mittels AsciidoctorJ-Extensions wird in xref:werkzeuge:handbuch_dokumentation/inhalt.adoc#asccidoc-zu-pdf-html[Dokumentation der IsyFact] erklärt.

[[bearbeitung-vorlagen-selbst]]
== Bearbeitung der Vorlagen selbst

Wenn die Vorlagen in `isyfact-standards` geändert werden, müssen auch die Downloads im ZIP- und PDF-Format erneut generiert werden.
Dazu wird im Maven Submodul `isyfact-standards-doc` der Maven-Befehl `mvn package` ausgeführt.
Die ZIP-Archive und PDF-Dokumente der Vorlagen befinden sich nun in `isyfact-standards-doc` im Ordner `src/docs/antora/modules/methodik/attachments/vorlage-generated`.
