[[changelog]]
= Changelog

*Änderungen IsyFact 2.4.0*

// tag::release-2.4.0[]
- `RF-1040`: Scope für Spotbugs-Annotation Abhängigkeit auf provided gesetzt
// end::release-2.4.0[]

*Änderungen IsyFact 2.2.0*

// tag::release-2.2.0[]
- `IFS-568`: Entfernt redundante Methode `getMessage(String schluessel)` aus dem MessageSourceHolder
// end::release-2.2.0[]

// *Änderungen IsyFact 2.1.0*

// tag::release-2.1.0[]
// end::release-2.1.0[]

*Änderungen IsyFact 2.0.0*

// tag::release-2.0.0[]
- `IFS-32`: Package-Name auf de.bund.bva.isyfact geändert
// end::release-2.0.0[]

// *Änderungen IsyFact 1.8.0*

// tag::release-1.8.0[]
// end::release-1.8.0[]

*Änderungen IsyFact 1.7.0*

// tag::release-1.7.0[]
// Interne alte Version: 1.8.0
- `IFS-262`: `isyfact-masterpom` deprecated (Abschaffung mit IsyFact 2.0), `isyfact-masterpom-lib` aufgelöst, Bibliotheken benutzen `isyfact-standards` als Parent-POM
// end::release-1.7.0[]

*Änderungen IsyFact 1.6.0*

// tag::release-1.6.0[]
// Interne alte Version: 1.7.0
- `IFS-189`: Repositories der IsyFact-Standards zusammengeführt, Bibliotheken benutzen wieder gemeinsames Produkt-BOM und werden zentral über das POM isyfact-standards versioniert
// end::release-1.6.0[]

*Änderungen IsyFact 1.5.0*

// tag::release-1.5.0[]
// Interne alte Version: 1.6.0
- `IFS-111`: Abhängigkeit von isy-util auf isy-serviceapi-sst aufgelöst. StelltLoggingKontextBereitInterceptor nach isy-serviceapi-core verschoben.
**Achtung**: Dieses Ticket nimmt die Änderungen von `IFS-9` (s. v1.5.1) zurück. Der `checkAndUpdate()`-Task der Konfiguration kann in Zukunft direkt über die Bibliothek `isy-task` eingebunden und konfiguriert werden.
- `IFS-120`: Der StelltLoggingKontextBereitInterceptor erzeugt keine Warn-Logausgabe mehr, wenn eine StelltLoggingKontextBereit-Annotation mit dem Parameter nutzeAufrufKontext = false definiert ist.
// end::release-1.5.0[]

*Änderungen IsyFact 1.4.0*

// tag::release-1.4.0[]
// Interne alte Version: 1.5.1
- `RF-161`: Bibliotheken binden genutzte Bibliotheken direkt ein und nicht mehr über BOM-Bibliotheken
- `IFS-9`: StelltLoggingKontextBereit-Annotation auch ohne AufrufkontextTo nutzbar
// end::release-1.4.0[]

// *Änderungen IsyFact 1.3.5*

// tag::release-1.3.5[]
// end::release-1.3.5[]

// *Änderungen IsyFact 1.3.0*

// tag::release-1.3.0[]
// end::release-1.3.0[]

