= Fachliche Referenzarchitektur

Die fachliche Referenzarchitektur beschreibt die Strukturierung von Anwendungslandschaften aus fachlicher Sicht und legt fest, wie Anwendungen in die Anwendungslandschaft integriert werden.

[[awl-fachliche-architektur]]
== Fachliche Architektur einer Anwendungslandschaft

[[awl-fachlich]]
.Fachliche Architektur einer Anwendungslandschaft
image::referenzarchitektur:fachlich/fachliche-referenzarchitektur-anwendungslandschaft.dn.svg[]

Zur Strukturierung der xref:glossary::terms-definitions.adoc#glossar-anwendungslandschaft[Anwendungslandschaft] werden drei fachliche Hierarchieebenen festgelegt.

[[domaene]]
=== Domäne

Auf der obersten Hierarchieebene werden xref:glossary::terms-definitions.adoc#glossar-domaene[Domänen] gebildet.
Eine Domäne gruppiert fachlich zusammengehörende Anwendungen zur Unterstützung von Geschäftsprozessen, die als eine Einheit angesehen werden können.
In <<awl-fachlich,der obigen Abbildung>> wurden zwei Domänen gebildet.
Zwischen den Anwendungen unterschiedlicher Domänen sollten nur wenige, klar definierte Nutzungsbeziehungen existieren.

[[anwendung]]
=== Anwendung

include::glossary::terms-definitions.adoc[tag="anwendung-definition"]

[[anwendungskomponente]]
=== Anwendungskomponente

Eine Anwendungskomponente beschreibt eine Menge funktional zusammenhängender Anwendungsfälle.
Anwendungskomponenten sind Bestandteile von Anwendungen.
Im Rahmen weitergehender Architekturvorgaben beim Einsatz der IsyFact in einem konkreten Anwendungskontext wird man in der Regel auch vorgeben, welche Arten von Anwendungen es in diesem Kontext geben soll und aus welchen Komponenten sie bestehen.
In <<awl-fachlich,der obigen Abbildung>> werden Anwendungskomponenten nicht dargestellt: Sie wären die Bestandteile der blauen und gelben Kästen.

[[anwendungstypen]]
=== Anwendungstypen

Im Rahmen der Referenzarchitektur werden Geschäftsanwendungen und Querschnittsanwendungen als Typen von Anwendungen unterschieden.
Eine weitergehende Unterscheidung von Geschäftsanwendungen muss durch ein xref:tailoring.adoc[Tailoring] der Referenzarchitektur erfolgen.

[[geschaeftsanwendung]]
==== Geschäftsanwendung

Eine xref:glossary::terms-definitions.adoc#glossar-geschaeftsanwendung[Geschäftsanwendung] implementiert für sich genommen oder im Zusammenspiel mit anderen Geschäftsanwendungen einen oder mehrere Geschäftsprozesse einer Domäne.
Sie implementiert entweder die gesamte hierfür notwendige Funktionalität (monolithisch), von der Benutzerschnittstelle über die Geschäftslogik, die Prozesse bis hin zur Datenhaltung, oder sie implementiert nur einen Teilbereich der Funktionalität und greift für den Rest über Schnittstellen auf benachbarte Geschäftsanwendungen zu.

.Trennung in Bestandsverwaltung und Benutzerinteraktion
====
Ein häufig anzutreffendes Beispiel hierfür ist die Trennung in eine _daten-zentrierte Anwendung_ für die Bestandsverwaltung und eine _prozess-zentrierte Anwendung_ für die Benutzerinteraktion, die auf die Bestandsverwaltung zugreift.
Im Zuge einer solchen Aufgabenteilung werden auch weitergehende Regeln definiert, wie Anwendungen aufeinander zugreifen dürfen.
Derartige Prinzipien und Regeln zur Strukturierung sind jedoch immer spezifisch für den jeweiligen Kontext der Anwendungslandschaft und können nicht allgemeingültig festgelegt werden.
====

[[querschnittsanwendung]]
==== Querschnittsanwendung

include::glossary::terms-definitions.adoc[tag="querschnittsanwendung-definition"]

[[awl-zugriff]]
=== Zugriff auf die Anwendungslandschaft

Anwendungslandschaften bieten menschlichen Anwendern und externen Anwendungen zwei dedizierte Zugriffswege.

[[portal]]
==== Portal

Das xref:glossary::terms-definitions.adoc#glossar-portal[Portal] stellt den Anwendern eine einheitliche Dialogoberfläche für den Zugriff auf die Anwendungen der Anwendungslandschaft zur Verfügung.
Geschäftsanwendungen stellen grafische Oberflächen zur Verfügung.
Das Portal integriert diese, bildet einen zentralen Einstiegspunkt für alle Anwendungen und übernimmt die Aufgabe der Authentifizierung und der Autorisierung auf Anwendungsebene.

[[api-gateway]]
==== API-Gateway

Im xref:glossary::terms-definitions.adoc#api-gateway[API-Gateway] werden alle xref:glossary::terms-definitions.adoc#service[Services] der Anwendungen bereitgestellt, die externe Anwendungen direkt nutzen dürfen.
Das API-Gateway übernimmt die Authentifizierung und Autorisierung der externen Anwendungen.
Weiterhin transformiert es das intern verwendete Kommunikationsprotokoll in das von den externen Anwendungen erwartete Protokoll.

[[anwendung-fachliche-architektur]]
== Fachliche Architektur einer Anwendung

Die fachliche Referenzarchitektur muss beim Einsatz der IsyFact innerhalb des jeweiligen Anwendungskontexts definiert werden.
Die IsyFact dient hier als allgemeiner konzeptioneller Rahmen und macht keine Vorgaben über die Arten von Anwendungen, die in einem bestimmten Kontext vorkommen.

Als Teil der fachlichen Architektur ist unter anderem folgendes zu definieren:

* Die verschiedenen Arten von Geschäftsanwendungen, die es innerhalb des Anwendungskontexts geben soll.
* Die Aufgaben und Verantwortlichkeiten der einzelnen Arten von Geschäftsanwendungen.
* Der daraus resultierende interne Aufbau der Geschäftsanwendungen aus Komponenten.
* Die Interaktion und die Abhängigkeiten zwischen den Geschäftsanwendungen, insbesondere die zulässigen Kommunikationsbeziehungen.
