= Fachliche Referenzarchitektur

include::glossary:licence:partial$licence.adoc[]

Zu den Aufgaben einer öffentlichen oder privatwirtschaftlichen Organisation gehört die Durchführung verschiedener fachlicher Verfahren.
Wenn solche Verfahren vollständig oder teilweise automatisiert werden sollen, so erfolgt dies in der Regel mit Anwendungssystemen, die zunächst aus fachlicher Sicht beschrieben, dann mit softwaretechnischen Mitteln umgesetzt und schließlich auf einer technischen Infrastruktur betrieben werden.

Bei einer großen Zahl von vollständig oder teilweise automatisierten Verfahren entsteht eine entsprechende Anzahl von Anwendungssystemen.
Hier kann schnell der Überblick verloren gehen, sodass Prinzipien zur Strukturierung benötigt werden, die Ordnung schaffen.

Die Menge aller Anwendungssysteme einer Organisation und deren Nutzungsbeziehungen untereinander bilden eine Anwendungslandschaft.
Die fachliche Architektur einer Anwendungslandschaft gibt hier die Strukturierung aus fachlicher Sicht vor und legt fest, wie Anwendungssysteme in die Anwendungslandschaft integriert werden.

[[awl-fachliche-architektur]]
== Fachliche Architektur einer Anwendungslandschaft

[[awl-fachlich]]
.Fachliche Architektur einer Anwendungslandschaft
image::referenzarchitektur:fachlich/fachliche-referenzarchitektur-anwendungslandschaft.dn.svg[]

Zur Strukturierung der xref:glossary:glossary:master.adoc#glossar-anwendungslandschaft[Anwendungslandschaft] werden drei fachliche Hierarchieebenen festgelegt:

*xref:glossary:glossary:master.adoc#glossar-anwendungsdomaene[Anwendungsdomäne]:*
Auf der obersten Hierarchieebene werden Anwendungsdomänen gebildet.
Eine Anwendungsdomäne gruppiert fachlich zusammengehörende Anwendungssysteme zur Unterstützung von Geschäftsprozessen, die als eine Einheit angesehen werden können.
In <<awl-fachlich,der obigen Abbildung>> wurden zwei Domänen gebildet.

Zwischen den Anwendungssystemen unterschiedlicher Anwendungsdomänen sollten nur wenige, klar definierte Nutzungsbeziehungen existieren.

*xref:glossary:glossary:master.adoc#glossar-anwendungssystem[Anwendungssystem]:* Ein Anwendungssystem ist eine zusammengehörende, logische Einheit aus Funktionen, Daten und Schnittstellen.
Anwendungssysteme unterstützen Geschäftsprozesse.
Anwendungssysteme sind einer Anwendungsdomäne zugeordnet und setzen sich aus Anwendungskomponenten zusammen.
Ein Anwendungssystem ist Bestandteil der xref:glossary:glossary:master.adoc#glossar-a-architektur[A-Architektur].
Aus Sicht der xref:glossary:glossary:master.adoc#glossar-t-architektur[T-Architektur] bildet ein xref:glossary:glossary:master.adoc#glossar-it-system[IT-System] die software-technische Umsetzung eines Anwendungssystems ab.

*xref:glossary:glossary:master.adoc#glossar-anwendungskomponente[Anwendungskomponenten]:* Eine Anwendungskomponente beschreibt eine Menge funktional zusammenhängender Anwendungsfälle.
Anwendungskomponenten sind Bestandteile von Anwendungssystemen.
Im Rahmen weitergehender Architekturvorgaben beim Einsatz der IsyFact in einem konkreten Anwendungskontext wird man in der Regel auch vorgeben, welche Arten von Anwendungssystemen es in diesem Kontext geben soll und aus welchen Komponenten sie bestehen.
In <<awl-fachlich,der obigen Abbildung>> werden Anwendungskomponenten nicht dargestellt: Sie wären die Bestandteile der blauen und gelben Kästen.

=== Arten von Anwendungen

Im Rahmen der Referenzarchitektur werden zunächst Geschäftsanwendungen und Querschnittsanwendungen als Typen von Anwendungssystemen unterschieden.
Eine weitergehende Unterscheidung der Geschäftsanwendungen muss durch ein xref:tailoring.adoc[Tailoring] der Referenzarchitektur erfolgen.

*xref:glossary:glossary:master.adoc#glossar-geschaeftsanwendung[Geschäftsanwendung]:* Eine Geschäftsanwendung implementiert für sich genommen oder im Zusammenspiel mit anderen Geschäftsanwendungen einen oder mehrere Geschäftsprozesse einer Anwendungsdomäne.
Sie implementiert entweder die gesamte hierfür notwendige Funktionalität (monolithisch), von der Benutzerschnittstelle über die fachliche Logik, die Prozesse bis hin zur Datenhaltung, oder sie implementiert nur einen Teilbereich der Funktionalität und greift für den Rest über Schnittstellen auf benachbarte Geschäftsanwendungen zu.

.Trennung in Bestandsverwaltung und Benutzerinteraktion
====
Ein häufig anzutreffendes Beispiel hierfür ist die Trennung in ein Anwendungssystem zur Bestandsverwaltung (z.B. Register) und einem Anwendungssystem für die Benutzerinteraktion, die auf die Bestandsverwaltung zugreift.
Im Zuge einer solchen Aufgabenteilung werden auch weitergehende Regeln definiert, wie Anwendungssysteme aufeinander zugreifen dürfen.
Derartige Prinzipien und Regeln zur Strukturierung sind jedoch immer spezifisch für den jeweiligen Kontext der Anwendungslandschaft und können nicht allgemeingültig festgelegt werden.
====

*xref:glossary:glossary:master.adoc#glossar-querschnittsanwendung[Querschnittsanwendung]:* Eine Querschnittsanwendung ist ein Anwendungssystem, das Services für mehrere Geschäftsanwendungen bereitstellt, wie z.B. ein Behördenverzeichnis oder ein Output-Management.
Diese Services sind oft technisch motiviert.

=== Zugriff auf die Anwendungslandschaft

*xref:glossary:glossary:master.adoc#glossar-portal[Portal]:* Das Portal stellt den Benutzern eine einheitliche Dialogoberfläche für den Zugriff auf die Services der Anwendungslandschaft zur Verfügung.
Einzelne Geschäftsanwendungen stellen Nutzerschnittstellen zur Verfügung, das Portal integriert diese, bildet einen zentralen Einstiegspunkt für alle Web-Anwendungen und übernimmt die Aufgabe der Authentifizierung und der Autorisierung auf Anwendungsebene.

*xref:glossary:glossary:master.adoc#glossar-service-gateway[Service-Gateway]:* Im Service-Gateway werden alle Services der Anwendungssysteme bereitgestellt, die externe Nutzer direkt nutzen dürfen.
Dazu führt das Service-Gateway die Authentifizierung und Autorisierung der Service-Aufrufer auf Anwendungsebene durch.
Weiterhin transformiert das Service-Gateway das interne Kommunikationsprotokoll einer IsyFact-Systemlandschaft in das vom Service-Aufrufer erwartete Protokoll.
Dies sind in der Regel Web Service-Aufrufe.


[[anwendung-fachliche-architektur]]
== Fachliche Architektur eines Anwendungssystems

Die fachliche Referenzarchitektur muss beim Einsatz der IsyFact innerhalb des jeweiligen Anwendungskontexts definiert werden.
Die IsyFact dient hier als allgemeiner konzeptioneller Rahmen und macht keine Vorgaben über die Arten von Anwendungssystemen, die in einem bestimmten Kontext vorkommen.

Als Teil der fachlichen Architektur ist unter anderem folgendes zu definieren:

* Die verschiedenen Arten von Geschäftsanwendungen, die es innerhalb des Anwendungskontexts geben soll.
* Die Aufgaben und Verantwortlichkeiten der einzelnen Arten von Geschäftsanwendungen.
* Der daraus resultierende interne Aufbau der Geschäftsanwendungen aus Komponenten.
* Die Interaktion und die Abhängigkeiten zwischen den Geschäftsanwendungen, insbesondere die zulässigen Kommunikationsbeziehungen.
