= Software-technische Referenzarchitektur

include::glossary:licence:partial$licence.adoc[]

// tag::architektursicht-definition[]

Die software-technische Referenzarchitektur beschreibt, wie die in der fachlichen Referenzarchitektur definierten xref:glossary::terms-definitions.adoc#glossar-anwendung[Anwendungen] software-technisch in Form von xref:glossary::terms-definitions.adoc#glossar-it-system[IT-Systemen] umgesetzt werden.

Eine zentrale Eigenschaft der software-technischen Referenzarchitektur ist, dass sie nicht zwischen xref:glossary::terms-definitions.adoc#glossar-anwendungstyp[Anwendungstypen] unterscheidet.
Die software-technische Umsetzung von Anwendungen ist ungeachtet ihrer Fachlichkeit gleich.
Die software-technische Referenzarchitektur definiert hierzu das xref:glossary::terms-definitions.adoc#glossar-it-system[*IT-System*] als Oberbegriff und beschreibt die Umsetzung einer Anwendung mittels einer Menge von IT-Systemen, die jedes für sich eine bestimmte Ausprägung besitzen.
Diese Ausprägung ist technisch motiviert und umfasst aktuell *Backends*, *Frontends* und *Batches*.

// end::architektursicht-definition[]

== Definition der Systemlandschaft

Der Begriff der Anwendungslandschaft ist fachlich motiviert.
Die technische Entsprechung hierfür ist der Begriff der xref:glossary::terms-definitions.adoc#glossar-systemlandschaft[Systemlandschaft].
Eine Systemlandschaft, die eine Anwendungslandschaft nach den IsyFact-Standards umsetzt, wird im Folgenden als _IsyFact-Systemlandschaft_ bezeichnet.
Eine solche IsyFact-Systemlandschaft beinhaltet alle IT-Systeme als technische Umsetzung der Anwendungen  der Anwendungslandschaft sowie technische Systeme zur Unterstützung (z.B. Datenbanken oder Web-Server).

[[strukturierung-der-systemlandschaft]]
== Strukturierung der Systemlandschaft

Wichtige Grundlagen für die Software-Referenzarchitektur sind die Schnittstellen und Aufruf-Beziehungen der IT-Systeme vom Typ _Geschäftsanwendung_, _Querschnittsanwendung_ sowie _Portal_ und _Service-Gateway_.
Aufruf-Beziehungen werden stets unterschieden in _interne Aufrufe_, in welchen ein IT-System einer IsyFact-Systemlandschaft mit einem anderen IT-System derselben IsyFact-Systemlandschaft kommuniziert, und _externe Aufrufe_, in welchen ein IT-System der IsyFact-Systemlandschaft mit einem Anwender oder einem IT-System außerhalb dieser IsyFact-Systemlandschaft kommuniziert.
Interne und externe Aufrufe unterscheiden sich sowohl in ihrer Authentifizierung und Autorisierung als auch (bei automatisierten Schnittstellen) in der verwendeten Technologie.

Im Folgenden werden die Schnittstellen und Aufrufbeziehungen pro Anwendungstyp erläutert.

*Das xref:glossary::terms-definitions.adoc#glossar-service-gateway[Service-Gateway]:* Service-Gateway-Systeme haben die Aufgabe, Aufrufe aus der Systemlandschaft an xref:glossary::terms-definitions.adoc#externes-system[externe Systeme] sowie Aufrufe von externen Systemen in die Systemlandschaft weiterzuleiten und dabei unterschiedliche Schnittstellentechnologien zu überbrücken.

Für die Weiterleitung von Aufrufen enthält ein Service-Gateway die folgenden Funktionalitäten:

* Es bildet die Aufrufe zwischen der Schnittstellentechnologie der externen Systeme und der Schnittstellentechnologie der Systemlandschaft ab.
* Bei Aufrufen durch externe Systeme führt es die Authentifizierung und eine erste Autorisierung des Aufrufs durch.

Ein Service-Gateway-System besitzt weder eine eigene Datenhaltung noch eigene Fachlichkeit.

*Die xref:glossary::terms-definitions.adoc#glossar-geschaeftsanwendung[Geschäftsanwendung]*: Eine Geschäftsanwendung implementiert allgemein die Geschäftsprozesse einer Domäne.
Geschäftsanwendungen können monolithisch strukturiert sein und alle Schichten der Softwarearchitektur umfassen, von der Benutzeroberfläche über Prozesse und xref:glossary::terms-definitions.adoc#glossar-geschaeftslogik[Geschäftslogik] bis hin zur Datenspeicherung.
Sie können aber auch jeweils nur Teile davon implementieren, sodass z.B. eine Geschäftsanwendung eine GUI bereitstellt, eine weitere die Geschäftslogik implementiert und eine dritte schließlich die Persistierung der Daten realisiert.
In diesem Fall würde die Gesamtfunktionalität durch das Zusammenwirken der drei Geschäftsanwendungen erbracht.

Die Geschäftsanwendungen einer IsyFact-Systemlandschaft können sich intern gegenseitig über ihre Service-Schnittstellen aufrufen.
In einem konkreten Anwendungskontext einer IsyFact-Systemlandschaft wird man in der Regel die Arten von Geschäftsanwendungen noch genauer definieren und dabei auch die möglichen Aufrufbeziehungen zwischen ihnen geeignet einschränken.

Für die Kommunikation mit externen Systemen muss eine Geschäftsanwendung ein Service-Gateway-System verwenden, egal in welche Richtung die Kommunikation verläuft.

Geschäftsanwendungen, die eine Benutzeroberfläche bereitstellen, dürfen aus Sicherheitsgründen nicht direkt vom Benutzer aufgerufen werden, sondern werden in das _Portal_ (siehe unten) der IsyFact-Systemlandschaft eingebunden.

*Das xref:glossary::terms-definitions.adoc#glossar-portal[Portal]:* Die Referenzarchitektur sieht keinen Portal-Server im klassischen Sinne vor.
Es gibt weder einen systemübergreifenden Rahmen noch eine systemübergreifende Navigation.

Ein Portal im Sinne der Referenzarchitektur besteht aus:

* Einem Web-Server-Cluster, der Aufrufe entgegennimmt und an die Application-Server der Geschäftsanwendungen weiterleitet.
* Einer zentralen Startseite, welche den eingeloggten Benutzern die Geschäftsanwendungen der Anwendungslandschaft, für welche sie berechtigt sind, präsentiert.

Der Zweck eines Portals ist die gemeinsame Authentifizierung und Autorisierung für alle Geschäftsanwendungen und die Indirektion des Zugriffs von Nutzern auf die Geschäftsanwendungen.

*Die xref:glossary::terms-definitions.adoc#glossar-querschnittsanwendung[Querschnittsanwendung]:* Eine Querschnittsanwendung bietet Geschäftsanwendungen querschnittlich genutzte Funktionalitäten an, etwa für die Bereitstellung von Schlüsseldaten.
Querschnittsanwendungen können eine eigene Datenhaltung besitzen.

Querschnittsanwendungen werden nur von internen Benutzern oder anderen IT-Systemen derselben Systemlandschaft aufgerufen. Sie rufen selbst nur andere Querschnittsanwendungen auf.
Eine Ausnahme bilden Querschnittsanwendungen, wie z.B. ein Mail-Gateway für den Versand von E-Mails an externe Empfänger.

[[servicekommunikation]]
== Servicekommunikation

Services sind ein wesentlicher Bestandteil jeder <<strukturierung-der-systemlandschaft,Systemlandschaft>>.
Die software-technische Referenzarchitektur definiert HTTP als grundsätzliches Übertragungsprotokoll und xref:software-technisch/services.adoc[weitere Vorgaben für Services] zu den Themen:

* Kommunikation mit Systemen innerhalb und außerhalb der Systemlandschaft,
* Übertragung von Metadaten und Nutzdaten,
* Versionierung von Services.

[[prinzipien-der-sicherheitsarchitektur]]
== Prinzipien der Sicherheitsarchitektur

Die IsyFact-Referenzarchitektur beinhaltet auch Vorgaben für die Sicherheitsarchitektur einer Systemlandschaft.
Eine davon ist die Forderung, dass IsyFact-konforme IT-Systeme gegen unberechtigte Nutzung zu schützen sind.
Folgende Prinzipien der Sicherheit liegen der Erstellung einer Systemlandschaft zugrunde:

* Authentifizierungsinformationen, wie Benutzername und Passwort, werden nicht über IT-Systeme hinweg weitergegeben.
Nur der Eigentümer der Authentifizierungsinformationen und der zentrale IAM-Service besitzen Kenntnis über diese Informationen.
* Eine Zweifaktor-Authentifizierung ist durch das Client-Zertifikat und dem darin enthaltenen Behördenkennzeichen (BHKNZ) als zusätzliches Authentifizierungsmerkmal konzipiert, allerdings setzt dies im IAM-Service voraus, dass dieses Merkmal dort auch ausgewertet werden kann.
* Bei Aufrufen von Außen (durch Web-Clients oder externen Anwendungen) erfolgt die Authentifizierung und grobgranulare Autorisierung an den Außengrenzen der Systemlandschaft (Portal, Service-Gateway bzw. Authentication-Gateway).
* Kommt der Aufruf von innerhalb der Systemlandschaft (z.B. bei einem Batch- oder Task-Aufruf), benötigt der (technische) Aufrufer eigene Authentifizierungsinformationen.
Die Authentifizierung und grob granulare Autorisierung erfolgen durch das aufrufende IT-System (Batch/Task).
* Wird zur Ausführung des Aufrufs ein Service einer anderen Geschäftsanwendung / Domäne benötigt, erfolgt dessen Aufruf im Namen und mit der Autorisierung des ursprünglichen Aufrufers.
* Die feingranulare Autorisierung geschieht an den Systemgrenzen / externen Schnittstellen der aufgerufenen Geschäftsanwendung.
* Existiert keine Systemlandschaft (d.h. IT-Systeme stehen für sich allein), gilt grundsätzlich, dass die Authentifizierung und grob granulare Autorisierung durch das aufrufende IT-System (Service oder Batch) erfolgen müssen.

Folgende Abbildung zeigt die Umsetzung der Prinzipien in der Systemlandschaft:

.Integration des IAM-Service in eine Systemlandschaft
image::software-technisch/sicherheit_iam_integration_awl.dn.svg[]

* *Portal:* +
Interne und externe Anwender rufen über das Portal die Geschäftsanwendung auf und werden dabei durch das Portal an den IAM-Service weitergeleitet, um die Authentifizierung durchzuführen.
Erst nach erfolgreicher Authentifizierung leitet das Portal den Anwender zusammen mit den Autorisierungsinformationen an die Geschäftsanwendung weiter.

* *Service-Gateway:* +
Das Service-Gateway hat die Aufgabe, Anfragen von _externen Anwendungen_ entgegenzunehmen und zusammen mit den Autorisierungsinformationen an den passenden Service der Geschäftsanwendung weiterzuleiten.
Aktuell übernimmt das Service-Gateway auch die Authentifizierung von externen Anwendungen.
Dazu leitet es die von der externen Anwendung erhaltenen Authentifizierungsdaten an den IAM-Service weiter.
Nach erfolgreicher Authentifizierung leitet das Service-Gateway die Anfrage zusammen mit den Autorisierungsinformationen an die Geschäftsanwendung weiter.
Zukünftig soll das Service-Gateway keine Authentifizierungsanfragen mehr verarbeiten.
Stattdessen soll das Authentication-Gateway verwendet werden.

* *Authentication-Gateway:* +
Das Authentication-Gateway übernimmt die Authentifizierung von externen Anwendungen.
Dazu leitet es die von der externen Anwendung erhaltene Authentifizierungsanfrage an den IAM-Service weiter.
Nach erfolgreicher Authentifizierung gibt das Authentication-Gateway die Autorisierungsinformationen an die externe Anwendung zurück.
Die externe Anwendung sendet die erhaltenen Autorisierungsinformationen gemeinsam mit der fachlichen Anfrage über das Service-Gateway an die Geschäftsanwendung.

* *Anwendungen innerhalb der Anwendungslandschaft:* +
Wenn Anwendungen andere Geschäfts- und Querschnittsanwendungen innerhalb der Systemlandschaft aufrufen, verwenden sie die Autorisierungsinformationen des ursprünglichen Aufrufers oder authentifizieren sich mit ihren eigenen Zugangsdaten direkt am IAM-Service und nutzen die erhaltenen Autorisierungsinformationen zum Aufruf.

* *IAM-Service:* +
Der IAM-Service verarbeitet die Authentifizierungsanfragen und beantwortet sie mit zeitlich begrenzten Autorisierungsinformationen.
Dazu greift er im Regelfall auf das Benutzerverzeichnis zu.

NOTE: IAM steht für https://en.wikipedia.org/wiki/Identity_management[Identity and Access Management].

Darüber hinaus finden Authentifizierung und Autorisierung nach den Vorgaben des Berechtigungskonzepts statt.
Da das Berechtigungskonzept individuell für jede Systemlandschaft erstellt wird und sich im Einzelnen stark von Inhalt und Umfang her unterscheidet, ist es kein Bestandteil  der IsyFact.

Eine detaillierte Beschreibung der erwähnten Zugriffskomponenten (Portal, Service-Gateway, Authentication-Gateway), des IAM-Service, der implementierten Authentifizierungsverfahren und der Autorisierungsinformationen (Access-Token) findet sich im xref:isyfact-standards-doku:isy-security:konzept/master.adoc[].

[[authentifizierung]]
=== Authentifizierung

NOTE: Authentifikation: Verifikation der Identität eines Benutzers als Zugangskontrolle zu einem geschützten System.
Dabei ist es erforderlich, eindeutige Eigenschaften (z.B. biometrische Daten) oder geheime Daten (z.B. Passwort) zur Überprüfung zu übergeben.

Nach der erfolgreichen Authentifizierung eines Benutzers gibt der IAM-Service Autorisierungsinformationen zurück.
Diese Autorisierungsinformationen dienen dann als Nachweis des Nutzungsrechts des aufgerufenen Dienstes (s. <<autorisierung>>).
Die tatsächliche Identität und Authentifizierungsinformationen des Benutzers spielen ab hier keine Rolle mehr und sind deshalb nicht Teil der Autorisierungsinformationen.

In der Regel erfolgt die Authentifizierung von Benutzern über eine zentrale Komponente der Systemlandschaft, in welche das IT-System eingebettet ist, dem IAM-Service.
Die Authentifizierung darf auch lokal, d.h. vom IT-System selbst, durchgeführt werden, falls es beispielsweise nicht in eine Systemlandschaft eingebettet ist.

Für die zentrale Authentifizierung wird in der IsyFact ein OAuth 2.0 konformer IAM-Service verwendet.

[[autorisierung]]
=== Autorisierung

NOTE: Autorisierung: Zustimmung oder Erlaubnis, spezieller die Einräumung von Rechten gegenüber interessierten Rechtssubjekten, gegebenenfalls als Nutzungsrecht gegenüber Dritten.

Im aufgerufenen IT-System wird die Anfrage – je nach Schutzbedarf und Funktionalität – autorisiert.
Zwingend wird das Vorhandensein sowie die Authentizität und Gültigkeit der mit der Anfrage mitgegebenen Autorisierungsinformationen geprüft.
In IsyFact ist eine feingranulare Autorisierung vorgesehen:
Im Benutzerverzeichnis sind zu einem Benutzer die ihm zugewiesenen *Rollen* in der Systemlandschaft verknüpft und Bestandteil der Autorisierungsinformationen aus dem IAM-Service.
Anhand dieser Rollen aus den Autorisierungsinformationen weist das IT-System einem Aufruf anwendungsspezifische *Rechte* zu und prüft diese gegen die für die Nutzung des angefragten Service benötigten Rechte.
Wie genau Rollen und Rechte spezifiziert werden, beschreibt das xref:isyfact-standards-doku:isy-security:konzept/master.adoc[] im Kapitel xref:isyfact-standards-doku:isy-security:konzept/master.adoc#rollen-und-rechte[Rollen und Rechte].

[[nutzung-von-zertifikaten]]
=== Nutzung von Zertifikaten
Ein Sicherheitszertifikat ist ein digitales Dokument, das die Identität einer Entität (Website oder eines Dienstes) bestätigt und zur Absicherung der Kommunikationspartner auf der Transportschicht eingesetzt werden kann.
Für den Einsatz eines Sicherheitszertifikates wird eine Public Key Infrastructure (PKI) benötigt.
Hierbei besitzt jede Entität ein Schlüsselpaar und ein zugehöriges Zertifikat, welches den öffentlichen Schlüssel enthält.
Durch die Signatur mit dem privaten Schlüssel beweist die Entität ihre Identität, überprüfbar für jeden mit dem öffentlichen Schlüssel.
Für die konkrete Umsetzung der Absicherung der Kommunikationsstrecke sind die Vorgaben der jeweiligen Security, die gegebene Infrastruktur und die Tatsache, dass sich diese verändern, zu beachten (Vgl. xref:methodik:versionierung/master.adoc[Versionierung]).
Welche Maßnahmen für eine sichere Kommunikation realisiert werden, ist mit dem jeweiligen Partner, der einen xref:isyfact-standards-doku:referenzarchitektur:software-technisch/services.adoc[Service]  anbietet, abzustimmen.

Für alle implementierten Authentifizierungs- und Verschlüsselungsverfahren werden jedoch die folgenden Festlegungen getroffen:

* Alle verwendeten Zertifikate müssen dem X509v3-Standard entsprechen (siehe: https://tools.ietf.org/html/rfc3280[X509]).
* Privater Schlüssel und Zertifikate werden in einem PKCS#12-Format abgelegt(siehe: https://tools.ietf.org/html/rfc7292[PKCS12]).
* Verwendet werden nur die im Standardumfang des JDKs enthaltenen kryptografischen Verfahren (siehe https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html[Java Secure Socket Extensions]).

Der xref:referenzarchitektur:software-technisch/backend.adoc#awk-service-consumer[Sevice-Consumer] kann die Verbindung zum externen Service entweder unverschlüsselt per HTTP oder verschlüsselt per HTTPS aufbauen.
Eine unverschlüsselte Verbindung bei der sich der Service-Consumer gegenüber dem externen Service über Benutzername und Passwort authentifiziert wird aus Sicherheitsgründen nicht empfohlen.
Bei der Nutzung von einer verschlüsselten Verbindung via HTTPS ist eine zertifikatsbasierte Authentifizierung notwendig.

* Einseitige Authentifizierung:
Der externe Service weist sich mit seinem Server-Zertifikat gegenüber dem Service-Consumer aus.
Dies ist für verschlüsselte Verbindungen obligatorisch.
* Beidseitige Authentifizierung (mTLS):
Zusätzlich weist sich auch der Service-Consumer gegenüber dem externen Service mit einem Client-Zertifikat aus.
Dies sollte immer dann eingesetzt werden, wenn besonders schützenswerte Daten verarbeitet oder sicherheitskritische Domänen berührt werden.

[[zertifikatsbasierte-authentifizierung]]
==== Zertifikatsbasierte Client-Authentifizierung
Bei Verwendung der Client-Authentifizierung per Zertifikat benötigt der Service-Consumer:

 * ein Zertifikat, das von einer vertrauenswürdigen CA signiert ist,
 * den zugehörigen privaten Schlüssel, welcher lokal im Keystore bleibt.
Die nutzende Anwendung übergibt dem Service-Consumer das Zertifikat zusammen mit dem privaten Schlüssel beim Aufruf der internen Service-Methode.
Der private Schlüssel wird ausschließlich zur kryptografischen Signatur des TSL-Handshakes genutzt.

NOTE: Alle notwendigen Informationen zur Erstellung von Zertifikaten -ausgehend von einem Sicherheitsschlüsselpaar- können z.B. https://de.wikipedia.org/wiki/Certificate_Signing_Request[hier] eingesehen werden.

In der nutzenden Anwendung werden das Zertifikat und der private Schlüssel in einer PKCS#12-Datei im Config-Verzeichnis der Anwendung abgelegt werden.
Die Aktualisierung bzw. Austausch des Zertifikats oder Schlüssels wird vom Betrieb durch Austauschen der Datei vorgenommen.
Wird das Passwort für den privaten Schlüssel in einer Property zusammen mit den übrigen betrieblichen Konfigurationen der Anwendung vorgehalten ist zu beachten:
Die Gefahr besteht, dass der private Schlüssel über Logs, Artefakte, Konfigurations-Viewer oder Versions-Verwaltungslösungen zugänglich wird.
Aus diesem Grund sollte das Passwort für den privaten Schlüssel über einen Secret-Mechanismus (Secret-Datei, Secret-Manager, ...) verfügbar gemacht werden.
Die Bereitstellung des privaten Schlüssels ist vom Betrieb im Rahmen des betrieblichen Konfigurationsprozesses festzulegen.

[[ablage-von-zertifikaten]]
=== Ablage von Zertifikaten
Bei einer verschlüsselten Verbindung weist sich der externe Service mit einem Server-Zertifikat aus.
Zur Überprüfung ist ein TrustStore erforderlich, der vertrauenswürdige CA-Zertifikate enthält.
Diese dienen der Validierung eingehender Zertifikate und stellen die Integrität der Gegenstelle sicher.

Für höhere Sicherheit wird mTLS empfohlen.
Dabei authentifiziert sich zusätzlich der Service-Consumer mit einem KeyStore, der das Client-Zertifikat samt privatem Schlüssel (und ggf. Zertifikatskette) enthält (siehe <<zertifikatsbasierte-authentifizierung>>).
Damit wird die eigene Identität nachgewiesen.

Ein PKCS#12-Keystore speichert die privaten Schlüssel und die zugehörigen Zertifikate der eigenen Komponente.
Der TrustStore dagegen enthält ausschließlich die CA-Zertifikate, die für die Authentifizierung der Kommunikationspartner dienen.

[[installation-des-zertifikates-auf-der-maschine]]
==== Installation des Zertifikats auf der Maschine
Zertifikate können direkt als Dateien auf dem Dateisystem einer Maschine gespeichert werden, z. B. als .pem-, .crt- oder .key-Dateien.
Für den produktiven Einsatz wird jedoch die Ablage in Keystores/TrustStores empfohlen, die von der Anwendung beim Start oder zur Laufzeit geladen werden.

[[besonderheiten-bei-der-kommunikation-ueber-soap]]
==== Besonderheiten bei der Kommunikation über SOAP
Für Kommunikation mit externen Services auf Basis von SOAP im Zusammenspiel mit Client-Zertifikaten ist zu beachten:
Sofern nicht für alle Verbindungen derselbe Schlüssel verwendet wird, muss eine SocketFactory-Instanz pro Verbindung zur Verfügung gestellt werden.
Damit ist ein globales Setzen von Key- und Truststores in der JVM nicht mehr ausreichend.
Die SocketFactory-Instanzen können erst nach Initialisierung des ServiceStubs gesetzt werden, so kann die WSDL-Datei nicht über die gesicherte Verbindung abgerufen werden.
Empfohlen wird die WSDL-Datei lokal vorzuhalten und aus dem Dateisystem zu laden, sodass sie nicht zur Laufzeit über das Netz geladen werden muss.


[[verwendung-von-produkten]]
== Verwendung von Produkten

Bei der Umsetzung einer Architektur für eine Anwendung oder eine Anwendungslandschaft können an vielen Stellen fertige Produkte Dritter eingesetzt werden.
Das beschleunigt die Entwicklung und reduziert die Kosten.

Bei der Produktentscheidung sind zwei Seiten zu berücksichtigen: Auf der einen Seite bietet die Konzentration auf projektübergreifend einheitliche Produkte die Möglichkeit, die Fähigkeiten der Mitarbeiter zu bündeln und diese übergreifend einzusetzen.
Auf der anderen Seite besteht die Gefahr, durch einen zu engen Fokus die Möglichkeiten eines Projekts zu sehr zu beschränken.
Eine Lösung kann dann auch Gefahr laufen, zu allgemein zu werden, was letztlich die Komplexität steigert und größeren Aufwand verursacht.

Die für die Umsetzung der Architektur verwendeten Produkte lassen sich in die Kategorien Basistechnologien, Systemsoftware und Bibliotheken für die Anwendungsentwicklung unterteilen.

*Basistechnologien:* Basistechnologien legen grundlegende technische Entscheidungen fest, wie z.B. die Programmiersprache und die verwendete Web-Technologie.

*Systemsoftware:* Die Systemsoftware legt die technische Ablaufumgebung für die Software fest und bietet grundlegende Services für eine IsyFact-Systemlandschaft an.
Hierzu gehören z.B. das Betriebssystem, der Web-Server, der Application-Server, das IAM-System und die Datenbank.

*Bibliotheken für die Anwendungsentwicklung:* Die Anwendungsentwicklung wird durch den Einsatz von Frameworks und entsprechenden Bibliotheken vereinfacht und beschleunigt.
Die IsyFact verwendet insbesondere Spring, Hibernate und Angular.

Eine detaillierte Liste der verbindlichen und empfohlenen Produkte ist im xref:einstieg:produkte.adoc#produktkatalog[Produktkatalog] zu finden.
