= Konzept Überwachung: Inhalt

// tag::inhalt[]
[[ueberwachung-von-anwendungen]]
== Überwachung von Anwendungen

In diesem Kapitel werden die Anforderungen an die Überwachung von Anwendungen beschrieben.
Der Fokus liegt dabei auf der Schaffung von einheitlichen Administrationsschnittstellen, welche dem Betrieb eine einfache Überwachung der Anwendungen erlauben.
Alle Vorgaben sind beim Entwurf und der Realisierung von neuen Anwendungen nach IsyFact-Architektur zu berücksichtigen.
Gegebenenfalls können in Systementwürfen Verfeinerungen der hier getroffenen Vorgaben gemacht werden.
Weiterhin können die hier gemachten Vorgaben als Basis für die Beschreibung der Überwachungsschnittstelle im Betriebshandbuch der Anwendungssysteme verwendet werden.

[[kurzeinfuehrung-in-das-system-monitoring-mit-spring-boot-actuator]]
=== Kurzeinführung in das System-Monitoring mit Spring Boot Actuator

Spring Boot bringt mit Actuator eine Reihe zusätzlicher Funktionen mit, die dabei helfen, Anwendungen zu überwachen und zu verwalten.
Die Kommunikation mit der Anwendung erfolgt über sogenannte _Endpoints_.
Diese können über HTTP oder JMX bereitgestellt werden.
Actuator bringt eine Reihe von eingebauten Endpoints mit und bietet auch die Möglichkeit, eigene Endpoints hinzuzufügen.
So wird für Informationen über den Systemzustand der eingebauten Endpoint `health` angeboten und über den Endpoint `metrics` können Metriken gelesen werden.

[[micrometer]]
==== Micrometer

Die im Endpoint `metrics` bereitgestellen Metriken werden von Micrometer erfasst.
Micrometer bietet eine einfache anbieterneutrale Fassade für die gängigsten Überwachungssysteme und ermöglicht es, Metriken im Anwendungscode ohne Herstellerbindung zu implementieren.
Seit Spring Boot 2.0 ist Micrometer die Standardbibliothek zur Bereitstellung von Anwendungsmetriken von Spring.

NOTE: Für eine Liste der unterstützten Monitoring-Systeme siehe xref:glossary:literaturextern:inhalt.adoc#litextern-monitoring-systeme-unterstuetzt[unterstützte Monitoring-Systeme]

[[festlegungen-und-ausgrenzungen]]
=== Festlegungen und Ausgrenzungen

Die Nutzungsvorgaben finden sich im dem Dokument xref:konzept/master.adoc#einleitung[Überwachung Nutzungsvorgaben]

Das Konzept für die Prüfung der Verfügbarkeit ist:

* Anwendungen nach IsyFact-Architektur sollen Mechanismen bereitstellen, die es erlauben, die Verfügbarkeit der Anwendung durch eine betriebliche Überwachung zu prüfen.
* Grundlage dafür ist die Bereitstellung eines `HealthIndicators` und einer Ping-Methode durch die Anwendung.

Folgende Punkte sind bewusst nicht Teil dieses Konzeptes:

* Micrometer unterstützt die Anbindung zahlreicher Monitoring-Systeme.
  Es werden keine Vorgaben zur Verwendung eines bestimmten Systems gemacht.

[[health-check]]
=== Health Check
Die IsyFact sieht eine Enkopplung der Evaluation von Health-Checks vor, bei der der Health-Endpoint jeweils nur das aktuellste Ergebnis liest. Durch diese Entkopplung wird die Systemstabilität durch extrem häufige Aufrufe des Endpoints nicht beeinflusst.

Der Health-Check führt nur bei einem Fehlschlag zu einem Logeintrag. In diesen Fall wird eine Warnung, bei nicht-essentiellen, oder ein Error, bei essentiellen, Nebensystemen geloggt. Implementiert und konfiguriert wurde bzw. wird der Health-Check als `isy-task`.

Es ist möglich Nebensysteme zo kontrollieren. Hierfür steht ein `@FunctionalInterface`zur Verfügung.

Sollte das Ergebnis eines Checks komplexer sein, als ein `boolean` erfolgt der Zugriff über `synchronized` um Probleme mit der Nebenläufigkeit zu verhindern.

// end::inhalt[]

// tag::architekturregel[]

// end::architekturregel[]

// tag::sicherheit[]

// end::sicherheit[]
