[[changelog]]
= Changelog

*Änderungen IsyFact 3.1.0*

// tag::release-3.1.0[]

* `IFS-3992`: Entfernung der Vorlage "Tailoring" Dokument

// end::release-3.1.0[]

*Änderungen IsyFact 3.0.0*

// tag::release-3.0.0[]
* `IFS-2383`: Grafiken der TI-Architektur aller Umgebungen neu erstellt und an aktuelle Gegebenheiten angepasst.
// end::release-3.0.0[]

*Änderungen IsyFact 2.4.0*

// tag::release-2.4.0[]
- `IFS-1162`: Interne Verschlüsselung als SOLL-Anforderung an eine Systemlandschaft beschrieben
- `IFS-1092`: Übertragungswege von Daten in der internen Servicekommunikation beschrieben
// end::release-2.4.0[]

*Änderungen IsyFact 2.3.0*

// tag::release-2.3.0[]
- `IFS-624`: SAGA-Referenzen durch Architekturrichtlinie der IT des Bundes ersetzt
// end::release-2.3.0[]

*Änderungen IsyFact 2.2.0*

// tag::release-2.2.0[]
- `IFS-962`: Alte Tickets zur Anpassung der Dokumentation auf Aktualität geprüft und Dokumentation entsprechend angepasst.
// end::release-2.2.0[]

// *Änderungen IsyFact 2.1.0*

// tag::release-2.1.0[]

// end::release-2.1.0[]

// *Änderungen IsyFact 2.0.0*

// tag::release-2.0.0[]

// end::release-2.0.0[]

*Änderungen IsyFact 1.7.0*

// tag::release-1.7.0[]
- `IFS-294`: Ablageorte der Referenzarchitektur sowie der Checkstyle-Konfiguration korrigiert
// end::release-1.7.0[]

// *Änderungen IsyFact 1.6.0*

// tag::release-1.6.0[]

// end::release-1.6.0[]