= Isyfact-Bridges-Guide: Inhalt
include::{isy-dokumentvorlagen}/docs/common/isyfact-attributes.adoc[]

// tag::inhalt[]

== Nutzen der Isy-SST-Bridge

Mit der Versionsanhebung von IsyFact 1 auf IsyFact 2, wurden einige Module aus dem ehemaligen "plis-common"-Namensraum in den "isyfact"-Namensraum umgezogen.
Dies hat unter Anderem dazu geführt, dass IsyFact 2 Anwendungen nicht mehr die Schnittstellen von Isyfact 1 Anwendungen zugreifen konnten, da sie die den "plis-common"-Namensraum nicht mehr kennen.
Das Modul Isy-SST-Bridge stellt IsyFact 2-Anwendungen die wichtigsten Transfer-Objekte aus dem "plis-common"-Namensraum zur Verfügung.
Enthalten sind die Transferobjekte der isy-exception-sst und der isy-serviceapi-sst, sowie einige Hilfsmapper.

== Einbindung

Um in einer 2er Anwendungen auch Schnittstellen von 1er Anwendungen nutzen zu können, müssen die Bridges als Dependency in Maven hinzugefügt werden.

:desc-listing-pom: Einbindung der Bridge-SST-Module in pom.xml
[id="listing-pom",reftext="Listing SST pom.xml"]
.{desc-listing-pom}
[source,xml]
----
<dependency>
    <groupId>de.bund.bva.isyfact</groupId>
    <artifactId>isy-exception-sst-bridge</artifactId>
</dependency>
<dependency>
    <groupId>de.bund.bva.isyfact</groupId>
    <artifactId>isy-serviceapi-sst-bridge</artifactId>
</dependency>
----

Die richtige Version wird aus der Standard-Products-BOM mitgeliefert.
Generell muss eine 2.x Anwendung die 2.x Version des Wrappers einbinden, um auf 1.x Anwendungen zugreifen zu können.

Standardmäßig werden beim Einbinden über die Autokonfiguration alle notwendigen Konverter-Beans initialisiert.
Ist dies nicht erwünscht, kann die Autokonfiguration über `isy.sst.serviceapibridge.autoconfiguration.enabled=false` in den `application.properties` ausgeschaltet werden.

== Verwendung auf Client-Seite

Der Service-Zugriff ist nach dem <<DetailkonzeptKomponenteService, Detailkonzept Komponente Service>> zu gestalten.
Der folgende Abschnitt beschreibt den Zugriff einer 2.x-Anwendung auf einen 1.x-Service einer 1er Anwendung.

Die Bridge beinhaltet hierfür einen ServiceApiMapper zum einfachen Mappen des 2.x-AufrufKontextTo auf einen 1.x-AufrufKontextTo.
Standardmäßig wird der ServiceApiMapper mit der Autokonfiguration des Moduls als Bean zur Verfügung gestellt.
Das <<listing-serviceapimapper>> zeigt am Beispiel die Nutzung des ServiceApiMapper.

:desc-listing-serviceapimapper: Nutzung des ServiceApiMapper
[id="listing-serviceapimapper",reftext="Listing Nutzung des ServiceApiMapper"]
.{desc-listing-serviceapimapper}
[source,java]
----
import
de.bund.bva.isyfact.serviceapi.service.httpinvoker.v1_0_0.bridge.util.ServiceApiMapper;
import de.bund.bva.pliscommon.serviceapi.service.httpinvoker.v1_0_0.AufrufKontextTo;
...

// Injection
@Autowired
private ServiceApiMapper aufrufKontextMapper;

...
/* In der Aufrufmethode */
// Erstelle Isyfact AufrufKontextTo wie gehabt
de.bund.bva.isyfact.serviceapi.service.httpinvoker.v1_0_0.AufrufKontextTo isyAufrufKontextTo = // ...
// Mappe in einen plis-AufrufKontext
AufrufKontextTo plisAufrufKontextTo = aufrufKontextMapper.map(isyAufrufKontextTo);
//Aufruf der 1.x-RemoteBean
remoteBean.doSomething(plisAufrufKontextTo, ...);

...
----

Da in der Klasse sowohl der "pliscommon"- als auch der "isyfact"-AufrufKontextTo genutzt wird, kann nur einer der beiden als Import angegeben werden.
Sofern der andere explizit im Code benötigt wird, muss der volle Pfad angegeben werden, wie im <<listing-serviceapimapper>> zu sehen.

[TIP]
====
Eine 1.x-RemoteBean wird nur 1.x-AufrufKontextTo-Objekte akzeptieren.
Wenn Ihnen beim Aufruf Kompilationsfehler angezeigt werden, überprüfen Sie nochmals, ob die richtige Version des AufrufKontextTo übergeben wird.
====

Wirft die Funktion der RemoteBean Exceptions, werden diese, wie in <<DetailkonzeptKomponenteService, Detailkonzept Komponente Service>> beschrieben abgefangen.
Das isy-exception-sst-bridge-Modul, welches in <<listing-pom>> eingebunden wurde, liefert hierfür die ExceptionTo-Klassen des Plis-Namensraums.



== Verwendung auf Service-Seite

Die Bridge kann auch verwendet werden, falls eine 2.x-Anwendung eine 1er-Serviceschnittstelle zur Verfügung stellen möchte.
Hierfür liefert die Bridge zusätzlich auch zusätzliche Mapper für Exceptions, sowie für die Service-Annotationen.

Der BridgeExceptionMapper ermöglicht es reguläre Isyfact2-Exceptions in Isyfact1-TranferExceptions zu konvertieren.
Die Verwendung ist dabei identisch zum ExceptionMapper aus isy-serviceapi-core.
Das <<listing-exceptionmapper>> zeigt, wie die Verwendung in einer Exception-Fassade aussieht.

:desc-listing-exceptionmapper: Nutzung des BridgeExceptionMapper
[id="listing-exceptionmapper",reftext="Listing Nutzung des BridgeExceptionMapper"]
.{desc-listing-exceptionmapper}
[source,java]
----
import de.bund.bva.isyfact.exception.service.bridge.util.BridgeExceptionMapper;

...
public class BeispielExceptionFassade implements BeispielRemoteBean
{
    private BeispielService beispielService;
...
    public BeispielHolenAntwortTo holeBeispielAnfrage(
            AufrufKontextTo kontext,
            BeispielHolenAnfrageTo anfrage
        ) throws TargetPlisToException {
        try {
            return beispielService.holeBeispielAnfrage(kontext,anfrage);
        } catch (SomeIsyException someIsyException) {
            logger.error("Fehler bei Transaktion", someIsyException);
            throw BridgeExceptionMapper.mapException(someIsyException, TargetPlisToException.class);
        }
        // weitere Exceptions
}
...
----

Werden die `@Gesichert` und `@StelltAufrufKontextBereit`-Annotationen genutzt, bietet die Bridge zudem einen zusätzlichen Resolver an, damit der IsyFact1-AufrufKontextTo korrekt aufgelöst wird.

Hierfür muss neben den SST-Modulen auch die isy-serviceapi-core-bridge eingebunden werden:

:desc-listing-pom: Einbindung des Bridge-Serviceapi-Core-Moduls in pom.xml
[id="listing-pom-services",reftext="Listing Core pom.xml"]
.{desc-listing-pom-services}
[source,xml]
----
<dependency>
    <groupId>de.bund.bva.isyfact</groupId>
    <artifactId>isy-serviceapi-core-bridge</artifactId>
</dependency>
----

Über die Autokonfiguration wird damit automatisch der korrekte AufrufKontextToResolver eingebunden und die Annotationen lassen sich wie gehabt verwenden.

Weitere Informationen zum Aufbau der Service-Logik sind dem <<DetailkonzeptKomponenteService, Detailkonzept Komponente Service>> zu entnehmen.

// end::inhalt[]
