= Konzept Task Scheduling: Inhalt

// tag::inhalt[]
[[anforderungen]]
== Anforderungen

Im Folgenden werden die Anforderungen an die Steuerung von Aufgaben definiert.
Diese bilden die Grundlage für die Vorgaben im darauffolgenden Kapitel.

[[authentifizierung]]
=== Authentifizierung

Aufgaben muss es möglich sein, sich bei Bedarf zu authentifizieren, um entsprechend gesicherte fachliche Operationen durchzuführen.
Dazu müssen Aufgaben einen Benutzernamen und ein Passwort bereithalten.

[[nachvollziehbarkeit]]
=== Nachvollziehbarkeit

Aufgaben müssen fachliche Operationen nachvollziehbar aufrufen.
Das bedeutet, dass sich alle aufgerufenen fachlichen Operationen eindeutig einer bestimmten Ausführung einer Aufgabe zuordnen lassen.

[[logging]]
=== Logging

Aufgaben müssen mindestens die folgenden Ereignisse ins Log schreiben:

* Start und Ende der Ausführung (Log-Level: INFO)
* Fachliche Fehlermeldungen (Log-Level: INFO)
* Technische Fehlermeldungen (Log-Level: ERROR)

Die Bibliothek muss mindestens die folgenden Ereignisse ins Log schreiben:

* Fehler in der Konfiguration von Aufgaben (Log-Level: ERROR)
* Aktivierung und Deaktivierung von Aufgaben zur Laufzeit (Log-Level: INFO)

[[überwachung]]
=== Überwachung

Aufgaben müssen Überwachungsmöglichkeiten bieten.
Die folgenden Parameter müssen lesend zur Verfügung stehen:

* Zeitraum (Start, Ende) der letzten Ausführung
* Ergebnis der letzten Ausführung (Erfolg, fachliche / technische Fehler) inklusive einer Beschreibung des Fehlers
* alle Konfigurationsparameter

Aufgaben müssen über die Überwachung manuell gestartet werden können.

[[programmatische-steuerung]]
=== Programmatische Steuerung

Aufgaben müssen, neben der betrieblichen Konfiguration, auch programmatisch gesteuert werden können.
Dazu gehören die folgenden Operationen:

* Aufgaben manuell und ohne Zeitverzögerung ausführen
* Aufgaben aktivieren und deaktivieren

[[vorgaben]]
== Vorgaben

Die folgenden architektonischen und technischen Vorgaben beziehen sich auf die Umsetzung der in Kapitel siehe xref:konzept/master.adoc#anforderungen[Anforderungen]
genannten Anforderungen in der zu diesem Baustein gehörenden Bibliothek.

[[namenskonventionen]]
=== Namenskonventionen

Die Bibliothek besitzt die folgenden Maven-Koordinaten:

* Group-ID: `de.bund.bva.isyfact`
* Artifact-ID: `isy-task`

Das Stammpackage für alle Klassen der Umsetzung lautet: `de.bund.bva.isyfact.task`.

[[bedeutung-der-standardbibliothek]]
=== Bedeutung der Standardbibliothek

Die Bibliothek muss zur Umsetzung der Anforderungen so stark wie möglich auf die in der Java-Standardbibliothek vorhandenen Möglichkeiten setzen.
Insbesondere soll sie die Möglichkeiten des Packages `java.util.concurrent` nutzen, darunter vor allem die der Klasse `ScheduledExecutorService`.
Die Bibliothek muss die Implementierung dieser Klasse, `ScheduledThreadPoolExecutor`, mit sinnvollen Standardwerten konfigurieren und wichtige Kenngrößen wie die Größe des Thread Pools konfigurierbar gestalten.

Die Klassen des Packages `org.springframework.core.task` können ergänzend benutzt werden, falls sie gegenüber der Standardbibliothek einen signifikanten funktionalen Mehrwert aufweisen.

Die folgenden Klassen dürfen von der Bibliothek nicht verwendet werden:

* `java.util.Timertask` sowie `java.util.Timer` zur Planung und Ausführung von Aufgaben, da diese Klassen wesentlich weniger Funktionalität bieten als die des Packages `java.util.concurrent`,

[[authentifizierung-1]]
=== Authentifizierung

Die Bibliothek muss Aufgaben bei Bedarf über den Baustein Sicherheit (s. <<TODO anderes Dokument: NutzungsvorgabenSicherheit>>) authentifizieren.
Dazu ist ein Benutzername und ein Passwort nötig, dass die Bibliothek als betriebliche Konfiguration, wie im Baustein Konfiguration (s. <<TODO anderes Dokument: KonzeptKonfiguration>>) vorgegeben, einlesen muss.

[[nachvollziehbarkeit-1]]
=== Nachvollziehbarkeit

Die Bibliothek muss zur Sicherstellung der Nachvollziehbarkeit Korrelations-IDs verwenden.
Das Konzept der Korrelations-ID ist im<<TODO anderes Dokument: KonzeptLogging>> des Bausteins Logging beschrieben.

Die Bibliothek muss für jede Ausführung einer Aufgabe eine Korrelations-ID erzeugen und sie im MDC von logback als auch, falls sich die Aufgabe authentifizieren muss, im Aufrufkontext setzen.
Die Dokumente <<TODO anderes Dokument: NutzungsvorgabenLogging>> sowie <<TODO anderes Dokument: NutzungsvorgabenSicherheit>> der Bausteine Logging und Sicherheit beschreiben im Detail, wo und wie die Korrelations-ID gesetzt werden muss.

[[ueberwachung]]
=== Überwachung

Die Bibliothek muss zur Überwachung von Aufgaben eine JMX-Bean definieren.
Diese ist mit Standardattributen, die allen Aufgaben gemein sind, gefüllt.
Anwendungen können von diesen abstrakten JMX-Beans ableiten, um weitere Attribute überwachbar zu gestalten.

Die Bibliothek muss des Weiteren eine Standardkonfiguration bereitstellen, um JMX-Beans automatisch beim Start der Anwendung zu registrieren.

[[programmatische-steuerung-1]]
=== Programmatische Steuerung

Die Bibliothek muss die folgenden Operationen auf Aufgaben anbieten:

* Aufgaben manuell und ohne Zeitverzögerung ausführen
* Aufgaben aktivieren und deaktivieren

Die Deaktivierung von Aufgaben ist temporärer Natur und wird spätestens beim Neustart der Anwendung auf die Werte der betrieblichen Konfiguration zurückgesetzt.
Für eine dauerhafte Änderung muss die betriebliche Konfiguration angepasst werden.

[[zuweisung-zwischen-aufgaben-und-maschinen]]
=== Zuweisung zwischen Aufgaben und Maschinen

Die Bibliothek muss vorsehen, dass Aufgaben fest Maschinen zugeordnet werden.
Dazu wird die Aufgabe mit einem Hostnamen konfiguriert.
Die Aufgabe wird nur dann dem Scheduler hinzugefügt, wenn der konfigurierte Hostname mit dem der ausführenden Maschine übereinstimmt.

[[darstellung]]
=== Darstellung

Die Bibliothek unterstützt die Darstellung bzw. programmatische Steuerung von Aufgaben mittels grafischen Oberflächen nicht direkt.
Sie muss ihre Funktionalität allerdings so bereitstellen, dass sie leicht von GUI-Technologien verwendet werden kann.

[[konfiguration]]
=== Konfiguration

Die Konfiguration der Aufgaben geschieht über Konfigurationsparameter.
Die Parameter entsprechen Java Properties.
Alle Properties entsprechen folgendem Schema:

*isyfact.task.<aufgaben-id>.<property>*

Jede Aufgabe erhält eine eindeutige ID, die standardmäßig dem Klassennamen, beginnend mit einem Kleinbuchstaben, entspricht.
Die ID ist außerdem Teil der Spring-Konfiguration einer Aufgabe.
Die Bibliothek stellt über die ID sicher, dass jede Aufgabe automatisch beim Start der Anwendung konfiguriert werden kann.

Die Bibliothek definiert für alle allgemeinen Parameter sinnvolle Standardwerte.
Alle Standardwerte entsprechen folgendem Schema:

*isyfact.task.standard.<property>*

Die Definition der Standardwerte ergänzt die Regelungen zu Default-Werten in der betrieblichen Konfiguration (s. <<TODO anderes Dokument: KonzeptKonfiguration>>).
Während diese Default-Werte des Bausteins Konfiguration jeweils nur für eine konkrete Aufgabe gelten, sind die hier beschriebenen Standardwerte für alle in einer Anwendung definierten Aufgaben gültig.

Zum Auslesen der Konfiguration einer Aufgabe wird die Klasse `TaskKonfiguration` definiert.
Sie wird mit dem Interface Konfiguration des gleichnamigen Bausteins und dem Namen einer Aufgabe initialisiert.
Zum Lesen der Konfigurationsparameter enthält die Klasse entsprechende Methoden.
Die Klasse löst die Parameter der Aufgabe bei jedem Aufruf einer dieser Methoden dynamisch auf.
Die Klasse `TaskKonfiguration` sollte von Anwendungen erweitert werden, um weitere, spezifische Konfigurationsparameter aufzulösen.

Die Klasse `TaskKonfiguration` benutzt eine weitere Klasse `TaskStandardKonfiguration`, um die Standardwerte für Aufgaben aufzulösen.
`TaskStandardKonfiguration` ist ebenfalls von `TaskKonfiguration` abgeleitet.

Die Bibliothek muss Anwendungen eine Konfigurationsklasse bzw. Spring Bean bereitstellen, die es ermöglicht, alle konfigurierten Aufgaben beim Start der Anwendung einzulesen und dem Scheduler hinzuzufügen.

// end::inhalt[]

// tag::architekturregel[]

// end::architekturregel[]

// tag::sicherheit[]

// end::sicherheit[]
