= Konzept Task Scheduling: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Dieses Dokument beschreibt die konzeptionellen Grundlagen der Steuerung (d.h. Planung und Ausführung) von Aufgaben (Task Scheduling) in der IsyFact.
Mit „Aufgaben“ sind hier periodisch wiederkehrende Tätigkeiten gemeint, die innerhalb einer xref:glossary:glossary:master.adoc#glossar-anwendungskomponente[Anwendungskomponenten] angesiedelt sind und zur Erfüllung der fachlichen oder technischen Anforderungen der Anwendung beitragen.
Das Dokument beschreibt die Anforderungen und Vorgaben zur Umsetzung der Steuerung von Aufgaben und bildet so die Grundlage einer technisch und fachlich einheitlichen Umsetzung.

Die aus diesem Dokument abgeleitete Umsetzung der Steuerung von Aufgaben im Rahmen der Anwendungsentwicklung ist in dem Dokument xref:nutzungsvorgaben/master.adoc#einleitung[Task-Scheduling - Nutzungsvorgaben] beschrieben.

Sowohl dieses Dokument als auch das Umsetzungsdokument bedienen sich Erfahrungen sowie Best Practices aus erfolgreich abgeschlossenen Projekten.Nutzungsvorgaben Scheduling

[[abgrenzung-zu-batches]]
=== Abgrenzung zu Batches

Das xref:blaupausen:detailkonzept-komponente-batch/master.adoc[Detailkonzept Komponente Batch] definiert xref:glossary:glossary:master.adoc#glossar-batch[Batches] wie folgt:
_„Der Begriff „Batch“ bedeutet im Kern lediglich „nicht interaktive Stapelverarbeitung“.
Ein Batch teilt sich auf in einen „Batchrahmen“, die Batchlogik der einzelnen Batch-Anwendungen, sowie die von ihnen aufgerufenen Komponenten des Anwendungskerns. […]
Typischerweise verarbeiten Batches dabei Dateilieferungen oder eine definierte Menge von Datensätzen aus dem Datenbestand.“_

Die in diesem Konzept beschriebenen Aufgaben sind hingegen nicht die Grundlage einer eigenen (Batch-) Anwendung, sondern in die eigentliche Anwendung integriert.
Die Aufgaben sind Teil einer Komponente des xref:glossary:glossary:master.adoc#glossar-anwendungskern[Anwendungskerns].
Sie besitzen in der Regel einen kleineren Umfang als Batches und werden nicht manuell von außen gesteuert.
Stattdessen werden sie durch die Anwendung selbst konfiguriert, zeitlich geplant und selbstständig ausgeführt.

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

Ziel des Dokuments ist die Definition einheitlicher Vorgaben für die Steuerung von Aufgaben unter Berücksichtigung fachlicher und technischer Anforderungen.

Das Dokument ist entsprechend dieser Zielsetzungen folgendermaßen aufgebaut:

Zunächst werden die xref:konzept/master.adoc#anforderungen[Anforderungen] an die Steuerung von Aufgaben definiert, welche die Grundlage für das nachfolgende Kapitel bilden.

Anschließend werden die xref:konzept/master.adoc#vorgaben[Vorgaben] zur Steuerung von Aufgaben innerhalb der Anwendungen sowie zur Umsetzung in der zu diesem xref:glossary:glossary:master.adoc#glossar-baustein[Baustein] gehörenden xref:glossary:glossary:master.adoc#glossar-bibliothek[Bibliothek] definiert.
// end::inhalt[]
