= Umsetzung des Datenzugriffs

include::glossary:licence:partial$licence.adoc[]

Die Umsetzung des Datenzugriffs mit JPA und Hibernate beachtet die xref:konzept/vorgaben-konventionen.adoc[] zu diesem Thema.
Das Produkt Spring Data JPA vereinfacht die Umsetzung weiter.

[[umsetzung-daos]]
== Umsetzung der Data Access Objects

Für die Ablage der Data Access Objects (DAOs) und Entitäten gibt es eine Konvention.

//tag::namenskonvention[]

.Vorgaben zur Paketstruktur für Klassen des Datenzugriffs
[[table-paketstruktur]]
[cols="1s,4m",options="header"]
|===
|Klassen |Package
|DAO
|<organisation>.<domäne>.<system>.persistence.<komponente>.dao

|Entity
|<organisation>.<domäne>.<system>.persistence.<komponente>.entity
|===

//end::namenskonvention[]

Um den Anteil an Boilerplate Code bei der Umsetzung des Datenzugriffs deutlich zu reduzieren, werden (Spring Data) *Repositories* eingesetzt.
Die häufig verwendeten CRUD-Methoden (Create, Read, Update, Delete) werden vom Interface `CrudRepository` (siehe <<listing-crudrepository>>) zur direkten Verwendung angeboten.
Zur Implementierung werden zwei Typ-Parameter benötigt: der Typ der Entität `T` und der Typ des Primärschlüssels `ID`.

.Methoden von CrudRepository
[[listing-crudrepository]]
[source,java]
----
public interface CrudRepository<T,ID> {
    long        count();
    void        delete(T entity);
    void        deleteAll();
    void        deleteAll(Iterable<? extends T> entities);
    void        deleteById(ID id);
    boolean     existsById(ID id);
    Iterable<T> findAll();
    Iterable<T> findAllById(Iterable<ID> ids);
    Optional<T> findById(ID id);
    T           save(T entity);
    Iterable<T> saveAll(Iterable<T> entities);
}
----

Der Zugriff auf die Datenbank aus dem xref:glossary:glossary:master.adoc#glossar-anwendungskern[Anwendungskern] heraus erfolgt immer über diese Repositories.
Die Repositories werden als Spring-Beans in den Anwendungskern injiziert.
Für jede Entität wird ein entsprechendes Repository als Interface angelegt.

Die Repositories werden im Package der Fachkomponente abgelegt, welche die Datenhoheit über die Tabelle(n) des Repositories besitzt (zum Thema Datenhoheit siehe xref:blaupausen:referenzarchitektur-it-system/master.adoc#datenzugriff[Referenzarchitektur IT-System]).
Die Repositories werden nur von Klassen der Fachkomponente mit Datenhoheit aufgerufen.

Gemäß der xref:blaupausen:referenzarchitektur-it-system/master.adoc#datenzugriff[Referenzarchitektur] dürfen Entitäten nur von der Fachkomponente im Anwendungskern verändert werden, welche zur Fachkomponente im Datenzugriff gehört.
Der Anwendungskern darf für andere Fachkomponenten nur Geschäftsobjekte an seiner Fachkomponentenschnittstelle anbieten.

Für ein konkretes DAO ist ein eigenes Interface von der Basisschnittstelle `CrudRepository` abzuleiten.
Die Benennung erfolgt gemäß der xref:konzept/vorgaben-konventionen.adoc#namenskonvention-spring-data-repository[Namenskonvention].
In der Dao-Klasse können weitere DAO-Operationen definiert werden, zum Beispiel zur Durchführung von Queries.
Ein Beispiel hierfür ist in <<listing-beispielrepository>> zu sehen.

Weiterhin ist das eigene Interface mit der Annotation `@Repository` zu versehen, damit alle vom Entity Manager erzeugten Exceptions in die besser auszuwertenden Exceptions von Spring Data umgewandelt werden.

.Beispiel für ein eigenes Data Access Object
[[listing-beispielrepository]]
[source,java]
----
@Repository
public interface PersonRepository extends Repository<Person, Long> { }
----

Damit die DAOs von Spring automatisch als Beans erzeugt werden, muss eine Konfigurationsklasse der Anwendung mit der Annotation `@EnableJpaRepositories` annotiert werden.

.Automatische Erstellung von DAO-Beans durch Spring
[[listing-enablejparepositories]]
[source,java]
----
@Configuration
@EnableJpaRepositories("<organisation>.<domäne>.<system>.persistence")
class PersistenceConfiguration { }
----

[[definition-von-query-methoden]]
=== Definition von Query Methoden

Der von Spring Data erzeugte Proxy für das Repository-Interface kann die Queries auf zwei Arten ableiten.

==== Ableitung des Queries über den Namen der Methode

Bei dieser Ableitung wird das Präfix des Methodennamens abgeschnitten und der Rest geparst.
Nach dem ersten `By` beginnen die eigentlichen Abfragekriterien.
In den Abfragekriterien werden Bedingungen auf Feldern der Entität definiert und diese können mit `And` und `Or`
verknüpft werden.

.Beispiele für die Ableitung des Queries aus dem Methodennamen
[[listing-querymethodenname]]
[source,java]
----
@Repository
public interface PersonRepository extends Repository<Person, Long> {

    List<Person> findByEmailAdresseAndNachname(EmailAdresse emailAdresse, String nachname);

    // Verwendung von DISTINCT
    List<Person> findDistinctPeopleByNachnameOrVorname(String nachname, String vorname);
    List<Person> findPeopleDistinctByNachnameOrVorname(String nachname, String vorname);

    // Ignorieren der Groß-/Kleinschreibung für ein bestimmtes Feld
    List<Person> findByNachnameIgnoreCase(String nachname);
    // Ignorieren der Groß-/Kleinschreibung für alle betroffenen Felder
    List<Person> findByNachnameAndVornameAllIgnoreCase(String nachname, String vorname);

    // Statisches Sortieren mit ORDER BY
    List<Person> findByNachnameOrderByVornameAsc(String nachname);
    List<Person> findByNachnameOrderByVornameDesc(String nachname);

}
----

NOTE: Eine Übersicht zur Ableitung von Queries aus Methodennamen befindet sich in der
https://docs.spring.io/spring-data/jpa/docs/2.7.x/reference/html/#repositories.query-methods.details[Referenzdokumentation zu Spring Data JPA].

==== Ableitung über eine manuell definierte Query.

Die Query wird über die `@Query`-Annotation in JPQL direkt an die Methode des DAO geschrieben.

.Beispiele für die Ableitung des Queries aus dem Methodennamen.
[[listing-queryannotation]]
[source,java]
----
@Repository
public interface PersonRepository extends Repository<Person, Long> {

    @Query("select p from Person p where p.emailAdresse = ?1")
    Person findByEmailAdresse(String emailAdresse);

}
----

Bevorzugt wird die Ableitung der Queries über den Methodennamen.
Kann die Query nicht über den Methodennamen ausgedrückt werden, werden manuell definierte Queries verwendet.


[[definition-or-mapping]]
== Definition des O/R-Mappings

Entitäten werden über Annotationen gekennzeichnet.

.Definition einer Entität
[source,java]
----
@Entity
public class MyEntity { }
----

Primärschlüssel werden wie folgt annotiert.

.Konfiguration der ID und Sequenz
[source,java]
----
@Entity
public class MyEntity {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO, generator="my_seq")
    @SequenceGenerator(name="my_seq",sequenceName="MY_SEQ", allocationSize=50)
    private int id;

}
----

Es muss unbedingt darauf geachtet werden, das Inkrement (`INCREMENT BY`) der zur ID-Generierung genutzt Datenbanksequenz auf denselben Wert einzustellen, der auch beim `SequenceGenerator` im Parameter `allocationSize` angegeben ist.

[[assoziationen]]
=== Assoziationen

1-zu-n-Assoziationen werden entweder über eine unsortierte Menge oder eine von der Datenbank vorsortierten Liste definiert.

.Definition von 1-zu-n-Assoziationen
[[definition-1-zu-n-assoziation]]
[source,java]
----
@Entity
public class MyEntity {

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "unsorted_id")
    private Set<UnsortedEntity> unsortedEntities = new HashSet<>();

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "sorted_id")
    @OrderBy("field ASC")
    private List<SortedEntity> sortedEntities = new ArrayList<>();

}
----

[[lazy-loading]]
==== Lazy Loading

Standardmäßig soll für alle Assoziationen Lazy Loading verwendet werden.
Um Lazy Loading auch für 1-zu-1-Assoziationen einzuschalten, wird das `fetch`-Attribut der Annotation `@OneToOne` auf `FetchType.LAZY` gesetzt.
Damit das Lazy Loading über Proxies funktioniert, muss die Assoziation nicht optional sein, d.h. das Feld darf nicht `null` sein.

.Lazy Loading bei 1-zu-1-Assoziationen
[source,java]
----
@Entity
public class MyEntity {

    @OneToOne(optional = false, fetch = FetchType.LAZY)
    private OtherEntity otherEntity;

}
----

Für n-zu-1-Assoziationen wird genauso verfahren und das `fetch`-Attribut auf `FetchType.LAZY` gesetzt.

.Lazy Loading bei n-zu-1-Assoziationen
[source,java]
----
@Entity
public class MyEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    private OtherEntity otherEntity;

}
----

Anders als bei 1-zu-1-Assoziationen ist hier erlaubt, Eager Loading zu verwenden, wenn dieses Verhalten Sinn ergibt und keine negativen Auswirkungen zu erwarten sind.
Typische negative Auswirkungen sind N+1-Queries (die umgekehrte Assoziation von `OtherEntity` zu `MyEntity` benutzt Eager Loading) oder das Auslesen zu vieler Daten (`OtherEntity` besitzt viele Assoziationen mit Eager Loading).

[[datum-zeit]]
=== Datum & Zeit
Für Datumsangaben werden die Datums- und Zeitklassen aus der _Java 8 Date Time API_ verwendet.

WARNING: Der folgende, hervorgehobene Absatz wird nur noch aus historischen Gründen erwähnt und ist obsolet.

====
Für alte Anwendungen, die nicht die _Java 8 Date Time API_, sondern noch `java.util.Date` verwenden, gelten die folgenden Vorgaben.

Die Definition von Datumsangaben erfolgt in einem Attribut vom Typ `TemporalType.TIMESTAMP` oder `TemporalType.DATE`.

.Definition von Datumsangaben
[[definition-datum-legacy]]
[source,java]
----
@Entity
public class MyEntity {

    @Temporal(TemporalType.TIMESTAMP)
    private Date genauesDatum;

    @Temporal(TemporalType.DATE)
    private Date ungenauesDatum;

}
----

Vergleiche von Datumsangaben sind nur mittels `compareTo` und immer auf dem Attribut mit der höheren Genauigkeit durchzuführen.

.Vergleiche von Datumsangaben
[[vergleiche-datum-legacy]]
[source,java]
----
public class MyUseCase {

    public void calculateDates(MyEntity entity) {
        entity.getGenauesDatum().compareTo(entity.getUngenauesDatum()); // OK

        entity.getUngenauesDatum().compareTo(entity.getGenauesDatum()); // NICHT OK
        entity.getGenauesDatum().equals(entity.getUngenauesDatum());    // NICHT OK
        entity.getUngenauesDatum().equals(entity.getGenauesDatum());    // NICHT OK
    }
}
----

Für Berechnungen auf Datumsangaben ist der Typ `java.util.Calendar` zu verwenden.
====

[[enum-variablen]]
=== Enum-Variablen

Enums werden über zwei spezielle Hibernate User-Types definiert.
Diese ermöglichen es, Enum-Werte auf fest definierte Zeichenketten abzubilden.

Die Klasse `EnumUserType` erlaubt es, in einem Enum per Annotation die gewünschte Datenbankdarstellung zu jeder Ausprägung anzugeben.

.Definition eines Enums zur Verwendung mit `EnumUserType`
[[definition-enumusertype]]
[source,java]
----
public enum Richtung {

    @PersistentValue("L")
    LINKS,
    @PersistentValue("R")
    RECHTS,
    @PersistentValue("G")
    GERADEAUS

}
----

Die Klasse `EnumWithIdUserType` erlaubt die Persistierung von Enums, die einen fachlichen Schlüssel besitzen.

.Definition eines Enums zur Verwendung mit `EnumWithIdUserType`
[[definition-enumwithidusertype]]
[source,java]
----
public enum RichtungMitId {

    LINKS("L"),
    RECHTS("R"),
    GERADEAUS("G");

    private final String id;

    RichtungMitId(String id) {
        this.id = id;
    }

    @EnumId
    public String getId() {
        return id;
    }

}
----

Das folgende Beispiel zeigt die Verwendung dieser Enums in einer Entität.

.Verwendung von Enums in Entitäten
[[verwendung-enum-in-entitaeten]]
[source,java]
----
@Entity
public class MyEntity {

  @Column(nullable = false, length = 1)
  @Type(type = "de.bund.bva.isyfact.persistence.usertype.EnumUserType",
    parameters = { @Parameter(name = "enumClass",value = "<package>.Richtung") })
  private Richtung richtung;

  @Column(nullable = false, length = 1)
  @Type(type = "de.bund.bva.isyfact.persistence.usertype.EnumWithIdUserType",
    parameters = { @Parameter(name = "enumClass",value = "<package>.RichtungMitId") })
  private RichtungMitId richtungMitId;

}
----

[[initialisieren-von-string-feldern]]
=== Initialisieren von String-Feldern

Für die Verarbeitung in Regelwerken ist es hilfreich, dass String-Felder initialisiert werden, da ansonsten in nahezu allen Regeln zwischen einer leeren Zeichenkette und `null` differenziert werden müsste.
In Objekten, die in das Regelwerk eingegeben werden sollen, wird daher bei der Definition von String-Feldern initial ein Leer-String gesetzt.

[source,java]
----
@Entity
public class MyEntity {

   private String name = "";

}
----
// Zeitgemäß? Kann man doch sicher im Regelwerk abfangen...

[[optimistic-locking]]
=== Optimistisches Locking

Zur Umsetzung des optimistischen Lockings wird in Entitäten eine numerische Property mit der Annotation `@Version` gekennzeichnet.

.Versionierung von Entitäten für optimistisches Locking
[source,java]
----
@Entity
public class MyEntity {

    private int version;

    @Version
    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

}
----

Dieses Feld wird einzig von Hibernate verwaltet.
Es ist weder zu lesen noch zu schreiben.
