= API-Gateway

// tag::api-gateway-definition-fachlich[]

Das xref:fachlich/api-gateway.adoc[] stellt den zentralen, einheitlichen Einstiegspunkt für alle externen Anwendungen (Clients) dar, die auf fachliche Funktionalitäten der Anwendungslandschaft zugreifen. Es kapselt interne Schnittstellen, schützt nachgelagerte Geschäftsanwendungen und bietet nach außen konsolidierte, versionierte und gesicherte APIs an.

// end::api-gateway-definition-fachlich[]

[[fachliche-verantwortlichkeiten]]
== Fachliche Verantwortlichkeiten

Aus fachlicher Sicht übernimmt das API‑Gateway die folgenden Verantwortlichkeiten:

* Entkopplung zwischen den externen Anwendungen und den internen Backends der Geschäftsanwendungen durch einheitlich bereitgestellte und versionierte APIs,
* Standardisierung des Zugriffs auf Geschäftsobjekte und ‑prozesse,
* Schutz der internen Anwendungen vor Angriffen, Überlastung und unzulässigen Zugriffen,
* Durchsetzung fachlich relevanter Zugriffsregeln.

[[fachlicher-kontext]]
== Fachlicher Kontext

Das API‑Gateway kommuniziert mit den folgenden Akteuren:

* externen Anwendungen,
* internen Geschäfts- und Querschnittsanwendungen,
* dem zentralen Identity & Access Management (IAM).

.Fachliches Kontextdiagramm des API‑Gateways
image::fachlich/api-gateway.dn.svg[]

Externe Anwendungen rufen über das API-Gateway fachliche Schnittstellen auf, um Geschäftsvorgänge auszuführen oder Informationen abzurufen.

Interne Geschäfts- und Querschnittsanwendungen nutzen das API‑Gateway auf mehrere Arten.
Sie verarbeiten die durch das API‑Gateway delegierten Anfragen externer Anwendungen oder greifen selbst auf fachliche Schnittstellen externer Anwendungen zu.
Außerdem nutzen sie das API-Gateway zur Kommunikation zwischen ihren technischen Bestandteilen, falls diese in Teilen außerhalb der Anwendungslandschaft liegen, wie zum Beispiel die im Browser der Anwender laufenden xref:glossary::terms-definitions.adoc#frontend[Frontends].

Ein zentrales IAM befähigt das API-Gateway, externe Anwendungen zu authentifizieren und für den Zugriff auf interne Backends der Geschäftsanwendungen zu autorisieren, zum Beispiel durch Rollen oder eine Mandantenkennung.



