= Konzept JPA/Hibernate

include::glossary:licence:partial$licence.adoc[]

Das Konzept JPA/Hibernate konkretisiert die xref:referenzarchitektur:software-technisch/backend/persistenzschicht.adoc[Vorgaben aus der Referenzarchitektur] bezüglich der Persistenzschicht und bietet eine architektonische Lösung auf Basis des O/R-Mappers Hibernate.
Das Konzept verfolgt vor allem das Ziel, die Verwendung von JPA und Hibernate:

* projektübergreifend zu vereinheitlichen, und
* so einfach, komfortabel und verständlich wie möglich zu gestalten.

Abweichungen zu den Vorgaben dieses Konzepts müssen als Architekturentscheidung im xref:methodik:vorlagen.adoc#dokumentation-anwendung[Systementwurf] dokumentiert werden.

Das Konzept beinhaltet drei Themen.
Das größte Thema behandelt die xref:konzept/vorgaben-konventionen.adoc[] bei der Umsetzung der Persistenzschicht mit JPA und Hibernate.
Die Vorgaben und Konventionen betreffen die folgenden Bereiche:

* die generelle Verwendung von JPA und Hibernate,
* die Definition des O/R-Mappings.

Ausgehend von diesen Vorgaben beleuchtet das Konzept die beiden weiterführenden Themen xref:konzept/historisierung.adoc[] und Versionierung anhand  xref:konzept/versionierung-mit-liquibase.adoc[Liquibase] und einer xref:konzept/versionierung.adoc[Eigenentwicklung].
