= IsyFact-Whitepaper
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

== IsyFact: eine Software Factory zur effizienten Entwicklung von Anwendungen

*Das Bundesverwaltungsamt stellt seinen in einer Vielzahl von Projekten eingesetzten und etablierten Standard für die Erstellung von betrieblichen Informationssystemen als Open Source zur Verfügung.*

Bei der Entwicklung von Anwendungen für eine bestimmte Domäne stehen Architekten und Entwickler häufig vor denselben, wiederkehrenden Problemen.
Zwar unterscheiden sich je nach Anwendung die Datenstrukturen, die Geschäftslogik und die Benutzeroberflächen, aber die allgemeinen Prinzipien, z.B. der Datenhaltung, der Architektur und der Gestaltung von Benutzerschnittstellen, sind in der Regel für alle Anwendungen identisch und somit wiederverwendbar.

Die Herausforderung bei der Wiederverwendung besteht darin, das einmal erworbene Wissen über die Anwendungsentwicklung in einer Domäne zu strukturieren, zu dokumentieren und vorzuhalten, sodass nachfolgende Projekte einfach und verlässlich darauf zugreifen können, und damit die Einhaltung des definierten Architekturrahmens sicherzustellen.

Eine *Software Factory* ist ein Mittel, um dieses Ziel zu erreichen.

=== Standardisierung und Modularisierung der Softwareentwicklung

Die *IsyFact* ist eine Software Factory für den Bau von Informationssystemen in komplexen IT-Anwendungslandschaften.
Sie bündelt bestehendes technisches Know-how, um Anwendungssysteme effizienter entwickeln und betreiben zu können.
Wie in einer Fabrik, in der gleichartige Teile durch standardisierte Fertigkomponenten gefertigt werden, bietet die IsyFact einen Ansatz in der Informationstechnik.
Architektur, Konzepte, technische Infrastruktur, Querschnittsanwendungen, Programmierbibliotheken und Middleware sind standardisiert und können wiederverwendet werden.

=== IsyFact-Standards als Open Source-Projekt

Das Bundesverwaltungsamt stellt die IsyFact bereits seit geraumer Zeit anderen Behörden für ihre Softwareentwicklungsprojekte zur Verfügung.
Die Grundlagen der IsyFact sind jedoch so allgemein, dass sie sich für die Entwicklung von Informationssystemen in beliebigen Anwendungskontexten eignen.

Das Bundesverwaltungsamt hat deswegen 2015 die Grundlagen der IsyFact als IsyFact-Standards ausgekoppelt und stellt sie auch nicht-behördlichen Nutzern als Open-Source-Software bereit.
Interessenten können die IsyFact-Standards selbstständig aus dem GitHub-Repository beziehen.
Dies beschleunigt den Prozess der Bereitstellung und verringert die Einstiegshürde für potenzielle Nutzer.

Durch die Open-Source-Stellung stehen die IsyFact-Standards einem größeren Kreis von Nutzern zur Verfügung.
Auch wenn sie ursprünglich im Kontext der öffentlichen Verwaltung entwickelt wurde, können mit ihnen Anwendungslandschaften in anderen Anwendungskontexten ohne weiteres erstellt werden.
Jeder Nutzer kann die IsyFact nach seinen Bedürfnissen anpassen und eigene Erweiterungen schreiben.

Das Bundesverwaltungsamt nimmt gerne Feedback zur IsyFact entgegen und ist an Korrekturen, Aktualisierungen und Erweiterungen interessiert.
Entsprechende Vorschläge können gerne angeregt oder in Form von Pull Requests eingereicht werden.
Das Bundesverwaltungsamt behält sich vor, diese nach eigenem Ermessen in die IsyFact aufzunehmen.


[[die-fuenf-saeulen]]
== Die fünf Säulen der IsyFact

*Die IsyFact umfasst: Blaupausen, Bausteine, eine Betriebsplattform, methodische Vorgaben zum Software-Engineering und Entwicklungswerkzeuge.*

Die IsyFact stellt Ihre Inhalte strukturiert in fünf *Säulen* zur Verfügung:

<<blaupausen>>:: Vorlagen für die Erstellung von Geschäftsanwendungen auf fachlicher, software-technischer und technisch-infrastruktureller Ebene.

<<bausteine>>:: Wiederverwendbare Softwarelösungen, querschnittliche Systeme sowie Programmierbibliotheken und -vorlagen.

<<plattform>>:: Eine einheitliche, hochverfügbare Betriebsumgebung mit leistungsfähiger Hardware und der benötigten Systemsoftware.

<<methodik>>:: Konventionen und Vorgaben für die Spezifikation und Programmierung sowie das Projektvorgehen nach V-Modell XT.

<<werkzeuge>>:: Tools für teilweise Automatisierung von Modellierung, Programmierung, Tests und Fehlerverfolgung.

.Die fünf Säulen der IsyFact
image::einstieg:sf-saeulen.dn.svg[]

Die folgenden Abschnitte beschreiben die einzelnen Säulen im Detail.

[[blaupausen]]
=== Blaupausen

include::blaupausen:page$blaupausen.adoc[tag=whitepaper,leveloffset=2]

[[bausteine]]
=== Bausteine

include::bausteine:page$bausteine.adoc[tag=whitepaper,leveloffset=2]

[[plattform]]
=== Plattform

include::plattform:page$plattform.adoc[tag=whitepaper,leveloffset=2]

[[methodik]]
=== Methodik

include::methodik:page$methodik.adoc[tag=whitepaper,leveloffset=2]

[[werkzeuge]]
=== Werkzeuge

include::werkzeuge:page$werkzeuge.adoc[tag=whitepaper,leveloffset=2]

[[vorteile-nutzen]]
== Vorteile / Nutzen

Die IsyFact wird seit 2007 durch das Bundesverwaltungsamt entwickelt und in unterschiedlichen Projekten in der Praxis eingesetzt.
Sie ist mittlerweile ein wertvoller Know-how-Baustein des BVA geworden.

Das Bundesverwaltungsamt stellt die IsyFact seit 2015 als Open Source auch für nicht-behördliche Anwender zur Verfügung.

Die Vorteile bei Nutzung der IsyFact sind:

* *Festes Fundament durch fünf Säulen:* Blaupausen, Bausteine, Plattform, Methodik, Werkzeuge
* *Universelle Vorbereitung für verschiedenste Geschäftsanwendungen:* Nutzung der Gemeinsamkeiten von Geschäftsanwendungen
* *Effizienter Bau von Geschäftsanwendungen:* Schneller und kostengünstiger als ohne IsyFact-Standards
* *Effizienter Betrieb von Geschäftsanwendungen:* Vorteile durch Standardisierung und Nutzungsvorgaben
* *In der Praxis erprobtes Verfahren:* Migration bestehender und Umsetzung neuer Geschäftsanwendungen im Bundesverwaltungsamt

[[produktueberblick]]
== Produktüberblick

*Basistechnologie der IsyFact sind die Programmiersprache Java und das Anwendungsframework Spring Boot.
Soweit möglich nutzt die IsyFact etablierte Softwareprodukte, Frameworks und Bibliotheken.*

Die nachfolgende Tabelle gibt einen Überblick über die in der IsyFact vorgegebenen bzw. empfohlenen Produkte.

[cols="1,1",options="header"]
|====
2+|Basistechnologien
|Programmiersprache |Java
|Web-Technologie |XHTML
|Architekturmuster |Service-orientierte Architektur (SOA)
|====

[cols="1,1",options="header"]
|====
2+|Systemsoftware
|JEE-Applikationsserver | Apache Tomcat
|Authentifizierung / Autorisierung | OAuth2 / OpenID Connect +
Keycloak
|Webserver |Apache HTTP Server
|====

[cols="1,1",options="header"]
|====
2+|Bibliotheken für die Anwendungsentwicklung
|Web-Framework |JSF/Spring MVC/Webflow +
Angular
|Anwendungskern-Framework |Spring Boot
|Persistenz-Framework |Spring Data & JPA/Hibernate
|Logging-Framework |Logback
|====

[cols="1,1",options="header"]
|====
2+|Spezielle Software und Bibliotheken
|Überwachung / Monitoring |Micrometer
|Test-Framework | JUnit, Mockito
|====

[cols="1,1",options="header"]
|====
2+|Werkzeuge und Methodiken
|Programmierung |Eclipse, IntelliJ IDEA
|Modellierung|diagrams.net, Enterprise Architect
|====

[cols="1,1",options="header"]
|====
2+|Basistechnologien
|Build und Deployment |Maven
|Fehler- und Änderungsmanagement |Jira
|====

[[uebersicht-isyfact-standards]]
== Übersicht IsyFact-Standards

Die IsyFact-Standards sind an folgenden Orten dokumentiert:

* http://isyfact.de[Webseite des Bundesverwaltungsamts zur IsyFact],
* https://isyfact.github.io[Online-Dokumentation der IsyFact].