= Whitepaper: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

Bei der Entwicklung von Anwendungssystemen für eine bestimmte Domäne stehen Architekten und Entwickler häufig vor denselben, wiederkehrenden Problemen.
Zwar unterscheiden sich je nach Anwendung die Datenstrukturen, die Geschäftslogik und die Benutzeroberflächen, aber die allgemeinen Prinzipien, z.B. der Datenhaltung, der Architektur und der Gestaltung von Benutzerschnittstellen, sind in der Regel für alle Anwendungen identisch und somit wiederverwendbar.

Die Herausforderung bei der Wiederverwendung besteht darin, das einmal erworbene Wissen über die Anwendungsentwicklung in einer Domäne zu strukturieren, zu dokumentieren und vorzuhalten, so dass nachfolgende Projekte einfach und verlässlich darauf zugreifen können, und damit die Einhaltung des definierten Architekturrahmens sicherzustellen.
Software Factories sind ein Mittel, dies zu erreichen.

Die IsyFact ist eine Software Factory für den Bau von Informationssystemen in komplexen IT-Anwendungslandschaften, die vom Bundesverwaltungsamt entwickelt wurde.
Sie bündelt bestehendes technisches Know-how um Anwendungssysteme effizienter entwickeln und betreiben zu können.

Die Grundlage einer Software Factory sind die Standards, nach denen sich alle anderen Bausteine der Factory richten.


[[aufbau-und-zweck-des-dokuments]]
=== Aufbau und Zweck des Dokuments

Die in diesem Dokument vorgestellten IsyFact-Standards bilden diese Grundlage für die IsyFact.
// end::inhalt[]