= Release Notes Version {page-component-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Ergänzend zu den Release Notes erläutert der xref:release:migrationsleitfaden.adoc[Migrationsleitfaden] die notwendigen Schritte zur Migration älterer Anwendungen auf das aktuelle Release.


[[kapitel-aenderungen]]
== Allgemeine Änderungen

...

[[kapitel-referenzarchitektur]]
== Referenzarchitektur

=== Software-technische Sicht
Datenzugriff:: Für die Überführung von persistenten Entitäten in Geschäftsobjekte sollen keine gesonderten Schnittstellenobjekte mehr genutzt werden.
Die Komponente Datenzugriff übergibt persistente Entitäten an den Anwendungskern.
Der Anwendungskern darf keine persistenten Entitäten mehr herausgeben, auch nicht zwischen seinen Fachkomponenten.
Entsprechende Ausnahmen wurden gestrichen.


[[kapitel-bausteine]]
== Bausteine

...

[[kapitel-deprecations]]
== Deprecations

...

[[kapitel-entfernt]]
== Entfernt

=== Dokumentation

Die IsyFact macht keine Vorgaben mehr zur Entwicklungsumgebung.
Alle Inhalte und Produktvorgaben diesbezüglich wurden entfernt.