= Release Notes Version {page-component-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Ergänzend zu den Release Notes erläutert der xref:release:migrationsleitfaden.adoc[Migrationsleitfaden] die notwendigen Schritte zur Migration älterer Anwendungen auf das aktuelle Release.


[[kapitel-aenderungen]]
== Allgemeine Änderungen

...

[[kapitel-referenzarchitektur]]
== Referenzarchitektur

[CAUTION]
====
Dieses Release enthält architektonische "Breaking Changes".
Anwendungen, die mit den vorigen Releases der IsyFact architektonisch im Einklang sind, sind es mit IsyFact {page-component-version} nicht mehr unbedingt.

Widersprüche zur Referenzarchitektur führen in der Regel zu einem (partiellen) Redesign betroffener Anwendungen.
====

Der Begriff "Referenzarchitektur" löst den bisherigen Begriff "Blaupause" ab.

=== Software-technische Sicht
// TODO: Links zu den entsprechenden Seiten ergänzen, wenn vorhanden!
IT-Systeme dürfen keine UI-Komponenten mehr enthalten.
Zur Umsetzung von UIs sieht die Referenzarchitektur nur noch eigenständige Frontend-Anwendungen vor.
Ergänzend hierzu beinhaltet die IsyFact einen Baustein zur Umsetzung dieser Anwendungen mit Angular.

Datenzugriff:: Für die Überführung von persistenten Entitäten in Geschäftsobjekte sollen keine gesonderten Schnittstellenobjekte mehr genutzt werden.
Die Komponente Datenzugriff übergibt persistente Entitäten an den Anwendungskern.
Der Anwendungskern darf keine persistenten Entitäten mehr herausgeben, auch nicht zwischen seinen Fachkomponenten.
Entsprechende Ausnahmen wurden gestrichen.

Anwendungskern:: Das Konzept der "Basisdaten" wurde gestrichen, in dem die Referenzarchitektur erlaubt hat, von Fachkomponenten gemeinsam benutzte Geschäftsobjekte zu definieren. Für diese Geschäftsobjekte gab es keine Komponente im Anwendungskern, sondern nur einen direkten Zugriff auf die dazugehörigen Entitäten. Die Referenzarchitektur sieht nun vor, dass Fachkomponenten ohne Ausnahme die vollständige Datenhoheit über ihre eigenen Geschäftsobjekte besitzen.


[[kapitel-bausteine]]
== Bausteine

...

[[kapitel-deprecations]]
== Deprecations

...

[[kapitel-entfernt]]
== Entfernt

=== Dokumentation

Die IsyFact macht keine Vorgaben mehr zur Entwicklungsumgebung.
Alle Inhalte und Produktvorgaben diesbezüglich wurden entfernt.