= Release Notes Version {page-component-version}
:icons: font
:sectnums:

include::glossary:licence:partial$licence.adoc[]

Ergänzend zu den Release Notes erläutert der xref:release:migrationsleitfaden.adoc[Migrationsleitfaden] die notwendigen Schritte zur Migration älterer Anwendungen auf das aktuelle Release.


[[kapitel-aenderungen]]
== Allgemeine Änderungen

_keine_

[[kapitel-referenzarchitektur]]
== Referenzarchitektur

=== Fachliche Referenzarchitektur

Der Begriff xref:glossary::terms-definitions.adoc#nachbarsystem[Nachbarsystem] wurde definiert und seine Verwendung wurde in der gesamten IsyFact, wo nötig, korrigiert.

=== Software-technische Referenzarchitektur

Der Begriff xref:glossary::terms-definitions.adoc#externes-system["externes System"] wurde definiert und seine Verwendung in der gesamten IsyFact, wo nötig, korrigiert.
Die Begrifflichkeiten "internes System" bzw. "interne Anwendung" wurden aus der IsyFact entfernt.


[[kapitel-bausteine]]
== Bausteine

=== JPA / Hibernate

Der Baustein bietet ein erweitertes xref:isy-persistence:konzept/versionierung-mit-liquibase.adoc[Konzept] sowie xref:isy-persistence:nutzungsvorgaben/versionierung-mit-liquibase.adoc[Nutzungsvorgaben] zur Schema-Versionierung mit Liquibase.
Diese soll die Eigenimplementierung der IsyFact ablösen.

=== Verschobene Bausteine
Folgende Bausteine wurden in eigenständige Repositories umgezogen:

[cols="1,1",options="header"]
|===
|Altes Repository
|Neues Repository

//|https://github.com/IsyFact/isyfact-standards/tree/release/4.x/...[icon:github[] isyfact-standards (Modul ...)]
//|https://github.com/IsyFact/...[icon:github[] ...]

|===

* Beide Bausteine lassen sich weiterhin über die `isyfact-standards-bom` einbinden und auch die Group- und Artifact-IDs bleiben dieselben.
* Die Version wird allerdings in zukünftigen Releases nicht mehr mit der Version der `isyfact-standards` synchron gehalten und entwickelt sich entkoppelt davon fort.
* Die Bausteine besitzen keinerlei Abhängigkeiten auf die restliche IsyFact mehr.
Sie setzen allein Java 17 voraus.
So können sie auch in Anwendungen integriert werden, die noch auf einem älteren Stand der IsyFact beruhen.

=== Gelöschte Bausteine

Die folgenden Bausteine wurden aus der IsyFact entfernt.
Die folgende Tabelle zeigt, auf welche Bausteine bzw. Konzepte die Anwendungen migrieren müssen

[cols="1s,2",options="header"]
|===
|Entfernter Baustein|Migrieren auf
//|...|xref:...:konzept/master.adoc[...]

|===


[[kapitel-deprecations]]
== Deprecations

_keine_

[[kapitel-dokumentation]]
== Dokumentation

_keine_
