= Release Notes Version {page-component-version}
:icons: font
:sectnums:

Ergänzend zu den Release Notes erläutert der xref:release:migrationsleitfaden.adoc[Migrationsleitfaden] die notwendigen Schritte zur Migration älterer Anwendungen auf das aktuelle Release.


[[kapitel-aenderungen]]
== Allgemeine Änderungen

_keine_

[[kapitel-referenzarchitektur]]
== Referenzarchitektur

=== Fachliche Referenzarchitektur

Der Begriff xref:glossary::terms-definitions.adoc#nachbarsystem[Nachbarsystem] wurde definiert und seine Verwendung wurde in der gesamten IsyFact, wo nötig, korrigiert.

=== Software-technische Referenzarchitektur

Der Begriff xref:glossary::terms-definitions.adoc#externes-system["externes System"] wurde definiert und seine Verwendung in der gesamten IsyFact, wo nötig, korrigiert.
Die Begrifflichkeiten "internes System" bzw. "interne Anwendung" wurden aus der IsyFact entfernt.

==== Backend

Die Seiten zur Persistenzschicht enthalten nun die Inhalte des aufgelösten Bausteins JPA/Hibernate:

* xref:referenzarchitektur:software-technisch/backend/persistenz/vorgaben-konventionen.adoc[Vorgaben und Konventionen] zur Nutzung von JPA und Hibernate,
* xref:referenzarchitektur:software-technisch/backend/persistenz/liquibase.adoc[Schema-Versionierung mit Liquibase],
* xref:referenzarchitektur:software-technisch/backend/persistenz/historisierung.adoc[Historisierung].

Die Inhalte wurden gestrafft und Abschnitte, die Dokumentation der verwendeten Produkte wiedergaben, wurden durch Verweise auf die entsprechenden Dokumentationen ersetzt.
Grundlegende Erklärungen zu den verwendeten Produkten wurden gänzlich entfernt.

Bisherige Verbote im Rahmen der Persistenz wurden durch eine Empfehlung, basierend auf den Qualitätskriterien der ISO 25010, ersetzt.
Dies gilt für den Einsatz eines xref:referenzarchitektur:software-technisch/backend/persistenz/vorgaben-konventionen.adoc#second-level-cache[Second-Level-Caches] sowie von xref:referenzarchitektur:software-technisch/backend/persistenz/vorgaben-konventionen.adoc#bulk-queries[Bulk Queries].

===== Schema-Versionierung

Die bisher angebotene Schema-Versionierung in Form einer Eigenentwicklung wird nicht mehr durch die IsyFact bereitgestellt.
Die Schema-Versionierung mit Liquibase wurde xref:referenzarchitektur:software-technisch/backend/persistenz/liquibase.adoc[konzeptionell] erweitert und um xref:referenzarchitektur:software-technisch/backend/persistenz/liquibase-umsetzung.adoc[Nutzungsvorgaben] ergänzt.

==== Services

Die Nutzung des Begriffs "Webservice" wurde vereinheitlicht und entspricht jetzt der https://www.w3.org/TR/ws-arch/#whatis[Definition des W3C].


[[kapitel-bausteine]]
== Bausteine

=== Erweiterte Bausteine

==== Rest
Die Konzeption wurde um die strukturierten Verwendung von HTTP-Statuscodes (inkl. `Retry-After`, Status-URLs, Fehlermeldungen) im Kapitel "Verwendung von HTTP-Statuscodes" ergänzt.
Architekten können ihre Anwendungen auf eine ergänzende Nutzung dieser prüfen.

=== Aufgelöste Bausteine

==== JPA/Hibernate

Die konzeptionellen Inhalte des Bausteins JPA/Hibernate wurden in die Referenzarchitektur überführt, da die zugehörige Bibliothek `isy-persistence` zugunsten der direkten Nutzung von Spring Data und Liquibase aufgelöst wurde.

=== Verschobene Bausteine
Folgende Bausteine wurden in eigenständige Repositories umgezogen:

[cols="2,1",options="header"]
|===
|Altes Repository
|Neues Repository

|https://github.com/IsyFact/isyfact-standards/tree/release/4.x/isy-persistence/src/main/java/de/bund/bva/isyfact/persistence/datetime[icon:github[] isyfact-standards (Package `de.bund.bva.isyfact.persistence.datetime`)]
|https://github.com/IsyFact/isy-datetime-persistence[icon:github[] isy-datetime-persistence]

|https://github.com/IsyFact/isyfact-standards/tree/release/4.x/isy-polling[icon:github[] isyfact-standards (Modul isy-polling)]
|https://github.com/IsyFact/isy-polling[icon:github[] isy-polling]

|https://github.com/IsyFact/isyfact-standards/tree/release/4.x/isy-security[icon:github[] isyfact-standards (Modul isy-security)]
|https://github.com/IsyFact/isy-security[icon:github[] isy-security]

|https://github.com/IsyFact/isyfact-standards/tree/release/4.x/isy-task[icon:github[] isyfact-standards (Modul isy-task)]
|https://github.com/IsyFact/isy-task[icon:github[] isy-task]

|https://github.com/IsyFact/isyfact-standards/tree/release/4.x/isy-util[icon:github[] isyfact-standards (Modul isy-util)]
|https://github.com/IsyFact/isy-util[icon:github[] isy-util]

|===

* Alle Bausteine lassen sich weiterhin über die `isyfact-standards-bom` einbinden und auch die Group- und Artifact-IDs bleiben dieselben.
* Die Version wird allerdings in zukünftigen Releases nicht mehr mit der Version der `isyfact-standards` synchron gehalten und entwickelt sich entkoppelt davon fort.
//* Die Bausteine besitzen keinerlei Abhängigkeiten auf die restliche IsyFact mehr.
//Sie setzen allein Java 17 voraus.
//So können sie auch in Anwendungen integriert werden, die noch auf einem älteren Stand der IsyFact beruhen.

=== Gelöschte Bausteine

Die folgenden Bausteine wurden aus der IsyFact entfernt.
Die folgende Tabelle zeigt, auf welche Bausteine bzw. Konzepte die Anwendungen migrieren müssen.

[cols="1s,2",options="header"]
|===
|Entfernter Baustein|Migrieren auf
|JPA/Hibernate
a|konzeptionell:

* xref:referenzarchitektur:software-technisch/backend/persistenzschicht.adoc[]
* xref:referenzarchitektur:software-technisch/backend/persistenz/vorgaben-konventionen.adoc[]

technisch:

* Standardfunktionen von Spring Data, Spring Boot und Spring
* Hilfsfunktionen im xref:util::konzept.adoc#persistence[Baustein Util]

|===


[[kapitel-deprecations]]
== Deprecations

_keine_

[[kapitel-dokumentation]]
== Dokumentation

_keine_
