= Detailkonzept Batch: Einleitung

// tag::inhalt[]
[[Einleitung]]
== Einleitung

Ein Batch bzw. die Batchverarbeitung bietet die Möglichkeit, Daten automatisiert und meist sequenziell zu verarbeiten.
Er stellt eine Variante zur Dialogverarbeitung dar, bei welcher die Datenverarbeitung von Benutzerinteraktionen gesteuert wird.

Neben einer Liste von Anforderungen für die Umsetzung von Batches, stellt IsyFact den technischen Baustein _Batchrahmen_ zur Verfügung, die in diesem Dokument näher beschrieben werden.

In Kapitel <<anforderungen>> werden die Anforderungen, in Kapitel <<ausgrenzungen>> die Ausgrenzungen definiert.
Die Funktionsweise des Batchrahmens und die verschiedenen Startarten sowie die Konfiguration folgt in Kapitel <<der-batchrahmen>>.
Dort werden auch die Transaktionssteuerung und die Restart-Funktionalität beschrieben, die es ermöglicht, abgebrochene Batches fortzusetzen.
Die Überwachung mittels JMX ist ebenfalls enthalten.
Kapitel <<die-ausfuehrungsbeans>> beschreibt schließlich, wie die konkrete Batchlogik über Ausführungsbeans angebunden wird.
// end::inhalt[]