= Detailkonzept Batch: Einleitung

// tag::inhalt[]
[[Einleitung]]
== Einleitung

Ein Batch bzw. die Batchverarbeitung bietet die Möglichkeit, Daten automatisiert und meist sequenziell zu verarbeiten.
Er stellt eine Variante zur Dialogverarbeitung dar, bei welcher die Datenverarbeitung von Benutzerinteraktionen gesteuert wird.

Neben einer Liste von Anforderungen für die Umsetzung von Batches, stellt IsyFact den technischen Baustein _Batchrahmen_ zur Verfügung, die in diesem Dokument näher beschrieben werden.

In Kapitel xref:detailkonzept-komponente-batch/master.adoc#anforderungen[Anforderungen] werden die Anforderungen, in Kapitel xref:detailkonzept-komponente-batch/master.adoc#ausgrenzungen[Ausgrenzungen] die Ausgrenzungen definiert.
Die Funktionsweise des Batchrahmens und die verschiedenen Startarten sowie die Konfiguration folgt in Kapitel xref:detailkonzept-komponente-batch/master.adoc#der-batchrahmen["Der Batchrahmen"].
Dort werden auch die Transaktionssteuerung und die Restart-Funktionalität beschrieben, die es ermöglicht, abgebrochene Batches fortzusetzen.
Die Überwachung mittels JMX ist ebenfalls enthalten.
Das Kapitel xref:detailkonzept-komponente-batch/master.adoc#die-ausfuehrungsbeans["Die Ausführungsbeans"] beschreibt schließlich, wie die konkrete Batchlogik über Ausführungsbeans angebunden wird.
// end::inhalt[]