= Detailkonzept Komponente Web-GUI: Einleitung

// tag::inhalt[]
Die xref:referenzarchitektur-it-system/master.adoc#einleitung[Referenzarchitektur IT-Systeme] beschreibt den Aufbau von xref:glossary:glossary:master.adoc#glossar-geschaeftsanwendung[Geschäftsanwendungen] in fünf Komponenten.
Eine davon ist die Komponente Web-GUI.
Das vorliegende Dokument enthält die Detailkonzeption dieser Komponente.
Es enthält eine Detaillierung der Referenzarchitektur und zeigt, wie die Fachlichkeit in GUI- und Dialog-Komponenten geschnitten wird.
Darüber hinaus trifft es allgemeine Vorgaben für querschnittliche Aspekte, wie Sicherheit, Transaktionssteuerung und Session Management.

Zielgruppe dieses Dokuments sind Entwickler und Architekten, die Interesse an den allgemeinen Vorgaben der IsyFact in Bezug auf Web-GUIs haben.

Allgemeine Angaben zur Gestaltung von Oberflächen finden sich im xref:isy-bedienkonzept:styleguide.adoc[Styleguide].
Weitere Informationen zur Umsetzung von Oberflächen sind den konkreten GUI-Bausteinen zu entnehmen.
// end::inhalt[]
