= Bausteine

// tag::whitepaper[]

*Wiederverwendbare Softwarelösungen, querschnittliche Anwendungen sowie Programmierbibliotheken und -vorlagen zur Erstellung von Geschäftsanwendungen.*

Diese Bausteine liegen in unterschiedlichen Formen vor: es gibt fachliche und technische Services im Sinne einer Service-Orientierten Architektur (SOA), querschnittlich nutzbare Komponenten sowie wiederverwendbare Bibliotheken und Programmiervorlagen.

Die Bausteine können auch am Markt verfügbare Fertigprodukte enthalten, dabei sowohl proprietäre als auch Open-Source-Software.

Die folgende Abbildung zeigt einen Überblick über die Bausteine im aktuellen Release der IsyFact.

[[bausteine-isyfact]]
.Bausteine der IsyFact
image::bausteine:bausteine.dn.svg[]

.Legende
[%collapsible]
====
****
Jede Wabe steht für einen Baustein.
Blau gefüllte Waben sind Teil der xref:einstieg:vorstellung/isyfact-standards.adoc[].
Grau gefüllte Waben sind Teil der xref:einstieg:vorstellung/isyfact-erweiterungen.adoc[].

Hellblau umrandete Waben bedeuten, dass der Baustein als Software-Bibliothek veröffentlicht wird.
****
====

Bausteine stellen in der Regel ein Dokument aus architektonischer Sicht – das Konzept – und ein Dokument aus technischer Sicht – die Nutzungsvorgaben – sowie eine Software-Bibliothek zur Integration in eigene Anwendungen bereit.

== IsyFact-Standards

include::einstieg:vorstellung.adoc[tags=isyfact-standards-definition]

[cols="1s,3a",options="header"]
|===
|Baustein
|Funktion

|Datum & Zeit
|Der Baustein stellt Vorgaben für die Anzeige, Eingabe und persistenter Speicherung von Datums- und Zeitwerten bereit.

|Fehlerbehandlung
|Der Baustein _Fehlerbehandlung_ enthält das technische Konzept und eine Bibliothek zur einheitlichen Implementierung der Fehlerbehandlung.

|Logging
|Der Baustein ermöglicht die einheitliche Erstellung und vereinfachte Auswertung von Log-Dateien, Fehlern und Systemzuständen über Komponentengrenzen hinweg.

|Polling
|Der Baustein _Polling_ implementiert Verfahren zum koordinierten, regelmäßigen Abholen von Daten (Polling) durch mehrere redundant ausgelegte Instanzen einer Anwendung.
Der Baustein unterstützt unterschiedliche Arten von Schnittstellen und sorgt dafür, dass Daten jeweils nur von einer Instanz der Anwendung verarbeitet werden.

|REST
|Der Baustein _REST_ bietet die Möglichkeit, interne Services der Anwendungslandschaft als REST-Services zu realisieren.

|Security
|Der Baustein _Security_ übernimmt die Authentifizierungsanfragen von natürlichen Anwendern als auch von technischen Systemen und leitet diese in die entsprechenden Credential-Flows des IAM-Service.
Aus den vom IAM-Service erhaltenen Zugangsdaten übernimmt der Baustein das Rollen- und Rechte-Handling zur Autorisierung der Anwendungsaufrufe innerhalb der Aufrufkette der Fachanwendungen.

|Sonderzeichen
|Der Baustein bietet wichtige Hinweise für den Umgang mit Sonderzeichen und enthält Transkriptionsregeln zur Übertragung von nicht-lateinischen Zeichen.
Unterstützt werden die Standards String Latin 1.1 und String Latin 1.2 („DIN SPEC 91379“) und eine generelle Kompatibilität zu UTF-8.

|Task Scheduling
|Der Baustein ermöglicht die Ausführung regelmäßiger Aufgaben innerhalb eines Backends mit voller Integration anderer Bausteine wie Konfiguration, Logging, Sicherheit und Überwachung.

|Überwachung
|Der Baustein macht Vorgaben für die Überwachung von Backends und stellt grundlegende Funktionalität bereit, so z.B. für die Überwachung von Komponentengrenzen.
Die einheitliche Überwachungsschnittstelle erlaubt die frühzeitige Erkennung von Problemen im IT-Betrieb.

|Util
|Der Baustein _Util_ bietet nützliche Hilfsmittel, die von den Anwendungen der IsyFact genutzt werden können.
Es handelt sich dabei um kleinere Utility-Klassen, wie z.B. Interzeptoren, mit denen sich das Laufzeitverhalten von Anwendungen nachvollziehen lässt.
|===

== IsyFact-Erweiterungen

include::einstieg:vorstellung.adoc[tags=isyfact-erweiterungen-definition]

[cols="1s,3a",options="header"]
|===
|Baustein
|Funktion

|Angular
|Der Baustein _Angular_ bietet eine Frontend-Bibliothek, deren Komponenten anhand der Vorgaben im Bedienkonzept entwickelt und exemplarisch in der Demo-Anwendung des Bausteins gezeigt werden.
Dadurch werden wiederverwendbare Widgets bereitgestellt, um User Interfaces zu vereinheitlichen.
Der Baustein basiert auf Angular, PrimeNG und PrimeFlex.

|Bedienkonzept
|Das _Bedienkonzept_ beschreibt die Gestaltungsregeln, Lösungsmuster und Workflows für fachliche Abläufe in Benutzeroberflächen.
Ziel des Bedienkonzepts ist es, dass sich Sachbearbeiter möglichst schnell zwischen unterschiedlichen Anwendungen orientieren können.

|===

// end::whitepaper[]
