[[changelog]]
= Changelog

*Änderungen IsyFact 2.4.0*

// tag::release-2.4.0[]
- `IFS-1176`: Fehler gefixt, bei dem der LegacyTransformator Texte ausgibt, die nicht konform zu String.Latin 1.1 sind.
// end::release-2.4.0[]

*Änderungen IsyFact 2.3.0*

// tag::release-2.3.0[]
- `IFS-1109`: DIN SPEC 91379:
* Erweiterung Transformator-Interface um Methoden, die Metadaten der Transformation tracken
* neuer LegacyTransformator, der Texte nach DIN-SPEC-91379 in String.Latin-1.1-konforme Texte transformiert
- `IFS-1035`: Funktion hinzugefügt, welche die Zugehörigkeit eines Strings zu einem DIN-SPEC-Datentyp prüft.
// end::release-2.3.0[]

// *Änderungen IsyFact 2.2.0*

// tag::release-2.2.0[]
// end::release-2.2.0[]

// *Änderungen IsyFact 2.1.0*

// tag::release-2.1.0[]
// end::release-2.1.0[]

*Änderungen IsyFact 2.0.0*

// tag::release-2.0.0[]
- `IFS-32`: Package-Name auf de.bund.bva.isyfact geändert
// end::release-2.0.0[]

// *Änderungen IsyFact 1.8.0*

// tag::release-1.8.0[]
// end::release-1.8.0[]

*Änderungen IsyFact 1.7.0*

// tag::release-1.7.0[]
// Interne alte Version: 1.8.0
- `IFS-262`: `isyfact-masterpom` deprecated (Abschaffung mit IsyFact 2.0), `isyfact-masterpom-lib` aufgelöst, Bibliotheken benutzen `isyfact-standards` als Parent-POM
// end::release-1.7.0[]

*Änderungen IsyFact 1.6.0*

// tag::release-1.6.0[]
// Interne alte Version: 1.7.0
- `IFS-189`: Repositories der IsyFact-Standards zusammengeführt, Bibliotheken benutzen wieder gemeinsames Produkt-BOM und werden zentral über das POM isyfact-standards versioniert
// end::release-1.6.0[]

// *Änderungen IsyFact 1.5.0*

// tag::release-1.5.0[]
// end::release-1.5.0[]

// *Änderungen IsyFact 1.4.0*

// tag::release-1.4.0[]
// end::release-1.4.0[]

// *Änderungen IsyFact 1.3.5*

// tag::release-1.3.5[]
// end::release-1.3.5[]

// *Änderungen IsyFact 1.3.0*

// tag::release-1.3.0[]
// end::release-1.3.0[]

