= Nutzungsvorgaben Isy Util: Inhalt

// tag::inhalt[]
[[aufbau-von-isy-util]]
== Aufbau von isy-util

[[common]]
=== Common

Das Package `de.bund.bva.isyfact.util.common` enthält allgemeine Klassen, die keiner speziellen Funktionalität zugeordnet sind.
Zurzeit besteht sie aus folgender Klasse:

* `RecursiveToStringBuilder`: Diese Klasse erzeugt eine Textausgabe für Objekte, die keine geeignete `toString`-Methode implementieren.

[[package-exception]]
=== Package exception

:linkaktuell: xref:isy-exception-core:nutzungsvorgaben/inhalt.adoc#fehlertextprovider[FehlertextProvider]
include::glossary:miscellaneous:partial$deprecated-abschnitt.adoc[]

****
*Anmerkung zur Deprecation*

Für Fehlermeldungen wird empfohlen, das Interface `de.bund.bva.isyfact.exception.FehlertextProvider` zu implementieren.
****

In `de.bund.bva.isyfact.util.exception` sind Klassen enthalten, die für die Fehlerbehandlung einzusetzen sind:

* `MessageSourceFehlertextProvider`: Durch diese Klasse wird der `FehlertextProvider` implementiert, der sich im Package `de.bund.bva.isyfact.exception` der Bibliothek isy-exception-core befindet.
Der `FehlertextProvider` beschreibt Methoden zum Auslesen von Fehlertexten auf Basis von IDs der Ausnahmen und Parameter, sofern welche vorhanden sind.

[[package-spring]]
=== Package spring

:linkaktuell: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/MessageSource.html[org.springframework.context.MessageSource]
include::glossary:miscellaneous:partial$deprecated-abschnitt.adoc[]

****
*Anmerkung zur Deprecation*

Für die Benennung der `MessageSource`-Bean wird empfohlen, einen eindeutigeren Namen zu wählen, damit diese mittels Spring-Bordmitteln überschrieben werden kann.
****

Das Package `de.bund.bva.isyfact.util.spring` enthält Werkzeuge für den Umgang mit Spring:

* `MessageSourceHolder`: Der `MessageSourceHolder` ist eine Referenz auf die aktuelle `MessageSource`-Bean.
Zusätzlich bietet er Convenience-Funktionen zum Auslesen von `ResourceBundle`-Einträgen aus der `MessageSource`.

// end::inhalt[]