= Nutzungsvorgaben HTTP Invoker: Einleitung

// tag::inhalt[]
[[einleitung]]
== Einleitung

[NOTE]
====
Dieses Dokument ist aus mehreren Quellen entstanden und fasst die vorhandene Dokumentation zum Thema HTTP Invoker zusammen.
Der Baustein HTTP Invoker steht unter Bestandsschutz und wird nicht mehr aktiv weiterentwickelt.
Er wird in einem der nächsten Major Releases aus der IsyFact entfernt.
// TODO Links zum REST-Konzept einfügen.
====

Das Dokument xref:konzept/master.adoc[KonzeptHttpInvoker] konzentriert sich auf die konzeptionellen Aspekte von Services mit HTTP Invoker.

Dieses Dokument beschreibt, wie diese Services konkret umgesetzt werden.
Es richtet sich an Entwickler, die ein xref:glossary:glossary:master.adoc#glossar-it-system[IT-System] gemäß den Vorgaben der IsyFact mit der Fähigkeit zur Kommunikation mit anderen IT-Systemen ausstatten müssen und beschreibt, was bei der Umsetzung zu bedenken ist.

Dazu beschreibt das Kapitel xref:nutzungsvorgaben/master.adoc#maven-konfiguration[Maven-Konfiguration] zunächst die grundlegende Konfiguration, um den Baustein in ein IT-System einzubinden.
Danach beschreibt das Dokument die Realisierung eines Services in den Kapiteln:

* xref:nutzungsvorgaben/master.adoc#realisierung-remote-bean[Realisierung des Remote-Beans],
* xref:nutzungsvorgaben/master.adoc#realisierung-exception-fassade[Realisierung der Exception-Fassade],
* xref:nutzungsvorgaben/master.adoc#realisierung-service-fassade[Realisierung der Service-Fassade],
* xref:nutzungsvorgaben/master.adoc#realisierung-to[Realisierung von Transportobjekten].

Danach geht es um die xref:nutzungsvorgaben/master.adoc#paketierung[Paketierung einer Service-Schnittstelle] und die xref:nutzungsvorgaben/master.adoc#nutzung[Nutzung einer Service-Schnittstelle] durch ein anderes IT-System.
// end::inhalt[]
