
CREATE TABLE BATCHSTATUS
(
    BATCHID                 VARCHAR2(255) NOT NULL,
    BATCHNAME               VARCHAR2(255),
    BATCHSTATUS             VARCHAR2(255),
    SATZNUMMERLETZTESCOMMIT NUMBER(19, 0),
    SCHLUESSELLETZTESCOMMIT VARCHAR2(255),
    DATUMLETZTERSTART       TIMESTAMP,
    DATUMLETZTERABBRUCH     TIMESTAMP,
    DATUMLETZTERERFOLG      TIMESTAMP,
    CONSTRAINT BATCHSTATUS_PK PRIMARY KEY (BATCHID)
);
