name: Commit Message Checker
on:
  pull_request:
    branches:
      - master
      - 'release/**'
  push:
    branches:
      - master
      - 'release/**'

  workflow_call:

jobs:
  check-commit-message:
    name: Check Conventional Commit Message
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: none
      checks: none
      deployments: none
      issues: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: Check Commit Message
        uses: gsactions/commit-message-checker@v2.0.0
        with:
          pattern: '^((feat|fix|build|ci|docs|refactor|style|test|perf|chore)(\(\w+\))?(: (.*\s*)*))|(Merge (.*\s*)*)|(Revert (.*\s*)*)'
          error: 'Commit message is not conventional.'
          checkAllCommitMessages: 'true'
          excludeDescription: 'true'
          excludeTitle: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}