name: Dependency Review Template
on:
  workflow_call:
    inputs:
      base-ref:
        description: Git references for the git base
        required: false
        default: ${{ github.event.pull_request.base.sha }}
        type: string
      head-ref:
        description: Git references for the git head
        required: false
        default: ${{ github.event.pull_request.head.sha }}
        type: string

jobs:
  DependencyReview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: IsyFact/isyfact-standards/.github/dependency-review-config.yml@feature/IFS-2835_license_management_isy_sonderzeichen
          base-ref: ${{ inputs.base-ref }}
          head-ref: ${{ inputs.head-ref }}