name: Dependency Review
on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'develop-**'
      - 'support/**'
  workflow_dispatch:

jobs:
  DependencyReview:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/dependency_review_template.yml@v3.0.0
    with:
      allow-dependencies-licenses: 'pkg:maven/io.github.git-commit-id/git-commit-id-maven-plugin'
