name: Dependency Review Template
on:
  workflow_call:

jobs:
  DependencyReview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: IsyFact/isyfact-standards/.github/dependency-review-config.yml@feature/IFS-2835_license_management_isy_sonderzeichen
          base-ref: ${{ github.event.pull_request.base.sha || 'master' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}