name: Dependabot Auto Merge Template

on:
  workflow_call:
    secrets:
      DEPENDABOT_TOKEN:
        description: 'GitHub Token for Dependabot'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  DependabotAutoMerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: Approve and enable auto-merge for PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}