name: Publishes the release after setting a tag

# Triggers the workflow on version tags like 1.0.0
on:
  push:
    tags:
      - '*.*.*'
permissions:
  contents: read

jobs:
  CreateRelease:
    permissions:
      contents: write
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_create_release_template.yml@v3.0.0
