name: Release Maven force
on:
  workflow_dispatch:
    inputs:
      confirm_deployment_without_checks:
        description: 'Confirm deployment without QualityGate and DependencyScan'
        required: true
        type: boolean
        default: false

jobs:
  Build:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_build_template.yml@v1.6.0
    with:
      version: ${{ github.ref_name }}
      sonar-skip: true

  DeployMavenCentral:
    if: ${{ inputs.confirm_deployment_without_checks }}
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.6.0
    with:
      version: ${{ github.ref_name }}
      maven-opts: '-P centralRelease'
      deploy-server-id: central
      sbom: true
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

  DependencyMonitor:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_dependency_scan_template.yml@v1.6.0
    with:
      jdk-version: 17
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
      snyk-reference: ${{ github.ref_name }}
      snyk-arguments: "--maven-aggregate-project"
      scan-dependency-management: false
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
