name: Release Maven
on:
  release:
    types: [released]

jobs:
  Build:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_build_template.yml@v3.0.0
    with:
      jdk-version: 17
      version: ${{ github.event.release.tag_name }}
      sonar-skip: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  DependencyScan:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_dependency_scan_template.yml@v3.0.0
    with:
      jdk-version: 17
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
      snyk-reference: master
      snyk-arguments: "--maven-aggregate-project"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  DeployReleaseVersion:
    needs: [DependencyScan]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v3.0.0
    with:
      version: ${{ github.event.release.tag_name }}
      jdk-version: 17
      maven-opts: '-P centralRelease'
      deploy-server-id: central
      sbom: true
      sign: true
      environment: 'Release'
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

  DependencyMonitor:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_dependency_scan_template.yml@v3.0.0
    with:
      jdk-version: 17
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
      snyk-reference: ${{ github.event.release.tag_name }}
      snyk-arguments: "--maven-aggregate-project"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}