name: Semgrep Scan

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'develop-**'
      - 'support/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  semgrep-scan:
    permissions:
      contents: read
    uses: IsyFact/isy-github-actions-templates/.github/workflows/semgrep.yml@v3.0.0
